      SUBROUTINE APWSUM (LFORCE,LSTRES,NOFORC,NBDS,TY,NAT,I1,I2,
     +IGLIST,NG1,NG2,NG3,LREAL,RWF3,VNLL,CWF4,IWF5,SATGR,SATGI,
     +CWORK,DWORK,D1WORK,D2WORK,D3WORK,CEV,WOCC,
     +ENONLO,SWF2,FORCE,NDIM1,NDIM5,NDIM8,NDIM9,NTYPMX)
C
C     CALCULATE NON-LOCAL CONTRIBUTIONS FROM A SET OF PLANE
C     WAVES TO TOTAL ENERGY, FORCES AND STRESSES, FROM THE
C     I2 TH ROW OF THE LOWER LEFT-HALF OF THE HAMILTONIAN.
C
C     VERSION FOR COMPLEX HAMILTONIANS
C
      LOGICAL LFORCE,LSTRES,NOFORC(NDIM9),LREAL
C.....STRUCTURE FACTORS:
      REAL SATGR(NDIM9,NDIM1),SATGI(NDIM9,NDIM1)
C.....G-VECTORS
      INTEGER IGLIST(3,NDIM1)
C.....ATOM TYPES
      INTEGER TY(NDIM9)
C.....WORKSPACES
      DOUBLE PRECISION ENONLO,SWF2(6),WOCC(NDIM8)
      DOUBLE PRECISION FORCE(3,NDIM9),DWORK(NDIM5),FF
      DOUBLE PRECISION D1WORK(NDIM5),D2WORK(NDIM5),D3WORK(NDIM5)
      DIMENSION VNLL(NDIM5),RWF3(NTYPMX,NDIM5),CWF4(6,NDIM5)
      DIMENSION CEV(NDIM5,NDIM8),CWORK(NDIM5)
      COMPLEX CWF4,VNLL,CEV,CWORK
      INTEGER IWF5(NDIM5)
CDIR$ INT24 N,J,KAPA,ITYPE
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C-----------------------------------------------------------------------
      IF (LREAL) WRITE(IOUT,*) '***PWSUM*** LREAL =',LREAL
C
      DO 10 N = I1,I2
10      CWORK(N) = (0.0,0.0)
C
      DO 30 J = 1,NBDS
C
C       2.0 BECAUSE OF SUM OVER UPPER AND LOWER TRIANGLES
C       1.0 ON THE DIAGONAL
        WOCCJ = WOCC(J)
        DO 20 N = I1,I2-1
20      CWORK(N)  = 2.0*WOCCJ*CEV(N ,J)*CONJG(CEV(I2,J)) + CWORK(N)
        CWORK(I2) =     WOCCJ*CEV(I2,J)*CONJG(CEV(I2,J)) + CWORK(I2)
30      CONTINUE
C
C.......NONLOCAL CONTRIBUTION TO TOTAL ENERGY
C
        DO 40 N = I1,I2
          ENONLO = ENONLO + DBLE(REAL (CWORK(N)))*DBLE(REAL (VNLL(N)))
     +                    - DBLE(AIMAG(CWORK(N)))*DBLE(AIMAG(VNLL(N)))
40        CONTINUE
C
C.......STRESS-TENSOR
C
        IF (LSTRES) THEN
          DO 50 N = I1,I2
          SWF2(1) = SWF2(1)+DBLE(REAL (CWORK(N)))*DBLE(REAL (CWF4(1,N)))
     +                     -DBLE(AIMAG(CWORK(N)))*DBLE(AIMAG(CWF4(1,N)))
          SWF2(2) = SWF2(2)+DBLE(REAL (CWORK(N)))*DBLE(REAL (CWF4(2,N)))
     +                     -DBLE(AIMAG(CWORK(N)))*DBLE(AIMAG(CWF4(2,N)))
          SWF2(3) = SWF2(3)+DBLE(REAL (CWORK(N)))*DBLE(REAL (CWF4(3,N)))
     +                     -DBLE(AIMAG(CWORK(N)))*DBLE(AIMAG(CWF4(3,N)))
          SWF2(4) = SWF2(4)+DBLE(REAL (CWORK(N)))*DBLE(REAL (CWF4(4,N)))
     +                     -DBLE(AIMAG(CWORK(N)))*DBLE(AIMAG(CWF4(4,N)))
          SWF2(5) = SWF2(5)+DBLE(REAL (CWORK(N)))*DBLE(REAL (CWF4(5,N)))
     +                     -DBLE(AIMAG(CWORK(N)))*DBLE(AIMAG(CWF4(5,N)))
          SWF2(6) = SWF2(6)+DBLE(REAL (CWORK(N)))*DBLE(REAL (CWF4(6,N)))
     +                     -DBLE(AIMAG(CWORK(N)))*DBLE(AIMAG(CWF4(6,N)))
50        CONTINUE
          ENDIF
C
C.......HELLMANN-FEYNMAN FORCES
C
        IF (LFORCE) THEN
        DO 60 N = I1,I2
          D1WORK(N) = DBLE(IGLIST(1,IWF5(N)))
          D2WORK(N) = DBLE(IGLIST(2,IWF5(N)))
          D3WORK(N) = DBLE(IGLIST(3,IWF5(N)))
60        CONTINUE
        DO 100 KAPA = 1,NAT
          IF (NOFORC(KAPA)) GOTO 100
          DO 80 N = I1,I2
            DWORK(N) = -DBLE(SATGI(KAPA,IWF5(N)))*DBLE(REAL (CWORK(N)))
     +                 -DBLE(SATGR(KAPA,IWF5(N)))*DBLE(AIMAG(CWORK(N)))
80          CONTINUE
          ITYPE = TY(KAPA)
          DO 90 N = I1,I2
            FF = DWORK(N)*DBLE(RWF3(ITYPE,N))
            FORCE(1,KAPA) = FORCE(1,KAPA) + D1WORK(N)*FF
            FORCE(2,KAPA) = FORCE(2,KAPA) + D2WORK(N)*FF
90          FORCE(3,KAPA) = FORCE(3,KAPA) + D3WORK(N)*FF
100       CONTINUE
          ENDIF
C
      RETURN
      END
