      SUBROUTINE COMPIT (IFILEH,NDIM3,NDIM5,NDIM8,NDIM13,NH,NA,NBDS,
     +CCR,CCI,DIAG,EE1,EE2,CEV,WK,CWF1,UBOUND,HRSUB,HISUB,SRSUB,SISUB,
     +VRSUB,VISUB,ALFR,ALFI,BETA,SHIFT,IWK,RES,NITMX,FAC,LREAL)
C
C                      COMPLEX VERSION
C
C     ROUTINE USES NEX'S CASE OF RUHE'S CONVERGENT SPLITTING
C     TO SOLVE FOR THE LOWEST EIGENVALUES OF A HERMITIAN
C     EIGENPROBLEM. FOR DETAILS OF THE METHOD SEE:  C.M.M. NEX
C     'A NEW SPLITTING TO SOLVE A LARGE HERMITIAN EIGENPROBLEM' (1986)
C
C     IFILEH : UNIT NUMBER CONTAINING LOWER TRIANGLE OF HAMILTONIAN
C              STORED IN ROWS IN REVERSE ORDER
C      NDIM3 : MAXIMUM DIMENSION OF A MATRIX
C      NDIM5 : MAXIMUM DIMENSION OF H MATRIX
C      NDIM8 : MAXIMUM NUMBER OF EIGENVALUES OF H MATRIX REQUIRED
C     NDIM13 : MAXIMUM NUMBER OF EIGENVALUES REQUIRED
C         WK : WORKSPACE
C     UBOUND : CONTAINS UPPER BOUNDS TO REQUIRED EIGENVALUES
C      HRSUB : REAL PART OF SUBSPACE HAMILTONIAN MATRIX (H*)
C      HISUB : IMAGINARY PART OF H*
C      SRSUB : REAL PART OF SUBSPACE OVERLAP MATRIX (S*)
C      SISUB : IMAGINARY PART OF S*
C      VRSUB : REAL PART OF EIGENVECTORS (Y) OF H* Y= S* Y LAMBDA
C      VISUB : IMAGINARY PART OF EIGENVECTORS Y
C       ALFR : BETA * REAL PART OF EIGENVALUES LAMBDA
C       ALFI : BETA * IMAGINARY PART OF EIGENVALUES LAMBDA
C       BETA : AS DEFINED ABOVE
C      SHIFT : SHIFTS OF THE EIGENVALUES. THIS ROUTINE WORKS FOR GENERAL
C              COMPLEX SHIFTS.
C
C       ON INPUT:
C        EE2 : ESTIMATE OF LOWEST NBDS EIGENVALUES OF H MATRIX
C        CEV : ESTIMATE OF CORRESPONDING EIGENVECTORS (X)
C         NH : DIMENSION OF H MATRIX
C         NA : DIMENSION OF A MATRIX
C       NBDS : NUMBER OF EIGENVALUES OF H MATRIX REQUIRED
C        CCR : REAL PART OF EIGENVECTORS OF A MATRIX
C        CCI : IMAGINARY PART OF EIGENVECTORS OF A MATRIX
C       DIAG : DIAGONAL PART OF H MATRIX
C        EE1 : EIGENVALUES OF A MATRIX
C        RES : ERROR TOLERANCE IN EIGENVALUES
C      NITMX : MAXIMUM NUMBER OF ITERATIONS
C        FAC : CONTROLS SIZE OF SHIFTS
C
C       ON OUTPUT:
C        EE2 : ITERATIVE ESTIMATE OF LOWEST NBDS EIGENVALUES
C              THESE ARE RIGOROUSLY UPPER BOUNDS TO THE LOWEST
C              NBDS EIGENVALUES OF H. THEY ARE NOT ORDERED
C        CEV : ITERATIVE ESTIMATE OF CORRESPONDING EIGENVECTORS
C
C       PARAMETERS:
C        EPS : ACCURACY OF SUBSPACE DIAGONALIZATION. IF EPS IS
C              NEGATIVE THEN THE ACCURACY IS MACHINE PRECISION
C      RDENT : VECTORS WITH OVERLAPS LARGER THAN RDENT ARE IDENTIFIED
C
      REAL CCR(NDIM3,NDIM13),CCI(NDIM3,NDIM13),DIAG(NDIM5)
      REAL EE1(NDIM13),EE2(NDIM8),UBOUND(NDIM8),SCNRM2
      INTEGER IWK(NDIM8)
      LOGICAL LREAL,LMATV
      COMPLEX SHIFT(NDIM8),CSHIFT,CDOTU,CDOTC,Z1,Z2,Z3
      DOUBLE PRECISION HRSUB(NDIM8,NDIM8),HISUB(NDIM8,NDIM8)
      DOUBLE PRECISION SRSUB(NDIM8,NDIM8),SISUB(NDIM8,NDIM8)
      DOUBLE PRECISION VRSUB(NDIM8,NDIM8),VISUB(NDIM8,NDIM8)
      DOUBLE PRECISION ALFR(NDIM8),ALFI(NDIM8),BETA(NDIM8)
      DOUBLE PRECISION EPS,D1,D2,D3,D4,D5,D6,D7,D8
      COMPLEX CEV(NDIM5,NDIM8),WK(NDIM5,NDIM8),CWF1(NDIM5)
      PARAMETER (LMATV = .TRUE.)
      PARAMETER (EPS = -1.0D0 , RDENT = 0.5)
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C------------------------------------------------------------------
C
      CALL USAGE (N0,T0)
C
      IF (NITMX .LE. 0) RETURN
      IF (LREAL) WRITE(IOUT,*) '***COMPIT*** LREAL = ',LREAL
      NAP1 = NA+1
      NB   = NH-NA
C
C     UPPER BOUNDS TO THE EIGENVALUES ARE STORED IN UBOUND
C     CALCULATED ACCORDING TO THE COURANT-FISCHER THEOREM
C     SEE WILKINSON 'THE ALGABRAIC EIGENVALUE PROBLEM'
C
      CALL SCOPY (NBDS,EE1,1,UBOUND,1)
      CALL BOUND (NBDS,NDIM8,EE2,UBOUND,IWK,ALFI,-1)
C
C     MAIN ITERATION LOOP
C
      DO 260 ITS = 1,NITMX
C
        DO 10 L = 1,NBDS
        DO 10 I = 1,NH
          WK(I,L) = (0.0,0.0)
10        CONTINUE
        DO 20 L = 1,NBDS
        DO 20 M = 1,L
          HRSUB(L,M) = 0.0D0
          HISUB(L,M) = 0.0D0
20        CONTINUE
C
C     SET SHIFTS OF EIGENVALUES
C
        CALL ESHIFT (EE1,SHIFT,FAC,NDIM8,NDIM13,NA,NBDS)
C
C     ACCESS HAMILTONIAN IN ROWS FROM BOTTOM UPWARDS
C
        CALL REWFIL (IFILEH)
        DO 60 IROW = NH,NAP1,-1
          NROW = IROW-1
C         The factor of 2 counts for 2 reals to a complex number
          CALL RDVEC (IFILEH,CWF1,2*NROW)
C
C     CALCULATE ELEMENTS OF NEW EIGENVECTOR X 2/S+1
C
          DO 30 L = 1,NBDS
            Z1 = WK(IROW,L) + CDOTU(NROW,CWF1,1,CEV(1,L),1)
            CEV(IROW,L) = Z1/(EE2(L)-DIAG(IROW))
30          CONTINUE
C
C     ACCUMULATE ELEMENTS OF H ACTING ON X 2/S+1
C
          CALL CONVEC (NROW,CWF1)
          DO 40 L = 1,NBDS
            CALL CAXPY(NROW,CEV(IROW,L),CWF1,1,WK(1,L),1)
40          CONTINUE
C
          D1 = DBLE(DIAG(IROW))
          DO 50 L = 1,NBDS
            D2 = DBLE(REAL (CEV(IROW,L)))
            D3 = DBLE(AIMAG(CEV(IROW,L)))
            DO 50 M = 1,L
              D4 = DBLE(REAL (CEV(IROW,M)))
              D5 = DBLE(AIMAG(CEV(IROW,M)))
              HRSUB(L,M) = HRSUB(L,M) + D1*(D2*D4+D3*D5)
              HISUB(L,M) = HISUB(L,M) + D1*(D2*D5-D3*D4)
50            CONTINUE
C
60        CONTINUE
C
        DO 70 L = 1,NBDS
        DO 70 M = 1,L
        DO 70 I = NAP1,NH
          D1 = DBLE(REAL (CEV(I,M)))
          D2 = DBLE(REAL (CEV(I,L)))
          D3 = DBLE(AIMAG(CEV(I,M)))
          D4 = DBLE(AIMAG(CEV(I,L)))
          D5 = DBLE(REAL ( WK(I,M)))
          D6 = DBLE(REAL ( WK(I,L)))
          D7 = DBLE(AIMAG( WK(I,M)))
          D8 = DBLE(AIMAG( WK(I,L)))
          HRSUB(L,M) = HRSUB(L,M) + D1*D6 + D3*D8 + D2*D5 + D4*D7
          HISUB(L,M) = HISUB(L,M) + D3*D6 + D2*D7 - D1*D8 - D4*D5
70        CONTINUE
C
C     USE EIGENVECTOR DECOMPOSITION OF A MATRIX TO CALCULATE X 1/S+1
C
        DO 140 L = NBDS,1,-1
C
          DO 80 I = 1,NA
            CWF1(I) = (0.0,0.0)
80          CONTINUE
C
C     PROJECT C X 2/S+1 - X 1/S R 1/S ONTO EIGENVECTORS OF A
C
          CSHIFT = SHIFT(L)
          DO 90 I = 1,NA
            Z1 = CSHIFT*CEV(I,L) + WK(I,L)
            DO 90 J = 1,NA
              CWF1(J) = CWF1(J) + CMPLX(CCR(I,J),-CCI(I,J))*Z1
90            CONTINUE
C
C     CALCULATE EIGENVECTOR PROJECTIONS OF X 1/S+1
C
          DO 100 I = 1,NA
            CWF1(I) = CWF1(I)/(EE2(L)-EE1(I)+CSHIFT)
100         CONTINUE
C
C     CALCULATE ELEMENTS OF X 1/S+1
C
          DO 130 I = 1,NA
            Z1 = (0.0,0.0)
            DO 110 J = 1,NA
              Z1 = Z1 + CMPLX(CCR(I,J),CCI(I,J))*CWF1(J)
110           CONTINUE
            D1 = DBLE(REAL (Z1))
            D2 = DBLE(AIMAG(Z1))
            DO 120 M = 1,L
              D3 = DBLE(REAL (CEV(I,M)))*D1
              D4 = DBLE(AIMAG(CEV(I,M)))*D1
              D5 = DBLE(REAL (CEV(I,M)))*D2
              D6 = DBLE(AIMAG(CEV(I,M)))*D2
              D7 = DBLE(REAL (SHIFT(M)))
              D8 = DBLE(AIMAG(SHIFT(M)))
              HRSUB(L,M) = HRSUB(L,M) + D8*(D4-D5) - D7*(D3+D6)
              HISUB(L,M) = HISUB(L,M) - D8*(D3+D6) - D7*(D4-D5)
120           CONTINUE
            CEV(I,L) = Z1
130         CONTINUE
C
140       CONTINUE
C
C     CALCULATE REST OF SUBSPACE HAMILTONIAN AND OVERLAP MATRIX
C
        DO 150 L = 1,NBDS
        DO 150 M = 1,L
          Z1 = CDOTC(NA,CEV(1,L),1,CEV(1,M),1)
          Z2 = CDOTC(NA,WK(1,L),1,CEV(1,M),1)
          Z3 = CDOTC(NB,CEV(NAP1,L),1,CEV(NAP1,M),1)
          D1 = DBLE(EE2(M) + REAL(SHIFT(M)))
          D2 = DBLE(AIMAG(SHIFT(M)))
          D3 = DBLE(REAL (Z1))
          D4 = DBLE(AIMAG(Z1))
          D5 = DBLE(REAL (Z2))
          D6 = DBLE(AIMAG(Z2))
          D7 = DBLE(REAL (Z3))
          D8 = DBLE(AIMAG(Z3))
          HRSUB(L,M) = HRSUB(L,M) + D1*D3 - D2*D4 + D5
          HISUB(L,M) = HISUB(L,M) + D1*D4 + D2*D3 + D6
          SRSUB(L,M) = D3 + D7
          SISUB(L,M) = D4 + D8
150       CONTINUE
C
C     COPY INTO UPPER TRIANGLE
C
         DO 160 L = 1,NBDS
         DO 160 M = 1,L-1
           HRSUB(M,L) =  HRSUB(L,M)
           HISUB(M,L) = -HISUB(L,M)
           SRSUB(M,L) =  SRSUB(L,M)
           SISUB(M,L) = -SISUB(L,M)
160        CONTINUE
C
C     SOLVE GENERALIZED EIGENVALUE PROBLEM FOR SUBSPACE MATRICES
C
        IFAIL = 0
        CALL F02GJF(NBDS,HRSUB,NDIM8,HISUB,NDIM8,SRSUB,NDIM8,
     +              SISUB,NDIM8,EPS,ALFR,ALFI,BETA,LMATV,VRSUB,
     +              NDIM8,VISUB,NDIM8,IWK,IFAIL)
        IF (IFAIL.NE.0) THEN
          WRITE(IOUT,*) '***ERROR*** FO2GJF FAILED IN COMPIT'
          WRITE(IOUT,*) ' IFAIL= ', IFAIL
          CALL EXIT
          ENDIF
        DO 170 L = 1,NBDS
          IF (ABS(ALFI(L)/ALFR(L)).GT.1.0D-04) THEN
            WRITE(IOUT,*) 'IMAGINARY PART OF EIGENVALUE TOO LARGE'
            WRITE(IOUT,*) 'REAL PART= ',ALFR(L),'IMAG PART= ',ALFI(L)
            ENDIF
170       CONTINUE
C
C     CALCULATE NEW EIGENVECTORS
C
        DO 180 L = 1,NBDS
        DO 180 I = 1,NH
          WK(I,L) = (0.0,0.0)
180       CONTINUE
        DO 190 L = 1,NBDS
        DO 190 M = 1,NBDS
          VR = SNGL(VRSUB(M,L))
          VI = SNGL(VISUB(M,L))
          Z1 = CMPLX(VR,VI)
          CALL CAXPY(NH,Z1,CEV(1,M),1,WK(1,L),1)
190       CONTINUE
C
C     NORMALIZE NEW EIGENVECTORS
C
        DO 210 L = 1,NBDS
          SNORM = SCNRM2(NH,WK(1,L),1)
          SNORM = 1.0/SNORM
          DO 200 I = 1,NH
200         CEV(I,L) = WK(I,L)*SNORM
210         CONTINUE
C
C     TEST FOR CONVERGENCE
C
C       WRITE(IUNIT8,*) ' ITERATION NUMBER ',ITS
        ERRMAX = 0.0
        DO 220 L = 1,NBDS
          ALFI(L) = EE2(L)
220       EE2(L) = SNGL(ALFR(L)/BETA(L))
        NDENT = 0
        ICONV = 0
        DO 250 L = 1,NBDS
          RMAX = 0.0
          DO 230 M = 1,NBDS
            RLAP = VRSUB(M,L)**2 + VISUB(M,L)**2
            IF (RLAP .GT. RMAX) THEN
              RMAX = RLAP
              IDENT = M
              ENDIF
230         CONTINUE
          IF (RMAX .LT. RDENT) THEN
            WRITE(IUNIT7,*) 'E ',L,' = ',EE2(L),' NOT IDENTIFIED',
     +      ' - OVERLAP TOO SMALL'
            GOTO 250
            ENDIF
          DO 240 M = 1,NDENT
            IF (IWK(M) .EQ. IDENT) THEN
              WRITE(IUNIT7,*) 'E ',L,' = ',EE2(L),' NOT IDENTIFIED',
     +        ' - CONFUSED WITH ANOTHER E'
              GOTO 250
              ENDIF
240         CONTINUE
          NDENT = NDENT + 1
          IWK(NDENT) = IDENT
          ERR = ABS(EE2(L) - ALFI(IDENT))
          IF (ERR .LT. RES) ICONV = ICONV+1
          ERRMAX = AMAX1(ERRMAX,ERR)
C         WRITE(IUNIT7,*) 'E ',L,' = ',EE2(L),' ERROR = ',ERR
250       CONTINUE
C
        IF (ICONV .EQ. NBDS) GOTO 270
C
C     KEEP EIGENVALUES WITHIN BOUNDS AND CALCULATE NEW BOUNDS
C
        IF (ITS .LT. NITMX) CALL BOUND(NBDS,NDIM8,EE2,UBOUND,IWK,ALFI,1)
C
C     END OF ITERATION LOOP
C
260     CONTINUE
C
C     EIGENVALUES NOT CONVERGED
C
      WRITE(IOUT,*) 'NOT CONVERGED AFTER ',NITMX,' ITERATIONS'
      WRITE(IOUT,*) 'MAXIMUM ERROR IN EIGENVALUE = ',ERRMAX,' RYD'
      GOTO 280
C
C     EIGENVALUES CONVERGED
C
270   WRITE(IOUT,*) 'CONVERGED AFTER ',ITS,' ITERATIONS'
C
280   CALL USAGE (N1,T1)
      WRITE(IUNIT7,290) T1-T0, N1-N0
290   FORMAT (' COMPIT - DIAGONALIZATION ',T30,F10.3,' SECONDS',
     +I10,' PAGE FAULTS')
C
      RETURN
      END
      SUBROUTINE ESHIFT (EE1,SHIFT,FAC,NDIM8,NDIM13,NA,NBDS)
C
C     SUBROUTINE TO SET THE COMPLEX SHIFTS OF THE EIGENVALUES NEEDED
C     TO PREVENT THE ITERATIVE DIAGONALIZATION FROM BECOMING SINGULAR.
C     THE SHIFTS ARE STORED IN SHIFT.
C     AT THE MOMENT THE SHIFTS ARE PURELY COMPLEX AND ARE COMPUTED
C     FROM THE AVERAGE SPACING BETWEEN THE EIGENVALUES MULTIPLIED BY
C     THE PARAMETER FAC WHICH IS SUPPLIED BY THE USER. TYPICALLY A
C     VALUE IN THE RANGE FAC=0.1-0.5 IS SATISFACTORY.
C
      COMPLEX SHIFT(NDIM8)
      REAL EE1(NDIM13)
      PARAMETER (RONE = 0.05)
C----------------------------------------------------------------------
C
      IF (NBDS .GT. 1) THEN
        DE = (EE1(NBDS)-EE1(1))/FLOAT(NBDS-1)
      ELSE IF (NBDS .EQ. 1) THEN
        IF (NA .GT. 1) DE = EE1(2) - EE1(1)
        IF (NA .EQ. 1) DE = RONE
        ENDIF
C
      DO 10 M = 1,NBDS
        SHIFT(M) = CMPLX(0.0,FAC*DE)
10      CONTINUE
C
      RETURN
      END
      SUBROUTINE BOUND (NBDS,NDIM8,E,UBOUND,IWK,RWK,INEWB)
C
C     KEEP EIGENVALUES STORED IN E WITHIN UPPER BOUNDS STORED
C     IN UBOUND. THE EIGENVALUES WITHIN THE BOUNDS FORM NEW
C     BOUNDS AND THE BOUNDS ARE ALSO UPDATED AND REORDERED.
C     RWK AND IWK ARE USED AS WORKSPACES.
C     INEWB : IF INEWB=+1 UPDATE BOUNDS WITH CONTENTS OF ARRAY E
C             IF INEWB=-1 DO NOT CHANGE BOUNDS
C     RPREC : EIGENVALUES EXCEEDING BOUNDS BY LESS THAN RPREC
C             ARE NOT REPORTED
C
      PARAMETER (RPREC = 1.0E-10)
      REAL E(NDIM8),UBOUND(NDIM8)
C     RWK is just a temporary workspace:
      REAL RWK(NDIM8)
      INTEGER IWK(NDIM8)
C
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C----------------------------------------------------------------------
C
C     KEEP E WITHIN BOUNDS
      CALL SCOPY (NBDS,E,1,RWK,1)
      DO 10 L = 1,NBDS
        IWK(L) = L
10      CONTINUE
      CALL VSRTR (RWK,NBDS,IWK)
      DO 20 L = 1,NBDS
        RMAX = E(IWK(L)) - UBOUND(L)
        IF (RMAX .GT. 0.0) THEN
          IF (RMAX .GT. RPREC) WRITE(IUNIT8,*) 'E ',IWK(L),' = ',
     +    E(IWK(L)),' E SET EQUAL TO BOUND = ',UBOUND(L)
          E(IWK(L)) = UBOUND(L)
          ENDIF
20      CONTINUE
C
C     UPDATE AND REORDER UPPER BOUNDS
      IF (INEWB .EQ. 1) THEN
        CALL SCOPY (NBDS,E,1,UBOUND,1)
        DO 30 L = 1,NBDS
          IWK(L) = L
30        CONTINUE
        CALL VSRTR (UBOUND,NBDS,IWK)
        ENDIF
C
      RETURN
      END
