      SUBROUTINE CONSTS
C
C.....FILES
C
C     DEFINITIONS:
C     2 ...... INPUT OF CRYSTAL STRUCTURE
C     3 ...... INPUT OF SPECIAL POINTS INFORMATION
C     4 ...... INPUT OF POTENTIAL FOR SELFCONSISTENCY
C     5 ...... ON-LINE INPUT
C     6 ...... ON-LINE OUTPUT
C     7 ...... ON-LINE OUTPUT, LESS IMPORTANT INFORMATION
C     8 ...... ON-LINE OUTPUT, EVEN LESS IMPORTANT INFORMATION
C     10 ..... OUTPUT OF POTENTIAL FOR SELFCONSISTENCY
C     11 ..... FILE FOR TEMPORARY STORAGE OF NONLOCAL MATRIX ELEMENTS
C     12 ..... BRIEF SUMMARY OF OUTPUT (FOR LONG-DISTANCE COMPUTING)
C     13 ..... TEMPORARY FILE FOR LOOP OVER K-POINTS
C     14 ..... USED BY 'EFERMI' TO STORE K-POINT EIGENVALUES
C     20+I ... I=1,2,...NTYPMX UNITS ASSOCIATED WITH ATOMIC FILES
C
C.....COMMON BLOCK FOR FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C
C     BOHR RADIUS, CONVERSION FACTOR FROM RYDBERGS TO EV,
C     RYDBERG TO ERG (1 RY = 2.179914E-11 ERG)
C
C     SOURCE FOR PHYSICAL CONSTANTS:
C     REV. MOD. PHYS. 41, 375, 1969.
C
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C.....COMMON BLOCK FOR KEEPING TRACK OF POSSIBLE WARNINGS
      COMMON /WARN/ IWARN
C
C     INITIALIZE COMMON BLOCK "FILES"
      INPUT  = 5
      IOUT   = 6
      IN290  = 3
      IN213  = 4
      ISTORE = 10
      IUNIT7 = 6
      IUNIT8 = 8
      ISTRUC = 2
      IVNLKK = 11
      ISUMRY = 12
      IKPTS  = 13
      IEVFIL = 14
      IFILEH = 15
      IFILEV = 11
C
      IWARN  = 0
C     PI AND SQRT(PI)
      PI  = 3.1415 92653 58979 32384 62643 D0
      SPI = 1.7724 53850 90551 60272 98167 D0
C     SOURCE FOR PHYSICAL CONSTANTS: REV. MOD. PHYS. 41, 375, 1969.
C     BOHR RADIUS:
      ABOHR  = 0.52917715 D0
C     CONVERSION FACTOR FROM RYDBERGS TO EV:
      RYEV   = 13.605826  D0
C     CONVERSION OF FORCE IN RYDBERG PER 'ULA' TO MILLIDYNES:
      RYDERG = 2.179914   D0
C
      RETURN
      END
