      SUBROUTINE DIAGON(HAMR,HAMI,CCR,CCI,CEV,EE1,EE2,DIAG,IWK,
     +  WK,CWF1,RWK,SHIFT,EISWRK,IFILEH,NDIM3,NDIM5,NDIM8,
     +  NDIM11,NDIM13,NA,NB,NBDS,NITMX,RES,ISWCH,LITER,IEVAL,
     +  LOWDIN,IWRCUA,LREAL,LPREV,IREC,FAC,
     +  IEVFIL,HRSUB,HISUB,SRSUB,SISUB,VRSUB,VISUB,ALFR,ALFI,BETA)
C
C     CONTROL OF NORMAL AND ITERATIVE DIAGONALIZATION
C     AND LOWDIN PERTURBATION SCHEMES
C
      REAL HAMR(NDIM11),HAMI(NDIM11),EISWRK(11*NDIM3),
     +  CCR(NDIM3,NDIM13),CCI(NDIM3,NDIM13),EE1(NDIM13),
     +  DIAG(NDIM5),EE2(NDIM8),RWK(NDIM8)
      DIMENSION CEV(NDIM5,NDIM8),CWF1(2*NDIM5),WK(NDIM5,NDIM8)
      DOUBLE PRECISION HRSUB(NDIM8,NDIM8),HISUB(NDIM8,NDIM8)
      DOUBLE PRECISION SRSUB(NDIM8,NDIM8),SISUB(NDIM8,NDIM8)
      DOUBLE PRECISION VRSUB(NDIM8,NDIM8),VISUB(NDIM8,NDIM8)
      DOUBLE PRECISION ALFR(NDIM8),ALFI(NDIM8),BETA(NDIM8)
      COMPLEX SHIFT(NDIM8)
      INTEGER IWK(NDIM8)
      LOGICAL LREAL,LITER,LOWDIN,LPREV
C
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C----------------------------------------------------------------------
C     FOR REAL HAMILTONIANS
      REAL CEV,WK,CMX
      CMX(X1,X2) = X1
      IF (.NOT. LREAL) WRITE(IOUT,*) '***DIAGON*** LREAL =',LREAL
C----------------------------------------------------------------------
C     FOR COMPLEX HAMILTONIANS
C     COMPLEX CEV,WK,CMX
C     CMX(X1,X2) = CMPLX(X1,X2)
C     IF (LREAL) WRITE(IOUT,*) '***DIAGON LREAL =',LREAL
C----------------------------------------------------------------------
C
      CALL USAGE (NP0,T0)
C
      IF (LITER) THEN
        NEVAL = NA
        NVECT = NA
      ELSE
        NEVAL = NBDS
        NVECT = NBDS
        IF (ISWCH .EQ. 3) NVECT = 0
        ENDIF
C
      CALL EIGEN (IOUT,HAMR,HAMI,NDIM3,NA,NEVAL,NVECT,IEISER,LREAL,
     +     EE1,CCR,CCI,EISWRK)
C
      IF (IEISER .NE. 0) THEN
        WRITE(IOUT,*) ' ******** EISPACK terminated with ERROR =',IEISER
        CALL EXIT
        ENDIF
C
      CALL USAGE (NP1,T1)
      WRITE(IUNIT7,90) NA,T1-T0, NP1-NP0
90    FORMAT(' Diagonalization (N=',I4,')',
     +       T30,F10.3,' seconds',I10,' page faults ')
C
      IF (LPREV .AND. NB .LE. 0) THEN
        WRITE (IOUT,*) 'DIAGON: NB=0. EISPACK results used'
        LPREV = .FALSE.
        ENDIF
C
      IF (LITER .AND. LPREV) THEN
        CALL RWEV (IEVFIL,IREC, -1 ,RWK,EE2,NREAD,NA+NB,
     +    NDIM5,NDIM8,CEV,LREAL)
        IF (NREAD .LT. NBDS) THEN
          WRITE (IOUT,*) 'Read eigenvectors and eigenvalues from file'
          WRITE (IOUT,*) 'READ ',NREAD,' bands is less than NBDS ',NBDS
          WRITE (IOUT,*) 'not sufficient - data from file not used'
          LPREV = .FALSE.
          ENDIF
        ENDIF
C
      IF (LPREV) THEN
        DO 5 J = 1,NBDS
5         EE2(J) = EE2(J)/RYEV
      ELSE 
        DO 10 J = 1,NBDS
        DO 10 I = 1,NA
10        CEV(I,J) = CMX(CCR(I,J),CCI(I,J))
        CALL SCOPY (NBDS,EE1,1,EE2,1)
        ENDIF
C
      IF (.NOT. (LITER .OR. LOWDIN)) RETURN
      IF (NB .LE. 0) RETURN
C
      IF (.NOT. LPREV) CALL LOWPER (IFILEH,NDIM5,NDIM8,NA,NB,NBDS,DIAG,
     +  EE2,CEV,CWF1,WK,RWK,LREAL)
C
      IF (LOWDIN) THEN
        IF (IEVAL .GT. 0) CALL EVAL (CEV,EE1,EE2,WK,CWF1,RWK,IFILEH,
     +  NDIM5,NDIM8,NA,NB,NBDS,IEVAL,IWRCUA,HRSUB,HISUB,SRSUB,SISUB,
     +  VRSUB,VISUB,ALFR,ALFI,BETA,IWK,LREAL)
      ELSE IF (LITER) THEN
        IF (      LREAL) CALL REALIT (IFILEH,NDIM3,NDIM5,NDIM8,NDIM13,
     +  NA+NB,NA,NBDS,CCR,CCI,DIAG,EE1,EE2,CEV,WK,CWF1,CWF1(NDIM5+1),
     +  RWK,HRSUB,HISUB,SRSUB,SISUB,VRSUB,VISUB,ALFR,ALFI,BETA,SHIFT,
     +  IWK,RES,NITMX,FAC,LREAL)
        IF (.NOT. LREAL) CALL COMPIT (IFILEH,NDIM3,NDIM5,NDIM8,NDIM13,
     +  NA+NB,NA,NBDS,CCR,CCI,DIAG,EE1,EE2,CEV,WK,CWF1,
     +  RWK,HRSUB,HISUB,SRSUB,SISUB,VRSUB,VISUB,ALFR,ALFI,BETA,SHIFT,
     +  IWK,RES,NITMX,FAC,LREAL)
        ENDIF
C
C     SORT BANDS USING IWK,RWK AND WK AS WORK ARRAYS
      DO 20 J = 1,NBDS
20      IWK(J) = J
      CALL VSRTR (EE2,NBDS,IWK)
      CALL SCOPY (NBDS,EE1,1,RWK,1)
      DO 30 J = 1,NBDS
30      EE1(J) = RWK(IWK(J))
      IF (LREAL) THEN
        DO 40 J = 1,NBDS
40        CALL SCOPY (NA+NB,CEV(1,J),1,WK(1,J),1)
        DO 50 J = 1,NBDS
50        CALL SCOPY (NA+NB,WK(1,IWK(J)),1,CEV(1,J),1)
      ELSE
        DO 60 J = 1,NBDS
60        CALL CCOPY (NA+NB,CEV(1,J),1,WK(1,J),1)
        DO 70 J = 1,NBDS
70        CALL CCOPY (NA+NB,WK(1,IWK(J)),1,CEV(1,J),1)
        ENDIF
C
      RETURN
      END
