      SUBROUTINE DIAHAM (NA,NB,GK,DIAG,
     +POTPAR,POTTYP,VNLIJ,NDIM1,NDIM5,NDIM20,
     +NLMAX,NPARAM,STRFAC,NTYPMX,VOLUM,ULA,RWF3,CWF1,
     +VNLL,CWF4,IWF5,LSTRES,NONLOC,CONV1,LREAL)
C
C     CALCULATE THE B PART OF THE DIAGONAL OF THE HAMILTONIAN
C
C.....POTENTIALS
      REAL VNLIJ(0:NDIM20,0:NDIM20,NLMAX,NTYPMX)
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      INTEGER POTTYP(NTYPMX)
C.....MATRIX ELEMENTS
      REAL RWF3(NTYPMX,NDIM5)
      DIMENSION CWF1(NDIM5),VNLL(NDIM5),CWF4(6,NDIM5)
      REAL DIAG(NDIM5)
      INTEGER IWF5(14*NDIM5)
C.....STRUCTURE FACTORS
      COMPLEX STRFAC(NTYPMX,NDIM1)
C.....WAVES
      DIMENSION GK(4,NDIM5)
C.....SWITCHES
      LOGICAL LSTRES,NONLOC,LREAL
      DOUBLE PRECISION CONV1
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C-----------------------------------------------------------------------
C     FOR COMPLEX HAMILTONIANS
C     COMPLEX CWF1,CWF4,VNLL,Z
C     REAL REALP
C     REALP(Z) = REAL(Z)
C     IF (LREAL) WRITE(IOUT,*) '***DIAHAM*** LREAL =',LREAL
C-----------------------------------------------------------------------
C     FOR REAL HAMILTONIANS
      REAL CWF1,CWF4,VNLL
      REAL REALP
      REALP(X) = X
      IF (.NOT. LREAL) WRITE(IOUT,*) '***DIAHAM*** LREAL =',LREAL
C-----------------------------------------------------------------------
C
C
      DO 10 I = NA+1,NA+NB
10      DIAG(I) = GK(4,I)**2*CONV1
C
      IF (NONLOC) THEN
        DO 20 I = NA+1,NA+NB
20        IWF5(I) = 1
        DO 30 I = NA+1,NA+NB
          CALL VNLKK (LSTRES,GK,I,I,I,
     +      POTPAR,POTTYP,VNLIJ,NDIM5,NDIM20,NLMAX,NPARAM,
     +      STRFAC,IWF5(1),NTYPMX,NDIM1,VOLUM,ULA,LREAL,
     +      IWF5(NDIM5+1)   ,IWF5(2*NDIM5+1) ,IWF5(3*NDIM5+1) ,
     +      IWF5(4*NDIM5+1) ,IWF5(5*NDIM5+1) ,IWF5(6*NDIM5+1) ,
     +      IWF5(7*NDIM5+1) ,IWF5(8*NDIM5+1) ,IWF5(9*NDIM5+1) ,
     +      IWF5(10*NDIM5+1),IWF5(11*NDIM5+1),IWF5(12*NDIM5+1),
     +      IWF5(13*NDIM5+1),RWF3,CWF4,VNLL)
C
30      DIAG(I) = DIAG(I) + REALP(VNLL(I))
        ENDIF
C
      RETURN
      END
