      SUBROUTINE EIGEN (IERR,AR,AI,NM,N,NVAL,NVECT,IERSIG,LREAL,
     +  EE,ZR,ZI,WORK)
C
C EIGENPROBLEM, USING EISPACK
C
C INPUT MATRIX IN SYMMETRIC STORAGE MODE, REAL AND IMAGINARY
C PARTS SEPARATELY.
C
C SUBROUTINES NEEDED: HTRIDI,IMTQLV,TINVIT,HTRIBK,TRIDIB,TRED1,TRBAK1
C
C INPUT DATA:
C
C   IERR ....  THE NUMBER OF OUTPUT UNIT ONTO WHICH THE ERROR
C              MESSAGES ARE TO BE WRITTEN
C   NM ...     MAXIMUM ALLOWED DIMENSION OF HAMILTONIAN, WHEN IT IS
C              VIEWED AS A SQUARE MATRIX NM X NM.
C              DIMENSION OF THE VECTOR OF EIGENVALUES EE,
C              ROW DIMENSION OF THE MATRIX OF EIGENVECTORS Z.
C   AR,AI ... LINEAR ARRAYS CONTAINING THE REAL AND IMAGINARY
C              PARTS OF THE HAMILTONIAN TO BE DIAGONALIZED,
C              IN SYMMETRIC STORAGE MODE.
C              IN OTHER WORDS, THE ELEMENTS OF THE MEANINGFUL
C              N X N PART OF HAMILTONIAN ARE PACKED INTO A
C              IN THE ORDER
C              11, 21, 22, 31, 32, 33 ..... N N ,
C              SO THAT ELEMENT (I,J), I.GE.J , IS PACKED INTO THE
C              LOCATION (I**2-I)/2+J.
C   N ......   DIMENSION OF THE MEANINGFUL PART OF THE HAMILTONIAN
C              WHEN IT IS VIEWED AS A SQUARE MATRIX  N X N SITUATED
C              IN THE UPPER-LEFT CORNER OF A MATRIX OF
C              DIMENSIONS NM X NM.
C   NVECT ...  HOW MANY EIGENVECTORS ARE TO BE CALCULATED.
C              THEY WILL CORRESPOND TO EIGENVALUES
C              EE(1),....,EE(NVECT).
C              IF NVECT .LE. 0 , ONLY EIGENVALUES ARE CALCULATED.
C
C OUTPUT DATA:
C
C   EE .....   EIGENVALUES, ARRANGED IN ASCENDING ORDER;
C              ONLY THE FIRST NVECT OF THEM ARE MEANINGFUL.
C   ZR, ZI...CORRESPONDING EIGENVECTORS, REAL AND IMAGINARY PARTS.
C              COLUMNWISE AND ORTHONORMALIZED.
C              ONLY THEIR UPPER-LEFT N X NVECT BLOCKS ARE MEANINGFUL.
C  WORK ...... WORKSPACE OF DIMENSION (NM,11)
C
C     IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION AR(*),AI(*)
      DIMENSION EE(NM),ZR(NM,NVAL),ZI(NM,NVAL)
      DIMENSION WORK(NM,11)
      LOGICAL LREAL
C-----------------------------------------------------------------------
C
C     CHECK DIMENSIONS
C
      IERSIG = - NM
      IF (N .GT. NM) THEN
        WRITE (IERR,120) N,NM
120     FORMAT(' EIGEN: N,NM INCOMPATIBLE:',2I6)
        CALL EXIT
        ENDIF
C
      IF (NVAL .GT. N) THEN
        WRITE (IERR,100) N
100     FORMAT (' EIGEN: NUMBER OF VALUES REQUESTED EXCEEDS DIMENSION'/
     +          ' NVAL SET TO',I6)
        NVAL = N
        ENDIF
C
      IF (NVECT .GT. NVAL) THEN
        WRITE (IERR,110) NVAL
110     FORMAT (' EIGEN: NUMBER OF VECTORS REQUESTED > NO. OF VALUES'/
     +          ' NVECT SET TO',I6)
        NVECT = NVAL
        ENDIF
C
      IERSIG = 0
C-----------------------------------------------------------------------
C
C     TRI-DIAGONALIZATION:
C
C     REAL SYMMETRIC MATRICES
C
      IF (LREAL) THEN
        CALL TRED1(N,AR,WORK(1,1),WORK(1,2),WORK(1,3),WORK(1,5))
      ELSE
C
C       COMPLEX HERMITIAN MATRICES
C
        CALL HTRIDI (N,AR,AI,WORK(1,1),WORK(1,2),WORK(1,3),
     +    WORK(1,10),WORK(1,4),WORK(1,5))
        ENDIF
C
C      COLUMNS 4 ... 8 OF 'WORK' ARE THE WORKING
C      ARRAYS RV1 ... RV5 OF THE STANDARD EISPACK DESCRIPTION;
C      SIMILARLY, THE COLUMNS 1,2,3 OF WORK CORRESPOND TO D,E,E2.
C      WORKING FIELD WORK(1,10+11) IS TAU AND WORK(1,9) IS IND.
C
C-----------------------------------------------------------------------
C
      IF (NVAL .GT. N/4) THEN
C
C       WHEN MORE THAN 1/4 OF ALL EGENVALUES ARE REQUESTED,
C       IT IS MORE EFFICIENT TO USE IMTQLV THAN TRIDIB.
C       WRITE (6,*) 'CALLING IMTQLV'
C
        CALL IMTQLV(N,WORK(1,1),WORK(1,2),WORK(1,3),EE,WORK(1,9),
     +    IERSIG,WORK(1,4) )
C
        IF(IERSIG .LE. NVAL .AND. IERSIG .GT.0) THEN
C
          WRITE  (IERR,1000) IERSIG
1000      FORMAT ('0SUBROUTINE EIGEN - ERROR:'/
     +            ' IN THE SUBROUTINE IMTQLV THE',I4,
     +            '-TH EIGENVALUE HAS NOT BEEN DETERMINED'/
     +            '0 AFTER 30 ITERATIONS.')
          RETURN
C
        ELSE IF (IERSIG .GT. NVAL) THEN
C
C         THE HIGHER-THAN-REQUESTED EIGENVALUES WERE INCORRECT:
          WRITE  (IERR,1005) IERSIG, NVAL
1005      FORMAT ('0SUBROUTINE EIGEN - WARNING :'/
     +            ' IN THE SUBROUTINE IMTQLV THE',I4,
     +            '-TH EIGENVALUE HAS NOT BEEN DETERMINED'/
     +            ' AFTER 30 ITERATIONS. BEWARE: THE',I4,
     +            ' EIGENVALUES ARE CORRECT AND ORDERED -'/
     +            ' - BUT MAY NOT BE THE SMALLEST EIGENVALUES.'/
     +            ' EXECUTION CONTINUES.')
C
        ENDIF
C
C-----------------------------------------------------------------------
C
      ELSE
C
C       WRITE (6,*) 'CALLING TRIDIB'
        EPS1 = - 1.0
C
        CALL TRIDIB (N,EPS1,WORK(1,1),WORK(1,2),WORK(1,3),
     +    RLB,RUB,1,NVAL,EE,WORK(1,9),IERSIG,WORK(1,4),WORK(1,5))
C
        IF (RLB .LT. -10.0 .OR. RUB .GT. 10.0) WRITE(IERR,1008) RLB,RUB
1008    FORMAT('0EIGEN - WARNING - EIGENVALUE BOUNDS =',2E15.6)
C
        IF (IERSIG .NE. 0) THEN
          WRITE (IERR,1010) IERSIG
1010      FORMAT(' EIGEN - TRIDIB RETURNED WITH ERROR =',I10)
          IF (IERSIG .EQ. 3*N+1)
     +      WRITE (IERR,*) 'NON-UNIQUE EIGENVALUES AT LOWER BOUND'
          IF (IERSIG .EQ. 3*N+2)
     +      WRITE (IERR,*) 'NON-UNIQUE EIGENVALUES AT UPPER BOUND'
          ENDIF
C
        ENDIF
C
      IF (NVECT .LE. 0) RETURN
C
C-----------------------------------------------------------------------
C
C     FIND EIGENVECTORS
C
      CALL TINVIT(NM,N,WORK(1,1),WORK(1,2),WORK(1,3),NVECT,EE,
     +  WORK(1,9), ZR, IERSIG,
     +  WORK(1,4),WORK(1,5),WORK(1,6),WORK(1,7),WORK(1,8))
C
      IF(IERSIG .NE. 0) THEN
        WRITE  (IERR,1020) ABS(IERSIG)
 1020   FORMAT ('0SUBROUTINE EIGEN - ',
     +          ' IN THE SUBROUTINE TINVIT, THE',I4,'-TH EIGENVECTOR'/
     +          ' FAILED TO CONVERGE IN 5 ITERATIONS - RETURN')
        RETURN
        ENDIF
C
C-----------------------------------------------------------------------
C
C     EIGENVECTOR BACKTRANSFORM
C
      IF (LREAL) THEN
        CALL TRBAK1 (NM,N,AR,WORK(1,2),NVECT,ZR)
      ELSE
        CALL HTRIBK (NM,N,AR,AI,WORK(1,10),NVECT,ZR,ZI)
        ENDIF
C
      RETURN
      END
