      SUBROUTINE TRED1(N,A,D,E,E2,RV5)
      INTEGER I,J,L,N,IROWI,II,IL
      REAL A(*),D(*),E(*),E2(*),RV5(*)
      REAL F,G,H,SCALE,ONE,ZERO
C
C     THIS SUBROUTINE IS A TRANSLATION OF THE ALGOL PROCEDURE TRED1,
C     NUM. MATH. 11, 181-195(1968) BY MARTIN, REINSCH, AND WILKINSON.
C     HANDBOOK FOR AUTO. COMP., VOL.II-LINEAR ALGEBRA, 212-226(1971).
C
C     THIS SUBROUTINE REDUCES A REAL SYMMETRIC MATRIX
C     TO A SYMMETRIC TRIDIAGONAL MATRIX USING
C     ORTHOGONAL SIMILARITY TRANSFORMATIONS.
C
C     ON INPUT-
C
C        N IS THE ORDER OF THE MATRIX,
C
C        IROW CONTAINS THE INDEX OF THE FIRST ELEMENT IN ROW I,
C
C        A CONTAINS THE REAL SYMMETRIC INPUT MATRIX.  ONLY THE
C          LOWER TRIANGLE OF THE MATRIX NEED BE SUPPLIED.
C          IT IS STORED IN PACKED FORM  A11,A12,A22,A31...
C
C        RV5 IS A TEMPORARY STORAGE ARRAY
C
C     ON OUTPUT-
C
C        A CONTAINS INFORMATION ABOUT THE ORTHOGONAL TRANS-
C          FORMATIONS USED IN THE REDUCTION IN ITS STRICT LOWER
C          TRIANGLE.  THE FULL UPPER TRIANGLE OF A IS UNALTERED,
C
C        D CONTAINS THE DIAGONAL ELEMENTS OF THE TRIDIAGONAL MATRIX,
C
C        E CONTAINS THE SUBDIAGONAL ELEMENTS OF THE TRIDIAGONAL
C          MATRIX IN ITS LAST N-1 POSITIONS.  E(1) IS SET TO ZERO,
C
C        E2 CONTAINS THE SQUARES OF THE CORRESPONDING ELEMENTS OF E.
C          E2 MAY COINCIDE WITH E IF THE SQUARES ARE NOT NEEDED.
C
C     QUESTIONS AND COMMENTS SHOULD BE DIRECTED TO B. S. GARBOW,
C     APPLIED MATHEMATICS DIVISION, ARGONNE NATIONAL LABORATORY
C
C     ------------------------------------------------------------------
C
C     STATEMENT FUNCTION DEFINING THE CORRESPONDENCE BETWEEN QUADRATIC
C     AND PACKED STORAGE OF MATRICES AR,AI. I >= J IS REQUIRED.
      LOC(I,J) = (I*I - I)/2 + J
      DATA ONE,ZERO /1.0,0.0/
C
      WRITE (6,*) 'CALLED TRED1 - CRAY VERSION'
C
      DO 100 I = 1,N
        II = LOC(I,I)
        D(I) = A(II)
100     CONTINUE
C
      DO 300 I = N,1,-1
         L = I - 1
         IROWI = LOC(I,0)
         I1    = IROWI + 1
C     ********** SCALE ROW (ALGOL TOL THEN NOT NEEDED) **********
         IF (L .EQ. 0) THEN
           SCALE = ZERO
         ELSE
           SCALE = SASUM (L,A(I1),1)
           ENDIF
         IF (SCALE .EQ. ZERO) THEN
           E(I) = ZERO
           E2(I) = ZERO
           GO TO 290
           ENDIF
         F = ONE/SCALE
         CALL SSCAL (L,F,A(I1),1)
         H = SDOT (L,A(I1),1,A(I1),1)
         E2(I) = SCALE * SCALE * H
C
         IL = IROWI + L
         F = A(IL)
         G = -SIGN(SQRT(H),F)
         E(I) = SCALE * G
         H = H - F * G
         A(IL) = F - G
         IF (L .EQ. 1) GO TO 270
C
C     ********** FORM ELEMENT OF A*U **********
         E(1) = A(1) * A(I1)
         DO 240 J = 2,L
            J1 = LOC(J,1)
            E(J) = SDOT (J,A(J1),1,A(I1),1)
            CALL SAXPY (J-1,A(IROWI+J),A(J1),1,E,1)
  240    CONTINUE
         F = ONE/H
         CALL SSCAL (L,F,E,1)
         F = SDOT (L,E,1,A(I1),1)
         H = F / (H + H)
C     ********** FORM REDUCED A **********
         DO 260 J = 1,L
            IJ = IROWI + J
            F = -A(IJ)
            G = -E(J) - H * F
            E(J) = -G
            J1 = LOC(J,1)
            CALL SAXPY (J,F,E,1,A(J1),1)
            CALL SAXPY (J,G,A(I1),1,A(J1),1)
260         CONTINUE
C
270      CALL SSCAL (L,SCALE,A(I1),1)
290      H = D(I)
         II = IROWI + I
         D(I) = A(II)
         A(II) = H
300   CONTINUE
C
      RETURN
C     ********** LAST CARD OF TRED1 **********
      END
      SUBROUTINE TRBAK1(NM,N,A,E,M,Z)
      INTEGER I,J,L,M,NM,N,IROWI,IL
      REAL A(*),E(*),Z(NM,*)
      REAL S,ZERO
C
C     THIS SUBROUTINE IS A TRANSLATION OF THE ALGOL PROCEDURE TRBAK1,
C     NUM. MATH. 11, 181-195(1968) BY MARTIN, REINSCH, AND WILKINSON.
C     HANDBOOK FOR AUTO. COMP., VOL.II-LINEAR ALGEBRA, 212-226(1971).
C
C     THIS SUBROUTINE FORMS THE EIGENVECTORS OF A REAL SYMMETRIC
C     MATRIX BY BACK TRANSFORMING THOSE OF THE CORRESPONDING
C     SYMMETRIC TRIDIAGONAL MATRIX DETERMINED BY  TRED1.
C
C     ON INPUT-
C
C        N IS THE ORDER OF THE MATRIX,
C
C        IROW CONTAINS THE INDEX OF THE FIRST ELEMENT IN ROW I,
C
C        A CONTAINS INFORMATION ABOUT THE ORTHOGONAL TRANS-
C          FORMATIONS USED IN THE REDUCTION BY  TRED1
C          IN ITS STRICT LOWER TRIANGLE,
C          IT IS STORED IN PACKED FORM  A11,A12,A22,A31...
C
C        E CONTAINS THE SUBDIAGONAL ELEMENTS OF THE TRIDIAGONAL
C          MATRIX IN ITS LAST N-1 POSITIONS.  E(1) IS ARBITRARY,
C
C        M IS THE NUMBER OF EIGENVECTORS TO BE BACK TRANSFORMED,
C
C        Z CONTAINS THE EIGENVECTORS TO BE BACK TRANSFORMED
C          IN ITS FIRST M*N POSITIONS.
C
C     ON OUTPUT-
C
C        Z CONTAINS THE TRANSFORMED EIGENVECTORS
C          IN ITS FIRST M*N POSITIONS.
C
C     NOTE THAT TRBAK1 PRESERVES VECTOR EUCLIDEAN NORMS.
C
C     QUESTIONS AND COMMENTS SHOULD BE DIRECTED TO B. S. GARBOW,
C     APPLIED MATHEMATICS DIVISION, ARGONNE NATIONAL LABORATORY
C
C     ------------------------------------------------------------------
C
C     STATEMENT FUNCTION DEFINING THE CORRESPONDENCE BETWEEN QUADRATIC
C     AND PACKED STORAGE OF MATRICES AR,AI. I >= J IS REQUIRED.
      LOC(I,J) = (I*I - I)/2 + J
      DATA ZERO /0.0/
C
      IF (M .EQ. 0) GO TO 200
      IF (N .EQ. 1) GO TO 200
C
      DO 140 I = 2, N
         L = I - 1
         IROWI = LOC(I,0)
         I1 = IROWI + 1
         IL = IROWI + L
         IF (E(I) .EQ. ZERO) GO TO 140
C
         DO 130 J = 1, M
            S = SDOT (L,A(I1),1,Z(1,J),1)
            S = (S / A(IL)) / E(I)
            CALL SAXPY (L,S,A(I1),1,Z(1,J),1)
  130    CONTINUE
C
  140 CONTINUE
C
  200 RETURN
C     ********** LAST CARD OF TRBAK1 **********
      END
     
