      SUBROUTINE EPS1 (NEL,VOLUM,ULA,Q2,EXFACT,FERMIK,EPSQ)
C                          WRITTEN ON NOVEMBER 19TH, 1979
C DIELECTRIC FUNCTION OF FREE-ELECTRON GAS, TAKING INTO
C ACCOUNT EXCHANGE AND CORRELATION
C TREATMENT DUE TO OVERHAUSER, PHYS. REV. B 3 (1971) 1888,
C MODIFIED BY R.M.MARTIN (UNPUBLISHED).
C FREE ELECTRON GAS WITH COULOMB INTERACTIONS, BASED ON THE
C ASSUMPTION THAT THE EXCHANGE POTENTIAL IS LOCAL AND
C PROPORTIONAL TO RO**(1/3).
C SUBROUTINES NEEDED: NONE
C
C INPUT DATA
C      NEL .... TOTAL NUMBER OF VALENCE ELECTRONS PER UNIT CELL
C               (E.G. NEL=8 FOR SILICON OR GAAS PROVIDING THAT
C               PRIMITIVE UNIT CELL IS USED), SO THAT
C               NEL/VOLUM IS THE DENSITY OF (FREE) ELECTRONS.
C      VOLUM .. VOLUME OF THE ELEMENTARY UNIT CELL SPANNED
C               BY THE VECTORS A1, A2, A3.  UNITS: CUBE OF AN
C               ARBITRARY UNIT OF LENGTH, ULA**3
C      ULA .... THE LENGTH IN ANGSTROEMS OF THE ARBITRARY UNIT
C               OF LENGTH (E.G. LATTICE CONSTANT, OR 1 ANGSTROEM
C               OR BOHR RADIUS, ETC.)
C      Q2 ..... SQUARED LENGTH OF WAVEVECTOR, IN UNITS
C               (2*PI/ULA)**2 .
C               Q2=(2.*FERMIK)**2           IS  ALLOWED
C               FOR Q2=0. THE DIELECTRIC FUNCTION IS INFINITE.
C               BUT, IF ABS(Q2).LE.1.E-10, THE SUBROUTINE WILL
C               EVALUATE EPSQ CORRESPONDING TO Q2=1.E-10.
C               Q2.LT.0 DOES NOT MAKE SENSE BUT THE SUBROUTINE
C               WORKS WITH ABS(Q2), ANYHOW.
C      EXFACT ... EXCHANGE FACTOR ALPHA OCCURRING IN THE
C               SLATER'S FORMULA FOR EXCHANGE AND CORRELATION,
C               IN THE PREFACTOR OF RO**(1/3).
C               EXFACT=0. CORRESPONDS TO RANDOM-PHASE APPROXIMATION
C                          (I.E. NO EXCHANGE AT ALL)
C               EXFACT=0.666666 CORRESPONDS TO APPROXIMATING EXCHANGE
C                          BY RO**1/3 WITH THE KOHN-SHAM PREFACTOR.
C               EXFACT=1. CORRESPONDS TO THE SLATER'S PREFACTOR
C OUTPUT DATA
C      FERMIK ... FERMI-WAVEVECTOR K(F), IN UNITS 2PI/ULA
C      EPSQ ... DIELECTRIC FUNCTION EPS(Q), DIMENSIONLESS
C               (EVALUATED IN ATOMIC UNITS).
C               IF EXFACT=0, THEN EPSQ IS GIVEN BY A FORMULA
C               IN HARRISON, EQ.(2.49) OR ZIMAN, EQ.(5.33),
C               WHICH IS THE HARTREE OR LINDHARD FORMULA
C               (AND IN WHICH WE HAD TO PUT E=M=H=1.)
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
C
C FERMI WAVEVECTOR, IN ATOMIC UNITS ABOHR**(-1):
C               (THIS ARE THE UNITS USED IN ALL TEXTBOOKS;
C               2PI FACTOR IS ALREADY INCLUDED IN THE DEFINITION
C               AND WE DO NOT NEED TO INSERT IT INTO ANY FORMULA
C               CONTAINING K(F):)
C     WVKF = (3.*PI**2*FLOAT(NEL)/VOLUM) ** (1./3.) * ABOHR/ULA
C THE SAME FERMI WAVEVECTOR, IN UNITS 2PI/ULA:
      FERMIK = (0.375*FLOAT(NEL)/(VOLUM*PI)) **(1./3.)
C AND ONCE MORE THE SAME, IN UNITS ABOHR**(-1):
      WVKF = 2.0*PI*FERMIK*ABOHR/ULA
C
      IF (ABS(Q2) .LT. 1.0E-10) THEN
C       SPECIAL CASE: X=0
        FFF = 1.0
        X   = 5.0E-6/FERMIK
      ELSE
        X  = 0.5*SQRT(ABS(Q2))/FERMIK
        IF (ABS(1.0 - X) .LT. 1.0E-4) THEN
C         SPECIAL CASE: X=1
          FFF = 0.5
        ELSE
C         STANDARD CASE:
          FFF = 0.5 + (1.0 - X*X )/(4.0*X) * ALOG(ABS((1.0+X)/(1.0-X)))
        ENDIF
      ENDIF
C
      EPSQ = 1.0 + FFF*(1.0/( X*X ) - EXFACT*1.5)/(PI*WVKF)
      RETURN
      END
