      SUBROUTINE GSHELL (IGLIST,NGTOT,NG1,NG2,NG3,A1,A2,A3,B1,B2,B3,
     + G2TAB,NTAB,NDIM1,NDIM2,R,IB,NC,LI)
C
C     SORT IGLIST AND G2TAB INTO STARS OF EQUIVALENT G-VECTORS
C     BY APPLYING THE OPERATIONS OF THE CRYSTAL TO EACH SHELL.
C
C     SHELLS WITH INEQUIVALENT STARS WILL BE SPLIT, AND INCOMPLETE
C     SHELLS WILL BE AMENDED BY VECTORS FROM THE NEXT SHELL (PROVIDED,
C     OF COURSE, THAT THIS IS THE CORRECT FIX !)
C
C     G2TAB AND IGLIST WILL THUS CONTAIN ALL THE STARS OF G-VECTORS.
C
      DIMENSION IGLIST(3,NDIM1),G2TAB(NDIM2),NTAB(NDIM2)
      DIMENSION A1(3),A2(3),A3(3),B1(3),B2(3),B3(3)
      DIMENSION A(3,3),B(3,3),RR(49,3,3),IGG(3),V(3)
      DIMENSION R(49,3,3),IB(48)
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C     CONTROLLING THE PRINTOUT OF MESSAGES:
      PARAMETER (MAXPRT = 2)
C----------------------------------------------------------------------
C
      DO 100 I = 1,3
        A(I,1) = A1(I)
        A(I,2) = A2(I)
        A(I,3) = A3(I)
        B(I,1) = B1(I)
        B(I,2) = B2(I)
        B(I,3) = B3(I)
100     CONTINUE
C
C     EXPRESS THE ROTATIONS IN THE B1,B2,B3 BASIS:
C
      DO 110 IR = 1,48
        DO 110 I = 1,3
        DO 110 J = 1,3
          RR(IR,I,J) = 0.0
          DO 110 K = 1,3
          DO 110 L = 1,3
            RR(IR,I,J) = RR(IR,I,J) + A(K,I) * R(IR,K,L) * B(L,J)
110         CONTINUE
C     WRITE (IUNIT8,*) 'ROTATIONS IN B1,B2,B3 BASIS:'
C     WRITE (IUNIT8,122)
C    +  (IB(IC),((RR(IB(IC),I,J),J=1,3),I=1,3),IC=1,NC)
C122     FORMAT( 48( 1X,I3,3(3F8.2,5X)/ ) )
C----------------------------------------------------------------------
C
      ISPLIT = 0
      IMERGE = 0
C
      DO 250 ISHELL = 1,NDIM2
      IF (G2TAB(ISHELL) .LT. 0.0) GOTO 260
130   NMIN = NTAB(ISHELL)
      NMAX = NTAB(ISHELL + 1) - 1
      IF (NMIN .EQ. NMAX) GOTO 250
      IF (NMIN .LE. 0 .OR. NMAX .LE. 0) THEN
        G2TAB(ISHELL) = 0.0
        GOTO 260
        ENDIF
C
C     SORTING POINTER: SHOWS THE NEXT ELEMENT WHICH HAS NOT BEEN
C                      INCLUDED IN THE STAR.
      IPOINT = NMIN + 1
C
      INVADD = 0
C     IF CRYSTAL DOES NOT CONTAIN INVERSION, ADD IT HERE:
      IF (LI .EQ. 0) INVADD = 1
      DO 200 INVERS = 0,INVADD
C
      IG1 = IGLIST(1,NMIN)
      IG2 = IGLIST(2,NMIN)
      IG3 = IGLIST(3,NMIN)
      IF (INVERS .EQ. 1) THEN
        IG1 = -IG1
        IG2 = -IG2
        IG3 = -IG3
        ENDIF
C     TRY ALL THE ROTATIONS
      DO 200 IC = 1,NC
        IR = IB(IC)
        DO 140 I = 1,3
          IGG(I) = NINT( RR(IR,I,1)*IG1 + RR(IR,I,2)*IG2 +
     +                   RR(IR,I,3)*IG3 )
140       CONTINUE
C     LOCATE IGG IN IGLIST. THIS IS A LOOKUP BUT WE DO NOT
C     BOTHER TO SET UP THE LOOKUP LIST.
      DO 150 IG = NMIN,NMAX
        IF (IGG(1) .NE. IGLIST(1,IG)) GOTO 150
        IF (IGG(2) .NE. IGLIST(2,IG)) GOTO 150
        IF (IGG(3) .EQ. IGLIST(3,IG)) GOTO 190
150     CONTINUE
C
C     ERROR IN ROTATION
C
C     PRINT-OUT ONLY FOR FIRST 'MAXPRT' MERGES
      IF (IMERGE .LE. MAXPRT) WRITE (IUNIT7,160)
     +   ISHELL,IG1,IG2,IG3,IR,IGG,ISHELL
160   FORMAT('0SUBROUTINE GSHELL - NOTICE - SHELL NO.',I5/
     +' THE VECTOR ',3I5,' ROTATED BY R(',I3,')'/
     +' TO BECOME ',3I5,' COULD NOT BE LOCATED IN SHELL NO.',I5)
C
C     TRY WHETHER THE VECTOR IS FOUND IN THE NEXT SHELL
      DO 175 IG = NTAB(ISHELL+1),NTAB(ISHELL+2) - 1
        IF (IGG(1) .NE. IGLIST(1,IG)) GOTO 175
        IF (IGG(2) .NE. IGLIST(2,IG)) GOTO 175
        IF (IGG(3) .EQ. IGLIST(3,IG)) GOTO 180
175     CONTINUE
C
      WRITE (IUNIT7,165) NMIN,NMAX
165   FORMAT ('0*** TROUBLES ***'/
     +  ' THE SHELL FROM ',I5,' TO',I5,' CONTAINS:')
      DO 170 IG = NMIN,NMAX
        WRITE (IUNIT7,*) IGLIST(1,IG),IGLIST(2,IG),IGLIST(3,IG)
170     CONTINUE
      WRITE (IUNIT7,*) 'PROCEEDING TO NEXT SHELL ......'
      GOTO 250
C
180   IMERGE = IMERGE + 1
      IF (IMERGE .LE. MAXPRT) WRITE (IOUT,182) IG,ISHELL,ISHELL+1
182   FORMAT (' VECTOR LOCATED IN IGLIST NO.',I10/
     +  ' WE WILL MERGE THE TWO SHELLS ',I5,' AND ',I5)
      DO 185 IS = (ISHELL + 1),(NDIM2 - 1)
        NTAB(IS) = NTAB(IS+1)
        G2TAB(IS) = G2TAB(IS+1)
185     CONTINUE
      GOTO 130
C
C     ROTATED G-VECTOR WAS LOCATED
C
190   IF (IG .LT. IPOINT) THEN
C       WAS IGLIST(*,IG) ALREADY ENCOUNTERED IN SORTING ?
        GOTO 200
      ELSE IF (IG .GT. IPOINT) THEN
C       INTERCHANGE VECTORS
        IF (IPOINT .GT. NMAX) THEN
          WRITE (IOUT,*) 'SUBROUTINE GSHELL - ERROR IN SORTING IGLIST'
          NGTOT = 0
          RETURN
          ENDIF
        DO 195 I = 1,3
          IGL = IGLIST(I,IPOINT)
          IGLIST(I,IPOINT) = IGLIST(I,IG)
          IGLIST(I,IG) = IGL
195       CONTINUE
        ENDIF
C     INCREMENT POINTER (THE ONLY ACTION IF IG=IPOINT ABOVE)
      IPOINT = IPOINT + 1
C
200   CONTINUE
C----------------------------------------------------------------------
C
C     SPLIT SHELL OR CONTINUE ?
C
      IF (IPOINT .GT. NMAX) GOTO 250
C     SHELL HAS MORE THAN ONE STAR - RESEQUENCE NTAB,G2TAB
      IF (G2TAB(NDIM2 - 1) .GE. 0.0) THEN
        WRITE (IOUT,205) ISHELL,NMIN,NMAX,NDIM2
205     FORMAT('0SUBROUTINE GSHELL - FATAL ERROR - WHILE SPLITTING',
     +' SHELL',I5,' FROM',I5,' TO',I5/'0NDIM2 =',I10,
     +' IS TOO SMALL TO ACCOMODATE ALL STARS')
        CALL EXIT
        ENDIF
      DO 210 IS = NDIM2,(ISHELL+2),-1
        G2TAB(IS) = G2TAB(IS-1)
        NTAB(IS)  = NTAB(IS-1)
210     CONTINUE
C     THE NEW SHELL BEGINS AT IPOINT AND HAS SAME LENGTH AS BEFORE
      NTAB(ISHELL+1) = IPOINT
      G2TAB(ISHELL+1) = G2TAB(ISHELL)
C
      ISPLIT = ISPLIT + 1
C     PRINT-OUT ONLY FOR FIRST 'MAXPRT' SPLITS:
C
      IF (ISPLIT .LE. MAXPRT) THEN
        WRITE (IUNIT7,220) ISHELL,NMIN,NMAX
220     FORMAT(' SUBROUTINE GSHELL - SHELL NO.',I5,' FROM',I5,
     +    ' TO',I5,' SPLIT INTO TWO:')
        CALL GCODE (IGLIST(1,NMIN),NG1,NG2,NG3,B1,B2,B3,IG1,IG2,IG3,V)
        WRITE (IUNIT7, 230) NMIN, IPOINT-1, IG1, IG2, IG3, V
        CALL GCODE (IGLIST(1,IPOINT),NG1,NG2,NG3,B1,B2,B3,IG1,IG2,IG3,V)
        WRITE (IUNIT7,230) IPOINT,NMAX,IG1,IG2,IG3,V
230     FORMAT(' SHELL FROM ',I5,' TO',I5,' (TYPICAL G =',3I4,
     +    ' OR',3F10.4,' )' )
        ENDIF
C
250   CONTINUE
C
C----------------------------------------------------------------------
C
260   IF (ISPLIT .GT. 0 .OR. IMERGE .GT. 0)
     +  WRITE (IOUT,1000) ISPLIT,IMERGE
1000    FORMAT('0*** GSHELL *** ',I5,' SHELLS SPLIT AND ',
     +  I5,' SHELLS MERGED'/)
      RETURN
      END
