      SUBROUTINE K207 (NSPIN,
     +  NDIM1,NDIM2,NDIM3,NDIM4,NDIM5,NDIM6,NDIM7,NDIM8,NDIM9,
     +  NDIM10,NDIM11,NDIM12,NDIM13,NDIM20,NLMAX,NPARAM,NQMAX,NRUN,
     +  NTYPMX,XKAPA,NATOM,G2TAB,TY,F0,NTAB,IGLIST,LIST,
     +  NG1MAX,NG2MAX,NG3MAX,
     +  POTPAR,ZKAPA,POTTYP,POTXC,POTFIL,VNLIJ,POTWRK,
     +  WVLIST,LWGHT,WEIGHT,
     +  FORCII,FORCEL,FORCWK,FORCLO,IFORC,INVERS,NOFORC,
     +  STRFAC,SATGR,SATGI,LREAL,HAMR,HAMI,CCR,CCI,EE1,EE2,SORT,
     +  EIGVAL,NBANDS,WOCC,OCC,IWK,DIAG,OCCLM,
     +  CWF1,CEV,RSPACE,VNLL,CWF4,RWF3,IWF5,LWORK,CFTWRK,EISWRK,
     +  VIONIC,VGTOT,VNEW,ROKG,ROTOT,MUXCG,EXCG,ROTEMP,
     +  NPWCHI,IDIFF,IPG,INDEX,HKMIX,XKMIX,FKMIX,YK,SK,SKHK,SMHY,HKOLD,
     +  LISTAB,GK,DX,IEVFIL,IFILEH,IFILEV,
     +  WK,RWK,SHIFT,HRSUB,HISUB,SRSUB,SISUB,VRSUB,VISUB,
     +  ALFR,ALFI,BETA,CHI,INVCHI,RTABLE,RLIST,RUNPAR)
C
C
C     Selfconsistent calculation of band structure and total energy,
C     Hellmann-Feynman forces and stress for semiconductors and metals.
C
C
C.....LATTICE STRUCTURE
      REAL XKAPA(3,NDIM9),A1(3),A2(3),A3(3),B1(3),B2(3),B3(3),
     +  V(3,48),R(49,3,3),RB(48,3,3),G2TAB(NDIM2),STRAIN(6),GMTRIC(3,3)
      INTEGER TY(NDIM9),F0(48,NDIM9),IB(48),NTAB(NDIM2),NATOM(NDIM9)
      INTEGER IGLIST(3,NDIM1)
      INTEGER LIST(-NG1MAX:NG1MAX,-NG2MAX:NG2MAX,-NG3MAX:NG3MAX)
C.....ATOMIC POTENTIALS
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      REAL ZKAPA(NDIM9)
      INTEGER POTTYP(NTYPMX), POTXC(NTYPMX)
      CHARACTER*80 POTFIL(NTYPMX)
      REAL VNLIJ(0:NDIM20,0:NDIM20,NLMAX,NTYPMX,NSPIN)
C.....SPECIAL POINTS
      REAL WVLIST(3,NDIM10)
      INTEGER LWGHT(NDIM10)
      DOUBLE PRECISION WEIGHT(NDIM10), TEST
C.....FORCE ARRAYS
      DOUBLE PRECISION FORCII(3,NDIM9), FORCEL(3,NDIM9), FORCLO(3,NDIM9)
      DOUBLE PRECISION FORCWK(3,NDIM9)
      INTEGER IFORC(NDIM9),INVERS(NDIM9)
      LOGICAL NONLOC,LFORCE,NLFORC,LSTRES,NLSTRS,NOFORC(NDIM9)
C.....STRESS ARRAYS
      DOUBLE PRECISION STRSII(3,3),STRSLO(3,3)
      REAL STRSAZ(3,3),STRSKE(3,3),STRSHA(3,3),
     +     STRSXC(3,3),STRSNL(3,3),
     +     STRES1(3,3),STRES2(3,3),STRES3(3,3)
      DOUBLE PRECISION SWF2(6)
C.....ATOMIC STRUCTURE FACTORS
      COMPLEX STRFAC(NTYPMX,NDIM1)
      REAL SATGR(NDIM9,NDIM1),SATGI(NDIM9,NDIM1)
C.....HAMILTONIAN AND EIGENVECTORS
      REAL HAMR(NDIM11),HAMI(NDIM11),CCR(NDIM3,NDIM13),
     +  CCI(NDIM3,NDIM13),DIAG(NDIM5)
C.....EIGENVALUES AND OCCUPATION NUMBERS
      REAL EE1(NDIM13),EE2(NDIM8),SORT(NDIM8*NDIM10)
      DOUBLE PRECISION EIGVAL(NDIM8,NSPIN,NDIM10)
      DOUBLE PRECISION OCC(NDIM8,NSPIN,NDIM10),
     +  WOCC(NDIM8),DEL,EF,EBOUND,DNEL
      DIMENSION OCCLM(9,NDIM9,NDIM8)
      INTEGER NBANDS(NSPIN,NDIM10)
      PARAMETER (NMORE=4)
C.....ITERATIVE DIAGONALIZATION AND LOWDIN PERTURBATION
      COMPLEX WK(NDIM5,NDIM8),SHIFT(NDIM8)
      INTEGER IWK(NDIM8)
      REAL RWK(NDIM8)
      LOGICAL LRWH,LRWV,LEXIST,LITER,LOWDIN,LUMTX,LPREV,LREAL
      DOUBLE PRECISION HRSUB(NDIM8,NDIM8),HISUB(NDIM8,NDIM8)
      DOUBLE PRECISION SRSUB(NDIM8,NDIM8),SISUB(NDIM8,NDIM8)
      DOUBLE PRECISION VRSUB(NDIM8,NDIM8),VISUB(NDIM8,NDIM8)
      DOUBLE PRECISION ALFR(NDIM8),ALFI(NDIM8),BETA(NDIM8)
C.....WORKSPACES
      COMPLEX CWF1(NDIM5),CEV(NDIM5,NDIM8),RSPACE(NDIM6,NSPIN),
     +  VNLL(NDIM5),CWF4(6,NDIM5)
      REAL RWF3(NTYPMX,NDIM5),CFTWRK(4*NDIM7),EISWRK(11*NDIM3)
      INTEGER IWF5(14*NDIM5),LWORK(3,NDIM5)
C.....POTENTIALS AND DENSITIES
      COMPLEX             VIONIC(NDIM1,NSPIN),  VGTOT(NDIM1,NSPIN),
     +  VNEW (NDIM1,NSPIN), ROKG(NDIM1,NSPIN),  ROTOT(NDIM1,NSPIN),
     +  MUXCG(NDIM1,NSPIN), EXCG(NDIM1,NSPIN), ROTEMP(NDIM1,NSPIN)
      DOUBLE PRECISION VALPHA(2)
      DOUBLE PRECISION POTWRK(0:NQMAX, 2*NSPIN + 1)
C.....A AND B WAVES
      DIMENSION LISTAB(NDIM5),GK(4,NDIM5)
C.....RUNNING PARAMETERS
      DIMENSION RUNPAR(NRUN)
C.....SCRATCH
      REAL WVK(3),WVK0(3),GVEC(3),STRN(3,3)
      INTEGER IND(6),JND(6)
      CHARACTER*80 TEXT
      COMPLEX CAUX,VDIFF
      DOUBLE PRECISION DX(3,NDIM9),GG22
      LOGICAL LSEMI,LBS,LCHARG,LIKPTS
C.....VARIABLES FOR SUMMING UP ENERGY CONTRIBUTIONS
      DOUBLE PRECISION TOTBDE,TOT1ST,TOTKIN,TOTNL,SHARTR,SWORK,SIONIC,
     +  XCMU,XCMU0,XCE,XCE0,ENTOT1,ENTOT2,ENTOT3,GCONV,SUMMU,SUMEXC,
     +  ETOTAZ,G2RYD,GAMAEW,XCETOT,EIGCOR,ENONLO,KE,ETERM,EHARTR
      COMPLEX VHARTR,VMUXC,DROTOT
C.....ARRAYS USED FOR MIXING IN MIXVG
      COMPLEX HKMIX(0:NDIM12,0:NDIM12,NSPIN),
     +  XKMIX(NDIM12,NSPIN), FKMIX(NDIM12,NSPIN)
      COMPLEX CHI(0:NPWCHI,0:NPWCHI)
      COMPLEX INVCHI(0:NPWCHI)
      COMPLEX YK(NDIM12),SK(NDIM12),SKHK(NDIM12),SMHY(NDIM12),
     +  HKOLD(0:NDIM12,0:NDIM12,NSPIN)
      INTEGER RTABLE(48,48),RLIST((NDIM12+1)*48)
      INTEGER IDIFF(3,NPWCHI),IPG(NPWCHI,NPWCHI),INDEX(NPWCHI)
C.....COMMON BLOCK FOR KEEPING TRACK OF POSSIBLE WARNINGS
      COMMON /WARN/ IWARN
C.....TEXT
      CHARACTER*20 LDF(0:3)
      CHARACTER*25 DASHES,ASTRIX,YESNO
C
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,
     +  ISTRUC,IVNLKK,ISUMRY,IKPTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C     MACHINE TYPE
      COMMON /MACH1/ MACTYP
      COMMON /MACH2/ MACHIN(0:20)
      CHARACTER*7  MACHIN
C
      DATA GMTRIC /1.,0.,0.,0.,1.,0.,0.,0.,1./
C.....ZEROING THE XC AND HARTREE ENERGIES
      DATA SHARTR,XCMU0,XCMU,XCE0,XCE /5*0.0D0/
C.....INITIALIZATION OF THE PARAMETERS DETERMINING THE RUN:
      DATA IEWALD/0/,IFIRST/0/,ICYCLE/1/,ISELFC/1/,ISWCH/2/,
     +     NDSPL1/1/,NUMKPT/0/,IVGDIS/6/,IEVAL/2/,NHK/0/
C.....DOUBLE FOURIER TRANSFORM, DISPLAY OF RHO IN REAL SPACE:
      DATA INIXC4 /0/, N1,N2,N3 /8,8,8/,
     +  JINIT1,JINIT2,JINIT3,JSTEP1,JSTEP2,JSTEP3 /6 * -1/
      DATA LRWH,LRWV,LEXIST /3 * .FALSE./
      DATA LOWDIN,LUMTX,LPREV,LITER /4 * .FALSE./
C.....STRESS TENSOR INDICES:
      DATA IND/1,2,3,2,1,1/, JND/1,2,3,3,3,2/
C     FORMAT FOR WRITING A LINE OF - OR * ON OUTPUT
      DATA DASHES /'(1X,79(''-''))'/, ASTRIX /'(1X,79(''*''))'/
      DATA YESNO /'('' (+1=yes; -1=no)'')'/
C
C     STATEMENT FUNCTION FOR INDEXING RSPACE
      LOC1(J1,J2,J3) = 1 + J1 + J2*N1 + J3*N1*N2
C-----------------------------------------------------------------------
C
      IWARN  = 0
      WRITE (IOUT,ASTRIX)
C     TIMING:
      CALL USAGE (NP000 , T000)
      CALL DAY (IYEAR,MONTH,IDAY)
C
      WRITE (IOUT,100) MACHIN(MACTYP)
100   FORMAT(' K207 - Selfconsistent calculation - ',A,' computer')
      CALL DAYPRT (IOUT,IYEAR,MONTH,IDAY)
C
      IF (NSPIN .NE. 1) WRITE (IOUT,101)
101   FORMAT ('0*** Spin polarized calculation ***'/)
      WRITE (ISUMRY,100) MACHIN(MACTYP)
      CALL DAYPRT (ISUMRY,IYEAR,MONTH,IDAY)
      IF (NSPIN .NE. 1) WRITE (ISUMRY,101)
C
C     READING THE POTENTIAL FILE:
C
      CALL POTGET (
     +  NDIM1,NDIM2,NDIM3,NDIM4,NDIM5,NDIM6,NDIM7,NDIM8,NDIM9,NDIM10,
     +  NDIM12,NDIM20,NLMAX,NPARAM,NTYPMX,NSPIN,NRUN,RUNPAR,
     +  ULA,VOLUM,A1,A2,A3,B1,B2,B3,NG1,NG2,NG3,EPSILO,
     +  STRAIN,XKAPA,G2TAB,TY,NTAB,IGLIST,NATOM,TEXT,
     +  POTPAR,ZKAPA,POTTYP,POTXC,POTFIL,VNLIJ,ZTOT,NEL,G2MAX,
     +  VNLL,POTWRK,VIONIC,VGTOT,ROTOT,NMIX,HKMIX,XKMIX,FKMIX,
     +  NAT,NGTOT,MINDIM,IEXCOR,EXFACT,NONLOC,LCHARG)
C
C     Check inversion symmetry against LREAL
      CALL CHKINV (LREAL,TY,XKAPA,NAT)
C
C     CONVERSION FACTOR FOR G-VECTORS FROM UNITS (2*PI/ULA)**2 TO RYDBERGS
      G2RYD = (2.0D0*PI*ABOHR/DBLE(ULA))**2
C
C     CONSTRUCT THE G-SPACE METRIC TENSOR:
      CALL GSPMTR(STRAIN,STRN,GMTRIC,ISTRAI)
C
C     INITIALIZE THE LOOKUP OF G-VECTORS
C
      CALL LOOK00 (IGLIST,LIST,NGTOT,NG1,NG2,NG3,NG1MAX,NG2MAX,NG3MAX)
C
C-----------------------------------------------------------------------
C
C     READ THE SPECIAL POINTS FILE
C
160   WRITE (IOUT,165)
165   FORMAT (/' Will you need the special points file ?')
      WRITE (IUNIT7,YESNO)
      READ (INPUT,*) IYES
      WRITE (IUNIT7,*) IYES,' answered'
      IF (IYES .NE. -1) 
     +  CALL SPPTRD (TEXT,IHG,IHC,ISY,LI,NC,IB,V,F0,R,
     +          NAT,NDIM9,NDIM10,NUMKPT,IQ1,IQ2,IQ3,WVK0,LWGHT,WVLIST)
C
      WRITE (IOUT,280) B1,B2,B3
280   FORMAT (' B1',3F10.5,' in units 2PI/ULA'/' B2',3F10.5,
     +  ' (i.e. A(I)*B(J)=1*DELTA(I,J) )'/' B3',3F10.5)
C
C     MINIMUM NUMBER OF BANDS NECESSARY TO ACCOMODATE THE ELECTRONS
C     = NUMBER OF ELECTRONS / 2; ADD A 1 IN THE CASE OF A METAL
      MINBDS = (NEL + 1) / 2
      IF (MINBDS .GT. NDIM8) THEN
        WRITE (IOUT,290) NEL,MINBDS,NDIM8
290     FORMAT(' ***ERROR*** NEL = ',I4/' however, MINBDS = ',
     +    I4,' (number of bands) > NDIM8 = ',I4)
        CALL EXIT
        ENDIF
C
C     NUMBER OF EIGENVALUES TO BE CALCULATED
      NBDS   = MINBDS
C     NUMBER OF BANDS TO BE PRINTED OUT
      NDSPL2 = NDIM8
C     Double precision copy of NEL for fractional band occupation
      DNEL = DBLE(NEL)
C
C-----------------------------------------------------------------------
C
C     Questioning whether the user wants to change any of the
C     parameters determining the run
C
300   CALL QUESTN (
     +  NDIM1,NDIM2,NDIM3,NDIM4,NDIM5,NDIM6,NDIM7,NDIM8,NDIM9,
     +  NDIM10,NDIM13,NSPIN,
     +  IFIRST,LDF,IEXCOR,EXFACT,DNEL,MINBDS,NBDS,DEL,NEXTRA,ISNK,
     +  E1,E2,EBAR,G2RYD,G2MAX,GMTRIC,
     +  LSEMI,LRWH,LRWV,LEXIST,LITER,LOWDIN,LUMTX,
     +  IPREV,NITMX,RES,FAC,IWRCUA,IEVAL,
     +  NUMKPT,WVLIST,WVK,ULA,B1,B2,B3,NG1,NG2,NG3,IGLIST,LIST,NGTOT,
     +  IWF5,LISTAB,GK,MAXAB,ISTRAI,
     +  NDSPL1,NDSPL2,IVGDIS,ISWCH,ISELFC,
     +  JINIT1,JINIT2,JINIT3,JSTEP1,JSTEP2,JSTEP3,N1,N2,N3,
     +  INIXC4,NTAB,ROTOT,NEWTOT,MUXCG,RSPACE,CFTWRK,VOLUM,SUMMU,SUMEXC,
     +  LSTRES,NLSTRS,LFORCE,NLFORC,NAT,INVERS,IFORC,NOFORC,NONLOC)
C
C     Make sure that we have an integral number of electrons
C     for those parts that need it:
      NEL = DNEL + 1.0D-8
C
C     END OF THE BLOCK FOR CHANGING PARAMETERS
C
C-----------------------------------------------------------------------
C
C     CHOOSE WHETHER TO DO BANDSTRUCTURE OR SELFCONSISTENT LOOP
C
      WRITE (IOUT,1060)
1060  FORMAT (' Do you wish the band structure only',
     +  ' or rather the selfconsistent loop?'/
     +  ' (+N=no of selfconsistency loops;',
     +  ' -1=band structure only; 0=stop)')
      READ (INPUT,*) ISELFC
      WRITE(IOUT,*) ISELFC,' chosen'
      WRITE(ISUMRY,*) 'Selfconsistent loop switch =',ISELFC
      IFIRST = IFIRST + 1
      IF (ISELFC .GT. 0) THEN
        LBS = .FALSE.
      ELSE IF (ISELFC .EQ. -1) THEN
        LBS = .TRUE.
        GOTO 1415
      ELSE IF (ISELFC .EQ. 0) THEN
        GOTO 2230
      ELSE
        WRITE(IOUT,*) 'Illegal choice of ISELFC = ',ISELFC
        GOTO 2230
        ENDIF
C
C-----------------------------------------------------------------------
C
C     SELFCONSISTENT CALCULATION
C
C     NLOOPS COUNTS THE NUMBER OF LOOPS INDICATED BY ISELFC
      NLOOPS = 0
      IF (NUMKPT .LE. 0) THEN
        WRITE (IOUT,1210)
1210    FORMAT (' Special points file not read - start again')
        GOTO 160
        ENDIF
C
C     CALCULATE THE SPECIAL POINTS WEIGHTS
      IWGHT = 0
      DO 1235 ISPPT = 1,NUMKPT
        IWGHT = IWGHT + LWGHT(ISPPT)
1235    CONTINUE
      DO 1236 ISPPT = 1,NUMKPT
        WEIGHT(ISPPT) = DBLE(LWGHT(ISPPT)) / DBLE(IWGHT)
1236    CONTINUE
C
C-----------------------------------------------------------------------
C
C     THE POSSIBILITY OF USING OVERLAPPING ATOMS FOR INITIAL SCREENING
C
      WRITE (IOUT,1250)
1250  FORMAT (' Do you want to use overlapping free atoms for the ',
     +        'initial guess ?')
      READ  (INPUT,*)  IYESNO
      WRITE (IUNIT7,*) IYESNO,'  initial guess switch'
      IF (IYESNO .EQ. -1) GOTO 1260
      IF (.NOT. LCHARG) THEN
        WRITE(IOUT,*) ' No charge density was generated by K213'
        GOTO 1260
        ENDIF
      ICYCLE = 0
      WRITE (IOUT,1410)   ICYCLE
      WRITE (ISUMRY,1410) ICYCLE
      GOTO 1665
C
C-----------------------------------------------------------------------
C
C     POSSIBILITY OF PROJECTING WAVEFUNCTIONS
C
1260  WRITE (IOUT,1270)
1270  FORMAT (' Projected wavefunctions: enter radius ?'/
     +  '  (<0 for none, =0 for Wigner-Seitz radius)')
      READ (INPUT,*) RPROJ
      WRITE (IOUT,*) RPROJ,' projection integration radius'
C
C-----------------------------------------------------------------------
C
C     ATOMIC STRUCTURE FACTORS
C
      CALL SFACT (STRFAC,SATGR,SATGI,TY,XKAPA,DX,IGLIST,
     +  B1,B2,B3,NDIM1,NDIM9,NTYPMX,NAT,NGTOT,NG1,NG2,NG3,LREAL)
C
C-----------------------------------------------------------------------
C
C     INITIALIZE FOR FIRST LOOP OVER K-POINTS
C
1400  WRITE (IOUT,1410) ICYCLE
      WRITE (ISUMRY,1410) ICYCLE
1410  FORMAT (1X,22('-'),'Selfconsistent loop - cycle',I3,27('-'))
      WRITE (ISUMRY,1411) NUMKPT
1411  FORMAT(' Begin loop over ',I4,' special k-points')
      NLOOPS = NLOOPS + 1
C     Reset the warning signals:
      IWARN = 0
C
C     OPEN THE TEMPORARY FILE FOR STORING K-POINT INFORMATION
      INQUIRE (UNIT=IKPTS, OPENED=LIKPTS)
      IF (LIKPTS) THEN
        REWIND (IKPTS)
      ELSE
C	Other machines don't like Apollo specials
C       IF (MACTYP .EQ. 11) THEN
C         Apollo: Have to specify non-ANSI RECL:
C         OPEN  (UNIT = IKPTS, STATUS = 'UNKNOWN', FORM = 'UNFORMATTED',
C    +      FILE='fort.13', RECL = 4*(8+5*NDIM5))
C         WRITE(IUNIT7,*) 'Open k-point file, unit=', IKPTS
C       ELSE
          OPEN  (UNIT = IKPTS, STATUS = 'UNKNOWN', FORM = 'UNFORMATTED')
C         ENDIF
        ENDIF
C
C     PERHAPS USE EIGENVECTORS FROM PREVIOUS CYCLE
      IF (LITER) THEN
        IF (NLOOPS .GE. IPREV) LPREV = .TRUE.
        ENDIF
C
1415  IF (LBS) THEN
        LPREV = .FALSE.
        WRITE (IOUT,*) 'Enter number of k points required'
        READ (INPUT,*) NUMKPT
        IF (NUMKPT .LE. 0) THEN
          GOTO 2230
        ELSE IF (NUMKPT .GT. NDIM10) THEN
          WRITE (IOUT,*) 'Too many k-points for NDIM10 = ',NDIM10
          GOTO 1415
          ENDIF
        DO 1100 K = 1,NUMKPT
          WRITE (IOUT,*) 'Enter cartesian components of wavevector',
     +      ' (units: 2pi/ula)'
          READ (INPUT,*) WVK
          WRITE (IOUT,1090) WVK
1090      FORMAT (' Wavevector: WVK =',3F14.6,' in units 2pi/ula')
          WVLIST(1,K) = WVK(1)
          WVLIST(2,K) = WVK(2)
          WVLIST(3,K) = WVK(3)
1100      CONTINUE
C
        ENDIF
C
C     SET NUMBER OF BANDS TO BE CALCULATED
C
      DO 1420 ISPPT = 1,NUMKPT
C
C       LOOP OVER THE SPIN-POLARIZATION INDEX
        DO 1420 ISPIN = 1, NSPIN
C
        IF (LSEMI) THEN
          NBANDS(ISPIN,ISPPT) = NBDS
        ELSE
          NBANDS(ISPIN,ISPPT) = MINBDS + NEXTRA
          IF (NBANDS(ISPIN,ISPPT) .GT. NDIM8) THEN
            WRITE(IOUT,1240) NBANDS(ISPIN,ISPPT),NDIM8,ISPPT
1240        FORMAT(' ***WARNING*** number of bands requested = ',I6,
     +      /,' but NDIM8 is only = ',I6,' at k-point number ',I6,
     +      /,' number of bands was set to NDIM8')
            NBANDS(ISPIN,ISPPT) = NDIM8
            ENDIF
          ENDIF
1420    CONTINUE
C
C     For iterative diagonalization, adjust the eigenvalue accuracy RES
C
      IF (LITER .AND. RES .LE. 0.0) THEN
C       A negative RES signals that it should be adjusted as the
C       selfconsistent calculation proceeds (i.e., RES is decreased
C       the closer we get to selfconsistency)
        IF (NLOOPS .GE. 2) THEN
          THRES = 1.0E-3
C         Choose the eigenvalue correction EIGCOR to set RES (units: Ryd)
          RES = MIN( ABS(RES) , THRES , 
     +      THRES * SNGL(ABS(EIGCOR/RYEV)) / FLOAT(MINBDS) )
C         Do not allow RES to be below 1E-8 Ryd
          RES = MAX( RES, 1.0E-8 )
C         RES has to be negative:
          RES = - ABS( RES )
          ENDIF
        WRITE (IOUT,1425) ABS(RES)*RYEV
1425    FORMAT(' Eigenvalue accuracy RES set to ',E10.3,' eV')
        ENDIF
C
C-------------------------------------------------------------------------
C
C     FIRST LOOP OVER K-POINTS
C
      REWIND (IKPTS)
C     Write dimension check to file IKPTS
      WRITE (IKPTS) NDIM3, NDIM4, NDIM8, NDIM9
C
      CALL USAGE(NPAGE0,TCYCL0)
      DO 1450 ISPPT = 1,NUMKPT
C
      WVK(1) = WVLIST(1,ISPPT)
      WVK(2) = WVLIST(2,ISPPT)
      WVK(3) = WVLIST(3,ISPPT)
C
C     FIND WHICH PLANE WAVES ARE TO BE INCLUDED FOR THIS E1,E2
      CALL GKCUT (WVK,E1,E2,B1,B2,B3,NG1,NG2,NG3,NDIM1,NDIM3,NDIM4,
     +  NDIM5,IWF5,IWF5(NDIM5+1),ISTRAI,GMTRIC,IGLIST,NGTOT,LISTAB,GK,
     +  NA,NB)
C
C     LOOP OVER THE SPIN-POLARIZATION INDEX
C
      DO 1450 ISPIN = 1, NSPIN
      IF (NA .GT. NDIM3 .OR. NB .GT. NDIM4) GOTO 1450
C
C     CHECK NUMBER OF BANDS REQUESTED
      IF (NBANDS(ISPIN,ISPPT) .GT. NA) THEN
        NBANDS(ISPIN,ISPPT) = NA
        WRITE(IOUT,*) 'More than NA bands requested - NBDS set to NA'
        ENDIF
      NBDS = NBANDS(ISPIN,ISPPT)
      IF (NBDS .GT. NDIM8 .OR. NBDS .GT. NDIM13) THEN
        WRITE(IOUT,*) '***ERROR*** too many bands requested'
        CALL EXIT
        ENDIF
      IF (NBDS .LE. 0) GOTO 1450
C
      CALL SETUP (IWRCUA,NONLOC,POTPAR,POTTYP,ULA,VOLUM,
     +  NG1,NG2,NG3,NDIM1,NDIM3,NDIM5,NDIM11,NDIM20,NLMAX,NPARAM,NTYPMX,
     +  IGLIST,LIST,VNLIJ(0,0,1,1,ISPIN),VGTOT(1,ISPIN),
     +  NGTOT,LISTAB,GK,NA,NB,CWF1,VNLL,CWF4,
     +  RWF3,IWF5,LWORK,LREAL,G2RYD,HAMR,HAMI,DIAG,IFILEH,IFILEV,EBAR,
     +  LRWH,LRWV,LUMTX,STRFAC,LEXIST)
C
      IREC = ((ISPPT-1)*NSPIN + (ISPIN - 1)) * NDIM8
      CALL DIAGON(HAMR,HAMI,CCR,CCI,CEV,EE1,EE2,DIAG,IWK,
     +  WK,CWF1,RWK,SHIFT,EISWRK,IFILEH,NDIM3,NDIM5,NDIM8,
     +  NDIM11,NDIM13,NA,NB,NBDS,NITMX, ABS(RES) ,ISWCH,LITER,IEVAL,
     +  LOWDIN,IWRCUA,LREAL,LPREV,IREC,FAC,
     +  IEVFIL,HRSUB,HISUB,SRSUB,SISUB,VRSUB,VISUB,ALFR,ALFI,BETA)
C
      DO 1430 J = 1,NBDS
        EE1(J) = EE1(J)*RYEV
        EE2(J) = EE2(J)*RYEV
        EIGVAL(J,ISPIN,ISPPT) = DBLE(EE2(J))
        OCC(J,ISPIN,ISPPT) = 0.0D0
1430    CONTINUE
C
      IF (LBS) THEN
        CALL EDISPL (WVK,NDSPL1,NDSPL2,LITER,LOWDIN,NA,NB,
     +    IEVAL,EE1,EE2,OCC,-1,ISPIN,NSPIN)
      ELSE
C       STORE INFORMATION ON A TEMPORARY FILE:
        WRITE (IKPTS) ISPPT,ISPIN,WVK,NBDS,NA,NB,LISTAB,GK
C       STORE EIGENVECTORS AND EIGENVALUES ON FILE
        IREC = ((ISPPT-1)*NSPIN + (ISPIN - 1)) * NDIM8
        CALL RWEV (IEVFIL,IREC, 1 ,EE1,EE2,NBDS,NA+NB,
     +    NDIM5,NDIM8,CEV,LREAL)
        ENDIF
C
1450  CONTINUE
C
C     END FIRST LOOP OVER K-POINTS
C
      IF (LBS) GOTO 2215
      IF (LRWV) LEXIST = .TRUE.
      REWIND (UNIT=IFILEV)
      REWIND (UNIT=IKPTS)
C
C-----------------------------------------------------------------------
C
C     CALCULATE OCCUPANCIES OF CALCULATED STATES
C
      IF (LSEMI) THEN
C
C     SEMICONDUCTOR
        TEST = 0.0
        DO 1460 ISPPT = 1,NUMKPT
        DO 1460 ISPIN = 1, NSPIN
        DO 1460 J = 1,NDIM8
C         OCC=2 for non-spinpolarized, OCC=1 for spinpolarized
          OCC(J,ISPIN,ISPPT) = DBLE( 3 - NSPIN )
          IF (J .GT. MINBDS) OCC(J,ISPIN,ISPPT) = 0.0D0
C         Breaking spin-symmetry for odd no. of electrons,
C         by occupying only the highest spin-up state:
          IF (J .GT. NEL / 2  .AND. ISPIN .EQ. 2)
     +      OCC(J,ISPIN,ISPPT) = 0.0D0
          TEST = TEST + WEIGHT(ISPPT) * OCC(J,ISPIN,ISPPT)
1460      CONTINUE
C
        IF ( ABS(TEST - DBLE(NEL)) .GT. 1.0E-9) THEN
          WRITE (IOUT,1462) TEST,NEL
1462      FORMAT(' K207 *** WARNING ***'/
     +      ' sum of occupancies =',D20.12,' but no. of electrons =',I4)
          IWARN = 1
        ELSE IF ( ABS(TEST - DBLE(NEL)) .GT. 0.5) THEN
          WRITE (IOUT,1463) TEST,NEL
1463      FORMAT(' K207 *** FATAL ERROR ***'/
     +      ' sum of occupancies =',F20.12,' but no. of electrons =',I4)
          CALL EXIT
          ENDIF
C
      ELSE
C
C       A METAL: FIND THE FERMI LEVEL
C
        CALL EFERMI (DNEL,NSPIN,NBANDS,DEL,NUMKPT,NDIM8,NDIM10,
     +    WEIGHT,OCC,EF,EIGVAL,SORT)
        IF (ABS(EF) .GT. 1.0E6) THEN
          WRITE (IOUT,*) 'K207:  Troubles in EFERMI'
          GOTO 300
          ENDIF
C
        ENDIF
C-----------------------------------------------------------------------
C
C     SUM UP CONTRIBUTIONS TO TOTAL ENERGY, FORCES AND STRESS FROM
C     THE INDIVIDUAL K-POINTS
C
C     ZERO THE QUANTITIES TO BE SUMMED UP:
C
C     CHARGE DENSITY:
      DO 1455 ISPIN = 1, NSPIN
      DO 1455 I = 1,NGTOT
        ROKG(I,ISPIN) = (0.0,0.0)
1455    CONTINUE
C
C     ENERGIES:
      TOTBDE = 0.0D0
      TOTKIN = 0.0D0
      TOTNL  = 0.0D0
      TOT1ST = 0.0D0
C
C     FORCES AND STRESS:
      DO 1466 N = 1,NDIM9
      DO 1466 I = 1,3
        FORCEL(I,N) = 0.0D0
1466    CONTINUE
      DO 1467 J = 1,3
      DO 1467 I = 1,3
        STRSKE(I,J) = 0.0
        STRSNL(I,J) = 0.0
1467    CONTINUE
C
      TRO5 = 0.0
C
C     SECOND LOOP OVER POINTS
C
C     Read dimension check from file IKPTS
      READ (IKPTS) I3, I4, I8, I9
C
      DO 1600 ISPPT = 1,NUMKPT
      DO 1600 ISPIN = 1, NSPIN
C
      NBDS = NBANDS(ISPIN,ISPPT)
      IF (NBDS .LE. 0) GOTO 1600
C
C     READ INFORMATION FROM THE TEMPORARY FILE:
      READ (IKPTS) ICHECK,ISPCHK,WVK,NBDS,NA,NB,LISTAB,GK
      IF (ICHECK .NE. ISPPT .OR. ISPCHK .NE. ISPIN) THEN
        WRITE (IOUT,*) 'K207 *** ERROR IN K-POINT FILE',
     +    ISPPT,ICHECK, '    ', ISPIN, ISPCHK
        CALL EXIT
        ENDIF
C     READ EIGENVECTORS AND EIGENVALUES FROM FILE
      IREC = ((ISPPT-1)*NSPIN + (ISPIN - 1)) * NDIM8
      CALL RWEV (IEVFIL,IREC, -1 ,EE1,EE2,NBDS,NA+NB,
     +  NDIM5,NDIM8,CEV,LREAL)
C
C     DISPLAY OF THE SELECTED ENERGIES:
C
      CALL EDISPL (WVK,NDSPL1,MIN(NBDS,NDSPL2),LITER,LOWDIN,NA,NB,
     +  IEVAL,EE1,EE2,OCC(1,ISPIN,ISPPT),1,ISPIN,NSPIN)
C
C     BAND-ENERGY CONTRIBUTION
C
      DO 1470 J = 1,NBDS
        WOCC(J) = WEIGHT(ISPPT) * OCC(J,ISPIN,ISPPT)
        TOTBDE  = TOTBDE + WOCC(J) * DBLE(EE2(J))
        TOT1ST  = TOT1ST + WOCC(J) * DBLE(EE1(J))
1470    CONTINUE
C
     
      IF (ISWCH .NE. 2) THEN
C
        IF (NONLOC) 
     +    CALL MATEL (IWRCUA,NONLOC,NLFORC,NLSTRS,NOFORC,
     +      NBDS,WOCC,POTPAR,POTTYP,TY,NAT,ULA,VOLUM,DX,XKAPA,B1,B2,B3,
     +      NG1,NG2,NG3,NDIM1,NDIM3,NDIM5,NDIM8,NDIM9,NDIM11,NDIM13,
     +      NDIM20,NLMAX,NPARAM,NTYPMX,IGLIST,LIST,STRFAC,SATGR,SATGI,
     +      VNLIJ(0,0,1,1,ISPIN),VGTOT(1,ISPIN),
     +      NGTOT,LISTAB,GK,NA+NB,CWF1,VNLL,CWF4,RWF3,IWF5,
     +      LWORK,LREAL,G2RYD,CEV,ENONLO,FORCWK,SWF2,IFILEV,LEXIST)
C
C       ENERGY (NON-LOCAL PART):
        IF (NONLOC) TOTNL = TOTNL + ENONLO
C       STRESS (NON-LOCAL PART):
        IF (NLSTRS) THEN
          K = 0
          DO 1480 II = 1,3
          DO 1480 JJ = II,3
            K = K + 1
            STRSNL(II,JJ) = STRSNL(II,JJ) + SWF2(K)
            STRSNL(JJ,II) = STRSNL(II,JJ)
1480        CONTINUE
          ENDIF
C       HELLMANN-FEYNMAN FORCES (NON-LOCAL PART):
        IF (NLFORC) THEN
          DO 1500 KAPA = 1,NAT
          DO 1500 IALF = 1,3
            FORCEL(IALF,KAPA) = FORCEL(IALF,KAPA) + FORCWK(IALF,KAPA)
1500      CONTINUE
          ENDIF
C
C       KINETIC ENERGY AND STRESS
        CALL KINETI (GK,NA+NB,KE,CEV,SWF2,WOCC,NBDS,G2RYD,
     +    NDIM5,NDIM8,LREAL)
        TOTKIN = TOTKIN + KE
        IF (LSTRES) THEN
          K = 0
          DO 1520 II = 1,3
          DO 1520 JJ = II,3
            K = K + 1
            STRSKE(II,JJ) = STRSKE(II,JJ) - SWF2(K)
            STRSKE(JJ,II) = STRSKE(II,JJ)
1520        CONTINUE
          ENDIF
C
        ENDIF
C
C-----------------------------------------------------------------------
C
C     GENERATE THE CHARGE DENSITY
C
      CALL USAGE(NPAGE0,T0RO5)
      CALL RO5 (NDIM1,NDIM5,NDIM8,NG1,NG2,NG3,
     +  NGTOT,IGLIST,LIST,NA+NB,LISTAB,NBDS,CEV,
     +  ROTEMP,WOCC,IWF5,IWF5(4*NDIM5+1),LWORK,LREAL)
C
      DO 1550 J = 1, NGTOT
        ROKG(J,ISPIN) = ROKG(J,ISPIN) + ROTEMP(J,1)
1550    CONTINUE
      CALL USAGE(NPAGE1,T1)
      TRO5 = TRO5 + T1 - T0RO5
C
C     ANGULAR MOMENTUM DECOMPOSITION
C
      IF (RPROJ .GE. 0.0) THEN
C       ATOMIC STRUCTURE FACTORS
        CALL SFACT (STRFAC,SATGR,SATGI,TY,XKAPA,DX,IGLIST,
     +    B1,B2,B3,NDIM1,NDIM9,NTYPMX,NAT,NGTOT,NG1,NG2,NG3,LREAL)
        CALL PROJCT
     +    (LREAL,NDIM1,NDIM3,NDIM4,NDIM5,NDIM8,NDIM9,
     +    RPROJ,VOLUM,NAT,SATGR,SATGI,
     +    CEV,NBDS,GK,LISTAB,NA,NB,OCC(1,ISPIN,ISPPT),IWF5,OCCLM)
        ENDIF
C
      IF (.NOT. LSEMI) THEN
C
C     SET NUMBER OF BANDS FOR NEXT CYCLE AT THIS K-POINT
C
      IF (ISNK .EQ. 1) THEN
C       KEEP SAME NUMBER OF BANDS AT NEXT CYCLE
C       TEST WHETHER THIS IS ENOUGH
        IF (WOCC(NBDS) .GT. 1.0E-8) THEN
          WRITE(IOUT,*) '***WARNING***'
          WRITE(IOUT,*) 'Number of bands ',NBDS,' at k-point'
     +                  ,ISPPT,' may be insufficient'
          ENDIF
      ELSE
C       REDUCE NUMBER OF BANDS CALCULATED IF POSSIBLE
        IF (DNEL .GT. 1.0) THEN
          NUM = 0
          DO 1551 J = 1,NBDS
            NUM = NUM + 1
1551        IF (WOCC(J) .LT. 1.0D-8) GOTO 1552
          NBANDS(ISPIN,ISPPT) = NBDS + NMORE
          GOTO 1553
1552      NBANDS(ISPIN,ISPPT) = NUM + NMORE - 1
1553      IF (NBANDS(ISPIN,ISPPT) .GT. NDIM8) THEN
            WRITE(IOUT,1240) NBANDS(ISPIN,ISPPT),NDIM8,ISPPT
            NBANDS(ISPIN,ISPPT) = NDIM8
            ENDIF
        ELSE IF (DNEL .EQ. 1.0D0) THEN
          IF (ICYCLE .EQ. 1 .AND. ISPPT .EQ. 1) WRITE(IOUT,1555)
1555      FORMAT(' Because NEL = 1 the potentially unsafe option',/,
     +    ' to detemine the number of bands to calculate for the next'
     +    ,/,' cycle was used, check whether this is satisfactory')
          IEMPTY = 0
          EBOUND =  EF + 5.0D0*DEL + 2.0D0
          DO 1556 J = 1,NBDS
1556        IF (EIGVAL(J,ISPIN,ISPPT) .GT. EBOUND) IEMPTY = IEMPTY + 1
          NBANDS(ISPIN,ISPPT) = NBANDS(ISPIN,ISPPT) - IEMPTY
          ENDIF
        ENDIF
C
        ENDIF
C
C     END SECOND LOOP OVER K-POINTS
C
1600  CONTINUE
C
C     close k-point file
      CLOSE (UNIT = IKPTS, STATUS = 'KEEP')
C
C-----------------------------------------------------------------------
C
C     Determine maximum G-vector with Rho(G) .NE. 0
      CALL ROGMAX (ROKG,NDIM1,NSPIN,NTAB,NDIM2, NGMAX)
      WRITE (IUNIT7,*) NGMAX,' G-vectors encountered in RO5'
C
      CALL USAGE(NPAGE1,T1)
      WRITE (ISUMRY,1605) T1- TCYCL0
1605  FORMAT (' special points ',T30,F10.3,' seconds total')
      WRITE (IUNIT7,DASHES)
      WRITE (IUNIT7,1610) T1-TCYCL0
1610  FORMAT(' Time for this cycle =',F10.3)
      WRITE(IUNIT7,1612) TRO5
1612  FORMAT(' Time in RO5         =',F10.3)
      IF (ISWCH .GE. 3) GOTO 300
      WRITE (IOUT,DASHES)
C-----------------------------------------------------------------------
C
C     SYMMETRIZATION OF CHARGE DENSITY, STRESS TENSOR AND FORCES:
C     (I.E., THE UNFOLDING OF SPECIAL K-POINTS)
C
      CALL USAGE(NPSYM0,TSYM0)
      CALL ROSYM4 (A1,A2,A3,B1,B2,B3,ISY,NC,IB,V,R,RB,IGLIST,LIST,
     +  NDIM1,NGTOT,NGMAX,NG1,NG2,NG3,ROKG,ROTOT,NSPIN,LREAL)
      CALL USAGE(NPSYM,TSYM)
      WRITE (IUNIT7,1615) TSYM - TSYM0
1615  FORMAT(1X,F10.3,' seconds in charge-density symmetrization')
C
      TEST = ROTOT(1,1)
      IF (NSPIN .EQ. 2) TEST = TEST + REAL(ROTOT(1,2))
      IF ( ABS(TEST - DNEL) .GT. 1.0E-10) THEN
        WRITE (IOUT,1616) TEST, DNEL
1616    FORMAT ('0K207 *** WARNING *** RHO-average = ',F16.10,
     +    ' BUT NEL = ',F10.6)
        IF (NSPIN .EQ. 1) THEN
          ROTOT(1,1) = DNEL
        ELSE
          ROTOT(1,1) = ROTOT(1,1) * SNGL(DNEL/TEST)
          ROTOT(1,2) = ROTOT(1,2) * SNGL(DNEL/TEST)
          ENDIF
        WRITE (IOUT,*) '... Rescaled to the proper normalization'
        IWARN = 1
        ENDIF
C
C     STRESS TENSORS:
      IF (LSTRES) THEN
        IF (NONLOC) CALL STRSYM(ISY,NC,IB,R,STRSNL)
        CALL STRSYM(ISY,NC,IB,R,STRSKE)
        ENDIF
C
C     NON-LOCAL PART OF THE FORCES:
C     IT MAY BE THAT SOME FORCES ARE RELATED BY INVERSION, AS DETERMINED
C     BY THE USER ABOVE BY ASSIGNING THE ARRAY "INVERS"
      IF (NLFORC) THEN
        DO 1660 KAPA = 1,NAT
          IF (INVERS(KAPA).LE.0 .OR. INVERS(KAPA).GT.NAT) GOTO 1660
          DO 1650 I = 1,3
            FORCEL(I,INVERS(KAPA)) = - FORCEL(I,KAPA)
1650        CONTINUE
1660      CONTINUE
C       SYMMETRIZATION OF NON-LOCAL FORCES:
        CALL FORSYM (TY,XKAPA,A1,A2,A3,NAT,ISY,NC,IB,V,F0,R,
     +    FORCWK,NDIM9,FORCEL)
        ENDIF
C
      IF (LFORCE) THEN
C       STRUCTURE FACTORS
        CALL SFACT (STRFAC,SATGR,SATGI,TY,XKAPA,DX,IGLIST,
     +    B1,B2,B3,NDIM1,NDIM9,NTYPMX,NAT,NGTOT,NG1,NG2,NG3,LREAL)
C       FORCES FROM THE LOCAL POTENTIAL
        CALL FORLOC (TY,POTTYP,NG1,NG2,NG3,B1,B2,B3,
     +    POTPAR,POTFIL,VOLUM,ULA,NAT,NTAB,G2TAB,IGLIST,SATGR,SATGI,
     +    NDIM1,NDIM2,NDIM9,NTYPMX,NPARAM,LREAL,
     +    NSPIN,POTWRK,NQMAX,
     +    FORCWK,ROTOT,FORCLO)
C       SYMMETRIZATION OF LOCAL POTENTIAL FORCES:
        CALL FORSYM (TY,XKAPA,A1,A2,A3,NAT,ISY,NC,IB,V,F0,R,
     +    FORCWK,NDIM9,FORCLO)
          ENDIF
C
C-----------------------------------------------------------------------
C
C     EXCHANGE-CORRELATION:
C
C     MAKE TRANSFORM TO REAL SPACE
1665  CALL USAGE(NPAGE0,TEXCH0)
      INIT=-1
C
      CALL EXCH4 (INIT,NDIM1,NDIM2,NDIM6,NDIM7,NG1,NG2,NG3,NGMAX,
     +  IGLIST,NGTOT,NTAB,ROTOT,N1,N2,N3,NEWTOT,MUXCG,RSPACE,
     +  CFTWRK,VOLUM,ULA,EXFACT,IEXCOR,NSPIN,SUMMU,SUMEXC)
C
      CALL USAGE(NP,TXC)
      WRITE (IUNIT8,1670) N1,N2,N3, TXC - TEXCH0
1670  FORMAT(' End EXCH4 (',3I4,') ',F10.3,' seconds')
C
C-----------------------------------------------------------------------
C
C     OUTPUT OF CHARGE DENSITY IN REAL SPACE:
C
1720  IF (JINIT1 .LT. 0) GOTO 1760
      DO 1750 ISPIN = 1, NSPIN
      IF (NSPIN .EQ. 2 .AND. ISPIN .EQ. 1) WRITE (IUNIT7,1705) 'Up'
      IF (NSPIN .EQ. 2 .AND. ISPIN .EQ. 2) WRITE (IUNIT7,1705) 'Down'
1705  FORMAT ('0The spin-polarized case: spin ',A/)
      WRITE (IUNIT7,1710)
1710  FORMAT ('0Charge density in direct space (units: number of electro
     +ns per unit cell):'/'0  J1  J2  J3       coordinates of the mesh p
     +oint         charge density'/57X,'Re',12X,'Im')
      JWORK1 = JINIT1
      JWORK2 = JINIT2
      JWORK3 = JINIT3
C
      DO 1750 IWORK = 1, 1000
      IF (JWORK1.GE.N1 .OR. JWORK2.GE.N2 .OR. JWORK3.GE.N3) GO TO 1760
C     COORDINATES:
      DO 1730 IALF=1,3
        GVEC(IALF) = FLOAT(JWORK1)*A1(IALF)/FLOAT(N1) +
     +               FLOAT(JWORK2)*A2(IALF)/FLOAT(N2) +
     +               FLOAT(JWORK3)*A3(IALF)/FLOAT(N3)
1730    CONTINUE
C     CHARGE EVEN-ODD:
      CAUX = + RSPACE(LOC1(JWORK1,JWORK2,JWORK3),ISPIN)
      IF (MOD(JWORK1+JWORK2+JWORK3,2) .EQ. 1) CAUX = - CAUX
      WRITE (IUNIT7,1740) JWORK1,JWORK2,JWORK3,GVEC,CAUX
1740  FORMAT (1X,3I4,3F12.5,1X,2G14.6)
      JWORK1 = JWORK1 + JSTEP1
      JWORK2 = JWORK2 + JSTEP2
      JWORK3 = JWORK3 + JSTEP3
1750  CONTINUE
C
C     A POSSIBLE DISPLAY OF MORE MESH-POINTS:
C
1760  IF (NLOOPS .EQ. 1) THEN
        WRITE (IOUT,*) 'Display mesh points of charge density ?',
     +  ' (YES=1, NO=-1)'
        READ (INPUT,*) IYES
        IF (IYES .EQ. 1) THEN
          WRITE (IOUT,1775)
1775  FORMAT(' Enter 6 integers with meaning of JINIT1,2,3, JSTEP1,2,3;'
     +/' (for an individual point choose JSTEP1,2,3 = 0)')
          READ (INPUT,*) JWORK1,JWORK2,JWORK3,JSTEP1,JSTEP2,JSTEP3
          IF (JWORK1 .GE. 0) GOTO 1720
          ENDIF
        ENDIF
C-----------------------------------------------------------------------
C
C     CONTINUATION OF THE DOUBLE FOURIER TRANSFORM:
C     BACKTRANSFORM OF THE XC-FUNCTION TO RECIPROCAL SPACE:
C     THE XC-POTENTIAL MU:
C
      INIT = -2
      CALL EXCH4 (INIT,NDIM1,NDIM2,NDIM6,NDIM7,NG1,NG2,NG3,NGMAX,
     +  IGLIST,NGTOT,NTAB,ROTOT,N1,N2,N3,NEWTOT,MUXCG,RSPACE,
     +  CFTWRK,VOLUM,ULA,EXFACT,IEXCOR,NSPIN,SUMMU,SUMEXC)
C
C     XC-ENERGY: IXCE=0 MEANS FROM REAL-SPACE INTEGRAL:
      IXCE = 0
      IF (IEXCOR .EQ. 1 .OR. IXCE .EQ. 0) GOTO 1800
C
C     XC-ENERGY FROM FOURIER TRANSFORM (PRESENTLY INACTIVE)
C     (NOW DONE IN REAL SPACE, BUT KEEP CODE FOR CHECKS)
C
C     TO SAVE MEMORY, TRANSFORM AGAIN TO REAL SPACE, AND
C     CALCULATE THE XC-ENERGY. WITH AMPLE MEMORY WE COULD
C     AFFORD TO DEFINE ANOTHER RSPACE AND ONLY TRANSFORM ONCE.
C     WE DO NOT NEED THIS FOR SELFCONSISTENCY, BUT ONLY FOR
C     THE TOTAL ENERGY, WHICH MAY ONLY BE NEEDED AT THE END
C     OF A SELF CONSISTENY RUN.
      INIT = 3
      CALL EXCH4 (INIT,NDIM1,NDIM2,NDIM6,NDIM7,NG1,NG2,NG3,NGMAX,
     +  IGLIST,NGTOT,NTAB,ROTOT,N1,N2,N3,NEWTOT,MUXCG,RSPACE,
     +  CFTWRK,VOLUM,ULA,EXFACT,IEXCOR,NSPIN,SUMMU,SUMEXC)
C
C     FOR FIGHTING THE ROUND-OFF ERRORS SYMMETRIZE MUXCG AND EXCG
C     THIS MEANS AVERAGING COMPONENTS WHICH SHOULD BE ARE EQUAL BY
C     SYMMETRY. THE HAMILTONIAN MAY INCLUDE INCOMPLETE
C     G-SHELLS, RESULTING IN ASYMMETRY ON OUTER SHELLS.
C
      CALL ROSYM4 (A1,A2,A3,B1,B2,B3,ISY,NC,IB,V,R,RB,IGLIST,LIST,
     +  NDIM1,NGTOT,NGMAX,NG1,NG2,NG3,EXCG,ROTEMP,NSPIN,LREAL)
C
C.................
C
1800  CALL ROSYM4 (A1,A2,A3,B1,B2,B3,ISY,NC,IB,V,R,RB,IGLIST,LIST,
     +  NDIM1,NGTOT,NGMAX,NG1,NG2,NG3,MUXCG,ROTEMP,NSPIN,LREAL)
C
      CALL USAGE(NPAGE1,T1)
      WRITE (IUNIT7,1820) T1 - TEXCH0
1820  FORMAT(' Time in exchange-correlation ',F15.3)
C-----------------------------------------------------------------------
C
C     EVALUATION OF THE NEW POTENTIAL AND OF THE SUMS IN TOTAL ENERGY:
C
C
C     ALPHA*Z TERM
C
C     CALCULATE THE G=0 PSEUDOPOTENTIAL CONTRIBUTION TO TOTAL ENERGY
C     (ALPHAZ WILL ALSO CALCULATE THE IONIC CHARGES FROM PARAMETERS)
C
      CALL ALPHAZ (POTTYP,TY,NAT,POTPAR,NTYPMX,NDIM9,NPARAM,ULA,VOLUM,
     +             ZKAPA,VALPHA)
      IF (NSPIN .EQ. 1) THEN
        ETOTAZ = SNGL(VALPHA(1)) * ROTOT(1,1)
      ELSE
        ETOTAZ = SNGL(VALPHA(1)) * ROTOT(1,1) +
     +           SNGL(VALPHA(2)) * ROTOT(1,2)
        ENDIF
C
      DO 1590 I = 1,3
      DO 1590 J = 1,3
        STRSAZ(I,J) = 0.0
        IF (I .EQ. J) STRSAZ(I,J) = - ETOTAZ
1590    CONTINUE
C
C     G2*VOL = GG22*(2.*PI*ABOHR/ULA)**2 * VOLUM*(ULA/ABOHR)**3
      GCONV = DBLE(VOLUM) * 4.0D0 * PI**2 * DBLE(ULA) / ABOHR
      VNEW(1,1) = (0.0,0.0)
      IF (NSPIN .EQ. 2) VNEW(1,NSPIN) = 0.0
      SHARTR  = 0.0D0
      SWORK   = 0.0D0
      SIONIC  = 0.0D0
      XCMU    = 0.0D0
      XCMU0   = 0.0D0
      XCE0    = 0.0D0
      XCE     = 0.0D0
      EIGCOR  = 0.0D0
      DO 1830 I = 1,3
      DO 1830 J = 1,3
        STRSHA(I,J) = 0.0
        STRSXC(I,J) = 0.0
1830    CONTINUE
C
C     THE G=0 COMPONENTS: X-C
C
      DO 1835 ISPIN = 1, NSPIN
      DROTOT = CONJG(ROTOT(1,ISPIN))
      VMUXC  = MUXCG(1,ISPIN)
C     MINUS BECAUSE X-C IS NEGATIVE  ???
      XCMU0  = XCMU0 + REAL(DROTOT*VMUXC)
      IF (IXCE .NE. 0) THEN
C       X-C ENERGY FROM FOURIER-SPACE SUM
        IF (IEXCOR .EQ. 1) THEN
C       SLATER X-ALPHA:
          XCE0 = 0.75D0*XCMU0
        ELSE
C         GENERAL CASE:
          VMUXC  = EXCG(1,ISPIN)
          XCE0 = - DROTOT*VMUXC
          ENDIF
        ENDIF
1835    CONTINUE
C
      DO 1840 IG = 2, NGMAX
C
        CALL GCODE (IGLIST(1,IG),NG1,NG2,NG3,B1,B2,B3,IG1,IG2,IG3,GVEC)
        GG22 = DPROD(GVEC(1),GVEC(1)) + DPROD(GVEC(2),GVEC(2)) +
     +         DPROD(GVEC(3),GVEC(3))
C       (WE USE PLENTY OF "DOUBLE COMPLEX" BELOW)
        IF (NSPIN .EQ. 1) THEN
          DROTOT = ROTOT(IG,1)
        ELSE
C         SPIN-UP + SPIN-DOWN FOR HARTREE TERM
          DROTOT = ROTOT(IG,1) + ROTOT(IG,2)
          ENDIF
        IF (ABS(DROTOT) .LT. 1.0E-14) DROTOT = 0.0D0
C       HARTREE POTENTIAL
C       8PI IN STEAD OF 4PI (FOR ENERGY IN RYDBERGS)
        VHARTR = 8.0D0 * PI / (GCONV * GG22)
        VHARTR = VHARTR * DROTOT
        IF (ABS(VHARTR) .LT. 1.0E-14) VHARTR = 0.0D0
        DO 1837 ISPIN = 1, NSPIN
          VNEW(IG,ISPIN) = VHARTR
1837      CONTINUE
C       HARTREE TERM IN ENERGY (EV)
        EHARTR = REAL( VHARTR * CONJG(DROTOT) ) * RYEV
        SHARTR = SHARTR + EHARTR
C
        IF (LSTRES) THEN
C         HARTREE STRESS:
          STRSHA(1,1) = STRSHA(1,1) +
     +      (DPROD( GVEC(1), GVEC(1) ) / GG22 - 0.5D0) * EHARTR
          STRSHA(2,2) = STRSHA(2,2) +
     +      (DPROD( GVEC(2), GVEC(2) ) / GG22 - 0.5D0) * EHARTR
          STRSHA(3,3) = STRSHA(3,3) +
     +      (DPROD( GVEC(3), GVEC(3) ) / GG22 - 0.5D0) * EHARTR
          STRSHA(1,2) = STRSHA(1,2) +
     +       DPROD( GVEC(1), GVEC(2) ) / GG22          * EHARTR
          STRSHA(1,3) = STRSHA(1,3) +
     +       DPROD( GVEC(1), GVEC(3) ) / GG22          * EHARTR
          STRSHA(2,3) = STRSHA(2,3) +
     +       DPROD( GVEC(2), GVEC(3) ) / GG22          * EHARTR
          ENDIF
1840  CONTINUE
C
C     NEW POTENTIAL
C
      DO 1850 ISPIN = 1 , NSPIN
      DO 1850 IG = 2, NGMAX
C
        VHARTR = VNEW(IG,ISPIN)
        VNEW(IG,ISPIN) = VIONIC(IG,ISPIN) + VHARTR + MUXCG(IG,ISPIN)
C
C       ELEMENTS SMALLER THAN 1.0E-15 IS CONSIDERED AS ZERO
        IF (ABS( REAL(VNEW(IG,ISPIN))) .LT. 1.0E-15)
     +                VNEW(IG,ISPIN) = CMPLX(0.0,AIMAG(VNEW(IG,ISPIN)))
        IF (ABS(AIMAG(VNEW(IG,ISPIN))) .LT. 1.0E-15)
     +                VNEW(IG,ISPIN) = CMPLX(REAL(VNEW(IG,ISPIN)),0.0)
        IF (LREAL)    VNEW(IG,ISPIN) = CMPLX(REAL(VNEW(IG,ISPIN)),0.0)
C
C       EXCHANGE-CORRELATION
C
        DROTOT = CONJG( ROTOT(IG,ISPIN) )
        IF (ABS(DROTOT) .LT. 1.0E-14) DROTOT = 0.0D0
C       DID WE DO FOURIER TRANSFORM OF XC-ENERGY ?:
        IF (IXCE .NE. 0) THEN
          IF (IEXCOR .EQ. 1) THEN
C           X-ALPHA:
            XCE  = XCE + 0.75 * REAL(MUXCG(IG,ISPIN) * DROTOT)
          ELSE
C           THE GENERAL CASE:
            XCE  = XCE + REAL(EXCG(IG,ISPIN) * DROTOT)
            ENDIF
          ENDIF
C
        XCMU   = XCMU   + REAL(DROTOT * MUXCG(IG,ISPIN))
        SWORK  = SWORK  + REAL(DROTOT * VGTOT(IG,ISPIN))
        SIONIC = SIONIC + REAL(DROTOT * VIONIC(IG,ISPIN))
C
1850    CONTINUE
C
C     IF WE WERE ON CYCLE 0 THEN NOW GO BACK TO START CYCLE 1
      IF (ICYCLE .EQ. 0) THEN
        DO 1855 ISPIN = 1, NSPIN
        VGTOT(1,ISPIN) = (0.0,0.0)
        DO 1855 I = 2, NGMAX
          VGTOT(I,ISPIN) = VNEW(I,ISPIN)
1855      CONTINUE
        ICYCLE = 1
        GOTO 1260
        ENDIF
C
C     CONVERSION TO EV AND PRINTOUT OF CONTRIBUTIONS TO TOTAL ENERGY:
      XCMU   = XCMU   * RYEV
      XCMU0  = XCMU0  * RYEV
      XCE    = XCE    * RYEV
      XCE0   = XCE0   * RYEV
      XCETOT = XCE + XCE0
      SWORK  = SWORK  * RYEV
      SIONIC = SIONIC * RYEV
      SUMMU  = SUMMU  * RYEV
      SUMEXC = SUMEXC * RYEV
      IF (IXCE .EQ. 0) XCETOT = SUMEXC
C     HARTREE CONTRIBUTION TO ETOT IS ONLY V-HARTREE / 2 !
      SHARTR = SHARTR * 0.5D0
C
C     CORRECTION TERM TO THE SUM OF EIGENVALUES:
C     (V-NEW - V-OLD) * RHO* = (D+2E+F - C)
C     WE EXCLUDE G=0, WHERE ONLY MU-XC CONTRIBUTES, SINCE THIS TERM
C     IS ABSENT IN THE EIGENVALUES (SEE COMMENT ABOUT TERM (G) ).
      EIGCOR = SIONIC + 2.0D0*SHARTR + XCMU - SWORK
C
      IF (LSTRES) THEN
C       EXCHANGE-CORRELATION STRESS:
        DO 1860 I = 1,3
          STRSXC(I,I) = XCETOT - (XCMU + XCMU0)
1860      CONTINUE
        ENDIF
C
C-----------------------------------------------------------------------
C
C     CALCULATION OF THE EWALD TERMS
C
      IF (IEWALD .EQ. 0) THEN
        CALL USAGE(NPAGE0,TII)
C       A reasonable value EPS = 2.0 (should be immaterial)
        EPS = 2.0
        CALL IONION (A1,A2,A3,XKAPA,ULA,ZKAPA,NAT,EPS,NDIM9,
     +      GAMAEW,FORCII,STRSII)
C       Symmetrization of ion-ion forces:
        CALL FORSYM (TY,XKAPA,A1,A2,A3,NAT,ISY,NC,IB,V,F0,R,
     +    FORCWK,NDIM9,FORCII)
        CALL USAGE(NPAGE1,T1)
        WRITE (IOUT,1598) T1 - TII
1598    FORMAT(' Gamma-Ewald, forces, stresses: ',F10.3,' seconds')
        IEWALD = 1
        ENDIF
C-----------------------------------------------------------------------
C
C     PRINTOUT OF THE TOTAL BAND AND KINETIC ENERGIES:
C
      WRITE (IOUT,DASHES)
      WRITE (IOUT,*) 'Terms in total energy per unit cell:'
C      IF (ICYCLE .LE. 0) GOTO 1630
C
      WRITE (IOUT,1620) TOTBDE
1620  FORMAT(' (A)  Sum of second order eigenvalues',
     +  T66,F12.5,' EV')
      IF (IEVAL .LT. 2) WRITE (IOUT,1621) TOT1ST
1621  FORMAT(' (A1) Sum of first order eigenvalues',
     +  T66,F12.5,' EV')
C
      WRITE (IOUT,1622) EIGCOR
1622  FORMAT(' (K)  Eigenvalue correction (D+2E+F - C):',
     +  T64,F14.5,' EV'/ 1X)
C
      WRITE (ISUMRY,1623) EIGCOR
1623  FORMAT(' Convergence: eigenvalue corr. (K) =',F15.6,' EV')
C
      IF (ISWCH .EQ. 1) THEN
C
      WRITE (IOUT,1624) TOTKIN
1624  FORMAT(' (B)  Total kinetic energy :',T66,F12.5,' EV')
      IF (NONLOC) WRITE (IOUT,1625) TOTNL
1625  FORMAT(' (H)  Non-local energy:     ',T66,F12.5,' EV')
      IF (.NOT. LOWDIN .OR. IEVAL .NE. 0) THEN
        CHECK = TOTKIN + TOTNL + SWORK - TOTBDE
        WRITE (IOUT,1880) CHECK
1880    FORMAT (' (M)  Energy check: kinetic+potential - eigenvalues ',
     +          '(B+H+C-A):',T64,F14.5,' eV')
C       Error: should be < 1 milli-eV
        IF (ABS(CHECK) .GT. 0.001) THEN
          WRITE (IOUT,*) '**** The checks differ significantly ****'
          WRITE (IOUT,*) 'The Schrodinger eq. is not solved correctly'
          IWARN = 1
          ENDIF
        ENDIF
C
        ENDIF
C
      CHECK = SUMMU - (XCMU+XCMU0)
      WRITE (IOUT,1870) SWORK,SIONIC,SHARTR,XCMU,XCMU0,SUMMU,CHECK
1870  FORMAT (' (C)  Sum of V(input)(G) * RO(G)* , G=0 excluded:',
     +  T64,F14.5,' EV'/
     +' (D)  Sum of V(ionic)(G) * RO(G)* , G=0 excluded:',
     +  T64,F14.5,' EV'/
     +' (E)  Sum of V(Hartree)(G)/2 * RO(G)* , G=0 excluded:',
     +  T64,F14.5,' EV'//
     +' (F)  Sum of mu(X-C)(G) * RO(G)* , G=0 excluded:',
     +  T64,F14.5,' EV'/
     +' (G)  mu(X-C)(G=0) * RO(G=0)*:',T64,F14.5,' EV'/
     +' (F+G) XC-potential, direct-space integral',T64,F14.5,' EV'/
     +' (N)   Check X-C: (F+G)-(F)-(G)',T64,F14.5,' eV')
C
C     Error: should be < 1 milli-eV
      IF (ABS(CHECK) .GT. 0.001) THEN
        WRITE (IOUT,*) '**** The checks differ significantly ****'
        WRITE (IOUT,*) 'Troubles in exchange-correlation (EXCH4)'
        IWARN = 1
        ENDIF
C
      IF (IXCE .NE. 0) WRITE (IOUT,1871) XCE,XCE0,XCETOT
1871  FORMAT(' (I) sum of E(X-C)(G) * RO(G)* , G=0 excluded:',
     +  T64,F14.5,' EV'/
     +' (J) term E(X-C)(G=0) * RO(G=0)*:',T64,F14.5,' EV'/
     +' (I+J)',T64,F14.5,' EV')
C
      WRITE (IOUT,1872) SUMEXC
1872  FORMAT(' (I+J) XC-energy, direct-space integral',T64,F14.5,' EV'/)
C
      WRITE (IOUT,1873) GAMAEW, ETOTAZ
1873  FORMAT (' (W)   Gamma-Ewald',T64,F14.5,' eV'/
     +        ' (Z)   Alpha*Z',    T64,F14.5,' eV')
C
C-----------------------------------------------------------------------
C
      IF (ISWCH .EQ. 1 .AND. ICYCLE .GT. 1) THEN
C
C       TOTAL ENERGY (SECOND FORMULA) COMBINED FROM EIGENVALUES OF THIS
C       CYCLE (OF SELFCONSISTENCY) AND CHARGE DENSITIES OF THE PREVIOUS
C       CYCLE (SEE EQ.(28) IN WENDEL,MARTIN, PHYS. REV. B19 (1979) 5251
        ENTOT2 = TOTBDE + XCMU0 - SHARTR +
     +    XCETOT - (XCMU0 + XCMU) + ETOTAZ + GAMAEW
C       WRITE (IOUT,1630) ENTOT2
C1630   FORMAT (' total energy per unit cell:',
C    +    ' (A+G)-E+(I+J)-(F+G)+W+Z:',T64,F14.5,' EV'/
C    +  ' (E,F,G,I,J FROM THE PREVIOUS CYCLE, A FROM THE PRESENT ONE)')
         ENDIF
C
C     THREE WAYS OF EVALUATING THE TOTAL ENERGY:
C
C     (IHM,ZUNGER,COHEN, J. PHYS. C 12 (1979) 4409, EQS. (16), (26) ):
C     THE TERM XCMU0 IN ENTOT2 CORRECTS THE OMISSION OF THE TERM
C     VMUXC(G=0) IN THE SCHRODINGER EQUATION:
C     ALL EIGENVALUES IN THE SUM TOTBDE WERE SHIFTED DOWN BY
C     THE AMOUNT VMUXC(G=0), THEREFORE WE HAVE TO ADD VMUXC(G=0)*NEL,
C     WHICH AMOUNTS TO ADDING VMUXC(G=0)*RO(G=0) TO TOTBDE.
C     THE BAND ENERGY IS ALSO CORRECTED AS DESCRIBED ABOVE, TO GIVE A
C     CONSISTENT EVALUATION OF THE TOTAL ENERGY
C     A THIRD WAY EXISTS, RELYING ON THE IDENTITY OF THE TWO CHECKS,
C     TAKING ONLY THE SUM OF EIGENVALUES (A1)
C
      ETERM  = SIONIC + SHARTR + XCETOT + GAMAEW + ETOTAZ
      ENTOT1 = TOTKIN + TOTNL  + ETERM
      ENTOT2 = TOTBDE - SWORK  + ETERM
      ENTOT3 = TOT1ST - SWORK  + ETERM
C      ENTOT1 = TOTKIN + TOTNL + SHARTR + XCETOT + SIONIC +
C     +         GAMAEW + ETOTAZ
C      ENTOT2 = (TOTBDE + EIGCOR) + XCMU0 - SHARTR + XCETOT -
C     +         (XCMU + XCMU0) + GAMAEW + ETOTAZ
C      ENTOT3 = TOT1ST - SWORK + SHARTR + XCETOT + SIONIC +
C     +         GAMAEW + ETOTAZ
C
      WRITE (IOUT,DASHES)
      WRITE (IOUT,*) 'Total energy per unit cell:'
C      IF (ISWCH .EQ. 1) THEN
C        WRITE(IOUT  ,1900) 'Kinetic energy formula ',ENTOT1
C        WRITE(ISUMRY,1900) 'Kinetic energy formula ',ENTOT1
C1900    FORMAT (1X,A,T35,'B+H+D+E+(I+J)+W+Z:',T64,F14.5,' EV')
C        ENDIF
      WRITE(IOUT  ,1910) 'Band energy formula ',ENTOT2
      WRITE(ISUMRY,1910) 'Band energy formula ',ENTOT2
1910  FORMAT(1X,A,T35,T35,'A-C+D+E+(I+J)+W+Z:',T64,F14.5,' eV')
      IF (LOWDIN .AND. IEVAL .NE. 2) THEN
        WRITE (IOUT  ,1920) 'Using first order eigenvalues ',ENTOT3
        WRITE (ISUMRY,1920) 'Using first order eigenvalues ',ENTOT3
1920    FORMAT(1X,A,T35,'A1-C+D+E+(I+J)+W+Z:',T64,F14.5,' EV')
        ENDIF
C
      WRITE (IOUT,DASHES)
      IF (IWARN .NE. 0) THEN
        WRITE (IOUT,*)   '***** WARNING(S) has been issued above ****'
        WRITE (ISUMRY,*) '***** WARNING(S) has been issued above ****'
        ENDIF
C
C-----------------------------------------------------------------------
C
C     FORCE THEOREM (HELLMANN-FEYNMAN FORCES)
C
      IF (.NOT. LFORCE) GOTO 1980
      WRITE(IOUT,1940)
1940  FORMAT(' Site   Atom  Alpha     Force F(alpha)'/
     +  ' Kappa  type  X,Y,Z     (units:millidyne)'/
     +  20X,'Ion-ion',8X,'El-ion(n.l.)   El-ion(local)        total')
      WRITE (ISUMRY,*) 'Forces (millidyne) on atoms:'
C
      DO 1970 KAPA = 1,NAT
        WRITE (IOUT,*) ' '
        DO 1960 IALF = 1,3
          F1 = FORCII(IALF,KAPA) * RYDERG
          F2 = FORCEL(IALF,KAPA) * RYDERG
          F3 = FORCLO(IALF,KAPA) * RYDERG
          FTOT = F1 + F2 + F3
          WRITE (IOUT,1950) KAPA,TY(KAPA),IALF,F1,F2,F3,FTOT
1950      FORMAT(1X,3I5,2X,3G15.7,F15.7)
1960      CONTINUE
        WRITE (ISUMRY,1965) KAPA, ( (FORCII(I,KAPA) + FORCEL(I,KAPA) +
     +    FORCLO(I,KAPA) ) * RYDERG, I=1,3)
1965    FORMAT(1X,I3,3X,3F15.5)
1970    CONTINUE
      WRITE (IOUT,DASHES)
C-----------------------------------------------------------------------
C
C     CALCULATION OF THE STRESS TENSOR
C
1980  IF (.NOT. LSTRES) GOTO 2070
C     LOCAL POTENTIAL STRESS:
      CALL STRLOC (POTPAR,POTFIL,NTYPMX,NDIM9,NPARAM,
     +  NSPIN,POTWRK,NQMAX,
     +  VOLUM,ULA,NAT,
     +  TY,POTTYP,STRFAC,NDIM1,IGLIST,NGTOT,G2TAB,NTAB,NDIM2,
     +  ROTOT,NG1,NG2,NG3,B1,B2,B3,STRSLO)
C     TOTAL STRESS
      DO 2000 I = 1,3
      DO 2000 J = 1,3
        STRES1(I,J) = STRSKE(I,J) + STRSNL(I,J) + STRSHA(I,J) +
     +  STRSXC(I,J) + STRSLO(I,J) + STRSAZ(I,J) + STRSII(I,J)
C       TOTAL POTENTIAL STRESS: NON-LOCAL + LOCAL + ALPHA*Z
        STRES3(I,J) = STRSNL(I,J) + STRSLO(I,J) + STRSAZ(I,J)
C       STRESS IN KILO-BAR, WITH MINUS TO INDICATE EXTERNAL PRESSURE
        STRES2(I,J) = - STRES1(I,J) * 1.60219E3/(VOLUM*ULA**3)
2000    CONTINUE
C
      WRITE (IOUT,2010) 1,2,3,4,5,6
2010  FORMAT(' Terms in the stress tensor (units: eV/cell):'/
     +  ' tensor index:  ',6(I1,11X))
      WRITE (IOUT,2020) 'Kinetic',(STRSKE(IND(I),JND(I)),I=1,6)
      IF (NONLOC)
     +WRITE (IOUT,2020) 'V-nonlo',(STRSNL(IND(I),JND(I)),I=1,6)
      WRITE (IOUT,2020) 'V-local',(STRSLO(IND(I),JND(I)),I=1,6)
      WRITE (IOUT,2020) 'Alpha*Z',(STRSAZ(I,I),I=1,3)
      WRITE (IOUT,2020) 'V-total',(STRES3(IND(I),JND(I)),I=1,6)
      WRITE (IOUT,2020) 'Hartree',(STRSHA(IND(I),JND(I)),I=1,6)
      WRITE (IOUT,2020) 'Ion-ion',(STRSII(IND(I),JND(I)),I=1,6)
      WRITE (IOUT,2020) 'XC E-mu',(STRSXC(I,I),I=1,3)
      WRITE (IOUT,*)    '-------'
      WRITE (IOUT,2020) 'Total :',(STRES1(IND(I),JND(I)),I=1,6)
2020  FORMAT (1X,A7,6F12.5)
      WRITE (IOUT,2030) '-kbar :',(STRES2(IND(I),JND(I)),I=1,6)
2030  FORMAT (1X,A7,6(F10.3,2X))
      WRITE (ISUMRY,*) 'Total stresses (- kbar) sigma(1-6)'
      WRITE (ISUMRY,2040) (STRES2(IND(I),JND(I)),I=1,6)
2040  FORMAT (1X,6(F10.3,2X))
      WRITE (IOUT,DASHES)
C
C     EVALUATION OF ENTHALPY
C
      PVTERM = STRES1(1,1)*STRAIN(1) + STRES1(2,2)*STRAIN(2) +
     +         STRES1(3,3)*STRAIN(3) + STRES1(2,3)*STRAIN(4) +
     +         STRES1(1,3)*STRAIN(5) + STRES1(1,2)*STRAIN(6)
      ENTOT1 = ENTOT1 + PVTERM
      ENTOT2 = ENTOT2 + PVTERM
      ENTOT3 = ENTOT3 + PVTERM
      WRITE (IOUT,*) 'ENTHALPY/CELL (EV): E + STRESS*STRAIN:'
      IF (ISWCH .EQ. 1) THEN
        IF (IEVAL .NE. 2) THEN
          WRITE(IOUT,2065) 1,ENTOT1,2,ENTOT2,3,ENTOT3
        ELSE
          WRITE(IOUT,2065) 1,ENTOT1,2,ENTOT2
          ENDIF
      ELSE IF (ISWCH .EQ. 2) THEN
        IF (IEVAL .NE. 2) THEN
          WRITE(IOUT,2065) 2,ENTOT2,3,ENTOT3
        ELSE
          WRITE(IOUT,2065) 2,ENTOT2
          ENDIF
        ENDIF
2065  FORMAT(' Formula no. ',I1,':',F14.5,I5,':',F14.5,I5,':',F14.5)
      WRITE (IOUT,DASHES)
C-----------------------------------------------------------------------
C
C     PRINTOUT OF RO AND POTENTIALS, FOR REPRESENTATIVE G-VECTORS:
C
2070  IF (IVGDIS .LE. 0) GOTO 2130
      DIFMAX = - 1.0
      MDIFF  = 0
      ISPDIF = 0
      IF (NSPIN .EQ. 1) THEN
        WRITE (IOUT,2100) ' '
      ELSE
        WRITE (IOUT,2100) '*** First spin-up, then spin-down ***'
        ENDIF
2100  FORMAT ('0Charge density and potentials at selected G-vectors: ',
     +  '(Real,Imaginary)'/A/
     +  '    I       G(I)**2',13X,'RHO(G)',
     +                   T52,'Output local-potential'/
     +  8X,'IG1 IG2 IG3',T52,'delta-V   (Ry/Un.cell)'/1X)
C
      DO 2120 M = 1, MINDIM - 1
      I     = NTAB(M)
      IF (I .GT. NGMAX) GOTO 2125
      DO 2120 ISPIN = 1, NSPIN
        VDIFF = VGTOT(I,ISPIN) - VNEW(I,ISPIN)
        IF (ABS(VDIFF) .GT. DIFMAX) THEN
          DIFMAX = ABS(VDIFF)
          MDIFF  = M
          ISPDIF = ISPIN
          ENDIF
        IF (M .GT. IVGDIS .OR. G2TAB(M) .LT. 0.0) GO TO 2120
        IG1 = IGLIST(1,I)
        IG2 = IGLIST(2,I)
        IG3 = IGLIST(3,I)
        WRITE (IOUT,2110) I,G2TAB(M),ROTOT(I,ISPIN),
     +    VNEW(I,ISPIN),IG1,IG2,IG3,VDIFF
2110    FORMAT (1X,I4,F14.4,2X,4G13.6/7X,3I4,22X,'delta=',2G13.6)
2120    CONTINUE
C
C     PRINT OUT MAXIMUM DEVIATION
C
2125  WRITE (IOUT,*) ' MAXIMUM DEVIATION FOUND AT'
      M = MDIFF
      ISPIN = ISPDIF
      I = NTAB(M)
      VDIFF = VGTOT(I,ISPIN) - VNEW(I,ISPIN)
        IG1 = IGLIST(1,I)
        IG2 = IGLIST(2,I)
        IG3 = IGLIST(3,I)
      WRITE (IOUT,2110) I,G2TAB(M),ROTOT(I,ISPIN),VNEW(I,ISPIN),
     +  IG1,IG2,IG3,VDIFF
      WRITE (ISUMRY,*) 'MAXIMUM DEVIATION FOUND AT:'
      WRITE (ISUMRY,2115) G2TAB(M),VNEW(I,ISPIN),VDIFF
2115    FORMAT (' G**2=',F8.2,' Vin/Vdiff=',4F12.6)
C
C     POSSIBLE MORE DETAILED DISPLAY:
C
2130  IF (NLOOPS .GT. 1) GOTO 2180
      WRITE (IOUT,2140)
2140  FORMAT (' Do you wish to see the table of charge density and poten
     +tials'/' in some more detail?')
      WRITE (IUNIT7,YESNO)
      READ (INPUT,*) IYES
      IF (IYES .LT. 0) GOTO 2180
      WRITE (IOUT,*) 'Enter two order-numbers meaning "from, to"'
      READ (INPUT,*) IFROM,ITO
      IFROM = MAX(1,IFROM)
      ITO   = MIN(ITO,NGTOT)
      DO 2170 I=IFROM,ITO
        IG1 = IGLIST(1,I)
        IG2 = IGLIST(2,I)
        IG3 = IGLIST(3,I)
        DO 2170 ISPIN = 1, NSPIN
        WRITE (IOUT,2160) I,IG1,IG2,IG3,ROTOT(I,ISPIN),
     +    VNEW(I,ISPIN),VGTOT(I,ISPIN)
2160    FORMAT (1X,I4,2X,3I4,4G13.6/45X,2G13.6)
2170    CONTINUE
      GOTO 2130
C
2180  WRITE (IOUT,DASHES)
C-----------------------------------------------------------------------
C
C MIXING THE OLD AND NEW POTENTIALS TO GET THE NEW WORKING POTENTIAL:
C
      CALL USAGE (NPM0,TM0)
      IF (NLOOPS .EQ. 1) THEN
        WRITE (IOUT,2210)
2210    FORMAT(' IDMAT - CONTROLS WHERE DIELECTRIC MATRIX COMES FROM',/,
     +  ' 1 ..... SIMPLE MIXING MATRIX',/,
     +  ' 2 ..... FREE ELECTRON LINDHARD MATRIX',/,
     +  ' 3 ..... FULL LINDHARD MATRIX',/,
     +  ' 4 ..... USE PREVIOUS DIELECTRIC MATRIX',/,
     +  ' UPDATE - DETERMINES THE TYPE OF UPDATING',/,
     +  ' 1 ..... USE PREVIOUS DIELECTRIC MATRIX (NO UPDATING)',/,
     +  ' 2 ..... RECALCULATE DIELECTRIC MATRIX',/,
     +  ' 3 ..... BROYDEN SCHEME',/,
     +  ' 4 ..... SYMMETRIC SCHEME',/,
     +  ' 5 ..... BFGS SCHEME')
        WRITE(IOUT,*) 'Enter IDMAT,UPDATE,VCL,ALPHAS,ALPHAB,GSQUBS'
        READ (INPUT,*)         IDMAT,IUPDAT,VCL,ALPHAS,ALPHAB,GSQUBS
        ENDIF
C
      DO 2200 ISPIN = 1, NSPIN
C
C       Preserve IDMAT and IUPDAT for NSPIN=2, because MIXVG changes them
        IDMAT0 = IDMAT
        IUPDA0 = IUPDAT
        CALL MIXVG (IDMAT0,IUPDA0,VCL,ALPHAS,ALPHAB,GSQUBS,
     +    VGTOT(1,ISPIN), VNEW(1,ISPIN),
     +    HKMIX(0,0,ISPIN),CHI,INVCHI,XKMIX(1,ISPIN),FKMIX(1,ISPIN),
     +    NDIM2,NDIM5,NDIM8,NDIM10,NDIM12,NDIM13,
     +    ISPIN,NSPIN,
     +    IGLIST,LIST,NGTOT,NTAB,G2TAB,NG1,NG2,NG3,A1,A2,A3,
     +    B1,B2,B3,VOLUM,ULA,NEL,LI,NC,IB,R,RB,RTABLE,RLIST,V,
     +    YK,SK,SKHK,SMHY,HKOLD(0,0,ISPIN),
     +    LISTAB,CEV,LWGHT,MINBDS,EE1,EE2,EF,IEVFIL,
     +    NUMKPT,LSEMI,LREAL,NHK,NPWCHI,IDIFF,IPG,INDEX,IFILEH)
C
2200    CONTINUE
C     Reset IDMAT and IUPDAT:
      IDMAT  = IDMAT0
      IUPDAT = IUPDA0
C
      CALL USAGE (NPM1,TM1)
      WRITE(IUNIT8,2211) TM1-TM0
2211  FORMAT(' Time in MIXVG =',F10.3,' seconds')
C
C-----------------------------------------------------------------------
C
C     CLOSING THE SELFCONSISTENCY LOOP:
C
      ICYCLE = ICYCLE + 1
C
C     TIMING
2215  CALL USAGE(NPAGE1,T1)
      T1 = T1 - TCYCL0
      WRITE (IUNIT7,2220) T1
2220  FORMAT (1X,F15.3,' CPU seconds spent in this cycle')
      WRITE (ISUMRY,*) 'S-C cycle time =',T1,' seconds'
C
C     CONTINUE WITH THE NUMBER OF LOOPS GIVEN BY ISELFC
      IF (NLOOPS .LT. ISELFC) GOTO 1400
C
2230  WRITE (IOUT,2240)
2240  FORMAT (' decide about the next step :'/
     +  ' 1 = repeat once more the selfconsistent loop'/
     +  ' 2 = modify any parameter defining the run'/
     +  ' 3 = stop the program'/
     +  ' 4 = stop, but first save the last working potential'/
     +  ' 5 = stop, as 4, but save also charge density on file')
      READ (INPUT,*) ISTEER
      WRITE (IOUT,*) ISTEER,' switch for next step'
C
      IF (ISTEER .EQ. 1) THEN
        GOTO 1400
      ELSE IF (ISTEER .EQ. 2) THEN
        GOTO 300
      ELSE IF (ISTEER .EQ. 3) THEN
        WRITE (IOUT,*) 'Are you sure that you want to stop ?'
        WRITE (IOUT,YESNO)
        READ (INPUT,*) IYES
        WRITE (IOUT,*) IYES
        IF (IYES .NE. 1) GOTO 2230
        GOTO 2300
      ELSE IF (ISTEER .NE. 4 .AND. ISTEER .NE. 5) THEN
        WRITE (IOUT,*) 'ISTEER = ',ISTEER,' is illegal'
        GOTO 2230
        ENDIF
C-----------------------------------------------------------------------
C
C     SAVING V ON FILE, IN THE SAME FORMAT AS THE INPUT POTENTIAL
C
      NPRGR = 207
      IVERSN = 1990
      CALL DAY(IYEAR,MONTH,IDAY)
      IRECTP = 11
C
      CALL POTWRI (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +  IRECTP,NAT,NGTOT,MINDIM,NSPIN,
     +  ULA,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +  G2MAX,NG1,NG2,NG3,EPSILO,NTAB,G2TAB,
     +  IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +  IGLIST,VIONIC,VGTOT,ROTOT,RUNPAR,
     +  NHK,HKMIX,XKMIX,FKMIX,POTWRK,
     +  NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,ISTORE)
C
      IF (ISTEER .EQ. 5) THEN
        IRECTP = 13
        CALL POTWRI (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +    IRECTP,NAT,NGTOT,MINDIM,NSPIN,
     +    ULA,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +    G2MAX,NG1,NG2,NG3,EPSILO,NTAB,G2TAB,
     +    IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +    IGLIST,VIONIC,VGTOT,ROTOT,RUNPAR,
     +    NHK,HKMIX,XKMIX,FKMIX,POTWRK,
     +    NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,ISTORE)
        ENDIF
C
C       STORE MIXING MATRIX
C
        IRECTP = 15
      CALL POTWRI (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +  IRECTP,NAT,NGTOT,MINDIM,NSPIN,
     +  ULA,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +  G2MAX,NG1,NG2,NG3,EPSILO,NTAB,G2TAB,
     +  IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +  IGLIST,VIONIC,VGTOT,ROTOT,RUNPAR,
     +  NHK,HKMIX,XKMIX,FKMIX,POTWRK,
     +  NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,ISTORE)
C
C     Close eigenvector and k-point files
2300  CLOSE (UNIT = IEVFIL , STATUS = 'KEEP')
      CLOSE (UNIT = IKPTS  , STATUS = 'KEEP')
      WRITE(IOUT,*) 'Closed units with KEEP option: ', IEVFIL,IKPTS
C
      WRITE (IOUT,2302) IKPTS
2302  FORMAT(' Do you want to store eigenvalues on unit ', I2,' ?')
      WRITE (IOUT,YESNO)
      READ  (INPUT,*) IYESNO
      WRITE (IOUT,*)  IYESNO,' ANSWERED'
      IF (IYESNO .EQ. 1) THEN
C
C     OPEN THE TEMPORARY FILE FOR STORING EIGENVALUE INFORMATION
      INQUIRE (UNIT=IKPTS, OPENED=LIKPTS)
      IF (LIKPTS) THEN
        REWIND (IKPTS)
      ELSE
C       Other machines don't like Apollo specials 
C       IF (MACTYP .EQ. 11) THEN
C         Apollo: Have to specify non-ANSI RECL:
C         OPEN  (UNIT = IKPTS, STATUS = 'UNKNOWN', FORM = 'UNFORMATTED',
C    +      FILE='fort.13', RECL = 8*NDIM8)
C       ELSE
          OPEN  (UNIT = IKPTS, STATUS = 'UNKNOWN', FORM = 'UNFORMATTED')
C         ENDIF
        ENDIF
        DO 2304 IKPT = 1, NUMKPT
          WRITE (IKPTS) (WVLIST(I,IKPT), I = 1, 3)
          DO 2304 ISPIN = 1, NSPIN
            WRITE (IKPTS) NBANDS(ISPIN,IKPT)
            WRITE (IKPTS) (EIGVAL(I,ISPIN,IKPT),I=1,NBANDS(ISPIN,IKPT))
2304        CONTINUE
        CLOSE (UNIT = IKPTS  , STATUS = 'KEEP')
        ENDIF
C
      CALL USAGE (NPEND,TEND)
      TEND   = TEND - T000
      NHOURS = IFIX ( TEND / 3600.0 )
      NMINUT = IFIX ( (TEND - NHOURS*3600.0) / 60.0 )
      SECS   = MOD  ( TEND , 60.0 )
      WRITE (IOUT,2308) TEND , NHOURS,NMINUT,SECS , NPEND - NP000
2308  FORMAT(1X,F15.3,' CPU seconds',
     +  ' = ',I3,' hours, ',I2,' minutes and ',F6.3,' seconds'/
     +  1X,I10,' page faults total')
      WRITE (ISUMRY,*) 'Total time =    ',TEND,' seconds'
      WRITE (IOUT,*) 'End of K207'
      WRITE (IOUT,ASTRIX)
C
      RETURN
      END
