      SUBROUTINE K214 (
     +  NDIM1,NDIM2,NDIM9,NDIM12,NPARAM,NRUN,NTYPMX,NSPIN,
     +  RUNPAR,HKMIX,XKMIX,FKMIX,
     +  XKAPA,G2TAB,TY,NTAB,IGLIST,G2LIST,LIST,NG1MAX,NG2MAX,NG3MAX,
     +  NATOM,POTPAR,POTTYP,POTFIL,POTWRK,
     +  VIONIC,VGTOT,VIOLD,VGOLD,IGLOLD,ROTOT)
C
C     READ A FILE WITH IONIC AND SCREENED POTENTIALS
C     AND MODIFY IT TO MAKE A (HOPEFULLY) BETTER STARTING
C     POINT FOR ANOTHER RUN WITH DIFFERENT LATTICE STRUCTURE
C
C     THE SCREENING POTENTIAL OF A PREVIOUS SELFCONSISTENT CALCULATION
C     IS ADDED TO V(IONIC) PLUS A SCREENED TERM OF DELTA-V(IONIC)
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....NUMERICAL AND PHYSICAL CONSTANTS USED THROUGHOUT PROGRAM
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
      COMPLEX HKMIX(0:NDIM12,0:NDIM12,NSPIN), XKMIX(NDIM12,NSPIN),
     +  FKMIX(NDIM12,NSPIN)
      COMPLEX POTWRK(NDIM1)
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      INTEGER TY(NDIM9),POTTYP(NTYPMX),NATOM(NDIM9)
      INTEGER LIST(-NG1MAX:NG1MAX,-NG2MAX:NG2MAX,-NG3MAX:NG3MAX)
      CHARACTER*80 POTFIL(NTYPMX)
      CHARACTER*(80) TEXT
C.....Running parameters
      REAL RUNPAR(NRUN)
      COMPLEX VIONIC(NDIM1,NSPIN), VGTOT(NDIM1,NSPIN),
     +  VIOLD(NDIM1,NSPIN), VGOLD(NDIM1,NSPIN), ROTOT(NDIM1,NSPIN)
      COMPLEX VSCREN
      INTEGER NTAB(NDIM2),IGLIST(3,NDIM1),IGLOLD(3,NDIM1)
      REAL G2TAB(NDIM2),XKAPA(3,NDIM9),STRAIN(6)
      REAL A1(3),A2(3),A3(3),B1(3),B2(3),B3(3)
C
      PARAMETER (INSCF = 1)
      PARAMETER (EXFACT = 0.8)
C     MACHINE TYPE
      COMMON /MACH1/ MACTYP
      COMMON /MACH2/ MACHIN(0:20)
      CHARACTER*7  MACHIN
C-----------------------------------------------------------------------
C
      CALL USAGE (NPAGE0,T0)
      CALL DAY(IYEAR,MONTH,IDAY)
      WRITE (IOUT,120) MACHIN(MACTYP),IDAY,MONTH,IYEAR
120   FORMAT(' K214 - SCREENING POTENTIAL - ',A,' COMPUTER',
     +  T63,I2,'-TH OF ',I2,',19',I2)
      WRITE (IOUT,*) 'NSPIN=',NSPIN
C
C     READ IN PREVIOUS SELFCONSISTENT POTENTIAL
C
      WRITE (IOUT,*) 'Reading previous potential from unit ', INSCF
      IRECTP = 11
C     PREVIOUS RUN: IONIC AND TRULY SELFCONSISTENT POTENTIAL
90    CALL POTRED (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +  IRECTP,NAT,NGOLD,MINDIM,NSPIN,
     +  ULAOLD,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +  G2MAX,NG1OLD,NG2OLD,NG3OLD,EPSILO,NTAB,G2TAB,
     +  IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +  IGLOLD,VIOLD,VGOLD,ROTOT,RUNPAR,NMIX,HKMIX,XKMIX,FKMIX,POTWRK,
     +  NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,INSCF)
C     READ IN OLD CHARGE DENSITY AND MIXING MATRIX SO RETURN TO POTRED
      IF (IRECTP .GT. 0) GOTO 90
C
C     ESTABLISH A LOOKUP LIST FOR IGLOLD
C
      CALL LOOK00 (IGLOLD,LIST,NGOLD,NG1OLD,NG2OLD,NG3OLD,
     +  NG1MAX,NG2MAX,NG3MAX)
C-----------------------------------------------------------------------
C
C     INITIAL GUESS FROM IONIC POTENTIAL SETUP
C
      WRITE (IOUT,*) 'Reading ionic potential from unit ', IN213
      IRECTP = 11
      CALL POTRED (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +  IRECTP,NAT,NGTOT,MINDIM,NSPIN,
     +  ULA,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +  G2MAX,NG1,NG2,NG3,EPSILO,NTAB,G2TAB,
     +  IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +  IGLIST,VIONIC,VGTOT,ROTOT,RUNPAR,NMIX,HKMIX,XKMIX,FKMIX,POTWRK,
     +  NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,IN213)
C
C     VOLUME OF THE UNIT CELL
      VOLUM = A1(1)*A2(2)*A3(3) + A2(1)*A3(2)*A1(3) +
     +        A3(1)*A1(2)*A2(3) - A1(3)*A2(2)*A3(1) -
     +        A2(3)*A3(2)*A1(1) - A3(3)*A1(2)*A2(1)
      VOLUM = ABS(VOLUM)
C
C-----------------------------------------------------------------------
C
      WRITE(IOUT,100) ULA
100   FORMAT('0ULA FOR THE COMING CALCULATION = ',F15.4)
C     SCALE THE POTENTIALS
      FACTOR = (ULAOLD/ULA)**3
      INFORM = 0
C
C     LOOP OVER SHELLS IN THE RECIPROCAL LATTICE
C
      DO 110 ISHELL = 1,NDIM2
      G2LGTH = G2TAB(ISHELL)
      IF (G2LGTH .LT. 0.0) GOTO 140
      NMIN = NTAB(ISHELL)
      NMAX = NTAB(ISHELL + 1) - 1
      CALL EPS1 (NEL,VOLUM,ULA,G2LGTH,EXFACT,FERMIK,EPSQ)
C     1 / EPS(Q):
      EPSQ1 = 1.0 / EPSQ
C
C     LOOP WITHIN ONE SHELL:
      DO 110 I = NMIN,NMAX
C
C     LOOKUP IN IGLOLD:
      CALL LOOKUP (LIST, NGOLD, IGLIST(1,I), IPLACE,
     +  NG1OLD, NG2OLD, NG3OLD, 1, 2)
C
      IF (IPLACE .LE. 0 .OR. IPLACE .GT. NGOLD) THEN
C       IGLIST(*,I) COULD NOT BE LOCATED:
        INFORM = INFORM + 1
        IF (INFORM .EQ. 1) WRITE (IOUT,*)
     +  'K214 *** WARNING *** INITIAL GUESS SCREENING RETAINED'
        IF (INFORM .LT. 5) WRITE(IOUT,130) I,IGLIST(1,I),
     +  IGLIST(2,I),IGLIST(3,I)
130     FORMAT(' IGLIST(',I5,') = ',3I9,' COULD NOT BE FOUND')
C
      ELSE
C
C       EXTRACT OLD SCREENING POTENTIAL, SCALE TO RIGHT VOLUME
        DO 135 ISPIN = 1, NSPIN
          VSCREN = (VGOLD(IPLACE,ISPIN) - VIOLD(IPLACE,ISPIN)) *
     +       FACTOR +
     +      (VIONIC(I,ISPIN) - VIOLD(IPLACE,ISPIN)*FACTOR) * 
     +      (EPSQ1 - 1.0)
C         ABOVE: SCREEN PERTURBATION IN IONIC POTENTIALS.
C
C         THE NEW SCREENED POTENTIAL:
          VGTOT(I,ISPIN) = VIONIC(I,ISPIN) + VSCREN
135       CONTINUE
C
        ENDIF
C
110   CONTINUE
C
140   IF (INFORM .GT. 0) WRITE (IOUT,*) INFORM,' WARNINGS IN TOTAL.'
      CALL DAY(IYEAR,MONTH,IDAY)
C
C     STORE NEW POTENTIAL
C
      NPRGR = 214
      IRECTP = 11
      CALL POTWRI (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +  IRECTP,NAT,NGTOT,MINDIM,NSPIN,
     +  ULA,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +  G2MAX,NG1,NG2,NG3,EPSILO,NTAB,G2TAB,
     +  IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +  IGLIST,VIONIC,VGTOT,ROTOT,RUNPAR,NMIX,HKMIX,XKMIX,FKMIX,POTWRK,
     +  NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,ISTORE)
C
C     STORE MIXING MATRIX
C
      IRECTP = 15
      CALL POTWRI (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +  IRECTP,NAT,NGTOT,MINDIM,NSPIN,
     +  ULA,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +  G2MAX,NG1,NG2,NG3,EPSILO,NTAB,G2TAB,
     +  IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +  IGLIST,VIONIC,VGTOT,ROTOT,RUNPAR,NMIX,HKMIX,XKMIX,FKMIX,POTWRK,
     +  NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,ISTORE)
C
      CALL USAGE (NPAGE1,T1)
      WRITE (IOUT,200) T1 - T0
200   FORMAT(' End of K214 ', F10.3, ' CPU seconds')
      RETURN
      END
