      SUBROUTINE LOWPER (IFILEH,NDIM5,NDIM8,NA,NB,NBDS,DIAG,
     +EE2,CEV,CWF1,WK,RWK,LREAL)
C
C     CALCULATE NEW APPROXIMATE EIGENVECTORS FROM A LOWDIN
C     PERTURBATION CALCULATION. THE NEW EIGENVECTORS ARE
C     NORMALIZED AND THE RENORMALIZATION FACTORS ARE STORED
C     IN RWK. A NEW APPROXIMATE (BUT NOT VARIATIONAL)
C     EIGENVALUE IS CALCULATED AND STORED IN EE2.
C
      REAL EE2(NDIM8),RWK(NDIM8),DIAG(NDIM5)
      DIMENSION CEV(NDIM5,NDIM8),CWF1(NDIM5),WK(NDIM5,NDIM8)
      COMPLEX Z1,CDOTC,CDOTU
      REAL SDOT,SNRM2,SCNRM2
      LOGICAL LREAL
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C------------------------------------------------------------------
C     FOR COMPLEX HAMILTONIANS
C     COMPLEX CEV,CWF1,WK
C     IF (LREAL) WRITE(IOUT,*) '***LOWPER*** LREAL =',LREAL
C------------------------------------------------------------------
C     FOR REAL HAMILTONIANS
      REAL CEV,CWF1,WK
      IF (.NOT. LREAL) WRITE(IOUT,*) '***LOWPER*** LREAL =',LREAL
C------------------------------------------------------------------
C
      CALL USAGE (N0,T0)
C
      N    = NA+NB
      NAP1 = NA+1
C
      CALL REWFIL (IFILEH)
      DO 10 J = N,NAP1,-1
      IF (      LREAL) CALL RDVEC (IFILEH,CWF1,NA)
      IF (.NOT. LREAL) CALL RDVEC (IFILEH,CWF1,2*NA)
      DO 10 L = 1,NBDS
        IF (      LREAL) WK(J,L) = SDOT (NA,CWF1,1,CEV(1,L),1)
        IF (.NOT. LREAL) WK(J,L) = CDOTU(NA,CWF1,1,CEV(1,L),1)
10      CONTINUE
C
      DO 30 L = 1,NBDS
C
        DO 20 I = NAP1,N
20        CEV(I,L) = WK(I,L)/(EE2(L)-DIAG(I))
        IF (LREAL) THEN
          SUMA = SDOT  (NB,WK(NAP1,L),1,CEV(NAP1,L),1)
          SUMB = SNRM2 (NA,CEV(1,L),1)
          SUMC = SNRM2 (NB,CEV(NAP1,L),1)
        ELSE
          Z1   = CDOTC (NB,WK(NAP1,L),1,CEV(NAP1,L),1)
          SUMB = SCNRM2(NA,CEV(1,L),1)
          SUMC = SCNRM2(NB,CEV(NAP1,L),1)
          SUMA = REAL(Z1)
          ENDIF
        EE2(L) = EE2(L) + SUMA/SUMB/SUMB
C       WRITE(6,98) EE2(L)
C98     FORMAT( ' SHIFTED EIGENVALUE',E20.12)
        SUMA = SUMB*SUMB + SUMC*SUMC
        SUMA = 1.0/SQRT(SUMA)
        RWK(L) = SUMA
        IF (      LREAL) CALL SSCAL (N,SUMA,CEV(1,L),1)
        IF (.NOT. LREAL) CALL CSSCAL(N,SUMA,CEV(1,L),1)
C
30      CONTINUE
C
      CALL USAGE (N1,T1)
      WRITE(IUNIT8,99) T1-T0, N1-N0
99    FORMAT(' LOWPER - PERTURBATION THEORY ',F10.3,' SECONDS',
     +I10,' PAGE FAULTS')
C
      RETURN
      END
