      SUBROUTINE MATEL (IWRCUA,NONLOC,LFORCE,LSTRES,NOFORC,NBDS,WOCC,
     +  POTPAR,POTTYP,TY,NAT,ULA,VOLUM,DX,XKAPA,B1,B2,B3,NG1,NG2,NG3,
     +  NDIM1,NDIM3,NDIM5,NDIM8,NDIM9,NDIM11,NDIM13,NDIM20,NLMAX,
     +  NPARAM,NTYPMX,IGLIST,LIST,STRFAC,SATGR,SATGI,VNLIJ,VGTOT,NGTOT,
     +  LISTAB,GK,NANB,CWF1,VNLL,CWF4,RWF3,IWF5,LWORK,LREAL,CONV1,
     +  CEV,ENONLO,FORCE,SWF2,IFILEV,LEXIST)
C----------------------------------------------------------------------
C
C     CALCUATES MATRIX ELEMENTS OF THE NON-LOCAL PART OF THE HAMILTONIAN
C
C---------------------------------------------------------------------
C
C.....A AND B WAVES
      DIMENSION LISTAB(NDIM5),GK(4,NDIM5)
C.....LATTICE STRUCTURE
      DIMENSION B1(3),B2(3),B3(3),IGLIST(3,NDIM1)
      DIMENSION LIST(-NG1:NG1,-NG2:NG2,-NG3:NG3)
      REAL XKAPA(3,NDIM9)
      INTEGER TY(NDIM9)
C.....STRUCTURE FACTORS
      COMPLEX STRFAC(NTYPMX,NDIM1)
      REAL SATGR(NDIM9,NDIM1),SATGI(NDIM9,NDIM1)
      DOUBLE PRECISION DX(3,NDIM9)
C.....LOGICAL SWITCHES
      LOGICAL NOFORC(NDIM9),LREAL
      LOGICAL NONLOC,LFORCE,LSTRES,READNL,CALCNL,WRITEV,LSTRHM,LEXIST
C.....POTENTIALS
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      INTEGER POTTYP(NTYPMX)
      COMPLEX VGTOT(NDIM1)
      REAL VNLIJ(0:NDIM20,0:NDIM20,NLMAX,NTYPMX)
C.....WORKSPACES
      DOUBLE PRECISION SWF2(6),FORCE(3,NDIM9),ENONLO,WOCC(NDIM8)
      COMPLEX CWF1(NDIM5),CEV(NDIM5,NDIM8),CWF4(6,NDIM5),VNLL(NDIM5)
      REAL RWF3(NTYPMX,NDIM5)
      INTEGER IWF5(14*NDIM5),LWORK(3,NDIM5)
      DOUBLE PRECISION CONV1
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C----------------------------------------------------------------------
C
      CALL USAGE (NP0,T0)
C
C     SET SWITCHES FOR FILE HANDLING
C
      CALL FILMAT (READNL,CALCNL,LSTRHM,WRITEV,LSTRES,
     +  LFORCE,LEXIST,IWRCUA)
C
C     CLEAR ARRAYS
C
      ENONLO = 0.0D0
      IF (LSTRES) CALL DZERO (6,SWF2)
      IF (LFORCE) CALL DZERO (3*NDIM9,FORCE)
C
C----------------------------------------------------------------------
C
C     EVALUATION OF MATRIX ELEMENTS
C
C----------------------------------------------------------------------
C
      IF (LFORCE) CALL SFACT (STRFAC,SATGR,SATGI,TY,XKAPA,DX,IGLIST,
     +  B1,B2,B3,NDIM1,NDIM9,NTYPMX,NAT,NGTOT,NG1,NG2,NG3,LREAL)
C
      DO 30 M = NANB,1,-1
C
        I1 = 1
        I2 = M
        NROW = I2-I1+1
        IF (M .EQ. NANB) THEN
          DO 10 J = 1,3
          DO 10 N = I1,I2
10          LWORK(J,N) = IGLIST(J,LISTAB(N))
          ENDIF
        DO 20 J = 1,3
        NSTART = NDIM5-2*I1+J-1
        DO 20 N = I1,I2
20        IWF5(NSTART+3*N) = IGLIST(J,LISTAB(M)) - LWORK(J,N)
        CALL LOOKUP (LIST,NGTOT,IWF5(NDIM5+I1),IWF5(I1),
     +    NG1,NG2,NG3,NROW,-1)
C
        IF (READNL) THEN
          IF (     LREAL) CALL RDVEC (IFILEV,VNLL,  NROW)
          IF (.NOT.LREAL) CALL RDVEC (IFILEV,VNLL,2*NROW)
          ENDIF
C
        IF (CALCNL) CALL ROWHAM (I1,I2,M,VGTOT,GK,POTPAR,POTTYP,VNLIJ,
     +    NDIM1,NDIM5,NDIM20,NLMAX,NPARAM,STRFAC,NTYPMX,VOLUM,ULA,RWF3,
     +    CWF1,VNLL,CWF4,IWF5,LSTRHM,READNL,CALCNL,NONLOC,CONV1,LREAL)
C
        IF (LREAL) THEN
          CALL RPWSUM (LFORCE,LSTRES,NOFORC,NBDS,TY,NAT,I1,I2,
     +    IGLIST,NG1,NG2,NG3,LREAL,RWF3,VNLL,CWF4,IWF5,SATGR,SATGI,
     +    IWF5(NDIM5+1),IWF5(4*NDIM5+1),IWF5(6*NDIM5+1),IWF5(8*NDIM5+1),
     +    IWF5(10*NDIM5+1),CEV,WOCC,ENONLO,SWF2,FORCE,NDIM1,NDIM5,NDIM8,
     +    NDIM9,NTYPMX)
        ELSE IF (.NOT. LREAL) THEN
          CALL APWSUM (LFORCE,LSTRES,NOFORC,NBDS,TY,NAT,I1,I2,
     +    IGLIST,NG1,NG2,NG3,LREAL,RWF3,VNLL,CWF4,IWF5,SATGR,SATGI,
     +    IWF5(NDIM5+1),IWF5(4*NDIM5+1),IWF5(6*NDIM5+1),IWF5(8*NDIM5+1),
     +    IWF5(10*NDIM5+1),CEV,WOCC,ENONLO,SWF2,FORCE,NDIM1,NDIM5,NDIM8,
     +    NDIM9,NTYPMX)
          ENDIF
C
30      CONTINUE
C
C----------------------------------------------------------------------
C
C     UNIT CONVERSION
C
C----------------------------------------------------------------------
C
      CALL UNICON (ENONLO,SWF2,FORCE,B1,B2,B3,ULA,NDIM9,NAT,
     +  LSTRES,LFORCE)
C
      CALL USAGE (NP1,T1)
      WRITE(IUNIT7,40) T1 - T0, NP1 - NP0
40    FORMAT(' MATEL  - MATRIX ELEMENTS  ',T30,F10.3,' SECONDS',I10,
     +  ' PAGE FAULTS')
C
      RETURN
      END
      SUBROUTINE FILMAT (READNL,CALCNL,LSTRHM,WRITEV,LSTRES,
     +  LFORCE,LEXIST,IWRCUA)
C
C     SET SWITCHES BEFORE CALCULATING THE NON-LOCAL MATRIX ELEMENTS
C
      LOGICAL READNL,CALCNL,WRITEV,LSTRHM
      LOGICAL LSTRES,LFORCE,LEXIST
C
      READNL = .FALSE.
      IF (LEXIST) READNL = .TRUE.
      IF (LFORCE .OR. LSTRES) READNL = .FALSE.
      IF (IWRCUA .EQ. 1) READNL = .FALSE.
      CALCNL = .NOT. READNL
      LSTRHM =  CALCNL .AND. LSTRES
      WRITEV = .FALSE.
C
      RETURN
      END
