      SUBROUTINE POTVG (POTTYP,POTPAR,POTFIL,NTYPMX,NPARAM,ITYPE,NSPIN,
     +                  WORK,NQMAX,VOLUM,ULA,INIT,L,G2,VG,VGP,RHOG)
C
C     CALCULATE POTENTIAL IN G-SPACE
C
C     INPUT DATA   (HARTREE ATOMIC UNITS):
C     POTTYP ..... POTENTIAL TYPES
C     POTPAR ..... PARAMETER ARRAY
C     POTFIL ..... ATOMIC FILE NAMES
C     NTYPMX ..... MAX NO. OF ATOM TYPES
C     NPARAM ..... MAX NO OF PARAMETERS
C     ITYPE ...... THE ATOM TYPE CONSIDERED IN THIS CALL
C     WORK ....... WORKSPACE FOR POT20 (DOUBLE PRECISION)
C                  SIZE (NQMAX+1)*(2*NSPIN+1)
C     VOLUM ...... VOLUME OF THE ELEMENTARY UNIT CELL SPANNED BY THE
C                  VECTORS A1,A2,A3. UNITS: ULA**3
C     ULA ........ THE (ARBITRARY) LENGTH SCALE IN ANGSTROMS
C     INIT ....... 1 MEANS INITIALIZE ARRAYS
C                  0 MEANS GO ON FOR THIS ITYPE WITH DIFFERENT G2
C     L .......... ANGULAR MOMENTUM VALUE SELECTING THE POTENTIAL
C                  TO BE CALCULATED (L = 0,1,2,...).
C                  L = -1 DENOTES THE  L O C A L  POTENTIAL PART.
C     G2 ......... SQUARED LENGTH OF THE WAVEVECTOR
C                  IN UNITS (2*PI/ULA)**2.
C                  G2=0 IS FORBIDDEN
C
C     OUTPUT DATA:
C     VG ......... POTENTIAL IN RYDBERGS.
C     VGP ........ G**2 TIMES D( V(G**2) ) / D( G**2 )
C                  THE POTENTIAL IS NORMALIZED TO THE VOLUME OF THE
C                  UNIT CELL (AND  N O T  TO VOLUME PER ATOM),
C                  I.E. ONLY ONE ATOM PER UNIT CELL IS ASSUMED.
C     RHOG ....... PSEUDO-CHARGE DENSITY CALCULATED FROM V(G).
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      INTEGER POTTYP(NTYPMX)
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      CHARACTER*80 POTFIL(NTYPMX)
      REAL VOLUM,ULA
      DOUBLE PRECISION WORK(0:NQMAX,*),
     +                 VG(NSPIN), VGP(NSPIN), RHOG(NSPIN)
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
C
C     G2 IN ATOMIC UNITS AND DOUBLE PRECISION:
      G2AU  = G2 * (2.0D0 * PI * ABOHR / DBLE(ULA) )**2
      IF (G2AU .LT. 1.0E-10) G2AU = 1.0D-10
C     VOLUM IN ATOMIC UNITS:
      VOLAU = DBLE(VOLUM) * (DBLE(ULA) / ABOHR)**3
C
      IF (POTTYP(ITYPE) .EQ. 0) THEN
C
        VG(1)   = 0.0D0
        VGP(1)  = 0.0D0
        RHOG(1) = 0.0D0
        IF (NSPIN .EQ. 2) THEN
          VG(2)   = 0.0D0
          VGP(2)  = 0.0D0
          RHOG(2) = 0.0D0
          ENDIF
C
      ELSE IF (POTTYP(ITYPE) .EQ. 10) THEN
C
C       JELLIUM
C
        VG(1)   = 0.0D0
        VGP(1)  = 0.0D0
        RHOG(1) = 0.0D0
        IF (NSPIN .EQ. 2) THEN
          VG(2)   = 0.0D0
          VGP(2)  = 0.0D0
          RHOG(2) = 0.0D0
          ENDIF
C
      ELSE IF (POTTYP(ITYPE) .EQ. 11) THEN
C
C       PURE COULOMB POTENTIAL
C
        CALL POT11 (POTPAR,NTYPMX,NPARAM,ITYPE,INIT,L,
     +              G2AU,VG(1),VGP(1),RHOG(1))
C
        IF (NSPIN .EQ. 2) THEN
          VG(2)   = VG(1)
          VGP(2)  = VGP(1)
          RHOG(2) = RHOG(1)
          ENDIF
C
      ELSE IF (POTTYP(ITYPE) .EQ. 13) THEN
C
C       APPELBAUM-HAMANN POTENTIAL POT13:
C
C       CUTOFF:
        IF (G2AU .LT. POTPAR(ITYPE,7) .OR. L .EQ. -1 .OR.
     +      POTPAR(ITYPE,7) .LT. 0.0) THEN
          CALL POT13 (POTPAR,NTYPMX,NPARAM,ITYPE,INIT,
     +                G2AU,VG(1),VGP(1),RHOG(1))
        ELSE
          VG(1)   = 0.0D0
          VGP(1)  = 0.0D0
          RHOG(1) = 0.0D0
          ENDIF
        IF (NSPIN .EQ. 2) THEN
          VG(2)   = VG(1)
          VGP(2)  = VGP(1)
          RHOG(2) = RHOG(1)
          ENDIF
C
      ELSE IF (POTTYP(ITYPE) .EQ. 15) THEN
C
C       BERKELEY IONIC POTENTIAL POT15:
C
C       CUTOFF:
        IF (G2AU .LT. POTPAR(ITYPE,7) .OR. L .EQ. -1 .OR.
     +      POTPAR(ITYPE,7) .LT. 0.0) THEN
          CALL POT15 (POTPAR,NTYPMX,NPARAM,ITYPE,INIT,
     +                G2AU,VG(1),VGP(1),RHOG(1))
        ELSE
          VG(1)   = 0.0D0
          VGP(1)  = 0.0D0
          RHOG(1) = 0.0D0
          ENDIF
        IF (NSPIN .EQ. 2) THEN
          VG(2)   = VG(1)
          VGP(2)  = VGP(1)
          RHOG(2) = RHOG(1)
          ENDIF
C
      ELSE IF (POTTYP(ITYPE) .EQ. 16) THEN
C
C       BELL LABS EARLY POTENTIALS: SUM OF GAUSSIANS
C
        CALL POT16 (POTPAR,NTYPMX,NPARAM,ITYPE,INIT,L,
     +              G2AU,VG(1),VGP(1),RHOG(1))
        IF (NSPIN .EQ. 2) THEN
          VG(2)   = VG(1)
          VGP(2)  = VGP(1)
          RHOG(2) = RHOG(1)
          ENDIF
C
      ELSE IF (POTTYP(ITYPE) .EQ. 17) THEN
C
C       BELL LABS 1982-"PERIODIC TABLE" NON-LOCAL POTENTIAL:
C
        CALL POT17 (POTPAR,NTYPMX,NPARAM,ITYPE,NSPIN,
     +              INIT,L,G2AU,VG,VGP,RHOG)
C
      ELSE IF (POTTYP(ITYPE) .EQ. 20) THEN
C
C       NUMERICALLY GENERATED POTENTIALS
C
        CALL POT20 (POTPAR,POTFIL,NTYPMX,NPARAM,ITYPE,NSPIN,
     +    WORK(0,1),WORK(0,1+NSPIN),WORK(0,1+2*NSPIN),
     +    NQMAX,INIT,L,G2AU,VG,VGP,RHOG)
C
      ELSE
C
        WRITE (IOUT,1000) POTTYP(ITYPE)
1000    FORMAT('0Subroutine POTVG *** FATAL ERROR ***'/
     +  ' The potential type ',I3,' does not exist')
        CALL EXIT
        ENDIF
C
C     DIVIDE BY THE UNIT CELL VOLUME
      VG(1)  = VG(1)  / VOLAU
      VGP(1) = VGP(1) / VOLAU
      IF (NSPIN .EQ. 2) THEN
        VG(2)   = VG(2)  / VOLAU
        VGP(2)  = VGP(2) / VOLAU
        ENDIF
      RETURN
      END
      SUBROUTINE POT11 (POTPAR,NTYPMX,NPARAM,ITYPE,INIT,L,
     +                  G2,V,VP,RHOG)
C
C                                   WRITTEN APRIL 21, 1985 (OHN)
C     FOURIER TRANSFORM OF THE PURE COULOMB POTENTIAL
C
C     INPUT DATA (UNITS A.U.)
C     POTPAR ..... PARAMETER ARRAY
C     NTYPMX ..... MAX NO. OF ATOM TYPES
C     NPARAM ..... MAX NO OF PARAMETERS
C     ITYPE ...... THE ATOM TYPE CONSIDERED IN THIS CALL
C     INIT ....... (NOT USED)
C     L .......... ANGULAR MOMENTUM VALUE SELECTING THE POTENTIAL
C                  TO BE CALCULATED (L = 0,1,2,...).
C                  L>=0 WILL RETURN V=0.
C                  L = -1 DENOTES THE  COULOMB (LOCAL) POTENTIAL.
C     G2 ......... SQUARED LENGTH OF THE WAVEVECTOR IN ATOMIC UNITS
C                  G2=0 IS FORBIDDEN
C
C     OUTPUT DATA:
C     V .......... POTENTIAL IN RYDBERGS.
C     VP ......... G**2 TIMES D( V(G**2) ) / D( G**2 )
C                  THE POTENTIAL IS NOT NORMALIZED TO THE VOLUME.
C     RHOG ....... APPROXIMATE PSEUDO-ATOM CHARGE DENSITY.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
C
      V    = 0.0D0
      VP   = 0.0D0
C     THE VALENCE CHARGE DENSITY (APPROXIMATE FORM)
      RHOG = 0.0D0
      IF (L .GE. 0) RETURN
      IF (G2 .LT. 1.0E-10) GOTO 260
C
      Z      = NINT(POTPAR(ITYPE,1))
      V    = - 4.0D0 * PI * Z / G2
      VP   = - V
C
C     CONVERSION TO UNITS RYDBERGS
C
      V  = V  * 2.0D0
      VP = VP * 2.0D0
C
      IF (ABS(V)  .LT. 1.0E-10) V  = 0.0D0
      IF (ABS(VP) .LT. 1.0E-10) VP = 0.0D0
C     WRITE(IOUT,*) 'G2 = ',G2,' V = ',V
      RETURN
C-----------------------------------------------------------------------
C
C     ERROR MESSAGES
C
260   WRITE(IOUT,210)
210   FORMAT(' SUBROUTINE POT11 *** FATAL ERROR ***')
      WRITE(IOUT,270) G2
270   FORMAT(' G2 = ',G15.8,' IS ILLEGAL')
      CALL EXIT
      RETURN
      END
      SUBROUTINE POT13 (POTPAR,NTYPMX,NPARAM,ITYPE,INIT,
     +                  G2,V,VP,RHOG)
C                       WRITTEN ON NOVEMBER 14TH, 1979
C FOURIER TRANSFORM OF THE
C SOFT-CORE (IONIC) PSEUDOPOTENTIAL OF THE FORM
C PROPOSED BY APPELBAUM AND HAMANN, PHYS. REV. B8 (1973),1777.
C INPUT DATA
C      PARAMETERS OF THE POTENTIAL, IN THE SAME UNITS AS
C      IN APPELBAUM-HAMANN:
C      ZV ..... ATOMIC VALENCE CHARGE OR CORE CHARGE
C               (FOR SI: ZV=+4)
C      ALPHA .. WIDTH OF THE GAUSSIAN DISTRIBUTION OF THE
C               CORE-CHARGE
C               (UNITS: (BOHR RADIUS)**(-2))
C      V1 ..... PARAMETER OF THE CORE POTENTIAL
C               (UNITS: HARTREE)
C      V2 ..... PARAMETER OF THE CORE POTENTIAL
C               (UNITS: HARTREE*(BOHR RADIUS)**(-2))
C      G2 ..... SQUARED LENGTH OF WAVEVECTOR, IN ATOMIC UNITS
C
C OUTPUT DATA
C      V ...... POTENTIAL IN RYDBERGS
C      VP ..... G**2 TIMES D( V(G**2) ) / D( G**2 )
C               THE POTENTIAL IS NOT NORMALIZED TO THE VOLUME.
C      RHOG ... APPROXIMATE PSEUDO-ATOM CHARGE DENSITY
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
      ZV    = POTPAR(ITYPE,1)
      ALPHA = POTPAR(ITYPE,2)
      V1    = POTPAR(ITYPE,3)
      V2    = POTPAR(ITYPE,4)
C     CUTOFF:
      VGMAX = POTPAR(ITYPE,7)
      V    = 0.0D0
      VP   = 0.0D0
      RHOG = 0.0D0
      IF ((VGMAX .GT. 0.0 .AND. G2 .GT. VGMAX) .OR. G2 .LE. 0.0) RETURN
C
C     THE POTENTIAL AND ITS DERIVATIVE:
C
      DARG = G2/(4.0D0*ALPHA)
      VV = (V1 + 1.5D0*V2/ALPHA - V2*DARG/ALPHA) * (PI/ALPHA)**1.5
      V0 = - 4.0D0*PI*ZV/G2
      EXPFAC = DEXP( - DARG )
C     (2.0 FOR UNITS RYDBERG, IN STEAD OF HARTREES)
      V = 2.0D0*(V0 + VV)*EXPFAC
C
C     G**2 * V'(G):
      VV = V1 + 1.5D0*V2/ALPHA - V2*DARG/ALPHA
      VV = - (VV*DARG + V2*DARG/ALPHA) * (PI/ALPHA)**1.5
      V0 = 4.0D0*PI*ZV/G2*(DARG + 1.0D0)
      VP = 2.0D0*(V0 + VV)*EXPFAC
C
C     THE VALENCE CHARGE DENSITY (APPROXIMATE FORM)
C     (DOES NOT WORK WELL)
C     RHOG = ZV * EXPFAC
C
      IF (ABS(V)  .LT. 1.0E-10) V  = 0.0
      IF (ABS(VP) .LT. 1.0E-10) VP = 0.0
C
C     CHARGE DENSITY RHO(G): USE - G2*V/8*PI
C
      RHOG = - G2 * V / (8.0D0 * PI)
      RETURN
      END
      SUBROUTINE POT15 (POTPAR,NTYPMX,NPARAM,ITYPE,INIT,
     +                  G2,V,VP,RHOG)
C
C WRITTEN ON JANUARY 31ST, 1980 (K. KUNC)
C BERKELEY IONIC POTENTIAL
C OF THE FORM DEFINED (FIRST TIME, PROBABLY) BY SCHLUETER ET AL.,
C PHYS. REV. B 12 (1975) 4200.
C SUBROUTINES NEEDED: NONE
C
C INPUT DATA:
C              PARAMETERS OF THE POTENTIAL, IN THE SAME UNITS AS
C              IN BERKELEY PUBLICATIONS:
C      AA1 ... AA4 ... PARAMETERS OF THE POTENTIAL. UNITS:
C              LIKE IN THE PUBLICATIONS (I.E. UNDEFINED)
C      VNORM ... VOLUME TO WHICH THE PUBLISHED POTENTIAL WAS
C              NORMALIZED. UNITS: BOHR RADIUS**3. THIS IS USUALLY
C              PUBLISHED TOGETHER WITH AA1...AA4.
C      G2 .... SQUARED LENGTH OF WAVEVECTOR, IN ATOMIC UNITS
C OUTPUT DATA:
C      V .... POTENTIAL IN RYDBERGS.
C      VP ... G**2 TIMES D( V(G**2) ) / D( G**2 )
C             THE POTENTIAL IS NOT NORMALIZED TO THE VOLUME.
C      RHOG...APPROXIMATE PSEUDO-ATOM CHARGE DENSITY.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
      AA1   = POTPAR(ITYPE,1)
      AA2   = POTPAR(ITYPE,2)
      AA3   = POTPAR(ITYPE,3)
      AA4   = POTPAR(ITYPE,4)
      VNORM = POTPAR(ITYPE,5)
C     CUTOFF:
      VGMAX = POTPAR(ITYPE,7)
      V    = 0.0D0
      VP   = 0.0D0
      RHOG = 0.0D0
      IF ((VGMAX .GT. 0.0 .AND. G2 .GT. VGMAX) .OR. G2 .LE. 0.0) RETURN
C
      Q1  = DSQRT(G2)
      Q4  = G2 * G2
      ARG = AA4*Q4
      IF (ARG .GT. -30.0) THEN
        EXA4Q4 = DEXP(ARG)
      ELSE
C       EXP IS PRACTICALLY ZERO:
        EXA4Q4 = 0.0D0
        ENDIF
C
C     THE POTENTIAL AND ITS DERIVATIVE:
C
      ARG2 = AA2*Q1
      V = VNORM * AA1 / G2 * EXA4Q4 * ( DCOS(ARG2) + AA3 )
C
C     G**2 * V'(G**2):
      VP  = - VNORM * AA1 / G2 * EXA4Q4 *
     +  ( (DCOS(ARG2) + AA3) * (1.0D0 - 2.0D0*ARG) +
     +     0.5D0*ARG2*DSIN(ARG2) )
C
C     THE VALENCE CHARGE DENSITY (APPROXIMATE FORM)
C
      RHOG = - V * G2 / (8.0D0 * PI)
C
      IF (ABS(V)  .LT. 1.0E-10) V  = 0.0
      IF (ABS(VP) .LT. 1.0E-10) VP = 0.0
      RETURN
      END
      SUBROUTINE POT16 (POTPAR,NTYPMX,NPARAM,ITYPE,INIT,L,
     +                  G2,V,VP,RHOG)
C
C                                   WRITTEN APRIL 14, 1982 (OHN)
C     FOURIER TRANSFORM OF THE HAMANN-SCHLUTER-CHIANG NON-LOCAL
C     POTENTIAL (PHYS.REV.LETT 43,1494(1979) AND
C     BACHELET ET AL. PHYS.REV.B 24,4745(1981))
C
C     INPUT DATA (UNITS A.U. AS IN BACHELET ET AL.)
C     POTPAR ..... PARAMETER ARRAY
C     NTYPMX ..... MAX NO. OF ATOM TYPES
C     NPARAM ..... MAX NO OF PARAMETERS
C     ITYPE ...... THE ATOM TYPE CONSIDERED IN THIS CALL
C     INIT ....... 1 MEANS INITIALIZE ARRAYS
C                  0 MEANS GO ON FOR THIS ITYPE WITH DIFFERENT G2
C     L .......... ANGULAR MOMENTUM VALUE SELECTING THE POTENTIAL
C                  TO BE CALCULATED (L = 0,1,2,...).
C                  L = -1 DENOTES THE  L O C A L  POTENTIAL PART.
C     G2 ......... SQUARED LENGTH OF THE WAVEVECTOR IN ATOMIC UNITS
C                  G2=0 IS FORBIDDEN
C
C     OUTPUT DATA:
C     V .......... POTENTIAL IN RYDBERGS.
C     VP ......... G**2 TIMES D( V(G**2) ) / D( G**2 )
C                  THE POTENTIAL IS NOT NORMALIZED TO THE VOLUME.
C     RHOG ....... APPROXIMATE PSEUDO-ATOM CHARGE DENSITY.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      PARAMETER (NGAUMX=6 , NLMAX=4)
      DOUBLE PRECISION C(NLMAX,NGAUMX),ALPHA(NLMAX,NGAUMX)
      INTEGER NGAUS(NLMAX)
      SAVE ITYOLD, Z, ALPHA0, NGAUS, C, ALPHA
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
      IF (INIT .EQ. 0) GOTO 130
C
C     INITIALIZATION
C
      ITYOLD = ITYPE
C     EXTRACTION OF THE PARAMETERS FOR THE LOCAL POTENTIAL
      Z      = NINT(POTPAR(ITYPE,1))
      ALPHA0 =      POTPAR(ITYPE,2)
      LMAX   = NINT(POTPAR(ITYPE,3))
C     WRITE(IOUT,*) 'POT16 - Z,ALPHA0,LMAX = ',Z,ALPHA0,LMAX
      ILMAX  = LMAX + 2
      IF (ILMAX .GT. NLMAX) GOTO 240
      IPARAM = 3
      DO 140 IL = 1,ILMAX
        IF (IPARAM .GE. NPARAM) GOTO 220
        IPARAM = IPARAM + 1
        NGAUS(IL) = NINT(POTPAR(ITYPE,IPARAM))
        NG     = NGAUS(IL)
        IF (NG .LT.0 .OR. NG .GT. NGAUMX) GOTO 200
        IF (NG .EQ. 0) GOTO 140
C       WRITE(IOUT,*) 'FOR L =',(IL-2),' THERE ARE ',NG,' GAUSSIANS'
        DO 100 I = 1,NG
          IPARAM  = IPARAM + 1
          C(IL,I) = DBLE(POTPAR(ITYPE,IPARAM))
          IPARAM  = IPARAM + 1
          ALPHA(IL,I) = DBLE(POTPAR(ITYPE,IPARAM))
C         WRITE(IOUT,*) 'CI = ',C(IL,I),' ALPHA-I = ',ALPHA(IL,I)
100       CONTINUE
140     CONTINUE
C
C     CALCULATION OF V
C
130   V    = 0.0D0
      VP   = 0.0D0
      RHOG = 0.0D0
      IF (ITYPE .NE. ITYOLD) GOTO 300
      IF (G2 .LT. 1.0E-10) GOTO 260
C
C     THE LOCAL POTENTIAL
C
      DARG   = G2/(4.0D0*ALPHA0)
      EXPFAC = DEXP( - DARG)
C     THE VALENCE CHARGE DENSITY (APPROXIMATE FORM)
C     (DOES NOT WORK WELL)
C     RHOG   = Z * EXPFAC
C     THE CORE PART OF THE POTENTIAL
      IF (L .LT. 0) THEN
        V    = - 4.0D0*PI*Z/G2 * EXPFAC
        VP   = - V*(1.0D0 + DARG)
        ENDIF
C
      IL = L + 2
      NG = NGAUS(IL)
      IF (NG .EQ. 0) GOTO 120
      DO 110 I=1,NG
        DTEMP = PI/ALPHA(IL,I)
        DTEMP = DTEMP*DSQRT(DTEMP)
        DARG  = G2/(4.0D0*ALPHA(IL,I))
        DTEMP = DTEMP * DEXP( - DARG)
        V     = V  + C(IL,I) * DTEMP
        DTEMP = - DTEMP*DARG
        VP    = VP + C(IL,I) * DTEMP
110     CONTINUE
C
C     CONVERSION TO UNITS RYDBERGS
C
120   V  = V  * 2.0D0
      VP = VP * 2.0D0
C
      IF (ABS(V)  .LT. 1.0E-10) V  = 0.0D0
      IF (ABS(VP) .LT. 1.0E-10) VP = 0.0D0
C     WRITE(IOUT,*) 'G2 = ',G2,' V = ',V
C
C     CHARGE DENSITY RHO(G): USE - G2*V/8*PI, CUT OFF BY EXP.
C
      RHOG = - G2 * V / (8.0D0 * PI) * EXP (- G2 / 4.0D0)
      RETURN
C-----------------------------------------------------------------------
C     ERROR MESSAGES
C
200   WRITE(IOUT,210)
210   FORMAT(' SUBROUTINE POT16 *** FATAL ERROR ***')
      WRITE(IOUT,215) NGAUS(IL),NGAUMX
215   FORMAT(I5,' Gaussians, but dimension is only ',I5)
      CALL EXIT
C
220   WRITE(IOUT,210)
      WRITE(IOUT,230) IPARAM,NPARAM
230   FORMAT(' in establishing potential parameters, IPARAM = ',I5,
     +' but NPARAM = ',I5)
      CALL EXIT
C
240   WRITE(IOUT,210)
      WRITE(IOUT,250) LMAX, NLMAX-2
250   FORMAT(' LMAX = ',I5,' but dimensions accomodate only ',I5)
      CALL EXIT
C
260   WRITE(IOUT,210)
      WRITE(IOUT,270) G2
270   FORMAT(' G2 = ',G15.8,' IS ILLEGAL')
      CALL EXIT
C
      WRITE(IOUT,210)
      WRITE(IOUT,290) L,LMAX
290   FORMAT(' L = ',I5,' IS ILLEGAL WHEN LMAX = ',I5)
      CALL EXIT
C
300   WRITE(IOUT,210)
      WRITE(IOUT,310) ITYPE,ITYOLD
310   FORMAT(' Call with ITYPE = ',I3,', but initialized with ITYPE=',
     +I3)
      CALL EXIT
C
      RETURN
      END
      SUBROUTINE POT17 (POTPAR,NTYPMX,NPARAM,ITYPE,NSPIN,
     +                  INIT,L,G2,VG,VGP,RHOG)
C
C                                   WRITTEN FEBRUARY 22, 1983 (O.H.N.)
C     FOURIER TRANSFORM OF THE BELL LABS 1982 NON-LOCAL POTENTIAL
C     (BACHELET ET AL. PHYS.REV.B 26,4199(1982))
C
C     INPUT DATA (UNITS A.U. AS IN BACHELET ET AL.)
C     POTPAR ..... PARAMETER ARRAY
C     NTYPMX ..... MAX NO. OF ATOM TYPES
C     NPARAM ..... MAX NO OF PARAMETERS
C     ITYPE ...... THE ATOM TYPE CONSIDERED IN THIS CALL
C     INIT ....... 1 MEANS INITIALIZE ARRAYS
C                  0 MEANS GO ON FOR THIS ITYPE WITH DIFFERENT G2
C     L .......... ANGULAR MOMENTUM VALUE.
C                  (L = -1 DENOTES THE  L O C A L  POTENTIAL PART).
C     G2 ......... SQUARED LENGTH OF THE WAVEVECTOR IN ATOMIC UNITS
C                  G2=0 IS FORBIDDEN IN CASE OF LOCAL POTENTIAL
C
C     OUTPUT DATA:
C     VG ......... POTENTIAL IN RYDBERGS.
C     VGP ........ G**2 TIMES D( V(G**2) ) / D( G**2 )
C                  THE POTENTIAL IS NOT NORMALIZED TO THE VOLUME.
C     RHOG ....... APPROXIMATE PSEUDO-ATOM CHARGE DENSITY
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM),
     +                 VG(NSPIN), VGP(NSPIN), RHOG(NSPIN)
      SAVE ITYOLD, IMSG, Z, ALPHA1, ALPHA2, C1, C2, LMAX, LOCAL
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
      DATA IMSG /0/
C
C-----------------------------------------------------------------------
C
      IF (INIT .EQ. 0) GOTO 130
C
C     INITIALIZATION
C
      ITYOLD = ITYPE
C     EXTRACTION OF THE PARAMETERS FOR THE LOCAL POTENTIAL
      Z      = POTPAR(ITYPE,1)
      ALPHA1 = POTPAR(ITYPE,2)
      ALPHA2 = POTPAR(ITYPE,3)
      C1     = POTPAR(ITYPE,4)
      C2     = POTPAR(ITYPE,5)
      LMAX   = NINT(POTPAR(ITYPE,6))
C     THE ANGULAR MOMENTUM DESCRIBING THE LOCAL POTENTIAL
      LOCAL  = NINT(POTPAR(ITYPE,16 + 9*LMAX))
C
C     CALCULATION OF V
C
130   VG(1)   = 0.0D0
      VGP(1)  = 0.0D0
      RHOG(1) = 0.0D0
      IF (NSPIN .EQ. 2) THEN
        VG(2)   = 0.0D0
        VGP(2)  = 0.0D0
        RHOG(2) = 0.0D0
        ENDIF
      IF (L .LT. -1 .OR. L .GT. LMAX) GOTO 320
      IF (ITYPE .NE. ITYOLD) GOTO 300
      IF (G2 .LT. 0.0) GOTO 340
      IF (L .GE. 0) GOTO 140
C
C     THE LOCAL PART OF THE POTENTIAL:
C
      IF (G2 .LT. 1.0E-10) GOTO 340
      DARG = G2/(4.0D0*ALPHA1)
      EXPFAC = DEXP( - DARG)
      V1   = - 4.0D0*PI*Z/G2 * EXPFAC
      V1P  = - V1 * (1.0D0 + DARG)
C     RO1  = EXPFAC
      DARG = G2/(4.0D0*ALPHA2)
      EXPFAC = DEXP( - DARG)
      V2   = - 4.0D0*PI*Z/G2 * EXPFAC
      V2P  = - V2 * (1.0D0 + DARG)
C     RO2  = EXPFAC
      VG(1)  = C1 * V1  + C2 * V2
      VGP(1) = C1 * V1P + C2 * V2P
C     THE CHARGE DENSITY (DOES NOT WORK WELL)
C     RHOG(1) = Z * (C1 * RO1 + C2 * RO2)
C
C     THE CORRECTION FROM L=LOCAL:
C
      IF (LOCAL .LT. 0) GOTO 120
      IPARAM = 6 + 9*LOCAL
      DO 155 I = 1, 3
        ALPHAI = POTPAR(ITYPE,IPARAM+I)
        DTEMP  = PI/ALPHAI
        DTEMP  = DTEMP*DSQRT(DTEMP)
        DARG   = G2/(4.0D0*ALPHAI)
        DTEMP  = DTEMP * DEXP( - DARG)
        AI     = POTPAR(ITYPE,IPARAM + 3 + I)
        AIP    = - AI*DARG
        VG(1)  = VG(1)  + AI  * DTEMP
        VGP(1) = VGP(1) + AIP * DTEMP
        DFAC   = 1.5D0 - DARG
        DFACP  = - DARG*(DFAC + 1.0D0)
        AI3    = POTPAR(ITYPE,IPARAM + 6 + I)
        VG(1)  =  VG(1)  + AI3 * DTEMP / ALPHAI * DFAC
        VGP(1) =  VGP(1) + AI3 * DTEMP / ALPHAI * DFACP
155     CONTINUE
      GOTO 120
C
C     THE NONLOCAL CORRECTION POTENTIAL:
C
C     STRESS TERM IS IRRELEVANT !
C
140   IPARAM = 6 + 9*L
      DO 150 I = 1, 6
        FAC = 1.0D0
C
C       SUBTRACTING THE L=LOCAL CORRECTION POTENTIAL
C
        IF (I .GT. 3) THEN
          IF (LOCAL .LT. 0) GOTO 120
          IPARAM = 6 + 9*LOCAL - 3
          FAC    = - 1.0D0
          ENDIF
C
        ALPHAI = POTPAR(ITYPE,IPARAM+I)
        DTEMP  = PI/ALPHAI
        DTEMP  = DTEMP*DSQRT(DTEMP)
        DARG   = G2/(4.0D0*ALPHAI)
        DTEMP  = DTEMP * DEXP( - DARG)
        AI     = FAC*POTPAR(ITYPE,IPARAM + 3 + I)
        VG(1)  = VG(1) + AI * DTEMP
        DTEMP  = DTEMP/ALPHAI*(1.5D0 - DARG)
        AI3    = FAC*POTPAR(ITYPE,IPARAM + 6 + I)
        VG(1)  = VG(1) + AI3 * DTEMP
150     CONTINUE
C
C     SPIN-ORBIT POTENTIAL
C
120   IPARAM = 16 + 9*LMAX + 1
170   LSO = NINT(POTPAR(ITYPE,IPARAM))
      IF (LSO .GE. 0 .AND. NSPIN .EQ. 1) THEN
C       DON'T CREATE SPIN-ORBIT POTENTIALS
        IF (IMSG .EQ. 0) WRITE (IOUT,*)
     +    'POT17 *** NSPIN=1: spin-orbit will be neglected'
        IMSG = 1
        GOTO 200
        ENDIF
C
      IF (LSO .LT. 0) THEN
        GOTO 200
      ELSE IF (LSO .EQ. L) THEN
        VG(2)  = 0.0D0
        VGP(2) = 0.0D0
CRAY bug (UNICOS 3.0) requires the following patch:
CDIR$   NOVECTOR
        DO 160 I = 1, 3
          ALPHAI = POTPAR(ITYPE,IPARAM+I)
          DTEMP  = PI/ALPHAI
          DTEMP  = DTEMP*DSQRT(DTEMP)
          DARG   = G2/(4.0D0*ALPHAI)
          DTEMP  = DTEMP * DEXP( - DARG)
          AI     = POTPAR(ITYPE,IPARAM + 3 + I)
          AIP    = - AI*DARG
          VG(2)  = VG(2)  + AI  * DTEMP
          VGP(2) = VGP(2) + AIP * DTEMP
          DFAC   = 1.5D0 - DARG
          DFACP  = - DARG*(DFAC + 1.0D0)
          AI3    = POTPAR(ITYPE,IPARAM + 6 + I)
          VG(2)  = VG(2)  + AI3 * DTEMP / ALPHAI * DFAC
          VGP(2) = VGP(2) + AI3 * DTEMP / ALPHAI * DFACP
160       CONTINUE
        ENDIF
      IPARAM = IPARAM + 9
      GOTO 170
C
C     CONVERSION TO UNITS RYDBERGS
C
200   DO 210 ISPIN = 1, NSPIN
        VG(ISPIN)  = VG(ISPIN)  * 2.0D0
        VGP(ISPIN) = VGP(ISPIN) * 2.0D0
        IF (ABS(VG(ISPIN))  .LT. 1.0E-10) VG(ISPIN)  = 0.0D0
        IF (ABS(VGP(ISPIN)) .LT. 1.0E-10) VGP(ISPIN) = 0.0D0
C
C       CHARGE DENSITY RHO(G): USE - G2*VG/8*PI
C
        RHOG(ISPIN) = - G2 * VG(ISPIN) / (8.0D0 * PI)
210     CONTINUE
C
      RETURN
C-----------------------------------------------------------------------
C
C     ERROR MESSAGES
C
340   WRITE (IOUT,400)
400   FORMAT(' Subroutine POT17 *** FATAL ERROR ***')
      WRITE (IOUT,350) G2
350   FORMAT(' G2 = ',G15.8,' is illegal')
      CALL EXIT
C
300   WRITE(IOUT,400)
      WRITE(IOUT,310) ITYPE,ITYOLD
310   FORMAT(' Call with ITYPE = ',I3,', but initialized with ITYPE=',
     +I3)
      CALL EXIT
C
320   WRITE(IOUT,400)
      WRITE(IOUT,*) 'Called POT17 with L = ',L
      CALL EXIT
C
      RETURN
      END
      SUBROUTINE POT20 (POTPAR,POTFIL,NTYPMX,NPARAM,ITYPE,NSPIN,
     +                  VLOCAL,RHOVAL,WORK,NQMAX,INIT,L,G2,VG,VGP,RHOG)
C                                          WRITTEN MAY 22, 1984 (O.H.N.)
C     READING FILE WITH THE FOURIER TRANSFORMED POTENTIALS,
C     AND EXTRACTING THE LOCAL PART.
C
C     INPUT DATA:
C     POTPAR ..... PARAMETER ARRAY
C     POTFIL ..... FILENAME OF ATOMIC FOURIER TRANSFORM FILE
C     NTYPMX ..... MAX NO. OF ATOM TYPES
C     NPARAM ..... MAX NO OF PARAMETERS
C     ITYPE ...... THE ATOM TYPE CONSIDERED IN THIS CALL
C     INIT ....... 1 MEANS INITIALIZE ARRAYS
C                  0 MEANS GO ON FOR THIS ITYPE WITH DIFFERENT G2
C     L .......... ANGULAR MOMENTUM VALUE.
C                  (L = -1 DENOTES THE  L O C A L  POTENTIAL PART).
C     G2 ......... SQUARED LENGTH OF THE WAVEVECTOR IN ATOMIC UNITS
C                  G2=0 IS FORBIDDEN.
C
C     OUTPUT DATA:
C     VG ......... POTENTIAL IN RYDBERGS.
C     VGP ........ G**2 TIMES D( VG(G**2) ) / D( G**2 )
C                  THE POTENTIAL IS NOT NORMALIZED TO THE VOLUME.
C     RHOG ....... APPROXIMATE PSEUDO-ATOM CHARGE DENSITY
C
C     WORKSPACE:
C     VLOCAL ..... LOCAL POTENTIAL (0:NQMAX,NSPIN)
C     RHOVAL ..... VALENCE DENSITY (0:NQMAX,NSPIN)
C     WORK ....... WORKSPACE (0:NQMAX)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM),
     +                 VG(NSPIN), VGP(NSPIN), RHOG(NSPIN)
      CHARACTER*80 POTFIL(NTYPMX)
C
      DIMENSION VLOCAL(0:NQMAX,NSPIN), RHOVAL(0:NQMAX,NSPIN),
     +          WORK(0:NQMAX)
      PARAMETER (MAXTIT=20)
      CHARACTER*40 TITLE(MAXTIT)
      CHARACTER NAME*2, ICORR*2, IREL*3, IFCORE*4, ICALC*2, CDTYPE*2
C     Apollo RECL:
      PARAMETER (NQNLMX=81)
      LOGICAL LVALEN,LOPEN
      SAVE ITYOLD, LVALEN, LSPIN, COUL, IMSG
      DIMENSION R(1000)
      DATA NR /1000/
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C.....Machine type
      COMMON /MACH1/ MACTYP
      DATA IMSG /0/
C
C-----------------------------------------------------------------------
C
      IF (INIT .EQ. 0) GOTO 100
C
C     INITIALIZATION
C
      ITYOLD = ITYPE
      LVALEN = .FALSE.
      LSPIN = NINT( POTPAR(ITYPE,11) )
      IF (LSPIN .LT. 1 .OR. LSPIN .GT. 2) THEN
        WRITE (IOUT,*) 'POT20: illegal LSPIN =',LSPIN
        CALL EXIT
        ENDIF
C
C     READ LOCAL POTENTIAL FROM FILE
C
C     THE VLOCAL(*,1-2) CONTAINS THE LOCAL (UP-DOWN) PSEUDO POTENTIAL,
C     MINUS THE COULOMBIC TERM (SEE ROUTINE 'PSTRAN')
C
C     INQUIRE IF THE FILE IS ALREADY OPENED
C
      IUNIT = NINT( POTPAR(ITYPE,2) )
      INQUIRE  (UNIT = IUNIT, OPENED = LOPEN)
      IF (LOPEN) THEN
        REWIND(UNIT = IUNIT)
      ELSE
C	Other machines don't like Apollo specials
C       IF (MACTYP .EQ. 11) THEN
C         Apollo: Have to specify RECL (Damned non-ANSI compiler !)
C         write (iout,*) 'POT20: open unit', IUNIT, ' file=',
C    +      potfil(itype)
C         OPEN  (UNIT = IUNIT, FILE = POTFIL(ITYPE), STATUS = 'OLD',
C    +      FORM = 'UNFORMATTED', RECL=4*NQNLMX**2)
C       ELSE
          OPEN  (UNIT = IUNIT, FILE = POTFIL(ITYPE), STATUS = 'OLD',
     +      FORM = 'UNFORMATTED')
C         ENDIF
        REWIND(UNIT = IUNIT)
        ENDIF
C
      NTITLE = MAXTIT
C
110   CALL ATOMRD
     +  (IUNIT,IRECTP,NAME,ICORR,IREL,IFCORE,ZION,NTITLE,TITLE,
     +   NR,A,B,R,NQL,DELQL,NQNL,DELQNL,NUMNL,
     +   ICALC,CDTYPE,NO,LO,MODE,  WORK(1))
C
      IF (IRECTP .LE. 0) THEN
        CLOSE (UNIT = IUNIT)
        GOTO 125
      ELSE IF (IRECTP .EQ. 20) THEN
C       FIRST RECORD - DO NOTHING
      ELSE IF (IRECTP .EQ. 23) THEN
        IF (NQL .GT. NQMAX .OR. NQL .LE. 0) GOTO 200
C
      ELSE IF (IRECTP .EQ. 31) THEN
C       LOCAL PSEUDOPOTENTIAL
        IF (CDTYPE .EQ. '  ') THEN
          ISPIN = 1
        ELSE IF (CDTYPE .EQ. 'UP' .OR. CDTYPE .EQ. 'up') THEN
          ISPIN = 1
        ELSE IF (CDTYPE .EQ. 'DN' .OR. CDTYPE .EQ. 'dn') THEN
          ISPIN = 2
        ELSE
          WRITE (IOUT,121) CDTYPE, IRECTP
121       FORMAT ('0POT20 *** illegal CDTYPE=',A,' IRECTP=',I6)
          CALL EXIT
          ENDIF
        IF (NQL .GT. NQMAX .OR. NQL .LE. 0) GOTO 200
        DO 122 I = 1, NQL
          VLOCAL(I,ISPIN) = WORK(I)
122       CONTINUE
C       FOR INTERPOLATION PURPOSES:
        VLOCAL(0,ISPIN) = VLOCAL(2,ISPIN)
C
      ELSE IF (IRECTP .EQ. 32) THEN
C       ATOMIC VALENCE CHARGE DENSITY
        LVALEN = .TRUE.
        IF (CDTYPE .EQ. '  ') THEN
          ISPIN = 1
        ELSE IF (CDTYPE .EQ. 'UP' .OR. CDTYPE .EQ. 'up') THEN
          ISPIN = 1
        ELSE IF (CDTYPE .EQ. 'DN' .OR. CDTYPE .EQ. 'dn') THEN
          ISPIN = 2
        ELSE
          WRITE (IOUT,121) IRECTP,CDTYPE
          CALL EXIT
          ENDIF
        IF (NQL .GT. NQMAX .OR. NQL .LE. 0) GOTO 200
        DO 120 I = 1, NQL
          RHOVAL(I,ISPIN) = WORK(I)
120       CONTINUE
C       FOR INTERPOLATION PURPOSES:
        RHOVAL(0,ISPIN) = RHOVAL(2,ISPIN)
C
      ELSE IF (IRECTP .EQ. 36) THEN
C       SKIP NONLOCAL POTENTIALS BY A 'DUMMY READ'
        READ (IUNIT)
C
      ELSE
C
        WRITE (IOUT,*) 'POT20: illegal IRECTP =',IRECTP
        CALL EXIT
        ENDIF
C
C     DO ANOTHER READING FROM FILE:
      GOTO 110
C
C     EXTRACTION OF THE ALPHA: AVERAGE V-PS MINUS COULOMB PART
C
125   IF (LSPIN .EQ. 1) THEN
        POTPAR(ITYPE,5)  = VLOCAL(1,1)
        POTPAR(ITYPE,12) = VLOCAL(1,1)
        POTPAR(ITYPE,13) = VLOCAL(1,1)
      ELSE
        POTPAR(ITYPE,5) = ( VLOCAL(1,1) + VLOCAL(1,2) ) / 2.0
C       ALPHA SPIN-UP
        POTPAR(ITYPE,12) = VLOCAL(1,1)
C       ALPHA SPIN-DOWN
        POTPAR(ITYPE,13) = VLOCAL(1,2)
        WRITE (IOUT,*) 'The potential from file is spin-polarized'
        ENDIF
C
C     THE COULOMB PART (EXCEPT THE FACTOR 1/G2) IN UNITS OF RYDBERG:
C
      COUL = - 8.0D0 * PI * ZION
C
      DO 90 ISPIN = 1, LSPIN
        WRITE (IUNIT8,92)
92      FORMAT ('     Q     V-local(Q) values (steps of 10*DELQL) are:')
        DO 90 I = 1, NQL, 50
          WRITE (IUNIT8,95) FLOAT(I - 1)*DELQL,
     +                      (VLOCAL(I + J,ISPIN), J = 0, 40, 10)
95        FORMAT (1X,F10.3,5F13.5)
90        CONTINUE
C
C     CALCULATION OF VG
C
100   IF (ITYPE .NE. ITYOLD) GOTO 340
      IF (L .NE. -1) GOTO 320
      IF (G2 .LT. 0.0) GOTO 260
      G = SQRT(G2)
C
C     THE LOCAL PART OF THE POTENTIAL:
C     POTENTIALS ARE ASSUMED TO BE IN UNITS RYDBERGS
C
      IF (G2 .LT. 1.0E-10) GOTO 260
C     EXTRACTION OF THE PARAMETERS
      NQL   = NINT( POTPAR(ITYPE,6) )
      DELQL =       POTPAR(ITYPE,7)
C
C     LOCATION IN THE LINEAR ARRAY OF G-VECTORS
C
      NG2 = NINT( G / DELQL ) + 1
      NG2 = MAX(1, NG2)
      IF (NG2 + 1 .GE. NQL) THEN
C       RETURN ZERO BEYOND RANGE
        DO 180 ISPIN = 1, NSPIN
          VG(ISPIN)   = 0.0D0
          VGP(ISPIN)  = 0.0D0
          RHOG(ISPIN) = 0.0D0
180       CONTINUE
        GOTO 195
        ENDIF
C
      X1  = (NG2 - 1) * DELQL
      X0  = X1 - DELQL
      X2  = X1 + DELQL
      IF (LSPIN .EQ. 2 .AND. NSPIN .EQ. 1 .AND. IMSG .EQ. 0) THEN
C       DON'T CREATE SPIN-POLARIZED POTENTIALS
        WRITE (IOUT,*)
     +    'POT20 *** NSPIN=1 but potential is spinpolarized'
        IMSG = 1
        ENDIF
C
C     LOOP OVER SPIN POLARIZATION INDEX
C
      DO 190 ISPIN = 1, LSPIN
C
      VG(ISPIN)   = 0.0D0
      VGP(ISPIN)  = 0.0D0
      RHOG(ISPIN) = 0.0D0
C
      F1  = VLOCAL(NG2,    ISPIN)
      F0  = VLOCAL(NG2 - 1,ISPIN)
      F2  = VLOCAL(NG2 + 1,ISPIN)
C     MAKE DIVIDED DIFFERENCES
      F01 = (F1 - F0)    / (X1 - X0)
      F12 = (F2 - F1)    / (X2 - X1)
      F012 = (F12 - F01) / (X2 - X0)
C     THE QUADRATIC POLYNOMIAL IS AX**2 + BX + C
      A   = F012
      B   = F01 - (X0 + X1)*F012
      C   = F0 - F01*X0 + F012*X0*X1
C
C     THE POTENTIAL VG(G)
C
      VG(ISPIN)  = A * G2 +       B * G + C + COUL / G2
C
C     THE DERIVATIVE OF VG(G) WITH RESPECT TO G**2, TIMES G**2
C
      VGP(ISPIN) = A * G2 + 0.5 * B * G     - COUL / G2
C
C     THE ATOMIC VALENCE CHARGE DENSITY
C
      IF (LVALEN) THEN
C
      F0  = RHOVAL(NG2 - 1,ISPIN)
      F1  = RHOVAL(NG2,    ISPIN)
      F2  = RHOVAL(NG2 + 1,ISPIN)
C     MAKE DIVIDED DIFFERENCES
      F01 = (F1 - F0)    / (X1 - X0)
      F12 = (F2 - F1)    / (X2 - X1)
      F012 = (F12 - F01) / (X2 - X0)
      A   = F012
      B   = F01 - (X0 + X1)*F012
      C   = F0 - F01*X0 + F012*X0*X1
      RHOG(ISPIN) = A * G2 + B * G + C
C
      ENDIF
C
      IF (ABS(VG(ISPIN))  .LT. 1.0E-10) VG(ISPIN)  = 0.0D0
      IF (ABS(VGP(ISPIN)) .LT. 1.0E-10) VGP(ISPIN) = 0.0D0
C
190   CONTINUE
C
195   IF (LSPIN .EQ. 1 .AND. NSPIN .EQ. 2) THEN
C       COPY UNPOLARIZED POTENTIALS FOR SPIN-POLARIZED CALCULATION
        VG(2)   = VG(1)
        VGP(2)  = VGP(1)
        RHOG(2) = RHOG(1)
        ENDIF
C
      RETURN
C-----------------------------------------------------------------------
C
C     ERROR MESSAGES
C
200   WRITE (IOUT,210)
210   FORMAT(' Subroutine POT20 *** FATAL ERROR ***')
      WRITE (IOUT,*) 'Dimensions insufficient:',NQMAX,NQL
      CALL EXIT
C
260   WRITE(IOUT,210)
      WRITE(IOUT,270) G2
270   FORMAT(' G2 = ',G15.8,' is illegal')
      CALL EXIT
C
320   WRITE(IOUT,210)
      WRITE(IOUT,*) 'Called POT20 with L = ',L
      CALL EXIT
C
340   WRITE(IOUT,210)
      WRITE(IOUT,350) ITYPE,ITYOLD
350   FORMAT('0POT20: Called with ITYPE =',I5,
     +  ' but initialized with ',I5)
      CALL EXIT
C
      RETURN
      END
      SUBROUTINE POT7 (POTPAR,NTYPMX,NPARAM,ITYPE,VOLUM,ULA,INIT,L,
     +                 RR,V,RHO)
C
C     BELL LABS 1982 NON-LOCAL POTENTIAL IN REAL SPACE
C     (BACHELET ET AL. PHYS.REV.B 26,4199(1982))
C
C     INPUT DATA (UNITS A.U. AS IN BACHELET ET AL.)
C     POTPAR ..... PARAMETER ARRAY
C     NTYPMX ..... MAX NO. OF ATOM TYPES
C     NPARAM ..... MAX NO OF PARAMETERS
C     ITYPE ...... THE ATOM TYPE CONSIDERED IN THIS CALL
C     VOLUM ...... VOLUME OF THE ELEMENTARY UNIT CELL SPANNED BY THE
C                  VECTORS A1,A2,A3. UNITS: ULA**3
C     ULA ........ LATTICE CONSTANT IN ANGSTROMS
C     INIT ....... NOT USED
C     L .......... ANGULAR MOMENTUM VALUE.
C                  (LOCAL POTENTIAL CALCULATED FOR L<0 )
C     RR ......... RADIUS IN A.U.
C
C     OUTPUT DATA:
C     V .......... POTENTIAL IN RYDBERGS.
C     RHO ........ APPROXIMATE CHARGE DENSITY
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      EXTERNAL DERFC
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      REAL VOLUM,ULA,V,RR
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
      IF (RR .LT. 0.0) GOTO 260
      LMAX   = NINT(POTPAR(ITYPE,6))
      LOCAL  = NINT(POTPAR(ITYPE,16 + 9*LMAX))
C
C     THE LOCAL PART OF THE POTENTIAL
C
      DV = 0.0D0
      IF (L .GT. LMAX) GOTO 120
      DR = DBLE(RR)
      IF (DR .LE. 0.0) DR = 1.0E-10
      XX = SQRT(POTPAR(ITYPE,2))*DR
      DV = POTPAR(ITYPE,4) * (1.0D0 - DERFC(XX))
      XX = SQRT(POTPAR(ITYPE,3))*DR
      DV = DV + POTPAR(ITYPE,5) * (1.0D0 - DERFC(XX))
C     THE APPROXIMATE CHARGE DENSITY:
      RHO =  DV * POTPAR(ITYPE,1)
C     THE 'CORE' POTENTIAL:
      DV = - DV * POTPAR(ITYPE,1)/DR
C
      IF (L .LT. 0) THEN
        I0 = 6 + 9*LOCAL
      ELSE
        I0 = 6 + 9*L
        ENDIF
C
      DO 300 I = 1,3
        ARG =  - POTPAR(ITYPE,I0+I) * DR**2
        IF (ABS(ARG) .GT. 70.0) GOTO 300
        DV = DV + (POTPAR(ITYPE,I0+3+I) + POTPAR(ITYPE,I0+6+I) * DR**2)*
     +            EXP (ARG)
300     CONTINUE
C
C     2.0 TO CONVERT HARTREES TO RYDBERGS
C
120   V = DV * 2.0D0
      RETURN
C-----------------------------------------------------------------------
C
C     ERROR MESSAGES
C
260   WRITE(IOUT,210)
210   FORMAT(' SUBROUTINE POT7 *** ERROR ***')
      WRITE(IOUT,270) RR
270   FORMAT(' RR = ',G15.8,' IS ILLEGAL')
      V = 0.0
      RETURN
      END
      SUBROUTINE POT6 (POTPAR,NTYPMX,NPARAM,ITYPE,VOLUM,ULA,INIT,L,
     +                 RR,V,RHO)
C
C     FOURIER TRANSFORM OF THE HAMANN-SCHLUTER-CHIANG NON-LOCAL
C     POTENTIAL (PHYS.REV.LETT 43,1494(1979) AND
C     BACHELET ET AL. PHYS.REV.B 24,4745(1981))
C
C     INPUT DATA (UNITS A.U. AS IN BACHELET ET AL.)
C     POTPAR ..... PARAMETER ARRAY
C     NTYPMX ..... MAX NO. OF ATOM TYPES
C     NPARAM ..... MAX NO OF PARAMETERS
C     ITYPE ...... THE ATOM TYPE CONSIDERED IN THIS CALL
C     VOLUM ...... VOLUME OF THE ELEMENTARY UNIT CELL SPANNED BY THE
C                  VECTORS A1,A2,A3. UNITS: ULA**3
C     ULA ........ LATTICE CONSTANT IN ANGSTROMS
C     INIT ....... NOT USED
C     L .......... ANGULAR MOMENTUM VALUE.
C                  (LOCAL POTENTIAL CALCULATED FOR L<0 )
C     RR ......... RADIUS IN A.U.
C
C     OUTPUT DATA:
C     V .......... POTENTIAL IN RYDBERGS.
C     RHO ........ APPROXIMATE VALENCE CHARGE DENSITY
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      EXTERNAL DERFC
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      REAL VOLUM,ULA,V,RR
      PARAMETER (NGAUMX=6 , NLMAX=4)
      DIMENSION C(NLMAX,NGAUMX),ALPHA(NLMAX,NGAUMX)
      INTEGER NGAUS(NLMAX)
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
      IF (RR .LT. 0.0) GOTO 260
C
C     EXTRACTION OF THE PARAMETERS
C
      Z      = NINT(POTPAR(ITYPE,1))
      ALPHA0 =      POTPAR(ITYPE,2)
      LMAX   = NINT(POTPAR(ITYPE,3))
C     WRITE(IOUT,*) 'POT16 - Z,ALPHA0,LMAX = ',Z,ALPHA0,LMAX
      ILMAX  = LMAX + 2
      IF (ILMAX .GT. NLMAX) GOTO 240
      IPARAM = 3
      DO 140 IL = 1,ILMAX
        IF (IPARAM .GE. NPARAM) GOTO 220
        IPARAM = IPARAM + 1
        NGAUS(IL) = NINT(POTPAR(ITYPE,IPARAM))
        NG     = NGAUS(IL)
        IF (NG .LT.0 .OR. NG .GT. NGAUMX) GOTO 200
        IF (NG .EQ. 0) GOTO 140
C       WRITE(IOUT,*) 'FOR L =',(IL-2),' THERE ARE ',NG,' GAUSSIANS'
        DO 100 I = 1,NG
          IPARAM  = IPARAM + 1
          C(IL,I) = POTPAR(ITYPE,IPARAM)
          IPARAM  = IPARAM + 1
          ALPHA(IL,I) = POTPAR(ITYPE,IPARAM)
C         WRITE(IOUT,*) 'CI = ',C(IL,I),' ALPHA-I = ',ALPHA(IL,I)
100       CONTINUE
140     CONTINUE
C
C     THE LOCAL PART OF THE POTENTIAL
C
      DV = 0.0D0
      IF (L .GT. LMAX) GOTO 120
      DR = DBLE( MAX( RR , 1.0E-10 ) )
      XX = SQRT(ALPHA0)*DR
      DV = (1.0D0 - DERFC(XX))
      RHO =  Z * DV
      DV = - Z * DV / DR
C     THE GAUSSIAN PART:
      IL = 1
      NG = NGAUS(IL)
      DO 310 I = 1,NG
        ARG = - ALPHA(IL,I)*DR**2
        IF (ABS(ARG) .GT. 70.0) GOTO 310
        DV = DV + C(IL,I)*EXP(ARG)
310     CONTINUE
      IF (L .LT. 0 .OR. L .GT. LMAX) GOTO 120
C
      IL = L + 2
      NG = NGAUS(IL)
      IF (NG .EQ. 0) GOTO 120
      DO 320 I = 1,NG
        ARG = - ALPHA(IL,I)*DR**2
        IF (ABS(ARG) .GT. 70.0) GOTO 320
        DV = DV + C(IL,I)*EXP(ARG)
320     CONTINUE
C
C     2.0 TO CONVERT HARTREES TO RYDBERGS
C
120   V = DV * 2.0D0
      RETURN
C-----------------------------------------------------------------------
C     ERROR MESSAGES
C
200   WRITE(IOUT,210)
210   FORMAT(' SUBROUTINE POT6 *** FATAL ERROR ***')
      WRITE(IOUT,215) NGAUS(IL),NGAUMX
215   FORMAT(I5,' GAUSSIANS, BUT DIMENSION IS ONLY ',I5)
      CALL EXIT
C
220   WRITE(IOUT,210)
      WRITE(IOUT,230) IPARAM,NPARAM
230   FORMAT(' IN ESTABLISHING POTENTIAL PARAMETERS, IPARAM = ',I5,
     +' BUT NPARAM = ',I5)
      CALL EXIT
C
240   WRITE(IOUT,210)
      WRITE(IOUT,250) LMAX, NLMAX-2
250   FORMAT(' LMAX = ',I5,' BUT DIMENSIONS ACCOMODATE ONLY ',I5)
      CALL EXIT
C
260   WRITE(IOUT,*) 'SUBROUTINE POT6 *** ERROR ***'
      WRITE(IOUT,270) RR
270   FORMAT(' RR = ',G15.8,' IS ILLEGAL')
      V = 0.0
      RETURN
      END
