      SUBROUTINE POTRED (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +  IRECTP,NAT,NGTOT,MINDIM,NSPIN,
     +  ULA,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +  G2MAX,NG1,NG2,NG3,EPSILO,NTAB,G2TAB,
     +  IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +  IGLIST,VIONIC,VGTOT,ROTOT,RUNPAR,NMIX,HKMIX,XKMIX,FKMIX,CWORK,
     +  NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,
     +  IFILE)
C
C     READ A FILE WITH POTENTIAL
C
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      CHARACTER*80 POTFIL(NTYPMX), TEXT
      INTEGER TY(NDIM9), POTTYP(NTYPMX), NATOM(NDIM9)
      COMPLEX VIONIC(NDIM1,NSPIN), VGTOT(NDIM1,NSPIN),
     +        ROTOT(NDIM1,NSPIN),  CWORK(NDIM1)
      DIMENSION NTAB(NDIM2), G2TAB(NDIM2), IGLIST(3,NDIM1)
      REAL XKAPA(3,NDIM9),A1(3),A2(3),A3(3),B1(3),B2(3),B3(3),
     +  STRAIN(6),RUNPAR(NRUN)
      COMPLEX HKMIX(0:NDIM12,0:NDIM12,NSPIN),
     +  XKMIX(NDIM12,NSPIN), FKMIX(NDIM12,NSPIN)
      LOGICAL LSPLIT
      CHARACTER*2 NAME
C
C     MACHINE TYPE
      COMMON /MACH1/ MACTYP
      COMMON /MACH2/ MACHIN(0:20)
      CHARACTER*7 MACHIN
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
C     THE CALLING PROGRAM SIGNALIZES WHETHER THE FILE IS TO BE READ
C     FROM THE BEGINNING (IRECTP=11).
C
      IF (IRECTP .NE. 11) GOTO 1000
C
C     READING THE HEADING OF FILE
C
      WRITE (IOUT,*) 'POTRED: reading unit ', IFILE
      READ (IFILE) NPRGR,IDAY,MONTH,IYEAR,IVERSN,MACTIP
      IF (MACTIP .GT. 12 .OR. MACTIP .LT. 0) MACTIP = 0
      WRITE (IOUT,120) NPRGR,IVERSN,MACHIN(MACTIP)
120   FORMAT ('0Reading data from file created by program K',I3,
     +' (ver.',I3,') on ',A,' computer')
      IF (MACTIP .NE. MACTYP) THEN
        WRITE(IOUT,*) 'Warning: The computer type is not the same: ',
     +  MACHIN(MACTYP)
        ENDIF
      CALL DAYPRT (IOUT,IYEAR,MONTH,IDAY)
C
      READ (IFILE) TEXT
      WRITE (IOUT,'(1X,A)') TEXT
      READ (IFILE) IRECTP
      IF (IRECTP .NE. 11) THEN
        WRITE (IOUT,*) ' Subroutine POTRED - IRECTP = ',IRECTP
        CALL EXIT
        ENDIF
C
      READ (IFILE) NAT,NGTOT,MINDIM,NPAREM,NTIPMX,NSPEN
C
      IF (NPAREM .NE. NPARAM) THEN
C       ERROR - ARRAY POTPAR HAS WRONG DIMENSIONS
        WRITE(IOUT,151) NPARAM,NPAREM
151     FORMAT(' *** WARNING *** array POTPAR - NPARAM = ',I5,
     +  ' but the input file assumes dimension = ',I5)
        ENDIF
C
      IF (NTIPMX .NE. NTYPMX) THEN
C       ERROR - ARRAY POTPAR HAS WRONG DIMENSIONS
        WRITE(IOUT,152) NTYPMX,NTIPMX
152     FORMAT(' *** WARNING *** array POTPAR - NTYPMX = ',I5/
     +  ' but the input file assumes dimension = ',I5)
        ENDIF
C
      IF (NAT .GT. NDIM9) THEN
C       ERROR - NDIM9 TOO SMALL
        WRITE(IOUT,153) NAT,NDIM9
153     FORMAT(' ***FATAL ERROR*** number of atoms read in = ',I3,
     +  ' but NDIM9 =',I3)
        CALL EXIT
        ENDIF
C
      IF (NGTOT .LE. 0 .OR. NGTOT .GT. NDIM1) THEN
C       ERROR - NDIM1 TOO SMALL
        WRITE  (IOUT,155) NGTOT,NDIM1
155     FORMAT ('*** WARNING *** number of G-vectors on file = ',I6,
     +  ', but NDIM1 = ',I6/' truncation will take place'/1X)
        ENDIF
C
      IF (MINDIM .GT. NDIM2) THEN
C       ERROR - NDIM2 TOO SMALL
        WRITE(IOUT,157) MINDIM,NDIM2
157     FORMAT('*** WARNING *** MINDIM = ',I5,' but NDIM2 = ',I5/
     +          ' truncation will take place'/1X)
        ENDIF
C
      IF (NSPEN .NE. NSPIN) THEN
        WRITE (IOUT,160) NSPIN, NSPEN
160     FORMAT (' POTRED *** WARNING *** NSPIN = ',I5,
     +  '. in the input file it is = ',I5/)
        IF (NSPEN .EQ. 1 .AND. NSPIN .EQ. 2) THEN
          WRITE (IOUT,*) 'Potential will be the non-spinpolarized one'
        ELSE IF (NSPEN .EQ. 2 .AND. NSPIN .EQ. 1) THEN
          WRITE (IOUT,*) 'Potential will be the averaged up/down one'
        ELSE
          WRITE (IOUT,*) 'POTRED *** FATAL ERROR ***'
          CALL EXIT
          ENDIF
        ENDIF
C
C     CRYSTALLOGRAPHIC DATA
C
      READ (IFILE) A1,A2,A3,B1,B2,B3
C
      DO 190 KAPA = 1,NAT
        READ (IFILE) TY(KAPA),(XKAPA(J,KAPA),J=1,3),NATOM(KAPA)
190     CONTINUE
C     DISPLAY OF CRYSTALLOGRAPHIC DATA:
      WRITE (IUNIT7,210) A1,A2,A3
210   FORMAT ('0a1',3F10.5/' a2',3F10.5/' a3',3F10.5)
      WRITE (IUNIT7,220)
220   FORMAT ('0 Kappa  Type',14X,'X(kappa)',T45,'Atom no.    Name')
      DO 230 KAPA = 1,NAT
        CALL ELTNAM (NAME, NATOM(KAPA))
        WRITE(IUNIT7,240)
     +  KAPA,TY(KAPA),(XKAPA(J,KAPA),J=1,3),NATOM(KAPA), NAME
240     FORMAT (1X,2I5,3F10.5,I10,5X,A)
230     CONTINUE
C
C     READ THE STRAIN TENSOR (VOIGT INDICES)
      READ (IFILE) STRAIN
      TOTSTR = 0.0
      DO 242 I = 1,6
        TOTSTR = TOTSTR + ABS(STRAIN(I))
242     CONTINUE
      IF (TOTSTR .GT. 1.0E-10) WRITE (IUNIT7,245) STRAIN
245   FORMAT(' Strain e1-6: ',6F11.6)
C
      READ (IFILE) ULA
      WRITE (IUNIT7,170) ULA, ULA/ABOHR
170   FORMAT (' Unit of length: ULA = ',F14.6,' Angstroms =',
     +        F10.5,' a.u.')
C
      READ (IFILE) G2MAX,NG1,NG2,NG3,EPSILO
C
      DO 280 I = 1, NDIM2
        NTAB(I)  = - 1
        G2TAB(I) = - 1.0
280     CONTINUE
      IOVF = 0
      DO 290 J = 1, MINDIM
        READ (IFILE) NT,G2T
        IF (NT .GT. NDIM1 .OR. NT. LE. 0 .OR. J .GE. NDIM2) THEN
          IOVF = 1
          GOTO 290
          ENDIF
        NGMAX    = NT - 1
        NTAB(J)  = NT
        G2TAB(J) = G2T
290     CONTINUE
      IF (IOVF .NE. 0) THEN
        WRITE  (IOUT,294) NGTOT,NGMAX
294     FORMAT (' NGTOT = ',I6,' truncated = ',I6)
        NGTOT = MIN( NGTOT, NGMAX )
        ENDIF
C
C     MAKE SURE IGLIST AND NTAB ARE COMPATIBLE
C
      DO 316 J = 1, NDIM2
        IF (G2TAB(J) .LT. 0.0) GOTO 318
        NGMAX = NTAB(J) - 1
        IF (NGMAX .GT. NGTOT) THEN
          NGMAX = NTAB(J - 1) - 1
          WRITE (IOUT,314) NGTOT,J,NGMAX
314       FORMAT ('0*** WARNING *** NGTOT=',I6,
     +      ' exceeded by star no.',I6/
     +      ' truncated to NGTOT =',I6/1X)
          NGTOT = NGMAX
          NTAB(J - 1) = - 1
          G2TAB(J)    = - 1.0
          GOTO 318
          ENDIF
316     CONTINUE
C
318   NSTARS = J - 1
      WRITE (IOUT,320) NGTOT,NSTARS,NG1,NG2,NG3
320   FORMAT (1X,I6,' G-vectors in',I5,' stars read in, NG1,2,3 =',3I4)
C
C     INFORMATION ABOUT POTENTIALS
C
C     NUMBER OF ELECTRONS (USED TO DEDUCE NO. OF BANDS)
      READ (IFILE) IEXCOR,EXFACT,NEL
C     POTENTIAL TYPES FOR EACH TYPE OF ATOM:
      READ (IFILE) (POTTYP(I),I = 1, MIN(NTYPMX,NTIPMX))
C     POTENTIAL PARAMETERS:
      DO 295 ITYPE = 1, MIN(NTYPMX,NTIPMX)
        READ (IFILE) (POTPAR(ITYPE,I), I = 1, MIN(NPARAM,NPAREM))
295     CONTINUE
C     CHECK FOR POTENTIAL-TYPE = 20, WHICH REQUIRES STORING FILENAMES
      DO 300 ITYPE = 1, NTYPMX
        IF (POTTYP(ITYPE) .EQ. 20) THEN
          READ (IFILE) POTFIL
          GOTO 310
          ENDIF
300     CONTINUE
C
C     IGLIST AND IONIC POTENTIAL
C
310   READ (IFILE) ((IGLIST(J,I), J = 1, 3), I = 1, NGTOT)
      IF (NSPEN .EQ. NSPIN) THEN
        READ (IFILE) ((VIONIC(I,ISPIN), I = 1, NGTOT), ISPIN = 1, NSPIN)
      ELSE
        LSPLIT = .FALSE.
        CALL POTFIX (IFILE,NSPEN,NSPIN,VIONIC,NDIM1,NGTOT,CWORK,LSPLIT)
        ENDIF
C-----------------------------------------------------------------------
C
C     THE BLOCK FOR READING ADDITIONAL INFORMATION
C
      IRECTP = 12
C
1000  READ (IFILE,END=1100) IRECTP
C
C     WORKING POTENTIAL RECORD
C
      IF (IRECTP .EQ. 12) THEN
        READ (IFILE) NG
        IF (NG .LE. 0 .OR. NG .GT. NDIM1) THEN
C         ERROR - NDIM1 TOO SMALL
          WRITE(IOUT,155) NG,NDIM1
          ENDIF
        WRITE (IUNIT8,1010) 'Potential',IRECTP
1010    FORMAT (' POTRED: reading ',A20,' , IRECTP = ',I3)
        IF (NSPEN .EQ. NSPIN) THEN
          READ (IFILE) ((VGTOT(I,ISPIN), I=1,NGTOT), ISPIN=1,NSPIN)
        ELSE
          LSPLIT = .FALSE.
          CALL POTFIX (IFILE,NSPEN,NSPIN,VGTOT,NDIM1,NGTOT,CWORK,LSPLIT)
          ENDIF
C
C     CHARGE DENSITY RECORD
C
      ELSE IF (IRECTP .EQ. 13) THEN
        READ (IFILE) NG
        IF (NG .LE. 0 .OR. NG .GT. NDIM1) THEN
C         ERROR - NDIM1 TOO SMALL
          WRITE(IOUT,155) NG,NDIM1
          ENDIF
        WRITE (IUNIT8,1010) 'Charge density', IRECTP
        IF (NSPEN .EQ. NSPIN) THEN
          READ (IFILE) ((ROTOT(I,ISPIN), I=1,NGTOT), ISPIN=1,NSPIN)
        ELSE
          LSPLIT = .TRUE.
          CALL POTFIX (IFILE,NSPEN,NSPIN,ROTOT,NDIM1,NGTOT,CWORK,LSPLIT)
          ENDIF
	WRITE (IOUT,*) 'NGTOT, NSPIN, ROTOT(1,1) = ',
     +	  NGTOT, NSPIN, ROTOT(1,1)
C
C     RUNNING PARAMETER RECORD
C
      ELSE IF (IRECTP .EQ. 14) THEN
        WRITE (IUNIT8,1010) 'Run parameters', IRECTP
        READ (IFILE) (RUNPAR(I),I=1,NRUN)
C
C     MIXING MATRIX (SUBR. MIXVG) RECORD
C
      ELSE IF (IRECTP .EQ. 15) THEN
        WRITE (IUNIT8,1010) 'Mix parameters', IRECTP
        IF (NSPEN .EQ. NSPIN) THEN
          READ (IFILE) HKMIX
          READ (IFILE) XKMIX
          READ (IFILE) FKMIX
        ELSE
          LSPLIT = .FALSE.
          MM = NDIM12 + 1
          CALL POTFIX (IFILE,NSPEN,NSPIN,HKMIX,
     +      MM*MM,MM*MM,CWORK,LSPLIT)
          CALL POTFIX (IFILE,NSPEN,NSPIN,XKMIX,
     +      NDIM12,NDIM12,CWORK,LSPLIT)
          CALL POTFIX (IFILE,NSPEN,NSPIN,FKMIX,
     +      NDIM12,NDIM12,CWORK,LSPLIT)
         ENDIF
C
C     ILLEGAL RECORD TYPE
C
      ELSE
        WRITE (IOUT,*) 'IRECTP = ',IRECTP,' is illegal'
        CALL EXIT
        ENDIF
      RETURN
C
1100  WRITE (IOUT,*) 'POTRED - met end-of-file'
      IRECTP = 0
      RETURN
      END
      SUBROUTINE POTFIX (IFILE,NSPEN,NSPIN,CARRAY,N1,N,CWORK,LSPLIT)
C
C     READ POTENTIAL RECORD
C     IN THE CASE OF INCONSISTENT SPIN-POLARIZATION VARIABLE
C
C     IFILE ..... POTENTIAL FILE
C     NSPEN ..... SPIN DIMENSION FROM FILE     
C     NSPIN ..... SPIN DIMENSION IN CURRENT PROGRAM
C     CARRAY .... ARRAY (VIONIC, ROTOT, ...) TO BE FIXED
C     N1 ........ 1ST DIMENSION OF CARRAY
C     N ......... NO. OF G-VECTORS
C     CWORK ..... WORKSPACE
C     LSPLIT .... SWITCH: FALSE IF CARRAY CAN BE AVERAGED/SHARED
C                         TRUE  IF CARRAY = CHARGE DENSITY (WHICH CAN'T)
C
      COMPLEX CARRAY(N1,NSPIN), CWORK(N)
      LOGICAL LSPLIT
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C-----------------------------------------------------------------------
C
      IF (NSPEN .EQ. 1 .AND. NSPIN .EQ. 2) THEN
C
        FACTOR = 1.0
        IF (LSPLIT) FACTOR = 0.5
        READ (IFILE) (CARRAY(I,1), I = 1, N)
C       SHARING BETWEEN SPIN-DOWN AND SPIN-UP
        DO 320 I = 1, N
          CARRAY(I,1) = CARRAY(I,1) * FACTOR
          CARRAY(I,2) = CARRAY(I,1)
320       CONTINUE
C
      ELSE IF (NSPEN .EQ. 2 .AND. NSPIN .EQ. 1) THEN
C
        READ (IFILE) (CARRAY(I,1), I = 1, N),
     +               (CWORK(I),    I = 1, N)
C       TAKE THE AVERAGE OF SPIN-DOWN AND SPIN-UP
        FACTOR = 0.5
        IF (LSPLIT) FACTOR = 1.0
        DO 330 I = 1, N
          CARRAY(I,1) = (CARRAY(I,1) + CWORK(I)) * FACTOR
330       CONTINUE
C
      ELSE
C
        WRITE (IOUT,*) 'POTFIX *** ERROR ***, NSPEN,NSPIN =',
     +    NSPEN, NSPIN
        CALL EXIT
        ENDIF
      RETURN
      END
      SUBROUTINE POTWRI (NPRGR,IVERSN,IDAY,MONTH,IYEAR,TEXT,
     +  IRECTP,NAT,NGTOT,MINDIM,NSPIN,
     +  ULA,A1,A2,A3,B1,B2,B3,STRAIN,TY,XKAPA,NATOM,
     +  G2MAX,NG1,NG2,NG3,EPSILO,NTAB,G2TAB,
     +  IEXCOR,EXFACT,NEL,POTTYP,POTPAR,POTFIL,
     +  IGLIST,VIONIC,VGTOT,ROTOT,RUNPAR,NMIX,HKMIX,XKMIX,FKMIX,CWORK,
     +  NDIM1,NDIM2,NDIM9,NDIM12,NTYPMX,NPARAM,NRUN,
     +  IFILE)
C
C     WRITE A FILE WITH POTENTIAL, CHARGE DENSITY ETC.
C
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      CHARACTER*80 POTFIL(NTYPMX), TEXT
      INTEGER TY(NDIM9), POTTYP(NTYPMX), NATOM(NDIM9)
      COMPLEX VIONIC(NDIM1,NSPIN), VGTOT(NDIM1,NSPIN),
     +        ROTOT(NDIM1,NSPIN)
C     Used to include also, but this is a dummy: COMPLEX CWORK(NDIM1)
      DIMENSION NTAB(NDIM2),G2TAB(NDIM2),IGLIST(3,NDIM1)
      REAL XKAPA(3,NDIM9),A1(3),A2(3),A3(3),B1(3),B2(3),B3(3),
     +     STRAIN(6),RUNPAR(NRUN)
      COMPLEX HKMIX(0:NDIM12,0:NDIM12,NSPIN),
     +        XKMIX(NDIM12,NSPIN), FKMIX(NDIM12,NSPIN)
C
C     MACHINE TYPE
      COMMON /MACH1/ MACTYP
      COMMON /MACH2/ MACHIN(0:20)
      CHARACTER*7 MACHIN
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C
C-----------------------------------------------------------------------
C     THE CALLING PROGRAM SIGNALIZES WHETHER THE FILE IS TO BE READ
C     FROM THE BEGINNING (IRECTP=11).
C
      IF (IRECTP .NE. 11) GOTO 1000
C
C     WRITING THE HEADING OF FILE
C
      WRITE (IOUT,*) 'POTWRI: writing unit ', IFILE
      WRITE (IFILE) NPRGR,IDAY,MONTH,IYEAR,IVERSN,MACTYP
      WRITE (IFILE) TEXT
      WRITE (IFILE) IRECTP
      NPAREM = NPARAM
      NTIPMX = NTYPMX
      NSPEN  = NSPIN
      WRITE (IFILE) NAT,NGTOT,MINDIM,NPAREM,NTIPMX,NSPEN
C
C     CRYSTALLOGRAPHIC DATA
C
      WRITE (IFILE) A1,A2,A3,B1,B2,B3
C
      DO 190 KAPA = 1,NAT
        WRITE (IFILE) TY(KAPA),(XKAPA(J,KAPA),J=1,3),NATOM(KAPA)
190     CONTINUE
C
C     WRITE THE STRAIN TENSOR (VOIGT INDICES)
      WRITE (IFILE) STRAIN
C
      WRITE (IFILE) ULA
C
      WRITE (IFILE) G2MAX,NG1,NG2,NG3,EPSILO
      DO 290 I=1,MINDIM
        WRITE (IFILE) NTAB(I),G2TAB(I)
290     CONTINUE
C
C     INFORMATION ABOUT POTENTIALS
C
C     NUMBER OF ELECTRONS (USED TO DEDUCE NO. OF BANDS)
      WRITE (IFILE) IEXCOR,EXFACT,NEL
C     POTENTIAL TYPES FOR EACH TYPE OF ATOM:
      WRITE (IFILE) POTTYP
C     POTENTIAL PARAMETERS:
      DO 295 ITYPE = 1, NTYPMX
        WRITE (IFILE) (POTPAR(ITYPE,I), I = 1, NPARAM)
295     CONTINUE
C     CHECK FOR POTENTIAL-TYPE = 20, WHICH REQUIRES STORING FILENAMES
      DO 300 ITYPE = 1, NTYPMX
        IF (POTTYP(ITYPE) .EQ. 20) THEN
          WRITE (IFILE) POTFIL
          GOTO 310
          ENDIF
300     CONTINUE
C
C     IGLIST AND IONIC POTENTIAL
C
310   WRITE (IFILE) ((IGLIST(J,I), J = 1, 3), I = 1, NGTOT)
      WRITE (IFILE) ((VIONIC(I,ISPIN), I = 1, NGTOT), ISPIN = 1, NSPIN)
C
      WRITE (IOUT,*) NGTOT,' G-vectors written to file'
      IRECTP = 12
C-----------------------------------------------------------------------
C
C     THE BLOCK FOR WRITING ADDITIONAL INFORMATION
C
1000  WRITE (IFILE) IRECTP
C
C     WORKING POTENTIAL RECORD
C
      IF (IRECTP .EQ. 12) THEN
        WRITE (IUNIT7,1010) 'Potential',IRECTP
1010    FORMAT (' POTWRI: writing ',A20,' , IRECTP = ',I3)
        WRITE (IFILE) NGTOT
        WRITE (IFILE) ((VGTOT(I,ISPIN), I = 1, NGTOT), ISPIN = 1, NSPIN)
C
C     CHARGE DENSITY RECORD
C
      ELSE IF (IRECTP .EQ. 13) THEN
        WRITE (IUNIT7,1010) 'charge density',IRECTP
        WRITE (IFILE) NGTOT
        WRITE (IFILE) ((ROTOT(I,ISPIN), I = 1, NGTOT), ISPIN = 1, NSPIN)
C
C     RUNNING PARAMETER RECORD
C
      ELSE IF (IRECTP .EQ. 14) THEN
        WRITE (IUNIT7,1010) 'running parameters',IRECTP
        WRITE (IFILE) (RUNPAR(I),I=1,NRUN)
C
C     MIXING MATRIX (SUBRT. MIXVG) RECORD
C
      ELSE IF (IRECTP .EQ. 15) THEN
        WRITE (IUNIT7,1010) 'mixing parameters',IRECTP
        WRITE (IFILE) HKMIX
        WRITE (IFILE) XKMIX
        WRITE (IFILE) FKMIX
C
C     ILLEGAL RECORD TYPE
C
      ELSE
        WRITE (IOUT,*) 'IRECTP = ',IRECTP,' is illegal'
        CALL EXIT
        ENDIF
      RETURN
      END
