      SUBROUTINE REALIT (IFILEH,NDIM3,NDIM5,NDIM8,NDIM13,NH,NA,NBDS,
     +CCR,CCI,DIAG,EE1,EE2,CEV,WK,CWFR,CWFI,UBOUND,HRSUB,HISUB,SRSUB,
     +SISUB,VRSUB,VISUB,ALFR,ALFI,BETA,SHIFT,IWK,RES,NITMX,FAC,LREAL)
C
C                      REAL VERSION
C
C     ROUTINE USES NEX'S CASE OF RUHE'S CONVERGENT SPLITTING
C     TO SOLVE FOR THE LOWEST EIGENVALUES OF A HERMITIAN
C     EIGENPROBLEM. FOR DETAILS OF THE METHOD SEE:  C.M.M. NEX
C     'A NEW SPLITTING TO SOLVE A LARGE HERMITIAN EIGENPROBLEM' (1986)
C
C     IFILEH : UNIT NUMBER CONTAINING LOWER TRIANGLE OF HAMILTONIAN
C              STORED IN ROWS IN REVERSE ORDER
C      NDIM3 : MAXIMUM DIMENSION OF A MATRIX
C      NDIM5 : MAXIMUM DIMENSION OF H MATRIX
C      NDIM8 : MAXIMUM NUMBER OF EIGENVALUES OF H MATRIX REQUIRED
C     NDIM13 : MAXIMUM NUMBER OF EIGENVALUES REQUIRED
C         WK : WORKSPACE
C     UBOUND : CONTAINS UPPER BOUNDS TO REQUIRED EIGENVALUES
C      HRSUB : REAL PART OF SUBSPACE HAMILTONIAN MATRIX (H*)
C      HISUB : IMAGINARY PART OF H*
C      SRSUB : REAL PART OF SUBSPACE OVERLAP MATRIX (S*)
C      SISUB : IMAGINARY PART OF S*
C      VRSUB : REAL PART OF EIGENVECTORS (Y) OF H* Y= S* Y LAMBDA
C      VISUB : IMAGINARY PART OF EIGENVECTORS Y
C       ALFR : BETA * REAL PART OF EIGENVALUES LAMBDA
C       ALFI : BETA * IMAGINARY PART OF EIGENVALUES LAMBDA
C       BETA : AS DEFINED ABOVE
C      SHIFT : SHIFTS OF THE EIGENVALUES. THIS ROUTINE WORKS ONLY FOR
C              SHIFTS WHICH ARE PURELY IMAGINARY.
C
C       ON INPUT:
C        EE2 : ESTIMATE OF LOWEST NBDS EIGENVALUES OF H MATRIX
C        CEV : ESTIMATE OF CORRESPONDING EIGENVECTORS (X)
C         NH : DIMENSION OF H MATRIX
C         NA : DIMENSION OF A MATRIX
C       NBDS : NUMBER OF EIGENVALUES OF H MATRIX REQUIRED
C        CCR : REAL PART OF EIGENVECTORS OF A MATRIX
C        CCI : IMAGINARY PART OF EIGENVECTORS OF A MATRIX
C       DIAG : DIAGONAL PART OF H MATRIX
C        EE1 : EIGENVALUES OF A MATRIX
C        RES : ERROR TOLERANCE IN EIGENVALUES
C      NITMX : MAXIMUM NUMBER OF ITERATIONS
C        FAC : CONTROLS SIZE OF SHIFTS
C
C       ON OUTPUT:
C        EE2 : ITERATIVE ESTIMATE OF LOWEST NBDS EIGENVALUES
C              THESE ARE RIGOROUSLY UPPER BOUNDS TO THE LOWEST
C              NBDS EIGENVALUES OF H. THEY ARE NOT ORDERED
C        CEV : ITERATIVE ESTIMATE OF CORRESPONDING EIGENVECTORS
C
C       PARAMETERS:
C        EPS : ACCURACY OF SUBSPACE DIAGONALIZATION. IF EPS IS
C              NEGATIVE THEN THE ACCURACY IS MACHINE PRECISION
C      RDENT : VECTORS WITH OVERLAPS LARGER THAN RDENT ARE IDENTIFIED
C
      REAL CCR(NDIM3,NDIM13),CCI(NDIM3,NDIM13),DIAG(NDIM5)
      REAL EE1(NDIM13),EE2(NDIM8),UBOUND(NDIM8)
      INTEGER IWK(NDIM8)
      LOGICAL LREAL,LMATV
      COMPLEX SHIFT(NDIM8)
      DOUBLE PRECISION HRSUB(NDIM8,NDIM8),HISUB(NDIM8,NDIM8)
      DOUBLE PRECISION SRSUB(NDIM8,NDIM8),SISUB(NDIM8,NDIM8)
      DOUBLE PRECISION VRSUB(NDIM8,NDIM8),VISUB(NDIM8,NDIM8)
      DOUBLE PRECISION ALFR(NDIM8),ALFI(NDIM8),BETA(NDIM8)
      DOUBLE PRECISION EPS,D1,D2,DSDOT
      REAL CEV(NDIM5,NDIM8),WK(NDIM5,NDIM8),CWFR(NDIM5),CWFI(NDIM5)
      PARAMETER (LMATV = .TRUE.)
      PARAMETER (EPS = -1.0D0 , RDENT = 0.5)
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C------------------------------------------------------------------
C
      CALL USAGE (N0,T0)
C
      IF (NITMX .LE. 0) RETURN
      IF (.NOT.LREAL) WRITE(IOUT,*) '***REALIT*** LREAL = ',LREAL
      NAP1 = NA+1
      NB   = NH-NA
C
C     UPPER BOUNDS TO THE EIGENVALUES ARE STORED IN UBOUND
C     CALCULATED ACCORDING TO THE COURANT-FISCHER THEOREM
C     SEE WILKINSON 'THE ALGABRAIC EIGENVALUE PROBLEM'
C
      CALL SCOPY (NBDS,EE1,1,UBOUND,1)
      CALL BOUND (NBDS,NDIM8,EE2,UBOUND,IWK,ALFI,-1)
C
C     MAIN ITERATION LOOP
C
      DO 260 ITS = 1,NITMX
C
        DO 10 L = 1,NBDS
        DO 10 I = 1,NH
          WK(I,L) = 0.0
10        CONTINUE
        DO 20 L = 1,NBDS
        DO 20 M = 1,L
          HRSUB(L,M) = 0.0D0
20        CONTINUE
C
C     SET SHIFTS OF EIGENVALUES
C
        CALL ESHIFT (EE1,SHIFT,FAC,NDIM8,NDIM13,NA,NBDS)
        DO 15 L = 1,NBDS
          IF (ABS(REAL(SHIFT(L))) .GT. 1.0E-6) THEN
            WRITE(IOUT,*) '***REALIT***SHIFT HAS REAL PART'
            CALL EXIT
            ENDIF
15        CONTINUE
C
C     ACCESS HAMILTONIAN IN ROWS FROM BOTTOM UPWARDS
C
        CALL REWFIL (IFILEH)
        DO 60 IROW = NH,NAP1,-1
          NROW = IROW-1
          CALL RDVEC (IFILEH,CWFR,NROW)
C
C     CALCULATE ELEMENTS OF NEW EIGENVECTOR X 2/S+1
C
          DO 30 L = 1,NBDS
            R1 = WK(IROW,L) + SDOT(NROW,CWFR,1,CEV(1,L),1)
            CEV(IROW,L) = R1/(EE2(L)-DIAG(IROW))
30          CONTINUE
C
C     ACCUMULATE ELEMENTS OF H ACTING ON X 2/S+1
C
          DO 40 L = 1,NBDS
            CALL SAXPY(NROW,CEV(IROW,L),CWFR,1,WK(1,L),1)
40          CONTINUE
C
          D1 = DBLE(DIAG(IROW))
          DO 50 L = 1,NBDS
            D2 = DBLE(CEV(IROW,L))
            DO 50 M = 1,L
              HRSUB(L,M) = HRSUB(L,M) + D1*D2*DBLE(CEV(IROW,M))
50            CONTINUE
C
60        CONTINUE
C
        DO 70 L = 1,NBDS
        DO 70 M = 1,L
          HRSUB(L,M) = HRSUB(L,M)+DSDOT(NB,CEV(NAP1,M),1,WK(NAP1,L),1)
     +                           +DSDOT(NB,CEV(NAP1,L),1,WK(NAP1,M),1)
70        CONTINUE
C
C     USE EIGENVECTOR DECOMPOSITION OF A MATRIX TO CALCULATE X 1/S+1
C
        DO 140 M = NBDS,1,-1
C
          DO 80 I = 1,NA
            CWFR(I) = 0.0
            CWFI(I) = 0.0
80          CONTINUE
C
C     PROJECT C X 2/S+1 - X 1/S R 1/S ONTO EIGENVECTORS OF A
C
          R3 = EE2(M)
          R4 = AIMAG(SHIFT(M))
          DO 90 I = 1,NA
            R1 = WK(I,M)
            R2 = R4*CEV(I,M)
            DO 90 J = 1,NA
              CWFR(J) = CWFR(J) + CCR(I,J)*R1
              CWFI(J) = CWFI(J) + CCR(I,J)*R2
90            CONTINUE
C
C     CALCULATE EIGENVECTOR PROJECTIONS OF X 1/S+1
C
          DO 100 I = 1,NA
            R1 = R3 - EE1(I)
            R2 = R1*R1 + R4*R4
            R5 = (CWFR(I)*R1 + CWFI(I)*R4)/R2
            CWFI(I) = (CWFI(I)*R1 - CWFR(I)*R4)/R2
            CWFR(I) = R5
100         CONTINUE
C
C     CALCULATE ELEMENTS OF X 1/S+1
C
          DO 130 I = 1,NA
            R1 = 0.0
            R2 = 0.0
            DO 110 J = 1,NA
              R1 = R1 + CCR(I,J)*CWFR(J)
              R2 = R2 + CCR(I,J)*CWFI(J)
110           CONTINUE
            CEV(I,M) = R1
            DO 120 L = M,NBDS
              HRSUB(L,M) = HRSUB(L,M) +
     +        DBLE(CEV(I,L))*(DBLE(R3)*DBLE(R1) - DBLE(R4)*DBLE(R2))
120           CONTINUE
130         CONTINUE
C
140       CONTINUE
C
C     CALCULATE REST OF SUBSPACE HAMILTONIAN AND OVERLAP MATRIX
C
        DO 150 L = 1,NBDS
        DO 150 M = 1,L
          HRSUB(L,M) = HRSUB(L,M) + DSDOT(NA,WK(1,L),1,CEV(1,M),1)
          SRSUB(L,M) = DSDOT(NH,CEV(1,L),1,CEV(1,M),1)
150       CONTINUE
C
C     COPY INTO UPPER TRIANGLE
C
         DO 160 L = 1,NBDS
         DO 160 M = 1,L-1
           HRSUB(M,L) =  HRSUB(L,M)
           SRSUB(M,L) =  SRSUB(L,M)
160        CONTINUE
C
C     SOLVE GENERALIZED EIGENVALUE PROBLEM FOR SUBSPACE MATRICES
C
        IFAIL = 0
        CALL F02BJF(NBDS,HRSUB,NDIM8,SRSUB,NDIM8,EPS,ALFR,ALFI,
     +              BETA,LMATV,VRSUB,NDIM8,IWK,IFAIL)
        IF (IFAIL.NE.0) THEN
          WRITE(IOUT,*) '***ERROR*** FO2BJF FAILED IN REALIT'
          WRITE(IOUT,*) ' IFAIL= ', IFAIL
          CALL EXIT
          ENDIF
        DO 170 L = 1,NBDS
          IF (ABS(ALFI(L)/ALFR(L)).GT.1.0D-04) THEN
            WRITE(IOUT,*) 'IMAGINARY PART OF EIGENVALUE TOO LARGE'
            WRITE(IOUT,*) 'REAL PART= ',ALFR(L),'IMAG PART= ',ALFI(L)
            ENDIF
170       CONTINUE
C
C     CALCULATE NEW EIGENVECTORS
C
        DO 180 L = 1,NBDS
        DO 180 I = 1,NH
          WK(I,L) = 0.0
180       CONTINUE
        DO 190 L = 1,NBDS
        DO 190 M = 1,NBDS
          VR = SNGL(VRSUB(M,L))
          CALL SAXPY(NH,VR,CEV(1,M),1,WK(1,L),1)
190       CONTINUE
C
C     NORMALIZE NEW EIGENVECTORS
C
        DO 210 L = 1,NBDS
          SNORM = SNRM2(NH,WK(1,L),1)
          SNORM = 1.0/SNORM
          DO 200 I = 1,NH
200         CEV(I,L) = WK(I,L)*SNORM
210         CONTINUE
C
C     TEST FOR CONVERGENCE
C
C       WRITE(IUNIT8,*) ' ITERATION NUMBER ',ITS
        ERRMAX = 0.0
        DO 220 L = 1,NBDS
          ALFI(L) = EE2(L)
220       EE2(L) = SNGL(ALFR(L)/BETA(L))
        NDENT = 0
        ICONV = 0
        DO 250 L = 1,NBDS
          RMAX = 0.0
          DO 230 M = 1,NBDS
            RLAP = VRSUB(M,L)**2
            IF (RLAP .GT. RMAX) THEN
              RMAX = RLAP
              IDENT = M
              ENDIF
230         CONTINUE
          IF (RMAX .LT. RDENT) THEN
            WRITE(IUNIT7,*) 'E ',L,' = ',EE2(L),' NOT IDENTIFIED',
     +      ' - OVERLAP TOO SMALL'
            GOTO 250
            ENDIF
          DO 240 M = 1,NDENT
            IF (IWK(M) .EQ. IDENT) THEN
              WRITE(IUNIT7,*) 'E ',L,' = ',EE2(L),' NOT IDENTIFIED',
     +        ' - CONFUSED WITH ANOTHER E'
              GOTO 250
              ENDIF
240         CONTINUE
          NDENT = NDENT + 1
          IWK(NDENT) = IDENT
          ERR = ABS(EE2(L) - ALFI(IDENT))
          IF (ERR .LT. RES) ICONV = ICONV+1
          ERRMAX = AMAX1(ERRMAX,ERR)
C         WRITE(IUNIT7,*) 'E ',L,' = ',EE2(L),' ERROR = ',ERR
250       CONTINUE
C
        IF (ICONV .EQ. NBDS) GOTO 270
C
C     KEEP EIGENVALUES WITHIN BOUNDS AND CALCULATE NEW BOUNDS
C
        IF (ITS .LT. NITMX) CALL BOUND(NBDS,NDIM8,EE2,UBOUND,IWK,ALFI,1)
C
C     END OF ITERATION LOOP
C
260     CONTINUE
C
C     EIGENVALUES NOT CONVERGED
C
      WRITE(IOUT,*) 'NOT CONVERGED AFTER ',NITMX,' ITERATIONS'
      WRITE(IOUT,*) 'MAXIMUM ERROR IN EIGENVALUE = ',ERRMAX,' RYD'
      GOTO 280
C
C     EIGENVALUES CONVERGED
C
270   WRITE(IOUT,*) 'CONVERGED AFTER ',ITS,' ITERATIONS'
C
280   CALL USAGE (N1,T1)
      WRITE(IUNIT7,290) T1-T0, N1-N0
290   FORMAT (' REALIT - DIAGONALIZATION ',T30,F10.3,' SECONDS',
     +I10,' PAGE FAULTS')
C
      RETURN
      END
