      SUBROUTINE RECLAT (B1,B2,B3,A1,A2,A3,NG1,NG2,NG3,G2MAX,
     +  NDIM1,NDIM2,EPS1,IGLIST,G2LIST,NGTOT,NTAB,G2TAB,IWORK,ICOPY)
C
C                WRITTEN ON SEPTEMBER 24TH, 1979 - FROM RLV2 AND PSPT3
C GENERATION OF RECIPROCAL LATTICE FROM GIVEN ELEMENTARY
C TRANSLATIONS, AND SYNOPSIS OF RECIPROCAL SPACE.
C CAN BE APPLIED IN DIRECT SPACE, AS WELL, FOR GENERATION OF
C DIRECT LATTICE FROM THE GIVEN A1, A2, A3.
C SUBROUTINES NEEDED: NONE
C INPUT DATA:
C   B1,2,3 ... THE ELEMENTARY TRANSLATIONS OF RECIPROCAL LATTICE,
C              IN SOME UNITS OF RECIPROCAL LENGTH
C   A1,2,3 ... THE ELEMENTARY TRANSLATIONS OF DIRECT SPACE,
C              IN THE UNITS DETERMINED BY B1,2,3.
C   NG1,2,3 .. LIMITS OF GENERATION OF THE RECIPROCAL SPACE
C              IN THE DIRECTIONS B1,2,3 (CALCULATED BY RECLAT)
C              (THE GENERATION WILL GO OVER -NG1 TO +NG1, ETC.)
C         ---->IF THEY ARE <= 0, DEFAULTS WILL BE CALCULATED.
C   G2MAX .... SQUARED LENGTH OF THE LONGEST G-VECTOR TO BE
C              CONSIDERED (IN THE SAME UNITS AS B1,2,3 SQUARED)
C   NDIM1 .... VARIABLE DIMENSION OF THE ARRAYS IGLIST AND G2LIST
C              (NUMBER OF THE GENERATED POINTS IN REC. SPACE)
C              NDIM1 SHOULD BE LARGE ENOUGH TO ACCOMODATE
C              ALL THE GENERATED POINTS - AN ERROR MESSAGE IS ISSUED
C              IF IT IS NOT.
C   NDIM2 .... VARIABLE DIMENSION OF THE TABLES NTAB, G2TAB.
C   EPS1 ..... SMALL PARAMETER USED IN THE CONSTRUCTION OF
C              THE SYNOPTIC TABLE.
C              TYPICAL VALUE: EPS1 = 1.0E-4
C              IN CONSTRUCTING THE SYNOPTIC TABLES NTAB,G2TAB,
C              THE SUBROUTINE CONSIDERS TWO VECTORS EQUAL WHEN
C              THEIR SQUARED LENGTHS DIFFER BY LESS THAN EPS1.
C         ---->IF EPS1 IS <= 0, A DEFAULT WILL BE CALCULATED.
C OUTPUT DATA:
C   IGLIST.... LIST OF ALL GENERATED POINTS OF RECIPROCAL SPACE.
C              A VECTOR OCCUPIES 3 ELEMENTS IF IGLIST
C              I.E. IGLIST(1,K) IGLIST(2,K) IGLIST(3,K) CONTAIN
C              THE MULTIPLES OF I1,I2 AND I3 DEFINING THE KTH VECTOR
C   G2LIST ... THE CORRESPONDING SQUARED LENGTHS
C   NGTOT .... TOTAL NUMBER OF G-VECTORS IN THE IGLIST AND G2LIST
C   NTAB,G2TAB ... SYNOPSIS OF THE RECIPROCAL SPACE:
C              G2TAB(I) GIVES THE SQUARED LENGTH
C              OF THE I-TH 'TYPE' G-VECTOR ('TYPES' ARE DISTINGUISHED
C              BY THEIR LENGTH ONLY)
C              NTAB(I) GIVES THE ORDER NUMBER OF ITS FIRST OCCURENCE
C              IN THE ARRAY IGLIST
C              E.G. THE DATA
C              NTAB:    1   2   10  16 ......855  913  -1 ....
C              G2TAB:   0.  3.  4. ..........99.  -1.  -1. ...
C              SHOULD BE READ AS FOLLOWS:
C              THE 1ST VECTOR IN IGLIST HAS THE LENGTH 0,
C              THE 2ND TO 9TH VECTORS HAVE THE SQUARED-LENGTH 3.,
C              THE 10TH TO 15TH THE LENGTH 4., ETC.
C              THE LAST 'TYPE' OF G-VECTORS HAVE THE SQUARED
C              LENGTH 99. AND ARE WRITTEN IN IGLIST(*,855)
C              THROUGH IGLIST(*,912)    (912=NGTOT)  (*=1,2,3)
C              THE REST OF BOTH TABLES (IF ANY) IS FILLED BY -1.
C              ON THE OTHER HAND,
C              IF THE DIMENSION NDIM2 IS TOO SMALL TO REPORT
C              ABOUT ALL THE G-VECTORS IN IGLIST, A WARNING IS
C              ISSUED ON THE UNIT IOUT AND CALCULATION GOES ON.
C              DISTINGUISHING THE 'TYPE' BY THE LENGTH ONLY
C              IS, IN GENERAL, NOT A SUFFICIENT CRITERION:
C              ONE ONLY SHOULD CONSIDER 2 VECTORS TO BELONG
C              TO THE SAME TYPE WHEN THERE EXISTS A ROTATION
C              IN THE POINT GROUP OF THE LATTICE, WHICH BRINGS
C              ONE VECTOR INTO ANOTHER. MOST FREQUENTLY THE TWO
C              CRITERIA COINCIDE, BUT OCCASIONALLY AN AMBIGUITY
C              CAN OCCUR:WHEN THERE APPEAR VECTORS OF 2 DISTINCT
C              TYPES BUT HAVING THE SAME LENGTHS.
C              IF THIS GENERATES A TROUBLE OR NOT WILL DEPEND
C              ON THE KIND OF APPLICATION OF NTAB+GTAB.
C
      DIMENSION B1(3),B2(3),B3(3),A1(3),A2(3),A3(3)
      DIMENSION IGLIST(3,NDIM1),G2LIST(NDIM1),NTAB(NDIM2),G2TAB(NDIM2)
      DIMENSION IWORK(NDIM1),ICOPY(NDIM1)
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C
C-----------------------------------------------------------------------
C
C     SCALAR PRODUCTS AND LENGTHS
      A11 = A1(1)*A1(1) + A1(2)*A1(2) + A1(3)*A1(3)
      A22 = A2(1)*A2(1) + A2(2)*A2(2) + A2(3)*A2(3)
      A33 = A3(1)*A3(1) + A3(2)*A3(2) + A3(3)*A3(3)
      B12 = 2.0*(B1(1)*B2(1) + B1(2)*B2(2) + B1(3)*B2(3))
      B13 = 2.0*(B1(1)*B3(1) + B1(2)*B3(2) + B1(3)*B3(3))
      B23 = 2.0*(B2(1)*B3(1) + B2(2)*B3(2) + B2(3)*B3(3))
      B11 = B1(1)**2 + B1(2)**2 + B1(3)**2
      B22 = B2(1)**2 + B2(2)**2 + B2(3)**2
      B33 = B3(1)**2 + B3(2)**2 + B3(3)**2
C
C-----------------------------------------------------------------------
C
C     DEFAULTS OR NO DEFAULTS ?
C
C     EPS1 IS CHOSEN AS 1.0E-4 TIMES MAXIMUM COMPONENT OF BI.
C     EVEN IF INEQUIVALENT STARS ARE IN ONE SHELL,
C     SUBSEQUENT PROCESSING BY SBRT. 'GSHELL' WILL FIX THE PROBLEM.
      IF (EPS1 .LE. 0.0) THEN
        BMAX  = 0.0
        DO 100 I = 1,3
          B1I = ABS(B1(I))
          B2I = ABS(B2(I))
          B3I = ABS(B3(I))
          IF (B1I .GT. BMAX) BMAX = B1I
          IF (B2I .GT. BMAX) BMAX = B2I
          IF (B3I .GT. BMAX) BMAX = B3I
100     CONTINUE
        EPS1 = 0.0001 * BMAX
        WRITE (IUNIT8,*) 'RECLAT - EPS1 CHOSEN =',EPS1
        ENDIF
      IF (NG1 .GT. 0 .AND. NG2 .GT. 0 .AND. NG3 .GT. 0) GOTO 140
C
      NG1 = INT( SQRT(G2MAX*A11) + EPS1 )
      NG2 = INT( SQRT(G2MAX*A22) + EPS1 )
      NG3 = INT( SQRT(G2MAX*A33) + EPS1 )
C
C     CHECK HOW LARGE NG1,2,3 ARE REALLY NEEDED
C
      NNG1 = 1
      NNG2 = 1
      NNG3 = 1
      DO 120 I1 = -NG1,NG1
      DO 120 I2 = -NG2,NG2
      DO 120 I3 = -NG3,NG3
        G2 = FLOAT(I1*I1)*B11 + FLOAT(I2*I2)*B22 + FLOAT(I3*I3)*B33 +
     +       FLOAT(I1*I2)*B12 + FLOAT(I1*I3)*B13 + FLOAT(I2*I3)*B23
        IF (G2 .LT. G2MAX + EPS1) THEN
          IF (ABS(I1) .GT. NNG1) NNG1 = ABS(I1)
          IF (ABS(I2) .GT. NNG2) NNG2 = ABS(I2)
          IF (ABS(I3) .GT. NNG3) NNG3 = ABS(I3)
          ENDIF
120   CONTINUE
C
      NG1 = NNG1
      NG2 = NNG2
      NG3 = NNG3
      WRITE (IOUT,130) NG1,NG2,NG3
130   FORMAT('0SUBROUTINE RECLAT: OPTIMAL NG1,2,3 ARE :',3I5)
C
C     GENERATION:
C
140   NGTOT = 0
      DO 180 I1 = -NG1,NG1
      DO 180 I2 = -NG2,NG2
      DO 180 I3 = -NG3,NG3
        G2 = FLOAT(I1*I1)*B11 + FLOAT(I2*I2)*B22 + FLOAT(I3*I3)*B33 +
     +       FLOAT(I1*I2)*B12 + FLOAT(I1*I3)*B13 + FLOAT(I2*I3)*B23
        IF (G2 .LT. G2MAX + EPS1) THEN
          NGTOT = NGTOT + 1
          IF (NGTOT .LE. NDIM1) THEN
            G2LIST(NGTOT) = G2
            IGLIST(1,NGTOT) = I1
            IGLIST(2,NGTOT) = I2
            IGLIST(3,NGTOT) = I3
            ENDIF
          ENDIF
180     CONTINUE
C     WE HAVE EXCEEDED THE AVAILABLE ARRAY SIZE
      IF (NGTOT .GT. NDIM1) GOTO 300
C
C     SORTING OF THE ARRAY G2LIST IN THE ORDER OF INCREASING LENGTH
      DO 190 I = 1,NGTOT
190     IWORK(I) = I
      CALL VSRTR(G2LIST,NGTOT,IWORK)
      DO 220 J = 1,3
        DO 200 I = 1,NGTOT
200       ICOPY(I) = IGLIST(J,I)
        DO 210 I = 1,NGTOT
210       IGLIST(J,I) = ICOPY(IWORK(I))
220     CONTINUE
C
C     FIND THE SHELLS OF RECIPROCAL SPACE
C
      NTAB(1)  = 1
      G2TAB(1) = G2LIST(1)
      IORDR    = 1
      DO 250 I = 2,NGTOT
        IF (ABS(G2LIST(I) - G2TAB(IORDR)) .LE. EPS1) GOTO 250
        IORDR = IORDR + 1
        IF (IORDR .GT. NDIM2) GOTO 340
        NTAB(IORDR)  = I
        G2TAB(IORDR) = G2LIST(I)
250   CONTINUE
      IF (IORDR + 1 .GT. NDIM2) GOTO 340
      NTAB(IORDR + 1) = NGTOT + 1
      G2TAB(IORDR + 1) = - 1.0
C     FILLING THE REST BY -1  (IF ANY SPACE IS LEFT)
      IORDR2 = IORDR + 2
      IF (IORDR2 .GT. NDIM2) RETURN
      DO 280 I = IORDR2, NDIM2
        NTAB(I)  = - 1
        G2TAB(I) = - 1.0
280   CONTINUE
C
      RETURN
C-----------------------------------------------------------------------
C     ERROR MESSAGES
C
300   WRITE (IOUT,310) NGTOT,NDIM1
310   FORMAT ('0RECLAT *** FATAL ERROR ***ARRAY DIMENSIONS INSUFFICIENT'
     +/' NO. OF VECTORS = ',I6,' BUT NDIM1 = ',I6/
     +' REDUCE G2MAX OR INCREASE NDIM1')
      CALL EXIT
      RETURN
C
340   WRITE (IOUT,350) NDIM2,NGTOT
350   FORMAT ('0RECLAT-WARNING'/
     +' SYNOPSIS OF RECIPROCAL SPACE TRUNCATED'/
     +' NDIM2 =',I5,' TOO SMALL FOR NGTOT =',I5,' REC. LATT. VECTORS')
      CALL EXIT
      RETURN
C
      END
