      SUBROUTINE RO5 (NDIM1,NDIM5,NDIM8,NG1,NG2,NG3,
     +  NGTOT,IGLIST,LIST,NANB,LISTAB,NBDS,CEV,
     +  ROTEMP,WOCC,IWORK,SUM,LWORK,LREAL)
C
C     WRITTEN ON DECEMBER  31ST, 1979 - FROM RO3
C     LOOKUP OF G-VECTORS MODIFIED 21-MAY-82 BY OHN
C     STARTING FROM WAVE-FUNCTIONS DETERMINED IN PSPT11, THIS
C     SUBROUTINE EVALUATES THE CONTRIBUTION FROM ONE SPECIAL K-POINT
C     TO THE CHARGE DENSITY.
C     IN PRINCIPLE, THIS SUBROUTINE IS NOTHING ELSE THAN THE
C     MULTIPLICATION OF TWO FOURIER SERIES.
C
C SUBROUTINES NEEDED: LOOKVP
C
C INPUT DATA:
C   NDIM1 ... CEV    SEE DESCRIPTION ELSEWHERE
C   WOCC ..... OCCUPANCY OF THE GIVEN BAND
C
C OUTPUT DATA
C   ROTEMP ... THE CONTRIBUTION TO THE CHARGE DENSITY FROM THE
C              FIRST NBDS WAVEFUNCTIONS LISTED IN CEV.
C              ELEMENTS OF THE ARRAY ROTEMP ARE COEFFICIENTS OF THE
C              PLANE-WAVE EXPANSION
C              ROTEMP(G)*EXP(I*G*R)
C              WITH G'S LISTED IN IGLIST, CORRESPONDING TO THE
C              WAVEVECTOR USED IN A PREVIOUS COMPUTATION OF CEV.
C              FOR GETTING THE TOTAL CHARGE DENSITY, ONE HAS TO
C              INTEGRATE (OUTSIDE THIS SUBROUTINE) OVER THE
C              WAVEVECTOR.
C              NORMALIZATION: THERE IS
C              INTEGRAL OF ROTEMP(R) = NUMBER OF ELECTRONS
C              IN OTHER WORDS: ROTEMP(G=0) = NEL
C              METHOD: ROTEMP(G) = SUM(C(G1)*C(G2)*) , WHERE
C              SUM = SUM OVER NBDS BANDS AND SUM OVER ALL
C              COMBINATIONS G1,G2 FOR WHICH G1-G2=G.
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C
      LOGICAL LREAL
      DIMENSION IGLIST(3,NDIM1),LIST(-NG1:NG1,-NG2:NG2,-NG3:NG3)
      DIMENSION LISTAB(NDIM5),IWORK(4*NDIM5),LWORK(3,NDIM5)
      DIMENSION CEV(NDIM5,NDIM8), SUM(NDIM5)
      DOUBLE PRECISION WOCC(NDIM8)
      COMPLEX ROTEMP(NDIM1)
C-----------------------------------------------------------------------
C     FOR COMPLEX-MATRIX CALCULATIONS
C     COMPLEX CEV,CONJUG,SUM,FACTOR,Z,ZERO
C     CONJUG(Z) = CONJG(Z)
C     ZERO = (0.0,0.0)
C     IF (LREAL) WRITE(IOUT,*) '***RO5*** LREAL =',LREAL
C-----------------------------------------------------------------------
C     FOR REAL-MATRIX CALCULATIONS
      REAL CEV,CONJUG,SUM,FACTOR
      CONJUG(X) = X
      ZERO = 0.0
      IF (.NOT. LREAL) WRITE(IOUT,*) '***RO5*** LREAL =',LREAL
C-----------------------------------------------------------------------

      DO 10 I = 1, NDIM1
        ROTEMP(I) = (0.0,0.0)
10      CONTINUE
C
C     THE LOWER LEFT-HAND TRIANGLE
C
      DO 60 I = 1,NANB
C
      DO 20 J = 1,NANB
20      SUM(J) = ZERO
      DO 30 N = 1,NBDS
        FACTOR = CONJUG(CEV(I,N))*SNGL(WOCC(N))
        IF (      LREAL) CALL SAXPY(NANB,FACTOR,CEV(1,N),1,SUM,1)
        IF (.NOT. LREAL) CALL CAXPY(NANB,FACTOR,CEV(1,N),1,SUM,1)
30      CONTINUE
      IF (I .EQ. 1) THEN
        DO 40 N = 1,NANB
          LWORK(1,N) = IGLIST(1,LISTAB(N))
          LWORK(2,N) = IGLIST(2,LISTAB(N))
40        LWORK(3,N) = IGLIST(3,LISTAB(N))
        ENDIF
      DO 50 N = I,NANB
        NSTART = NDIM5-2*I+3*N
        IWORK(NSTART  ) = IGLIST(1,LISTAB(I)) - LWORK(1,N)
        IWORK(NSTART+1) = IGLIST(2,LISTAB(I)) - LWORK(2,N)
50      IWORK(NSTART+2) = IGLIST(3,LISTAB(I)) - LWORK(3,N)
      NROW = NANB-I+1
      CALL LOOKUP (LIST,NGTOT,IWORK(NDIM5+I),IWORK(I),
     +  NG1,NG2,NG3,NROW,-1)
      DO 55 J = I,NANB
55      ROTEMP(IWORK(J)) = ROTEMP(IWORK(J)) + CONJUG(SUM(J))
C
60      CONTINUE
C
C     THE UPPER RIGHT-HAND TRIANGLE
C
C     THERE ARE THE SAME G-VECTORS AS IN THE LOWER
C     LEFT-HAND TRIANGLE, ONLY THEIR SIGN IS REVERSED
C     WE THUS ONLY HAVE TO ADD ROTEMP(-G)* TO EVERY ROTEMP(G)
C
C     GO IN STEPS OF NDIM5 BECAUSE IWORK HAS LIMITED SIZE
      DO 110 ISTEP = 1, NGTOT, NDIM5
      NSTEP = NDIM5
      IF (NGTOT-ISTEP+1 .LT. NDIM5) NSTEP = NGTOT-ISTEP+1
      J0 = ISTEP - 1
      DO 90 J = 1,NSTEP
        JJ = J0 + J
        IWORK(NDIM5+3*J-2) = - IGLIST(1,JJ)
        IWORK(NDIM5+3*J-1) = - IGLIST(2,JJ)
90      IWORK(NDIM5+3*J  ) = - IGLIST(3,JJ)
      CALL LOOKUP (LIST,NGTOT,IWORK(NDIM5+1),IWORK(1),
     +  NG1,NG2,NG3,NSTEP,-1)
      DO 100 J = 1,NSTEP
        JJ = J0 + J
        IPLACE = IWORK(J)
C       IPLACE < JJ IMPLIES THAT -G PRECEEDS G. THIS PAIR WAS ALREADY DONE.
        IF (IPLACE .GT. JJ) THEN
C         HERE IT IS: IPLACE IS -G VECTOR IF JJ REPRESENTS +G
          ROTEMP(JJ) = ROTEMP(JJ) + CONJG(ROTEMP(IPLACE))
          ROTEMP(IPLACE) = CONJG(ROTEMP(JJ))
          ENDIF
100     CONTINUE
110   CONTINUE
C
      RETURN
      END
      SUBROUTINE ROGMAX (ROKG,NDIM1,NSPIN,NTAB,NDIM2, NGMAX)
      COMPLEX ROKG(NDIM1,NSPIN)
      INTEGER NTAB(NDIM2)
C
C     Find maximum G-vector encountered (NGMAX)
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C-----------------------------------------------------------------------
      DO 100 I = NDIM1, 1, -1
        ROABS = 0.0
        DO 90 ISPIN = 1, NSPIN
          ROABS = ROABS + 
     +      REAL(ROKG(I,ISPIN))**2 + AIMAG(ROKG(I,ISPIN))**2
90        CONTINUE
        IF (ROABS .GT. 1.0E-20) GOTO 110
100     CONTINUE
C     This should not happen:
      WRITE (IOUT,*) 'ROGMAX: Did not find a reasonable NGMAX',
     +  ' since ROKG is all zeroes'
      CALL EXIT
110   NGMAX = I
C
C     Now make sure that NGMAX refers to a complete shell:
      DO 200 I = 1,NDIM2
        IF (NTAB(I) .GT. NGMAX) GOTO 210
200     CONTINUE
      I = NDIM2
210   NGMAX = NTAB(I) - 1
      IF (NGMAX .LE. 0 .OR. NGMAX .GT. NDIM1) THEN
        WRITE (IOUT,*) 'ROGMAX: NGMAX =',NGMAX,' does not make sense'
        WRITE (IOUT,*) 'tried to assign NGMAX to shell =',I
        CALL EXIT
        ENDIF
C
      RETURN
      END
