      SUBROUTINE ROSYM4 (A1,A2,A3,B1,B2,B3,ISY,NC,IB,V,R,RB,
     +  IGLIST,LIST,NDIM1,NGTOT,NGMAX,NG1,NG2,NG3,
     +  ROTOT,ROSYMM,NSPIN,LREAL)
C
C                 WRITTEN ON JANUARY 2ND, 1980 - FROM ROSYM1.
C                 LOOKUP OF G-VECTORS MODIFIED 19-MAY-82 BY OHN.
C                 ROTATION MATRICES MODIFIED 02-MAR-84 BY OHN.
C
C SYMMETRIZATION OF (FOURIER COMPONENTS OF) CHARGE DENSITY
C BY POINT-GROUP SYMMETRY OPERATIONS
C SUBROUTINES NEEDED: LOOKUP
C ROSYMM(G)=(1/NC)*SUM( EXP(-I*G*V(R(J)))*ROTOT(R(J)**(-1)*G) )
C WHERE THE SUM RUNS OVER ALL NC POINT-GROUP ROTATIONS R.
C
C INPUT DATA:
C      A1....B3 ... ELEMENTARY TRANSLATIONS OF THE DIRECT
C               AND RECIPROCAL LATTICES
C      NDIM1 ...VARIABLE DIMENSION OF ARRAYS IGLIST,ROTOT,ROSYMM
C      NGTOT ...THE NUMBER OF MEANINGFUL G-VECTORS IN IGLIST
C      NGMAX ...THE NUMBER OF G-VECTORS USED IN SUBROUTINE RO5  
C      NG1,...IGLIST ... SEE THE SUBROUTINE PSPTXX OR RLV4
C               INPUT DATA WHICH MAY BE OBTAINED FROM SBRT. GROUP1:
C      ISY .... CODE INDICATING WHETHER THE SPACE GROUP OF CRYSTAL
C               IS SYMMORPHIC OR NONSYMMORPHIC
C               ISY=0 MEANS NONSYMMORPHIC GROUP
C               ISY=1 MEANS SYMMORPHIC GROUP
C      NC ..... TOTAL NUMBER OF ELEMENTS IN THE POINT GROUP OF THE
C               CRYSTAL
C      IB ..... LIST OF THE ROTATIONS CONSTITUTING THE POINT GROUP
C               OF THE CRYSTAL. THE NUMBERING IS THAT DEFINED IN
C               WORLTON AND WARREN, I.E. THE ONE MATERIALIZED IN THE
C               ARRAY R (SEE BELOW)
C               ONLY THE FIRST NC ELEMENTS OF THE ARRAY IB ARE
C               MEANINGFUL
C      V ...... NONPRIMITIVE TRANSLATIONS (IN THE CASE OF NONSYMMOR-
C               PHIC GROUPS). V(I,N) IS THE I-TH COMPONENT
C               OF THE TRANSLATION CONNECTED WITH THE N-TH ELEMENT
C               OF THE POINT GROUP (I.E. WITH THE ROTATION
C               NUMBER IB(N) ).
C               ATTENTION: V(I) HAVE TO BE GIVEN IN THE
C               BASIS A1,A2,A3 AND NOT AS CARTESIAN COMPONENTS.
C               (I.E. ONE CAN USE THE OUTPUT OF THE
C               SUBROUTINE GROUP1 WITHOUT ANY MODIFICATION.)
C      R ...... LIST OF THE 3 X 3 ROTATION MATRICES
C               (XYZ REPRESENTATION OF THE O(H) OR D(6)H GROUPS)
C               ALL 48 OR 24 MATRICES ARE LISTED.
C      ROTOT .. ARRAY WITH ELEMENTS RO(G) CORRESPONDING TO
C               G-VECTORS LISTED IN THE IGLIST.
C               THIS IS THE ARRAY TO BE SYMMETRIZED. (IN NORMAL
C               CASES, IT WILL BE OBTAINED AS WEIGHTED SUM OF
C               RO(WVK,G) (SBRT. RO3) OVER A SET OF SPECIAL
C               POINTS WVK.)
C      ROSYMM . WORK ARRAY
C
C OUTPUT DATA:
C      ROTOT .. THE SYMMETRIZED ARRAY
C
      DIMENSION A1(3),A2(3),A3(3),B1(3),B2(3),B3(3),IB(48),V(3,48)
      DIMENSION RB(48,3,3),IPLACE(48),SUM(3,3),IGL(3,48),R(49,3,3)
      DIMENSION IGLIST(3,NDIM1),LIST(-NG1:NG1,-NG2:NG2,-NG3:NG3)
      COMPLEX ROTOT(NDIM1,NSPIN),ROSYMM(NDIM1,NSPIN)
      LOGICAL LREAL
C
      COMPLEX ROSUM, PHASE
      DOUBLE PRECISION ARG
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
      DATA INITLZ /0/
C-----------------------------------------------------------------------
C
      IF (INITLZ .NE. 0) GOTO 50
C
C     INITIALIZATION:
C
C     CHECK THAT THE FIRST SYMMETRY OPERATION IN THE LIST IS IDENTITY
      IF (IB(1) .NE. 1) THEN
        WRITE (IOUT,*) '*** ERROR *** ROSYM4'
        WRITE (IOUT,99 ) (IB(I),I=1,NC)
99      FORMAT (' THERE IS SOMETHING WRONG WITH THE LIST OF '/
     +  'SYMMETRY OPERATIONS OF THE POINT GROUP, IB:'/4(/1X,12I3))
        CALL EXIT
        ENDIF
C
C     EXPRESS THE ROTATION MATRICES IN THE BASIS B1,B2,B3:
C     (ACTUALLY, RB CONTAINS R**(-1) IN THIS BASIS;
C     R**(-1) IS JUST R(TRANSPOSE), BUT NOT SO FOR RB !!!).
C
      DO 40 N = 1,NC
        IC = IB(N)
        DO 10 I = 1,3
        DO 10 J = 1,3
          SUM(I,J) = 0.0
10        CONTINUE
        DO 20 I = 1,3
        DO 20 J = 1,3
          SUM(1,1) = SUM(1,1) + A1(I)*R(IC,J,I)*B1(J)
          SUM(2,1) = SUM(2,1) + A2(I)*R(IC,J,I)*B1(J)
          SUM(3,1) = SUM(3,1) + A3(I)*R(IC,J,I)*B1(J)
          SUM(1,2) = SUM(1,2) + A1(I)*R(IC,J,I)*B2(J)
          SUM(2,2) = SUM(2,2) + A2(I)*R(IC,J,I)*B2(J)
          SUM(3,2) = SUM(3,2) + A3(I)*R(IC,J,I)*B2(J)
          SUM(1,3) = SUM(1,3) + A1(I)*R(IC,J,I)*B3(J)
          SUM(2,3) = SUM(2,3) + A2(I)*R(IC,J,I)*B3(J)
          SUM(3,3) = SUM(3,3) + A3(I)*R(IC,J,I)*B3(J)
20        CONTINUE
        DO 30 I = 1,3
        DO 30 J = 1,3
          RB(N,I,J) = SUM(I,J)
30        CONTINUE
40        CONTINUE
C
      INITLZ = 1
C-----------------------------------------------------------------------
C
50    IF (NC .EQ. 1) THEN
        RETURN
      ELSE IF (NC .LT. 1 .OR. NC .GT. 48) THEN
        WRITE(IOUT,*) '***ERROR*** ROSYM4'
        WRITE(IOUT,*) 'NC = ',NC,' IS NOT ALLOWED'
        CALL EXIT
        ENDIF
C
C     We do I=1,NDIM1 in order to reset th entire content of ROSYMM,
C     which may well contain some garbage.   OHN, Nov. 1987
      DO 60 ISPIN = 1, NSPIN
      DO 60 I = 1, NDIM1
        ROSYMM(I,ISPIN) = ROTOT(I,ISPIN)
60      CONTINUE
C
      DO 100 I = 2, NGMAX
C
      IG1 = IGLIST(1,I)
      IG2 = IGLIST(2,I)
      IG3 = IGLIST(3,I)
C
      DO 70 J = 1,3
C     SINCE NC<= 48 WE CAN USE SHORTLOOP ON A CRAY (<=64)
CDIR$ SHORTLOOP
      DO 70 N = 2,NC
C       APPLICATION OR R**(-1) TO G (SEE NOTE ABOVE)
        IGL(J,N) = NINT( RB(N,J,1)*IG1 + RB(N,J,2)*IG2 + RB(N,J,3)*IG3 )
70      CONTINUE
C
      CALL LOOKUP (LIST,NGMAX,IGL(1,2),IPLACE(2),NG1,NG2,NG3,NC-1,-1)
C
      DO 100 ISPIN = 1, NSPIN
      ROSUM = (0.0,0.0)
      IF (ISY .EQ. 0) THEN
C
C       NONSYMMORPHIC GROUP
C
        IF (LREAL) THEN
CDIR$     SHORTLOOP
          DO 80 N = 2,NC
            ARG = - 2.0D0 * PI * (       DBLE(IG1) * DBLE(V(1,N)) + 
     +        DBLE(IG2) * DBLE(V(2,N)) + DBLE(IG3) * DBLE(V(3,N)) )
            ROSUM = ROSUM + ROTOT(IPLACE(N),ISPIN) * SNGL (DCOS (ARG))
80        CONTINUE
        ELSE
CDIR$     SHORTLOOP
          DO 85 N = 2,NC
            ARG = - 2.0D0 * PI * (       DBLE(IG1) * DBLE(V(1,N)) + 
     +        DBLE(IG2) * DBLE(V(2,N)) + DBLE(IG3) * DBLE(V(3,N)) )
            PHASE = CMPLX ( SNGL (DCOS (ARG)), SNGL (DSIN (ARG)) )
            ROSUM = ROSUM + ROTOT(IPLACE(N),ISPIN) * PHASE
85          CONTINUE
          ENDIF
      ELSE
C
C       SYMMORPHIC GROUP
C
CDIR$   SHORTLOOP
        DO 90 N = 2,NC
          ROSUM = ROSUM + ROTOT(IPLACE(N),ISPIN)
90        CONTINUE
        ENDIF
C
      ROSYMM(I,ISPIN) = ROSYMM(I,ISPIN) + ROSUM
C
100   CONTINUE
C
      DO 110 ISPIN = 1, NSPIN
      DO 110 I = 2, NGMAX
        ROSYMM(I,ISPIN) = ROSYMM(I,ISPIN) / FLOAT(NC)
        ROTOT(I,ISPIN)  = ROSYMM(I,ISPIN)
110     CONTINUE
C
      RETURN
      END
