      SUBROUTINE ROWHAM (I1,I2,M,VGTOT,GK,
     +  POTPAR,POTTYP,VNLIJ,NDIM1,NDIM5,NDIM20,
     +  NLMAX,NPARAM,STRFAC,NTYPMX,VOLUM,ULA,RWF3,CWF1,
     +  VNLL,CWF4,IWF5,LSTRES,READNL,CALCNL,NONLOC,CONV1,LREAL)
C
C     CALCULATE THE M TH ROW OF THE HAMILTONIAN
C     FROM ELEMENTS I1 TO I2
C
C.....POTENTIALS
      REAL VNLIJ(0:NDIM20,0:NDIM20,NLMAX,NTYPMX)
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      INTEGER POTTYP(NTYPMX)
      COMPLEX VGTOT(NDIM1)
C.....MATRIX ELEMENTS
      REAL RWF3(NTYPMX,NDIM5)
      DIMENSION CWF1(NDIM5),VNLL(NDIM5),CWF4(6,NDIM5)
      INTEGER IWF5(14*NDIM5)
C.....STRUCTURE FACTORS
      COMPLEX STRFAC(NTYPMX,NDIM1)
C.....WAVES
      DIMENSION GK(4,NDIM5)
C.....SWITCHES
      LOGICAL LSTRES,CALCNL,READNL,NONLOC,LREAL
      DOUBLE PRECISION CONV1
      LOGICAL LNUMER
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C-----------------------------------------------------------------------
C     FOR COMPLEX HAMILTONIANS
C     COMPLEX CWF1,CWF4,VNLL
C     IF (LREAL) WRITE(IOUT,*) '***ROWHAM*** LREAL =',LREAL
C-----------------------------------------------------------------------
C     FOR REAL HAMILTONIANS
      REAL CWF1,CWF4,VNLL
      IF (.NOT. LREAL) WRITE(IOUT,*) '***ROWHAM*** LREAL =',LREAL
C-----------------------------------------------------------------------
C
C     Decide whether to use numerical or analytical potentials
      LNUMER = .FALSE.
      DO 10 ITYPE = 1, NTYPMX
        IF (POTTYP(ITYPE) .EQ. 20) LNUMER = .TRUE.
10      CONTINUE
C
      DO 100 N = I1,I2
100     CWF1(N) = VGTOT(IWF5(N))
C
      IF (NONLOC) THEN
        IF (CALCNL) THEN
          IF (LNUMER) THEN
            CALL VNLKK (LSTRES,GK,I1,I2,M,
     +        POTPAR,POTTYP,VNLIJ,NDIM5,NDIM20,NLMAX,NPARAM,
     +        STRFAC,IWF5(1),NTYPMX,NDIM1,VOLUM,ULA,LREAL,
     +        IWF5(NDIM5+1)   ,IWF5(2*NDIM5+1) ,IWF5(3*NDIM5+1) ,
     +        IWF5(4*NDIM5+1) ,IWF5(5*NDIM5+1) ,IWF5(6*NDIM5+1) ,
     +        IWF5(7*NDIM5+1) ,IWF5(8*NDIM5+1) ,IWF5(9*NDIM5+1) ,
     +        IWF5(10*NDIM5+1),IWF5(11*NDIM5+1),IWF5(12*NDIM5+1),
     +        IWF5(13*NDIM5+1),
     +        RWF3,CWF4,VNLL)
          ELSE
            CALL VNLKKA (LSTRES,GK,I1,I2,M,
     +        POTPAR,POTTYP,NPARAM,
     +        STRFAC,IWF5(1),NTYPMX,NDIM1,VOLUM,ULA,LREAL,
     +        RWF3,CWF4,VNLL)
            ENDIF
          ENDIF
C
        DO 120 N = I1,I2
120       CWF1(N) = CWF1(N) + VNLL(N)
        ENDIF
C
      IF (I2 .EQ. M)
     +  CWF1(I2) = CWF1(I2) + REAL( GK(4,I2)**2 * CONV1 )
C
      RETURN
      END
