      SUBROUTINE RPWSUM (LFORCE,LSTRES,NOFORC,NBDS,TY,NAT,I1,I2,
     +IGLIST,NG1,NG2,NG3,LREAL,RWF3,VNLL,CWF4,IWF5,SATGR,SATGI,
     +CWORK,DWORK,D1WORK,D2WORK,D3WORK,CEV,WOCC,
     +ENONLO,SWF2,FORCE,NDIM1,NDIM5,NDIM8,NDIM9,NTYPMX)
C
C     CALCULATE NON-LOCAL CONTRIBUTIONS FROM A SET OF PLANE
C     WAVES TO TOTAL ENERGY, FORCES AND STRESSES, FROM THE
C     I2 TH ROW OF THE LOWER LEFT-HALF OF THE HAMILTONIAN.
C
C     VERSION FOR REAL HAMILTONIANS
C
      LOGICAL LFORCE,LSTRES,NOFORC(NDIM9),LREAL
C.....STRUCTURE FACTORS:
      REAL SATGR(NDIM9,NDIM1),SATGI(NDIM9,NDIM1)
C.....G-VECTORS
      INTEGER IGLIST(3,NDIM1)
C.....ATOM TYPES
      INTEGER TY(NDIM9)
C.....WORKSPACES
      DOUBLE PRECISION ENONLO,SWF2(6),WOCC(NDIM8)
      DOUBLE PRECISION FORCE(3,NDIM9),DWORK(NDIM5),FF
      DOUBLE PRECISION D1WORK(NDIM5),D2WORK(NDIM5),D3WORK(NDIM5)
      DIMENSION VNLL(NDIM5),RWF3(NTYPMX,NDIM5),CWF4(6,NDIM5)
      DIMENSION CEV(NDIM5,NDIM8),CWORK(NDIM5)
      INTEGER IWF5(NDIM5)
CDIR$ INT24 N,J,KAPA,ITYPE
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C-----------------------------------------------------------------------
      IF (.NOT. LREAL) WRITE(IOUT,*) '***PWSUM*** LREAL =',LREAL
C
      DO 10 N = I1,I2
10      CWORK(N) = 0.0
C
      DO 30 J = 1,NBDS
C
C       2.0 BECAUSE OF SUM OVER UPPER AND LOWER TRIANGLES
C       1.0 ON THE DIAGONAL
        DO 20 N = I1,I2-1
20      CWORK(N)  = 2.0*WOCC(J)*CEV(N ,J)*CEV(I2,J) + CWORK(N)
        CWORK(I2) =     WOCC(J)*CEV(I2,J)*CEV(I2,J) + CWORK(I2)
30      CONTINUE
C
C.......NONLOCAL CONTRIBUTION TO TOTAL ENERGY
C
        DO 40 N = I1,I2
40        ENONLO = ENONLO + DBLE(CWORK(N))*DBLE(VNLL(N))
C
C.......STRESS-TENSOR
C
        IF (LSTRES) THEN
          DO 50 N = I1,I2
            SWF2(1) = SWF2(1) + DBLE(CWORK(N))*DBLE(CWF4(1,N))
            SWF2(2) = SWF2(2) + DBLE(CWORK(N))*DBLE(CWF4(2,N))
            SWF2(3) = SWF2(3) + DBLE(CWORK(N))*DBLE(CWF4(3,N))
            SWF2(4) = SWF2(4) + DBLE(CWORK(N))*DBLE(CWF4(4,N))
            SWF2(5) = SWF2(5) + DBLE(CWORK(N))*DBLE(CWF4(5,N))
50          SWF2(6) = SWF2(6) + DBLE(CWORK(N))*DBLE(CWF4(6,N))
          ENDIF
C
C.......HELLMANN-FEYNMAN FORCES
C
        IF (LFORCE) THEN
        DO 60 N = I1,I2
          D1WORK(N) = DBLE(IGLIST(1,IWF5(N)))
          D2WORK(N) = DBLE(IGLIST(2,IWF5(N)))
          D3WORK(N) = DBLE(IGLIST(3,IWF5(N)))
60        CONTINUE
        DO 100 KAPA = 1,NAT
          IF (NOFORC(KAPA)) GOTO 100
          DO 70 N = I1,I2
            DWORK(N) = -DBLE(SATGI(KAPA,IWF5(N)))*DBLE(CWORK(N))
70          CONTINUE
          ITYPE = TY(KAPA)
          DO 90 N = I1,I2
            FF = DWORK(N)*DBLE(RWF3(ITYPE,N))
            FORCE(1,KAPA) = FORCE(1,KAPA) + D1WORK(N)*FF
            FORCE(2,KAPA) = FORCE(2,KAPA) + D2WORK(N)*FF
90          FORCE(3,KAPA) = FORCE(3,KAPA) + D3WORK(N)*FF
100       CONTINUE
          ENDIF
C
      RETURN
      END
