      SUBROUTINE SETUP (IWRCUA,NONLOC,POTPAR,POTTYP,ULA,VOLUM,
     +  NG1,NG2,NG3,NDIM1,NDIM3,NDIM5,NDIM11,NDIM20,NLMAX,NPARAM,NTYPMX,
     +  IGLIST,LIST,VNLIJ,VGTOT,NGTOT,LISTAB,GK,NA,NB,CWF1,VNLL,CWF4,
     +  RWF3,IWF5,LWORK,LREAL,CONV1,HAMR,HAMI,DIAG,IFILEH,IFILEV,EBAR,
     +  LRWH,LRWV,LUMTX,STRFAC,LEXIST)
C----------------------------------------------------------------------
C
C     CONSTRUCTION OF THE HAMILTONIAN
C
C----------------------------------------------------------------------
C.....HAMILTONIAN
      REAL HAMR(NDIM11),HAMI(NDIM11),DIAG(NDIM5)
C.....A AND B WAVES
      DIMENSION LISTAB(NDIM5),GK(4,NDIM5)
C.....LATTICE STRUCTURE
      DIMENSION IGLIST(3,NDIM1),LIST(-NG1:NG1,-NG2:NG2,-NG3:NG3)
C.....STRUCTURE FACTORS
      COMPLEX STRFAC(NTYPMX,NDIM1)
C.....LOGICAL SWITCHES
      LOGICAL LREAL,LRWH,LRWV,LUMTX,NONLOC
      LOGICAL READNL,CALCNL,WRITEV,LSTRHM,LEXIST
C.....POTENTIALS
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      INTEGER POTTYP(NTYPMX)
      COMPLEX VGTOT(NDIM1)
      REAL VNLIJ(0:NDIM20,0:NDIM20,NLMAX,NTYPMX)
C.....WORKSPACES
      COMPLEX CWF1(NDIM5),CWF4(6,NDIM5),VNLL(NDIM5)
      REAL RWF3(NTYPMX,NDIM5)
      INTEGER IWF5(14*NDIM5),LWORK(3,NDIM5)
      DOUBLE PRECISION CONV1
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C----------------------------------------------------------------------
C
      CALL USAGE(NPAGE0,TINIT)
C
C     SET SWITCHES FOR FILE HANDLING
C
      CALL FILHAM (LRWV,NONLOC,READNL,CALCNL,LSTRHM,WRITEV,LEXIST,
     +  IWRCUA)
C
      CALL REWFIL (IFILEH)
      NANB = NA + NB
      DO 30 M = NANB,1,-1
C
        I1 = 1
        I2 = M
        IF (IWRCUA .EQ. 1) I2 = MIN0(M,NA)
        NROW = I2-I1+1
        IF (M .EQ. NANB) THEN
          DO 10 J = 1,3
          DO 10 N = I1,I2
10          LWORK(J,N) = IGLIST(J,LISTAB(N))
          ENDIF
        DO 20 J = 1,3
        NSTART = NDIM5-2*I1+J-1
        DO 20 N = I1,I2
20        IWF5(NSTART+3*N) = IGLIST(J,LISTAB(M)) - LWORK(J,N)
        CALL LOOKUP (LIST,NGTOT,IWF5(NDIM5+I1),IWF5(I1),
     +    NG1,NG2,NG3,NROW,-1)
C
        IF (READNL) THEN
          IF (     LREAL) CALL RDVEC (IFILEV,VNLL,  NROW)
          IF (.NOT.LREAL) CALL RDVEC (IFILEV,VNLL,2*NROW)
          ENDIF
C
        CALL ROWHAM (I1,I2,M,VGTOT,GK,POTPAR,POTTYP,VNLIJ,NDIM1,NDIM5,
     +    NDIM20,NLMAX,NPARAM,STRFAC,NTYPMX,VOLUM,ULA,RWF3,CWF1,
     +    VNLL,CWF4,IWF5,LSTRHM,READNL,CALCNL,NONLOC,CONV1,LREAL)
C
        CALL PUTNL (CWF1,VNLL,HAMR,HAMI,DIAG,IFILEH,IFILEV,
     +    LRWH,WRITEV,NDIM5,NDIM11,NROW,I1,I2,M,NA,NB,IWRCUA,LREAL)
C
30      CONTINUE
C
      IF (IWRCUA .EQ. 1) CALL DIAHAM (NA,NB,GK,DIAG,POTPAR,POTTYP,
     +  VNLIJ,NDIM1,NDIM5,NDIM20,NLMAX,NPARAM,STRFAC,NTYPMX,VOLUM,
     +  ULA,RWF3,CWF1,VNLL,CWF4,IWF5,LSTRHM,NONLOC,CONV1,LREAL)
C
      CALL USAGE(NPAGE1,T1)
      WRITE(IUNIT7,40) NA+NB, T1 - TINIT, NPAGE1 - NPAGE0
40    FORMAT(' Setup - Hamiltonian (N=',I4,')',T30,F10.3,' seconds',
     +  I10,' page faults')
C
      IF (LUMTX) CALL LUMAT (HAMR,HAMI,CWF1,DIAG,EBAR,NDIM5,NDIM11,
     +  NA,NB,IFILEH,LREAL)
C
      RETURN
      END
      SUBROUTINE FILHAM (LRWV,NONLOC,READNL,CALCNL,LSTRHM,
     +  WRITEV,LEXIST,IWRCUA)
C
C     SET SWITCHES BEFORE CALCULATING THE HAMILTONIAN
C
      LOGICAL READNL,CALCNL,WRITEV,LSTRHM
      LOGICAL NONLOC,LRWV,LEXIST
C
      IF (NONLOC) THEN
        IF (LEXIST) THEN
          READNL = .TRUE.
          CALCNL = .FALSE.
          WRITEV = .FALSE.
        ELSE
          READNL = .FALSE.
          CALCNL = .TRUE.
          WRITEV =  LRWV
          ENDIF
        LSTRHM = .FALSE.
      ELSE
        READNL = .FALSE.
        CALCNL = .FALSE.
        LSTRHM = .FALSE.
        WRITEV = .FALSE.
        ENDIF
C
      RETURN
      END
