      SUBROUTINE STRLOC (POTPAR,POTFIL,NTYPMX,NDIM9,NPARAM,NSPIN,
     +  POTWRK,NQMAX,VOLUM,ULA,NAT,
     +  TY,POTTYP,STRFAC,NDIM1,IGLIST,NGTOT,G2TAB,NTAB,NDIM2,
     +  ROTOT,NG1,NG2,NG3,B1,B2,B3,STRSLO)
C
C     CONTRIBUTION TO THE STRESS TENSOR FROM LOCAL POTENTIAL
C
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      CHARACTER*80 POTFIL(NTYPMX)
      REAL B1(3),B2(3),B3(3), G2TAB(NDIM2)
      INTEGER TY(NDIM9),POTTYP(NTYPMX),IGLIST(3,NDIM1),NTAB(NDIM2)
      COMPLEX STRFAC(NTYPMX,NDIM1),ROTOT(NDIM1,NSPIN)
      DOUBLE PRECISION POTWRK(0:NQMAX, 2*NSPIN + 1)
      REAL GGG(3)
      DOUBLE PRECISION G2,VG(2),VGP(2),RHOG(2), ELOCAL, VGI,VGPI,SRO,
     +                 STRSLO(3,3), STRESS
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
C-----------------------------------------------------------------------
      DO 100 I = 1,3
      DO 100 J = 1,3
        STRSLO(I,J) = 0.0D0
100     CONTINUE
      ELOCAL = 0.0D0
C
      DO 200 ITYPE = 1,NTYPMX
C
      IF (POTTYP(ITYPE) .LE. 0) GOTO 200
C
      DO 190 M = 2, NDIM2
C
      G2 = DBLE(G2TAB(M))
      IF (G2 .LT. 0.0) GOTO 200
      NMIN = NTAB(M)
      NMAX = NTAB(M + 1) - 1
      INIT = 1
      IF (M .GT. 2) INIT = 0
      L = - 1
C
      CALL POTVG (POTTYP,POTPAR,POTFIL,NTYPMX,NPARAM,ITYPE,NSPIN,
     +            POTWRK,NQMAX,VOLUM,ULA,INIT,L,G2,VG,VGP,RHOG)
C     VG CONTAINS V(G), VGP CONTAINS G**2 * V'(G**2)
C
      DO 190 IG = NMIN, NMAX
C
      CALL GCODE(IGLIST(1,IG),NG1,NG2,NG3,B1,B2,B3,IG1,IG2,IG3,GGG)
C
      DO 190 ISPIN = 1, NSPIN
C
C       STRUCTURE FACTOR * CHARGE DENSITY(*)
        SRO = (DPROD(REAL( STRFAC(ITYPE,IG)), REAL(ROTOT(IG,ISPIN))) +
     +         DPROD(AIMAG(STRFAC(ITYPE,IG)),AIMAG(ROTOT(IG,ISPIN))) )
        VGI    = VG(ISPIN)  * SRO
        VGPI   = VGP(ISPIN) * SRO * 2.0D0 / G2
C       CHECK ON THE LOCAL-POTENTIAL ENERGY:
        ELOCAL = ELOCAL + VG(ISPIN) * SRO
        DO 190 I = 1,3
          DO 190 J = 1,3
            STRESS = VGPI * DPROD(GGG(I),GGG(J))
            IF (I .EQ. J) STRESS = STRESS + VGI
            STRSLO(I,J) = STRSLO(I,J) - STRESS * RYEV
C
190         CONTINUE
C
200   CONTINUE
C
      WRITE (IUNIT8,210) ELOCAL*RYEV
210   FORMAT(' SUBROUTINE STRLOC: CHECK ENERGY TERM (D) =',F15.5,' EV')
      RETURN
      END
      SUBROUTINE STRSYM(ISY,NC,IB,R,STRESS)
C
C     APPLY POINT GROUP OPERATIONS TO THE STRESS TENSOR CALCULATED BY
C     SUMMING OVER SPECIAL POINTS.
C     WRITTEN 14-OCT-82 BY OLE HOLM NIELSEN
C     INPUT: SEE SUBROUTINE ROSYM2.
C     STRESS ..... THE STRESS TO BE SYMMETRIZED. ON RETURN STRESS
C                 CONTAINS THE CORRECT STRESS TENSOR.
C
      INTEGER IB(48)
      REAL R(49,3,3)
      REAL STRESS(3,3), WORK(3,3)
C-----------------------------------------------------------------------
      DO 100 I = 1,3
      DO 100 J = 1,3
C       DIVIDE BY THE NUMBER OF GROUP OPERATIONS
        WORK(I,J) = STRESS(I,J) / DBLE(NC)
100     CONTINUE
C
      DO 190 I = 1,3
      DO 190 J = 1,3
        STRESS(I,J) = 0.0D0
C       SUM OVER ROTATIONS
        DO 190 IROT = 1,NC
C         NOTE THAT FROM K290, THE ARRAYS F0 AND V ARE ARRANGED
C         DIFFERENTLY FROM THE ROTATION MATRICES.
          IC = IB(IROT)
          DO 190 K1 = 1,3
          DO 190 K2 = 1,3
          STRESS(I,J) = STRESS(I,J) +
     +      DPROD( R(IC,I,K1), R(IC,J,K2) ) * WORK(K1,K2)
190       CONTINUE
      RETURN
      END
