      SUBROUTINE A02AAF(XXR, XXI, YR, YI)
C     MARK 2A RELEASE.  NAG COPYRIGHT 1973
C     MARK 4.5 REVISED
C     MARK 5C REVISED
C     COMPUTES THE SQUARE ROOT OF A COMPLEX NUMBER
C
      DOUBLE PRECISION ZERO, HALF, XI, XXI, H, XXR, YR, YI, A02ABF
      DATA ZERO /0.0D0/, HALF /0.5D0/
C
      XI = XXI
      H = DSQRT((DABS(XXR)+A02ABF(XXR,XI))*HALF)
      IF (XI.NE.ZERO) XI = XI/(H+H)
      IF (XXR.LT.ZERO) GO TO 20
      YR = H
      YI = XI
      RETURN
   20 IF (XI.LT.ZERO) GO TO 40
      YR = XI
      YI = H
      RETURN
   40 YR = -XI
      YI = -H
      RETURN
      END
      DOUBLE PRECISION FUNCTION A02ABF(XXR, XXI)
C     NAG COPYRIGHT 1975
C     MARK 4.5 REVISED
C     MARK 5C REVISED
C
C     RETURNS THE ABSOLUTE VALUE OF A COMPLEX NUMBER VIA ROUTINE
C     NAME
C
      DOUBLE PRECISION ZERO, ONE, XR, XXR, XI, XXI, H
      DATA ZERO /0.0D0/, ONE /1.0D0/
C
      XR = DABS(XXR)
      XI = DABS(XXI)
      IF (XI.LE.XR) GO TO 20
      H = XR
      XR = XI
      XI = H
   20 IF (XI.NE.ZERO) GO TO 40
      A02ABF = XR
      RETURN
   40 H = XR*DSQRT(ONE+(XI/XR)**2)
      A02ABF = H
      RETURN
      END
      SUBROUTINE A02ACF(XXR, XXI, YYR, YYI, ZR, ZI)
C     MARK 2A RELEASE.  NAG COPYRIGHT 1973
C     MARK 4.5 REVISED
C     MARK 5C REVISED
C
C     DIVIDES ONE COMPLEX NUMBER BY A SECOND
C
      DOUBLE PRECISION ONE, YYR, YYI, H, A, ZR, XXR, XXI, ZI
      DATA ONE /1.0D0/
C
      IF (DABS(YYR).LE.DABS(YYI)) GO TO 20
      H = YYI/YYR
      A = ONE/(H*YYI+YYR)
      ZR = (XXR+H*XXI)*A
      ZI = (XXI-H*XXR)*A
      RETURN
   20 H = YYR/YYI
      A = ONE/(H*YYR+YYI)
      ZR = (H*XXR+XXI)*A
      ZI = (H*XXI-XXR)*A
      RETURN
      END
      SUBROUTINE F02BJF(N, A, IA, B, IB, EPS1, ALFR, ALFI, BETA,MATZ, Z,
     * IZ, ITER, IFAIL)
C     MARK 6 RELEASE. NAG COPYRIGHT 1977
C     MARK 6A REVISED  IER-99
C     THIS SUBROUTINE PERFORMS THE QZ ALGORITHM FOR SOLVING THE
C     GENERALIZED MATRIX EIGENVALUE PROBLEM, A*Z = LAMBDA*B*Z
C     WHERE A AND B ARE REAL SQUARE MATRICES.
C     REFERENCE
C     SIAM J.NUMER.ANAL., 10, PP241-256, 1973.
C     C. B. MOLER AND G. W. STEWART.
C
C     THIS SUBROUTINE WAS WRITTEN BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C     IT CALLS F02BJW, F02BJX, F02BJY AND F02BJZ WHICH
C     WERE OBTAINED FROM EISPACK.
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION EPS1
      INTEGER IA, IB, IFAIL, IZ, N
      LOGICAL MATZ
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION A(IA,N), ALFI(N), ALFR(N), B(IB,N), BETA(N),
     * Z(IZ,N)
      INTEGER ITER(N)
C     ..
C     .. LOCAL SCALARS ..
C$P 1
      DOUBLE PRECISION SRNAME
      INTEGER ISAVE
C     .. FUNCTION REFERENCES ..
      INTEGER P01AAF
C     .. SUBROUTINE REFERENCES ..
C     F02BJW, F02BJX, F02BJY, F02BJZ
C     ..
      DATA SRNAME /8H F02BJF /
      ISAVE = IFAIL
      IFAIL = 1
      CALL F02BJW(N, A, IA, B, IB, MATZ, Z, IZ)
      CALL F02BJX(N, A, IA, B, IB, EPS1, MATZ, Z, IZ, ITER, IFAIL)
      IF (IFAIL.EQ.0) GO TO 20
      IFAIL = P01AAF(ISAVE,IFAIL,SRNAME)
   20 CALL F02BJY(N, A, IA, B, IB, ALFR, ALFI, BETA, MATZ, Z, IZ)
      IF (IFAIL.NE.0) RETURN
      IF (MATZ) CALL F02BJZ(N, A, IA, B, IB, ALFR, ALFI, BETA, Z,IZ)
      RETURN
      END
      SUBROUTINE F02BJW(N, A, IA, B, IB, MATZ, Z, IZ)
C     MARK 6 RELEASE  NAG COPYRIGHT 1977
C
C     THIS SUBROUTINE IS THE FIRST STEP OF THE QZ ALGORITHM
C     FOR SOLVING GENERALIZED MATRIX EIGENVALUE PROBLEMS,
C     SIAM J. NUMER. ANAL. 10, 241-256(1973) BY MOLER AND STEWART.
C
C     THIS SUBROUTINE ACCEPTS A PAIR OF REAL GENERAL MATRICES AND
C     REDUCES ONE OF THEM TO UPPER HESSENBERG FORM AND THE OTHER
C     TO UPPER TRIANGULAR FORM USING ORTHOGONAL TRANSFORMATIONS.
C     IT IS USUALLY FOLLOWED BY F02BJX, F02BJY AND, POSSIBLY,
C     F02BJZ.
C
C     ON INPUT
C
C     N IS THE ORDER OF THE MATRICES.
C
C     A CONTAINS A REAL GENERAL MATRIX.
C
C     IA MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY A AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IA.GE.N
C
C     B CONTAINS A REAL GENERAL MATRIX.
C
C     IB MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY B AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IB.GE.N
C
C     MATZ SHOULD BE SET TO .TRUE. IF THE RIGHT HAND
C     TRANSFORMATIONS
C     ARE TO BE ACCUMULATED FOR LATER USE IN COMPUTING
C     EIGENVECTORS, AND TO .FALSE. OTHERWISE.
C
C     IZ MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY Z AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IZ.GE.N
C
C     ON OUTPUT
C
C     A HAS BEEN REDUCED TO UPPER HESSENBERG FORM.  THE ELEMENTS
C     BELOW THE FIRST SUBDIAGONAL HAVE BEEN SET TO ZERO.
C
C     B HAS BEEN REDUCED TO UPPER TRIANGULAR FORM.  THE ELEMENTS
C     BELOW THE MAIN DIAGONAL HAVE BEEN SET TO ZERO.
C
C     Z CONTAINS THE PRODUCT OF THE RIGHT HAND TRANSFORMATIONS IF
C     MATZ HAS BEEN SET TO .TRUE.  OTHERWISE, Z IS NOT REFERENCED.
C
C     IMPLEMENTED FROM EISPACK BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C
C     INITIALIZE Z
C     .. SCALAR ARGUMENTS ..
      INTEGER IA, IB, IZ, N
      LOGICAL MATZ
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION A(IA,N), B(IB,N), Z(IZ,N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION ONE, R, RHO, S, T, U1, U2, V1, V2, ZERO
      INTEGER I, J, K, L1, L, LB, NK1, NM1, NM2
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION DSQRT
C     ..
      DATA ONE /1.0D0/, ZERO /0.0D0/
      IF (.NOT.MATZ) GO TO 60
C
      DO 40 I=1,N
C
         DO 20 J=1,N
            Z(I,J) = ZERO
   20    CONTINUE
C
         Z(I,I) = ONE
   40 CONTINUE
C     REDUCE B TO UPPER TRIANGULAR FORM
   60 IF (N.LE.1) GO TO 420
      NM1 = N - 1
C
      DO 260 L=1,NM1
         L1 = L + 1
         S = ZERO
C
         DO 80 I=L1,N
            S = S + DABS(B(I,L))
   80    CONTINUE
C
         IF (S.EQ.ZERO) GO TO 260
         S = S + DABS(B(L,L))
         R = ZERO
C
         DO 100 I=L,N
            B(I,L) = B(I,L)/S
            R = R + B(I,L)**2
  100    CONTINUE
C
         R = DSQRT(R)
         IF (B(L,L).LT.ZERO) R = -R
         B(L,L) = B(L,L) + R
         RHO = R*B(L,L)
C
         DO 160 J=L1,N
            T = ZERO
C
            DO 120 I=L,N
               T = T + B(I,L)*B(I,J)
  120       CONTINUE
C
            T = -T/RHO
C
            DO 140 I=L,N
               B(I,J) = B(I,J) + T*B(I,L)
  140       CONTINUE
C
  160    CONTINUE
C
         DO 220 J=1,N
            T = ZERO
C
            DO 180 I=L,N
               T = T + B(I,L)*A(I,J)
  180       CONTINUE
C
            T = -T/RHO
C
            DO 200 I=L,N
               A(I,J) = A(I,J) + T*B(I,L)
  200       CONTINUE
C
  220    CONTINUE
C
         B(L,L) = -S*R
C
         DO 240 I=L1,N
            B(I,L) = ZERO
  240    CONTINUE
C
  260 CONTINUE
C     REDUCE A TO UPPER HESSENBERG FORM, WHILE
C     KEEPING B TRIANGULAR
      IF (N.EQ.2) GO TO 420
      NM2 = N - 2
C
      DO 400 K=1,NM2
         NK1 = NM1 - K
C     FOR L=N-1 STEP -1 UNTIL K+1 DO --
         DO 380 LB=1,NK1
            L = N - LB
            L1 = L + 1
C     ZERO A(L+1,K)
            S = DABS(A(L,K)) + DABS(A(L1,K))
            IF (S.EQ.ZERO) GO TO 380
            U1 = A(L,K)/S
            U2 = A(L1,K)/S
            R = DSQRT(U1*U1+U2*U2)
            IF (U1.LT.ZERO) R = -R
            V1 = -(U1+R)/R
            V2 = -U2/R
            U2 = V2/V1
C
            DO 280 J=K,N
               T = A(L,J) + U2*A(L1,J)
               A(L,J) = A(L,J) + T*V1
               A(L1,J) = A(L1,J) + T*V2
  280       CONTINUE
C
            A(L1,K) = ZERO
C
            DO 300 J=L,N
               T = B(L,J) + U2*B(L1,J)
               B(L,J) = B(L,J) + T*V1
               B(L1,J) = B(L1,J) + T*V2
  300       CONTINUE
C     ZERO B(L+1,L)
            S = DABS(B(L1,L1)) + DABS(B(L1,L))
            IF (S.EQ.ZERO) GO TO 380
            U1 = B(L1,L1)/S
            U2 = B(L1,L)/S
            R = DSQRT(U1*U1+U2*U2)
            IF (U1.LT.ZERO) R = -R
            V1 = -(U1+R)/R
            V2 = -U2/R
            U2 = V2/V1
C
            DO 320 I=1,L1
               T = B(I,L1) + U2*B(I,L)
               B(I,L1) = B(I,L1) + T*V1
               B(I,L) = B(I,L) + T*V2
  320       CONTINUE
C
            B(L1,L) = ZERO
C
            DO 340 I=1,N
               T = A(I,L1) + U2*A(I,L)
               A(I,L1) = A(I,L1) + T*V1
               A(I,L) = A(I,L) + T*V2
  340       CONTINUE
C
            IF (.NOT.MATZ) GO TO 380
C
            DO 360 I=1,N
               T = Z(I,L1) + U2*Z(I,L)
               Z(I,L1) = Z(I,L1) + T*V1
               Z(I,L) = Z(I,L) + T*V2
  360       CONTINUE
C
  380    CONTINUE
C
  400 CONTINUE
C
  420 RETURN
      END
      SUBROUTINE F02BJX(N, A, IA, B, IB, EPS1, MATZ, Z, IZ, ITER,IERR)
C     MARK 6 RELEASE  NAG COPYRIGHT 1977
C     MARK 8 REVISED. IER-226 (MAR 1980).
C     MARK 9 REVISED. IER-326 (SEP 1981).
C
C     THIS SUBROUTINE IS THE SECOND STEP OF THE QZ ALGORITHM
C     FOR SOLVING GENERALIZED MATRIX EIGENVALUE PROBLEMS,
C     SIAM J. NUMER. ANAL. 10, 241-256(1973) BY MOLER AND STEWART.
C
C     THIS SUBROUTINE ACCEPTS A PAIR OF REAL MATRICES, ONE OF THEM
C     IN UPPER HESSENBERG FORM AND THE OTHER IN UPPER TRIANGULAR
C     FORM.
C     IT REDUCES THE HESSENBERG MATRIX TO QUASI-TRIANGULAR FORM
C     USING
C     ORTHOGONAL TRANSFORMATIONS WHILE MAINTAINING THE TRIANGULAR
C     FORM
C     OF THE OTHER MATRIX.  IT IS USUALLY PRECEDED BY F02BJW AND
C     FOLLOWED BY F02BJY AND, POSSIBLY, F02BJZ.
C
C     ON INPUT
C
C     N IS THE ORDER OF THE MATRICES.
C
C     A CONTAINS A REAL UPPER HESSENBERG MATRIX.
C
C     IA MUST SPECIFY THE FIRST DIMENSION OF ARRAY A AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IA.GE.N
C
C     B CONTAINS A REAL UPPER TRIANGULAR MATRIX.
C
C     IB MUST SPECIFY THE FIRST DIMENSION OF ARRAY B AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IB.GE.N
C
C     EPS1 IS A TOLERANCE USED TO DETERMINE NEGLIGIBLE ELEMENTS.
C     EPS1 = 0.0 (OR NEGATIVE) MAY BE INPUT, IN WHICH CASE AN
C     ELEMENT WILL BE NEGLECTED ONLY IF IT IS LESS THAN ROUNDOFF
C     ERROR TIMES THE NORM OF ITS MATRIX.  IF THE INPUT EPS1 IS
C     POSITIVE, THEN AN ELEMENT WILL BE CONSIDERED NEGLIGIBLE
C     IF IT IS LESS THAN EPS1 TIMES THE NORM OF ITS MATRIX.  A
C     POSITIVE VALUE OF EPS1 MAY RESULT IN FASTER EXECUTION,
C     BUT LESS ACCURATE RESULTS.
C
C     MATZ SHOULD BE SET TO .TRUE. IF THE RIGHT HAND
C     TRANSFORMATIONS
C     ARE TO BE ACCUMULATED FOR LATER USE IN COMPUTING
C     EIGENVECTORS, AND TO .FALSE. OTHERWISE.
C
C     Z CONTAINS, IF MATZ HAS BEEN SET TO .TRUE., THE
C     TRANSFORMATION MATRIX PRODUCED IN THE REDUCTION
C     BY F02BJW, IF PERFORMED, OR ELSE THE IDENTITY MATRIX.
C     IF MATZ HAS BEEN SET TO .FALSE., Z IS NOT REFERENCED.
C
C     IZ MUST SPECIFY THE FIRST DIMENSION OF ARRAY Z AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IZ.GE.N
C
C     ON OUTPUT
C
C     A HAS BEEN REDUCED TO QUASI-TRIANGULAR FORM.  THE ELEMENTS
C     BELOW THE FIRST SUBDIAGONAL ARE STILL ZERO AND NO TWO
C     CONSECUTIVE SUBDIAGONAL ELEMENTS ARE NONZERO.
C
C     B IS STILL IN UPPER TRIANGULAR FORM, ALTHOUGH ITS ELEMENTS
C     HAVE BEEN ALTERED.  THE LOCATION B(N,1) IS USED TO STORE
C     EPS1 TIMES THE NORM OF B FOR LATER USE BY F02BJY AND F02BJZ.
C
C     Z CONTAINS THE PRODUCT OF THE RIGHT HAND TRANSFORMATIONS
C     (FOR BOTH STEPS) IF MATZ HAS BEEN SET TO .TRUE..
C
C     IERR IS SET TO
C     ZERO       FOR NORMAL RETURN,
C     J          IF MORE THAN 30*N ITERATIONS HAVE BEEN
C                PERFORMED ALTOGETHER.
C
C     IMPLEMENTED FROM EISPACK BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION EPS1
      INTEGER IA, IB, IERR, IZ, N
      LOGICAL MATZ
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION A(IA,N), B(IB,N), Z(IZ,N)
      INTEGER ITER(N)
C     ..
C     .. LOCAL SCALARS ..
C$P 1
      DOUBLE PRECISION SRNAME
      DOUBLE PRECISION A11, A12, A1, A21, A22, A2, A33, A34, A3, A43,
     * A44, ANI,ANORM, B11, B12, B22, B33, B34, B44, BIT, BNI, BNORM,
     * EP,EPSA, EPSB, HALF, ONE, R, S, SH, T, TWO, U1, U2, U3, V1, V2,
     *V3, XXXX, ZERO
      INTEGER EN, ENM2, ENORN, I, ISAVE, ISH, J, K1, K2, K, KM1,L1, L,
     * LD, LL, LM1, LOR1, NA, ITSTOT
      LOGICAL NOTLAS
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION DSQRT, X02AAF
      INTEGER P01AAF
C     ..
      DATA ZERO /0.0D0/, ONE /1.0D0/, TWO /2.0D0/, BIT /1.1605D0/,
     * SRNAME/8H F02BJX /, HALF /0.5D0/
      ISAVE = IERR
      IERR = 0
C     COMPUTE EPSA,EPSB
      ANORM = ZERO
      BNORM = ZERO
      ITSTOT = 30*N
C
      DO 40 I=1,N
         ITER(I) = 0
         ANI = ZERO
         IF (I.NE.1) ANI = DABS(A(I,I-1))
         BNI = ZERO
C
         DO 20 J=I,N
            ANI = ANI + DABS(A(I,J))
            BNI = BNI + DABS(B(I,J))
   20    CONTINUE
C
         IF (ANI.GT.ANORM) ANORM = ANI
         IF (BNI.GT.BNORM) BNORM = BNI
   40 CONTINUE
C
      IF (ANORM.EQ.ZERO) ANORM = ONE
      IF (BNORM.EQ.ZERO) BNORM = ONE
      EP = EPS1
      IF (EP.LE.ZERO) EP = X02AAF(XXXX)
      EPSA = EP*ANORM
      EPSB = EP*BNORM
C     REDUCE A TO QUASI-TRIANGULAR FORM, WHILE
C     KEEPING B TRIANGULAR
      LOR1 = 1
      ENORN = N
      EN = N
C     BEGIN QZ STEP
   60 IF (EN.LE.2) GO TO 580
      IF (.NOT.MATZ) ENORN = EN
      NA = EN - 1
      ENM2 = NA - 1
   80 ISH = 2
C     CHECK FOR CONVERGENCE OR REDUCIBILITY.
C     FOR L=EN STEP -1 UNTIL 1 DO --
      DO 100 LL=1,EN
         LM1 = EN - LL
         L = LM1 + 1
         IF (L.EQ.1) GO TO 140
         IF (DABS(A(L,LM1)).LE.EPSA) GO TO 120
  100 CONTINUE
C
  120 A(L,LM1) = ZERO
      IF (L.LT.NA) GO TO 140
C     1-BY-1 OR 2-BY-2 BLOCK ISOLATED
      EN = LM1
      GO TO 60
C     CHECK FOR SMALL TOP OF B
  140 LD = L
  160 L1 = L + 1
      B11 = B(L,L)
      IF (DABS(B11).GT.EPSB) GO TO 200
      B(L,L) = ZERO
      S = DABS(A(L,L)) + DABS(A(L1,L))
      U1 = A(L,L)/S
      U2 = A(L1,L)/S
      R = DSQRT(U1*U1+U2*U2)
      IF (U1.LT.ZERO) R = -R
      V1 = -(U1+R)/R
      V2 = -U2/R
      U2 = V2/V1
C
      DO 180 J=L,ENORN
         T = A(L,J) + U2*A(L1,J)
         A(L,J) = A(L,J) + T*V1
         A(L1,J) = A(L1,J) + T*V2
         T = B(L,J) + U2*B(L1,J)
         B(L,J) = B(L,J) + T*V1
         B(L1,J) = B(L1,J) + T*V2
  180 CONTINUE
C
      IF (L.NE.1) A(L,LM1) = -A(L,LM1)
      LM1 = L
      L = L1
      GO TO 120
  200 A11 = A(L,L)/B11
      A21 = A(L1,L)/B11
      IF (ISH.EQ.1) GO TO 240
C     ITERATION STRATEGY
      IF (ITSTOT.LE.0) GO TO 560
      IF (ITER(EN).EQ.10) GO TO 280
C     DETERMINE TYPE OF SHIFT
      B22 = B(L1,L1)
      IF (DABS(B22).LT.EPSB) B22 = EPSB
      B33 = B(NA,NA)
      IF (DABS(B33).LT.EPSB) B33 = EPSB
      B44 = B(EN,EN)
      IF (DABS(B44).LT.EPSB) B44 = EPSB
      A33 = A(NA,NA)/B33
      A34 = A(NA,EN)/B44
      A43 = A(EN,NA)/B33
      A44 = A(EN,EN)/B44
      B34 = B(NA,EN)/B44
      T = HALF*(A43*B34-A33-A44)
      R = T*T + A34*A43 - A33*A44
      IF (R.LT.ZERO) GO TO 260
C     DETERMINE SINGLE SHIFT ZEROTH COLUMN OF A
      ISH = 1
      R = DSQRT(R)
      SH = -T + R
      S = -T - R
      IF (DABS(S-A44).LT.DABS(SH-A44)) SH = S
C     LOOK FOR TWO CONSECUTIVE SMALL
C     SUB-DIAGONAL ELEMENTS OF A.
C     FOR L=EN-2 STEP -1 UNTIL LD DO --
      DO 220 LL=LD,ENM2
         L = ENM2 + LD - LL
         IF (L.EQ.LD) GO TO 240
         LM1 = L - 1
         L1 = L + 1
         T = A(L,L)
         IF (DABS(B(L,L)).GT.EPSB) T = T - SH*B(L,L)
         IF (DABS(A(L,LM1)).LE.DABS(T/A(L1,L))*EPSA) GO TO 160
  220 CONTINUE
C
  240 A1 = A11 - SH
      A2 = A21
      IF (L.NE.LD) A(L,LM1) = -A(L,LM1)
      GO TO 300
C     DETERMINE DOUBLE SHIFT ZEROTH COLUMN OF A
  260 A12 = A(L,L1)/B22
      A22 = A(L1,L1)/B22
      B12 = B(L,L1)/B22
      A1 = ((A33-A11)*(A44-A11)-A34*A43+A43*B34*A11)/A21 + A12 -A11*B12
      A2 = (A22-A11) - A21*B12 - (A33-A11) - (A44-A11) + A43*B34
      A3 = A(L1+1,L1)/B22
      GO TO 300
C     AD HOC SHIFT
  280 A1 = ZERO
      A2 = ONE
      A3 = BIT
  300 ITER(EN) = ITER(EN) + 1
      ITSTOT = ITSTOT - 1
      IF (.NOT.MATZ) LOR1 = LD
C     MAIN LOOP
      DO 540 K=L,NA
         NOTLAS = K.NE.NA .AND. ISH.EQ.2
         K1 = K + 1
         K2 = K + 2
         KM1 = MAX0(K-1,L)
         LL = MIN0(EN,K1+ISH)
         IF (NOTLAS) GO TO 360
C     ZERO A(K+1,K-1)
         IF (K.EQ.L) GO TO 320
         A1 = A(K,KM1)
         A2 = A(K1,KM1)
  320    S = DABS(A1) + DABS(A2)
         IF (S.EQ.ZERO) GO TO 80
         U1 = A1/S
         U2 = A2/S
         R = DSQRT(U1*U1+U2*U2)
         IF (U1.LT.ZERO) R = -R
         V1 = -(U1+R)/R
         V2 = -U2/R
         U2 = V2/V1
C
         DO 340 J=KM1,ENORN
            T = A(K,J) + U2*A(K1,J)
            A(K,J) = A(K,J) + T*V1
            A(K1,J) = A(K1,J) + T*V2
            T = B(K,J) + U2*B(K1,J)
            B(K,J) = B(K,J) + T*V1
            B(K1,J) = B(K1,J) + T*V2
  340    CONTINUE
C
         IF (K.NE.L) A(K1,KM1) = ZERO
         GO TO 480
C     ZERO A(K+1,K-1) AND A(K+2,K-1)
  360    IF (K.EQ.L) GO TO 380
         A1 = A(K,KM1)
         A2 = A(K1,KM1)
         A3 = A(K2,KM1)
  380    S = DABS(A1) + DABS(A2) + DABS(A3)
         IF (S.EQ.ZERO) GO TO 540
         U1 = A1/S
         U2 = A2/S
         U3 = A3/S
         R = DSQRT(U1*U1+U2*U2+U3*U3)
         IF (U1.LT.ZERO) R = -R
         V1 = -(U1+R)/R
         V2 = -U2/R
         V3 = -U3/R
         U2 = V2/V1
         U3 = V3/V1
C
         DO 400 J=KM1,ENORN
            T = A(K,J) + U2*A(K1,J) + U3*A(K2,J)
            A(K,J) = A(K,J) + T*V1
            A(K1,J) = A(K1,J) + T*V2
            A(K2,J) = A(K2,J) + T*V3
            T = B(K,J) + U2*B(K1,J) + U3*B(K2,J)
            B(K,J) = B(K,J) + T*V1
            B(K1,J) = B(K1,J) + T*V2
            B(K2,J) = B(K2,J) + T*V3
  400    CONTINUE
C
         IF (K.EQ.L) GO TO 420
         A(K1,KM1) = ZERO
         A(K2,KM1) = ZERO
C     ZERO B(K+2,K+1) AND B(K+2,K)
  420    S = DABS(B(K2,K2)) + DABS(B(K2,K1)) + DABS(B(K2,K))
         IF (S.EQ.ZERO) GO TO 480
         U1 = B(K2,K2)/S
         U2 = B(K2,K1)/S
         U3 = B(K2,K)/S
         R = DSQRT(U1*U1+U2*U2+U3*U3)
         IF (U1.LT.ZERO) R = -R
         V1 = -(U1+R)/R
         V2 = -U2/R
         V3 = -U3/R
         U2 = V2/V1
         U3 = V3/V1
C
         DO 440 I=LOR1,LL
            T = A(I,K2) + U2*A(I,K1) + U3*A(I,K)
            A(I,K2) = A(I,K2) + T*V1
            A(I,K1) = A(I,K1) + T*V2
            A(I,K) = A(I,K) + T*V3
            T = B(I,K2) + U2*B(I,K1) + U3*B(I,K)
            B(I,K2) = B(I,K2) + T*V1
            B(I,K1) = B(I,K1) + T*V2
            B(I,K) = B(I,K) + T*V3
  440    CONTINUE
C
         B(K2,K) = ZERO
         B(K2,K1) = ZERO
         IF (.NOT.MATZ) GO TO 480
C
         DO 460 I=1,N
            T = Z(I,K2) + U2*Z(I,K1) + U3*Z(I,K)
            Z(I,K2) = Z(I,K2) + T*V1
            Z(I,K1) = Z(I,K1) + T*V2
            Z(I,K) = Z(I,K) + T*V3
  460    CONTINUE
C     ZERO B(K+1,K)
  480    S = DABS(B(K1,K1)) + DABS(B(K1,K))
         IF (S.EQ.ZERO) GO TO 540
         U1 = B(K1,K1)/S
         U2 = B(K1,K)/S
         R = DSQRT(U1*U1+U2*U2)
         IF (U1.LT.ZERO) R = -R
         V1 = -(U1+R)/R
         V2 = -U2/R
         U2 = V2/V1
C
         DO 500 I=LOR1,LL
            T = A(I,K1) + U2*A(I,K)
            A(I,K1) = A(I,K1) + T*V1
            A(I,K) = A(I,K) + T*V2
            T = B(I,K1) + U2*B(I,K)
            B(I,K1) = B(I,K1) + T*V1
            B(I,K) = B(I,K) + T*V2
  500    CONTINUE
C
         B(K1,K) = ZERO
         IF (.NOT.MATZ) GO TO 540
C
         DO 520 I=1,N
            T = Z(I,K1) + U2*Z(I,K)
            Z(I,K1) = Z(I,K1) + T*V1
            Z(I,K) = Z(I,K) + T*V2
  520    CONTINUE
C
  540 CONTINUE
C     END QZ STEP
      GO TO 80
C     SET ERROR -- NEITHER BOTTOM SUBDIAGONAL ELEMENT
C     HAS BECOME NEGLIGIBLE AFTER 30*N ITERATIONS ALTOGETHER
  560 IERR = P01AAF(ISAVE,EN,SRNAME)
C     SAVE EPSB FOR USE BY F02BJY AND F02BJZ
  580 IF (N.GT.1) B(N,1) = EPSB
      RETURN
      END
      SUBROUTINE F02BJY(N, A, IA, B, IB, ALFR, ALFI, BETA, MATZ, Z,IZ)
C     MARK 6 RELEASE  NAG COPYRIGHT 1977
C     MARK 8 REVISED. IER-232 (MAR 1980).
C
C     THIS SUBROUTINE IS THE THIRD STEP OF THE QZ ALGORITHM
C     FOR SOLVING GENERALIZED MATRIX EIGENVALUE PROBLEMS,
C     SIAM J. NUMER. ANAL. 10, 241-256(1973) BY MOLER AND STEWART.
C
C     THIS SUBROUTINE ACCEPTS A PAIR OF REAL MATRICES, ONE OF THEM
C     IN QUASI-TRIANGULAR FORM AND THE OTHER IN UPPER TRIANGULAR
C     FORM.
C     IT REDUCES THE QUASI-TRIANGULAR MATRIX FURTHER, SO THAT ANY
C     REMAINING 2-BY-2 BLOCKS CORRESPOND TO PAIRS OF COMPLEX
C     EIGENVALUES, AND RETURNS QUANTITIES WHOSE RATIOS GIVE THE
C     GENERALIZED EIGENVALUES.  IT IS USUALLY PRECEDED BY F02BJW
C     AND F02BJX AND MAY BE FOLLOWED BY F02BJZ.
C
C     ON INPUT
C
C     N IS THE ORDER OF THE MATRICES.
C
C     A CONTAINS A REAL UPPER QUASI-TRIANGULAR MATRIX.
C
C     IA MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY A AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IA.GE.N
C
C     B CONTAINS A REAL UPPER TRIANGULAR MATRIX.  IN ADDITION,
C     LOCATION B(N,1) CONTAINS THE TOLERANCE QUANTITY (EPSB)
C     COMPUTED AND SAVED IN F02BJX.
C
C     IB MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY B AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IB.GE.N
C
C     MATZ SHOULD BE SET TO .TRUE. IF THE RIGHT HAND
C     TRANSFORMATIONS
C     ARE TO BE ACCUMULATED FOR LATER USE IN COMPUTING
C     EIGENVECTORS, AND TO .FALSE. OTHERWISE.
C
C     Z CONTAINS, IF MATZ HAS BEEN SET TO .TRUE., THE
C     TRANSFORMATION MATRIX PRODUCED IN THE REDUCTIONS BY F02BJW
C     AND F02BJX, IF PERFORMED, OR ELSE THE IDENTITY MATRIX.
C     IF MATZ HAS BEEN SET TO .FALSE., Z IS NOT REFERENCED.
C
C     IZ MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY Z AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IZ.GE.N
C
C     ON OUTPUT
C
C     A HAS BEEN REDUCED FURTHER TO A QUASI-TRIANGULAR MATRIX
C     IN WHICH ALL NONZERO SUBDIAGONAL ELEMENTS CORRESPOND TO
C     PAIRS OF COMPLEX EIGENVALUES.
C
C     B IS STILL IN UPPER TRIANGULAR FORM, ALTHOUGH ITS ELEMENTS
C     HAVE BEEN ALTERED.  B(N,1) IS UNALTERED.
C
C     ALFR AND ALFI CONTAIN THE REAL AND IMAGINARY PARTS OF THE
C     DIAGONAL ELEMENTS OF THE TRIANGULAR MATRIX THAT WOULD BE
C     OBTAINED IF A WERE REDUCED COMPLETELY TO TRIANGULAR FORM
C     BY UNITARY TRANSFORMATIONS.  NON-ZERO VALUES OF ALFI OCCUR
C     IN PAIRS, THE FIRST MEMBER POSITIVE AND THE SECOND NEGATIVE.
C
C     BETA CONTAINS THE DIAGONAL ELEMENTS OF THE CORRESPONDING B,
C     NORMALIZED TO BE REAL AND NON-NEGATIVE.  THE GENERALIZED
C     EIGENVALUES ARE THEN THE RATIOS ((ALFR+I*ALFI)/BETA).
C
C     Z CONTAINS THE PRODUCT OF THE RIGHT HAND TRANSFORMATIONS
C     (FOR ALL THREE STEPS) IF MATZ HAS BEEN SET TO .TRUE.
C
C     IMPLEMENTED FROM EISPACK BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C
C     .. SCALAR ARGUMENTS ..
      INTEGER IA, IB, IZ, N
      LOGICAL MATZ
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION A(IA,N), ALFI(N), ALFR(N), B(IB,N), BETA(N),
     * Z(IZ,N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION A11, A11I, A11R, A12, A12I, A12R, A1, A1I, A21,
     * A22,A22I, A22R, A2, A2I, AN, B11, B12, B22, BN, C, CQ, CZ, D,DI,
     * DR, E, EI, EPSB, HALF, ONE, R, S, SQI, SQR, SSI, SSR,SZI, SZR, T,
     * TI, TR, U1, U2, V1, V2, ZERO
      INTEGER EN, I, ISW, J, NA, NN
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION DSQRT
C     ..
      DATA ZERO /0.0D0/, HALF /0.5D0/, ONE /1.0D0/
      EPSB = B(N,1)
      ISW = 1
C     FIND EIGENVALUES OF QUASI-TRIANGULAR MATRICES.
C     FOR EN=N STEP -1 UNTIL 1 DO --
      DO 500 NN=1,N
         EN = N + 1 - NN
         NA = EN - 1
         IF (ISW.EQ.2) GO TO 480
         IF (EN.EQ.1) GO TO 20
         IF (A(EN,NA).NE.ZERO) GO TO 40
C     1-BY-1 BLOCK, ONE REAL ROOT
   20    ALFR(EN) = A(EN,EN)
         IF (B(EN,EN).LT.ZERO) ALFR(EN) = -ALFR(EN)
         BETA(EN) = DABS(B(EN,EN))
         ALFI(EN) = ZERO
         GO TO 500
C     2-BY-2 BLOCK
   40    IF (DABS(B(NA,NA)).LE.EPSB) GO TO 180
         IF (DABS(B(EN,EN)).GT.EPSB) GO TO 60
         A1 = A(EN,EN)
         A2 = A(EN,NA)
         BN = ZERO
         GO TO 100
   60    AN = DABS(A(NA,NA)) + DABS(A(NA,EN)) + DABS(A(EN,NA)) +
     *   DABS(A(EN,EN))
         BN = DABS(B(NA,NA)) + DABS(B(NA,EN)) + DABS(B(EN,EN))
         A11 = A(NA,NA)/AN
         A12 = A(NA,EN)/AN
         A21 = A(EN,NA)/AN
         A22 = A(EN,EN)/AN
         B11 = B(NA,NA)/BN
         B12 = B(NA,EN)/BN
         B22 = B(EN,EN)/BN
         E = A11/B11
         EI = A22/B22
         S = A21/(B11*B22)
         T = (A22-E*B22)/B22
         IF (DABS(E).LE.DABS(EI)) GO TO 70
         E = EI
         T = (A11-E*B11)/B11
   70    C = HALF*(T-S*B12)
         D = C*C + S*(A12-E*B12)
         IF (D.LT.ZERO) GO TO 260
C     TWO REAL ROOTS.
C     ZERO BOTH A(EN,NA) AND B(EN,NA)
         E = E + C + DSQRT(D)
         IF (C.LT.ZERO) E = E - 2.0D0*DSQRT(D)
         A11 = A11 - E*B11
         A12 = A12 - E*B12
         A22 = A22 - E*B22
         IF (DABS(A11)+DABS(A12).LT.DABS(A21)+DABS(A22)) GO TO 80
         A1 = A12
         A2 = A11
         GO TO 100
   80    A1 = A22
         A2 = A21
C     CHOOSE AND APPLY REAL Z
  100    S = DABS(A1) + DABS(A2)
         U1 = A1/S
         U2 = A2/S
         R = DSQRT(U1*U1+U2*U2)
         IF (U1.LT.ZERO) R = -R
         V1 = -(U1+R)/R
         V2 = -U2/R
         U2 = V2/V1
C
         DO 120 I=1,EN
            T = A(I,EN) + U2*A(I,NA)
            A(I,EN) = A(I,EN) + T*V1
            A(I,NA) = A(I,NA) + T*V2
            T = B(I,EN) + U2*B(I,NA)
            B(I,EN) = B(I,EN) + T*V1
            B(I,NA) = B(I,NA) + T*V2
  120    CONTINUE
C
         IF (.NOT.MATZ) GO TO 160
C
         DO 140 I=1,N
            T = Z(I,EN) + U2*Z(I,NA)
            Z(I,EN) = Z(I,EN) + T*V1
            Z(I,NA) = Z(I,NA) + T*V2
  140    CONTINUE
C
  160    IF (BN.EQ.ZERO) GO TO 240
         IF (AN.LT.DABS(E)*BN) GO TO 180
         A1 = B(NA,NA)
         A2 = B(EN,NA)
         GO TO 200
  180    A1 = A(NA,NA)
         A2 = A(EN,NA)
C     CHOOSE AND APPLY REAL Q
  200    S = DABS(A1) + DABS(A2)
         IF (S.EQ.ZERO) GO TO 240
         U1 = A1/S
         U2 = A2/S
         R = DSQRT(U1*U1+U2*U2)
         IF (U1.LT.ZERO) R = -R
         V1 = -(U1+R)/R
         V2 = -U2/R
         U2 = V2/V1
C
         DO 220 J=NA,N
            T = A(NA,J) + U2*A(EN,J)
            A(NA,J) = A(NA,J) + T*V1
            A(EN,J) = A(EN,J) + T*V2
            T = B(NA,J) + U2*B(EN,J)
            B(NA,J) = B(NA,J) + T*V1
            B(EN,J) = B(EN,J) + T*V2
  220    CONTINUE
C
  240    A(EN,NA) = ZERO
         B(EN,NA) = ZERO
         ALFR(NA) = A(NA,NA)
         ALFR(EN) = A(EN,EN)
         IF (B(NA,NA).LT.ZERO) ALFR(NA) = -ALFR(NA)
         IF (B(EN,EN).LT.ZERO) ALFR(EN) = -ALFR(EN)
         BETA(NA) = DABS(B(NA,NA))
         BETA(EN) = DABS(B(EN,EN))
         ALFI(EN) = ZERO
         ALFI(NA) = ZERO
         GO TO 480
C     TWO COMPLEX ROOTS
  260    E = E + C
         EI = DSQRT(-D)
         A11R = A11 - E*B11
         A11I = EI*B11
         A12R = A12 - E*B12
         A12I = EI*B12
         A22R = A22 - E*B22
         A22I = EI*B22
         IF (DABS(A11R)+DABS(A11I)+DABS(A12R)+DABS(A12I).LT.DABS(A21)+
     *   DABS(A22R)+DABS(A22I)) GO TO 280
         A1 = A12R
         A1I = A12I
         A2 = -A11R
         A2I = -A11I
         GO TO 300
  280    A1 = A22R
         A1I = A22I
         A2 = -A21
         A2I = ZERO
C     CHOOSE COMPLEX Z
  300    CZ = DSQRT(A1*A1+A1I*A1I)
         IF (CZ.EQ.ZERO) GO TO 320
         SZR = (A1*A2+A1I*A2I)/CZ
         SZI = (A1*A2I-A1I*A2)/CZ
         R = DSQRT(CZ*CZ+SZR*SZR+SZI*SZI)
         CZ = CZ/R
         SZR = SZR/R
         SZI = SZI/R
         GO TO 340
  320    SZR = ONE
         SZI = ZERO
  340    IF (AN.LT.(DABS(E)+EI)*BN) GO TO 360
         A1 = CZ*B11 + SZR*B12
         A1I = SZI*B12
         A2 = SZR*B22
         A2I = SZI*B22
         GO TO 380
  360    A1 = CZ*A11 + SZR*A12
         A1I = SZI*A12
         A2 = CZ*A21 + SZR*A22
         A2I = SZI*A22
C     CHOOSE COMPLEX Q
  380    CQ = DSQRT(A1*A1+A1I*A1I)
         IF (CQ.EQ.ZERO) GO TO 400
         SQR = (A1*A2+A1I*A2I)/CQ
         SQI = (A1*A2I-A1I*A2)/CQ
         R = DSQRT(CQ*CQ+SQR*SQR+SQI*SQI)
         CQ = CQ/R
         SQR = SQR/R
         SQI = SQI/R
         GO TO 420
  400    SQR = ONE
         SQI = ZERO
C     COMPUTE DIAGONAL ELEMENTS THAT WOULD RESULT
C     IF TRANSFORMATIONS WERE APPLIED
  420    SSR = SQR*SZR + SQI*SZI
         SSI = SQR*SZI - SQI*SZR
         I = 1
         TR = CQ*CZ*A11 + CQ*SZR*A12 + SQR*CZ*A21 + SSR*A22
         TI = CQ*SZI*A12 - SQI*CZ*A21 + SSI*A22
         DR = CQ*CZ*B11 + CQ*SZR*B12 + SSR*B22
         DI = CQ*SZI*B12 + SSI*B22
         GO TO 460
  440    I = 2
         TR = SSR*A11 - SQR*CZ*A12 - CQ*SZR*A21 + CQ*CZ*A22
         TI = -SSI*A11 - SQI*CZ*A12 + CQ*SZI*A21
         DR = SSR*B11 - SQR*CZ*B12 + CQ*CZ*B22
         DI = -SSI*B11 - SQI*CZ*B12
  460    T = TI*DR - TR*DI
         J = NA
         IF (T.LT.ZERO) J = EN
         R = DSQRT(DR*DR+DI*DI)
         BETA(J) = BN*R
         ALFR(J) = AN*(TR*DR+TI*DI)/R
         ALFI(J) = AN*T/R
         IF (I.EQ.1) GO TO 440
  480    ISW = 3 - ISW
  500 CONTINUE
C
      RETURN
      END
      SUBROUTINE F02BJZ(N, A, IA, B, IB, ALFR, ALFI, BETA, Z, IZ)
C     MARK 6 RELEASE  NAG COPYRIGHT 1977
C     MARK 9A REVISED. IER-359 (NOV 1981)
C     MARK 10B REVISED. IER-415 (JAN 1983).
C
C     THIS SUBROUTINE IS THE OPTIONAL FOURTH STEP OF THE QZ
C     ALGORITHM
C     FOR SOLVING GENERALIZED MATRIX EIGENVALUE PROBLEMS,
C     SIAM J. NUMER. ANAL. 10, 241-256(1973) BY MOLER AND STEWART.
C
C     THIS SUBROUTINE ACCEPTS A PAIR OF REAL MATRICES, ONE OF THEM
C     IN
C     QUASI-TRIANGULAR FORM (IN WHICH EACH 2-BY-2 BLOCK CORRESPONDS
C     TO
C     A PAIR OF COMPLEX*16 EIGENVALUES) AND THE OTHER IN UPPER
C     TRIANGULAR
C     FORM.  IT COMPUTES THE EIGENVECTORS OF THE TRIANGULAR PROBLEM
C     AND
C     TRANSFORMS THE RESULTS BACK TO THE ORIGINAL COORDINATE
C     SYSTEM.
C     IT IS USUALLY PRECEDED BY F02BJW, F02BJX AND F02BJY.
C
C     ON INPUT
C
C     N IS THE ORDER OF THE MATRICES.
C
C     A CONTAINS A REAL UPPER QUASI-TRIANGULAR MATRIX.
C
C     IA MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY A AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IA.GE.N
C
C     B CONTAINS A REAL UPPER TRIANGULAR MATRIX.  IN ADDITION,
C     LOCATION B(N,1) CONTAINS THE TOLERANCE QUANTITY (EPSB)
C     COMPUTED AND SAVED IN F02BJX.
C
C     IB MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY B AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IB.GE.N
C
C     ALFR, ALFI, AND BETA  ARE VECTORS WITH COMPONENTS WHOSE
C     RATIOS ((ALFR+I*ALFI)/BETA) ARE THE GENERALIZED
C     EIGENVALUES.  THEY ARE USUALLY OBTAINED FROM F02BJY.
C
C     Z CONTAINS THE TRANSFORMATION MATRIX PRODUCED IN THE
C     REDUCTIONS BY F02BJW, F02BJX AND F02BJY, IF PERFORMED.
C     IF THE EIGENVECTORS OF THE TRIANGULAR PROBLEM ARE
C     DESIRED, Z MUST CONTAIN THE IDENTITY MATRIX.
C
C     IZ MUST SPECIFY THE FIRST DIMENSION OF THE ARRAY Z AS
C     DECLARED IN THE CALLING (SUB)PROGRAM.  IZ.GE.N
C
C     ON OUTPUT
C
C     A IS UNALTERED.  ITS SUBDIAGONAL ELEMENTS PROVIDE INFORMATION
C     ABOUT THE STORAGE OF THE COMPLEX*16 EIGENVECTORS.
C
C     B HAS BEEN DESTROYED.
C
C     ALFR, ALFI, AND BETA ARE UNALTERED.
C
C     Z CONTAINS THE REAL AND IMAGINARY PARTS OF THE EIGENVECTORS.
C     IF ALFI(I) .EQ. 0.0, THE I-TH EIGENVALUE IS REAL AND
C     THE I-TH COLUMN OF Z CONTAINS ITS EIGENVECTOR.
C     IF ALFI(I) .NE. 0.0, THE I-TH EIGENVALUE IS COMPLEX*16.
C     IF ALFI(I) .GT. 0.0, THE EIGENVALUE IS THE FIRST OF
C     A COMPLEX*16 PAIR AND THE I-TH AND (I+1)-TH COLUMNS
C     OF Z CONTAIN ITS EIGENVECTOR.
C     IF ALFI(I) .LT. 0.0, THE EIGENVALUE IS THE SECOND OF
C     A COMPLEX*16 PAIR AND THE (I-1)-TH AND I-TH COLUMNS
C     OF Z CONTAIN THE CONJUGATE OF ITS EIGENVECTOR.
C     EACH EIGENVECTOR IS NORMALIZED SO THAT THE COMPONENT WITH
C     LARGEST MODULUS IS REAL AND THE SUM OF SQUARES OF THE
C     MODULI OF THE COMPONENTS IS EQUAL TO 1.0
C
C     IMPLEMENTED FROM EISPACK BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C
C     .. SCALAR ARGUMENTS ..
      INTEGER IA, IB, IZ, N
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION A(IA,N), ALFI(N), ALFR(N), B(IB,N), BETA(N),
     * Z(IZ,N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION ALFM, ALMI, ALMR, BETM, D, DI, DR, EPSB, ONE, Q,
     * R, RA,RR, S, SA, T1, T2, T, TI, TR, W1, W, X1, X, Y, Z1, ZERO, ZZ
      INTEGER EN, ENM2, I, II, ISW, J, JJ, K, M, NA, NN
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION A02ABF, F04JGW
C     ..
      DATA ZERO /0.0D0/, ONE /1.0D0/
      EPSB = B(N,1)
      ISW = 1
C     FOR EN=N STEP -1 UNTIL 1 DO --
      DO 380 NN=1,N
         EN = N + 1 - NN
         NA = EN - 1
         IF (ISW.EQ.2) GO TO 360
         IF (ALFI(EN).NE.ZERO) GO TO 140
C     REAL VECTOR
         M = EN
         B(EN,EN) = ONE
         IF (NA.EQ.0) GO TO 380
         ALFM = ALFR(M)
         BETM = BETA(M)
C     FOR I=EN-1 STEP -1 UNTIL 1 DO --
         DO 120 II=1,NA
            I = EN - II
            W = BETM*A(I,I) - ALFM*B(I,I)
            R = ZERO
C
            DO 20 J=M,EN
               R = R + (BETM*A(I,J)-ALFM*B(I,J))*B(J,EN)
   20       CONTINUE
C
            IF (I.EQ.1 .OR. ISW.EQ.2) GO TO 40
            IF (BETM*A(I,I-1).EQ.ZERO) GO TO 40
            ZZ = W
            S = R
            GO TO 100
   40       M = I
            IF (ISW.EQ.2) GO TO 60
C     REAL 1-BY-1 BLOCK
            T = W
            IF (W.EQ.ZERO) T = EPSB
            B(I,EN) = -R/T
            GO TO 120
C     REAL 2-BY-2 BLOCK
   60       X = BETM*A(I,I+1) - ALFM*B(I,I+1)
            Y = BETM*A(I+1,I)
            Q = W*ZZ - X*Y
            T = (X*S-ZZ*R)/Q
            B(I,EN) = T
            IF (DABS(X).LE.DABS(ZZ)) GO TO 80
            B(I+1,EN) = (-R-W*T)/X
            GO TO 100
   80       B(I+1,EN) = (-S-Y*T)/ZZ
  100       ISW = 3 - ISW
  120    CONTINUE
C     END REAL VECTOR
         GO TO 380
C     COMPLEX*16 VECTOR
  140    M = NA
         ALMR = ALFR(M)
         ALMI = ALFI(M)
         BETM = BETA(M)
C     LAST VECTOR COMPONENT CHOSEN IMAGINARY SO THAT
C     EIGENVECTOR MATRIX IS TRIANGULAR
         Y = BETM*A(EN,NA)
         B(NA,NA) = -ALMI*B(EN,EN)/Y
         B(NA,EN) = (ALMR*B(EN,EN)-BETM*A(EN,EN))/Y
         B(EN,NA) = ZERO
         B(EN,EN) = ONE
         ENM2 = NA - 1
         IF (ENM2.EQ.0) GO TO 360
C     FOR I=EN-2 STEP -1 UNTIL 1 DO --
         DO 340 II=1,ENM2
            I = NA - II
            W = BETM*A(I,I) - ALMR*B(I,I)
            W1 = -ALMI*B(I,I)
            RA = ZERO
            SA = ZERO
C
            DO 160 J=M,EN
               X = BETM*A(I,J) - ALMR*B(I,J)
               X1 = -ALMI*B(I,J)
               RA = RA + X*B(J,NA) - X1*B(J,EN)
               SA = SA + X*B(J,EN) + X1*B(J,NA)
  160       CONTINUE
C
            IF (I.EQ.1 .OR. ISW.EQ.2) GO TO 180
            IF (BETM*A(I,I-1).EQ.ZERO) GO TO 180
            ZZ = W
            Z1 = W1
            R = RA
            S = SA
            ISW = 2
            GO TO 340
  180       M = I
            IF (ISW.EQ.2) GO TO 260
C     COMPLEX*16 1-BY-1 BLOCK
            TR = -RA
            TI = -SA
  200       DR = W
            DI = W1
C     COMPLEX*16 DIVIDE (T1,T2) = (TR,TI) / (DR,DI)
  220       IF (DABS(DI).GT.DABS(DR)) GO TO 240
            RR = DI/DR
            D = DR + DI*RR
            T1 = (TR+TI*RR)/D
            T2 = (TI-TR*RR)/D
            GO TO (320, 280), ISW
  240       RR = DR/DI
            D = DR*RR + DI
            T1 = (TR*RR+TI)/D
            T2 = (TI*RR-TR)/D
            GO TO (320, 280), ISW
C     COMPLEX*16 2-BY-2 BLOCK
  260       X = BETM*A(I,I+1) - ALMR*B(I,I+1)
            X1 = -ALMI*B(I,I+1)
            Y = BETM*A(I+1,I)
            TR = Y*RA - W*R + W1*S
            TI = Y*SA - W*S - W1*R
            DR = W*ZZ - W1*Z1 - X*Y
            DI = W*Z1 + W1*ZZ - X1*Y
            IF (DR.EQ.ZERO .AND. DI.EQ.ZERO) DR = EPSB
            GO TO 220
  280       B(I+1,NA) = T1
            B(I+1,EN) = T2
            ISW = 1
            IF (DABS(Y).GT.DABS(W)+DABS(W1)) GO TO 300
            TR = -RA - X*B(I+1,NA) + X1*B(I+1,EN)
            TI = -SA - X*B(I+1,EN) - X1*B(I+1,NA)
            GO TO 200
  300       T1 = (-R-ZZ*B(I+1,NA)+Z1*B(I+1,EN))/Y
            T2 = (-S-ZZ*B(I+1,EN)-Z1*B(I+1,NA))/Y
  320       B(I,NA) = T1
            B(I,EN) = T2
  340    CONTINUE
C     END COMPLEX*16 VECTOR
  360    ISW = 3 - ISW
  380 CONTINUE
C     END BACK SUBSTITUTION.
C     TRANSFORM TO ORIGINAL COORDINATE SYSTEM.
C     FOR J=N STEP -1 UNTIL 1 DO --
      DO 440 JJ=1,N
         J = N + 1 - JJ
C
         DO 420 I=1,N
            ZZ = ZERO
C
            DO 400 K=1,J
               ZZ = ZZ + Z(I,K)*B(K,J)
  400       CONTINUE
C
            Z(I,J) = ZZ
  420    CONTINUE
  440 CONTINUE
C     NORMALIZE SO THAT, FOR EACH VECTOR, THE COMPONENT
C     WITH LARGEST MODULUS IS REAL AND THE SUM OF SQUARES OF
C     THE MODULI OF THE COMPONENTS IS 1.0
      J = 0
  460 J = J + 1
      IF (ALFI(J).NE.ZERO) GO TO 520
      D = F04JGW(N,Z(1,J))
      DO 500 I=1,N
         Z(I,J) = Z(I,J)/D
  500 CONTINUE
      GO TO 580
  520 R = ZERO
      DO 540 I=1,N
         W = A02ABF(Z(I,J),Z(I,J+1))
         IF (W.LE.R) GO TO 540
         R = W
         X = Z(I,J)
         Y = -Z(I,J+1)
  540 CONTINUE
      D = A02ABF(F04JGW(N,Z(1,J)),F04JGW(N,Z(1,J+1)))*A02ABF(X,Y)
      DO 560 I=1,N
         W = Z(I,J)
         Z(I,J) = (Z(I,J)*X-Z(I,J+1)*Y)/D
         Z(I,J+1) = (Y*W+X*Z(I,J+1))/D
  560 CONTINUE
      J = J + 1
  580 IF (J.LT.N) GO TO 460
C
      RETURN
      END
      SUBROUTINE F02GJF(N, AR, IAR, AI, IAI, BR, IBR, BI, IBI,EPS1,
     * ALFR, ALFI, BETA, MATZ, ZR, IZR, ZI, IZI, ITER, IFAIL)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C
C     THIS ROUTINE IS THE COMPLEX ANALOGUE OF THE QZ ALGORITHM FOR
C     SOLVING THE GENERALIZED MATRIX EIGENVALUE PROBLEM,
C     A*Z = LAMBDA*B*Z
C     WHERE A AND B ARE REAL SQUARE MATRICES.
C     REFERENCE
C     SIAM J. NUMER. ANAL., 10, PP241-256, 1973.
C     C.B. MOLER AND G.W. STEWART.
C
C     THIS BLACK BOX ROUTINE WAS WRITTEN BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE
C
C     IT CALLS F02GJX, F02GJY AND F02GJZ WHICH
C     WERE OBTAINED FROM EISPACK.
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION EPS1
      INTEGER IAI, IAR, IBI, IBR, IFAIL, IZI, IZR, N
      LOGICAL MATZ
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION AI(IAI,N), ALFI(N), ALFR(N), AR(IAR,N), BETA(N),
     *BI(IBI,N), BR(IBR,N), ZI(IZI,N), ZR(IZR,N)
      INTEGER ITER(N)
C     ..
C     .. LOCAL SCALARS ..
C$P 1
      DOUBLE PRECISION SRNAME
      INTEGER ISAVE
C     .. FUNCTION REFERENCES ..
      INTEGER P01AAF
C     .. SUBROUTINE REFERENCES ..
C     F02GJX, F02GJY, F02GJZ
C     ..
      DATA SRNAME /8H F02GJF /
      ISAVE = IFAIL
      IFAIL = 1
      CALL F02GJX(N, AR, IAR, AI, IAI, BR, IBR, BI, IBI, MATZ, ZR,IZR,
     * ZI, IZI)
      CALL F02GJY(N, AR, IAR, AI, IAI, BR, IBR, BI, IBI, EPS1,ALFR,
     * ALFI, BETA, MATZ, ZR, IZR, ZI, IZI, ITER, IFAIL)
      IF (IFAIL.EQ.0) GO TO 20
      IFAIL = P01AAF(ISAVE,IFAIL,SRNAME)
      RETURN
   20 IF (MATZ) CALL F02GJZ(N, AR, IAR, AI, IAI, BR, IBR, BI, IBI,ALFR,
     * ALFI, BETA, ZR, IZR, ZI, IZI)
      RETURN
      END
      SUBROUTINE F02GJX(N, AR, IAR, AI, IAI, BR, IBR, BI, IBI,MATZ, ZR,
     * IZR, ZI, IZI)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 11A REVISED. IER-450 (JUN 1984).
C
C     THIS ROUTINE IS A COMPLEX ANALOGUE OF THE FIRST STEP OF THE
C     QZ ALGORITHM FOR SOLVING GENERALIZED MATRIX EIGENVALUE
C     PROBLEMS,
C     SIAM J. NUMER. ANAL. 10, 241-256(1973) BY MOLER AND STEWART.
C
C     THIS ROUTINE ACCEPTS A PAIR OF COMPLEX GENERAL MATRICES AND
C     REDUCES ONE OF THEM TO UPPER HESSENBERG FORM WITH REAL (AND
C     NON-NEGATIVE) SUBDIAGONAL ELEMENTS AND THE OTHER TO UPPER
C     TRIANGULAR FORM USING UNITARY TRANSFORMATIONS. IT IS
C     USUALLY FOLLOWED BY F02GJY AND, POSSIBLY, F02GJZ.
C
C     ON INPUT
C
C     N IS THE ORDER OF THE MATRICES.
C
C     A = (AR,AI) CONTAINS A COMPLEX GENERAL MATRIX.
C
C     B = (BR,BI) CONTAINS A COMPLEX GENERAL MATRIX.
C
C     MATZ SHOULD BE SET TO .TRUE. IF THE RIGHT HAND TRANSFORMATIONS
C     ARE TO BE ACCUMULATED FOR LATER USE IN COMPUTING EIGENVECTORS,
C     AND TO .FALSE. OTHERWISE.
C
C     IAR,IAI,IBR,IBI,IZR AND IZI MUST SPECIFY THE FIRST DIMENSIONS
C     OF THE ARRAYS AR,AI,BR,BI,ZR AND ZI AS DECLARED IN THE CALLING
C     (SUB)PROGRAM.  IAR,IAI,IBR,IBI,IZR,IZI.GE.N  .
C
C     ON OUTPUT
C
C     A HAS BEEN REDUCED TO UPPER HESSENBERG FORM. THE ELEMENTS
C     BELOW THE FIRST SUBDIAGONAL HAVE BEEN REDUCED TO ZERO,
C     AND THE SUBDIAGONAL ELEMENTS HAVE BEEN MADE REAL
C     (AND NON-NEGATIVE).
C
C     B HAS BEEN REDUCED TO UPPER TRIANGULAR FORM. THE ELEMENTS
C     BELOW THE MAIN DIAGONAL HAVE BEEN SET TO ZERO.
C
C     Z = (ZR,ZI) CONTAINS THE PRODUCT OF THE RIGHT HAND
C     TRANSFORMATIONS IF MATZ HAS BEEN SET TO .TRUE.
C     OTHERWISE, Z IS NOT REFERENCED.
C
C     IMPLEMENTED FROM EISPACK BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C
C     .. SCALAR ARGUMENTS ..
      INTEGER IAI, IAR, IBI, IBR, IZI, IZR, N
      LOGICAL MATZ
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION AI(IAI,N), AR(IAR,N), BI(IBI,N), BR(IBR,N),
     * ZI(IZI,N),ZR(IZR,N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION ONE, R, RHO, S, T, TI, U1, U1I, U2, XI, XR, YI,
     * YR, ZERO
      INTEGER I, J, K1, K, L1, L, LB, NK1, NM1
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION A02ABF, DSQRT
C     ..
      DATA ZERO /0.0D0/, ONE /1.0D0/
      IF (.NOT.MATZ) GO TO 60
C
C     ---------- INITIALIZE Z ----------
      DO 40 I=1,N
C
         DO 20 J=1,N
            ZR(I,J) = ZERO
            ZI(I,J) = ZERO
   20    CONTINUE
C
         ZR(I,I) = ONE
   40 CONTINUE
C     ---------- REDUCE B TO UPPER TRIANGULAR FORM WITH
C     TEMPORARILY REAL DIAGONAL ELEMENTS ----------
   60 IF (N.LE.1) GO TO 500
      NM1 = N - 1
C
      DO 300 L=1,NM1
         L1 = L + 1
         S = ZERO
C
         DO 80 I=L,N
            S = S + DABS(BR(I,L)) + DABS(BI(I,L))
   80    CONTINUE
C
         IF (S.EQ.ZERO) GO TO 300
         RHO = ZERO
C
         DO 100 I=L,N
            BR(I,L) = BR(I,L)/S
            BI(I,L) = BI(I,L)/S
            RHO = RHO + BR(I,L)**2 + BI(I,L)**2
  100    CONTINUE
C
         R = DSQRT(RHO)
         XR = A02ABF(BR(L,L),BI(L,L))
         IF (XR.EQ.ZERO) GO TO 120
         RHO = RHO + XR*R
         U1 = -BR(L,L)/XR
         U1I = -BI(L,L)/XR
         YR = R/XR + ONE
         BR(L,L) = YR*BR(L,L)
         BI(L,L) = YR*BI(L,L)
         GO TO 140
C
  120    BR(L,L) = R
         U1 = -ONE
         U1I = ZERO
C
  140    DO 200 J=L1,N
            T = ZERO
            TI = ZERO
C
            DO 160 I=L,N
               T = T + BR(I,L)*BR(I,J) + BI(I,L)*BI(I,J)
               TI = TI + BR(I,L)*BI(I,J) - BI(I,L)*BR(I,J)
  160       CONTINUE
C
            T = T/RHO
            TI = TI/RHO
C
            DO 180 I=L,N
               BR(I,J) = BR(I,J) - T*BR(I,L) + TI*BI(I,L)
               BI(I,J) = BI(I,J) - T*BI(I,L) - TI*BR(I,L)
  180       CONTINUE
C
            XI = U1*BI(L,J) - U1I*BR(L,J)
            BR(L,J) = U1*BR(L,J) + U1I*BI(L,J)
            BI(L,J) = XI
  200    CONTINUE
C
         DO 260 J=1,N
            T = ZERO
            TI = ZERO
C
            DO 220 I=L,N
               T = T + BR(I,L)*AR(I,J) + BI(I,L)*AI(I,J)
               TI = TI + BR(I,L)*AI(I,J) - BI(I,L)*AR(I,J)
  220       CONTINUE
C
            T = T/RHO
            TI = TI/RHO
C
            DO 240 I=L,N
               AR(I,J) = AR(I,J) - T*BR(I,L) + TI*BI(I,L)
               AI(I,J) = AI(I,J) - T*BI(I,L) - TI*BR(I,L)
  240       CONTINUE
C
            XI = U1*AI(L,J) - U1I*AR(L,J)
            AR(L,J) = U1*AR(L,J) + U1I*AI(L,J)
            AI(L,J) = XI
  260    CONTINUE
C
         BR(L,L) = R*S
         BI(L,L) = ZERO
C
         DO 280 I=L1,N
            BR(I,L) = ZERO
            BI(I,L) = ZERO
  280    CONTINUE
C
  300 CONTINUE
C     REDUCE A TO UPPER HESSENBERG FORM WITH REAL SUBDIAGONAL
C     ELEMENTS, WHILE KEEPING B TRIANGULAR
      DO 480 K=1,NM1
         K1 = K + 1
C     SET BOTTOM ELEMENT IN K-TH COLUMN OF A REAL
         R = A02ABF(AR(N,K),AI(N,K))
         IF (R.EQ.ZERO) GO TO 340
         U1 = AR(N,K)/R
         U1I = AI(N,K)/R
         AR(N,K) = R
         AI(N,K) = ZERO
C
         DO 320 J=K1,N
            XI = U1*AI(N,J) - U1I*AR(N,J)
            AR(N,J) = U1*AR(N,J) + U1I*AI(N,J)
            AI(N,J) = XI
  320    CONTINUE
C
         XI = U1*BI(N,N) - U1I*BR(N,N)
         BR(N,N) = U1*BR(N,N) + U1I*BI(N,N)
         BI(N,N) = XI
  340    IF (K.EQ.NM1) GO TO 500
         NK1 = NM1 - K
C     ---------- FOR L=N-1 STEP -1 UNTIL K+1 DO -- ----------
         DO 460 LB=1,NK1
            L = N - LB
            L1 = L + 1
C     ---------- ZERO A(L+1,K) ----------
            S = DABS(AR(L,K)) + DABS(AI(L,K)) + AR(L1,K)
            IF (S.EQ.ZERO) GO TO 460
            U1 = AR(L,K)/S
            U1I = AI(L,K)/S
            U2 = AR(L1,K)/S
            R = DSQRT(U1*U1+U1I*U1I+U2*U2)
            U1 = U1/R
            U1I = U1I/R
            U2 = U2/R
            AR(L,K) = R*S
            AI(L,K) = ZERO
            AR(L1,K) = ZERO
C
            DO 360 J=K1,N
               XR = AR(L,J)
               XI = AI(L,J)
               YR = AR(L1,J)
               YI = AI(L1,J)
               AR(L,J) = U1*XR + U1I*XI + U2*YR
               AI(L,J) = U1*XI - U1I*XR + U2*YI
               AR(L1,J) = U1*YR - U1I*YI - U2*XR
               AI(L1,J) = U1*YI + U1I*YR - U2*XI
  360       CONTINUE
C
            XR = BR(L,L)
            BR(L,L) = U1*XR
            BI(L,L) = -U1I*XR
            BR(L1,L) = -U2*XR
C
            DO 380 J=L1,N
               XR = BR(L,J)
               XI = BI(L,J)
               YR = BR(L1,J)
               YI = BI(L1,J)
               BR(L,J) = U1*XR + U1I*XI + U2*YR
               BI(L,J) = U1*XI - U1I*XR + U2*YI
               BR(L1,J) = U1*YR - U1I*YI - U2*XR
               BI(L1,J) = U1*YI + U1I*YR - U2*XI
  380       CONTINUE
C     ---------- ZERO B(L+1,L) ----------
            S = DABS(BR(L1,L1)) + DABS(BI(L1,L1)) + DABS(BR(L1,L))
            IF (S.EQ.ZERO) GO TO 460
            U1 = BR(L1,L1)/S
            U1I = BI(L1,L1)/S
            U2 = BR(L1,L)/S
            R = DSQRT(U1*U1+U1I*U1I+U2*U2)
            U1 = U1/R
            U1I = U1I/R
            U2 = U2/R
            BR(L1,L1) = R*S
            BI(L1,L1) = ZERO
            BR(L1,L) = ZERO
C
            DO 400 I=1,L
               XR = BR(I,L1)
               XI = BI(I,L1)
               YR = BR(I,L)
               YI = BI(I,L)
               BR(I,L1) = U1*XR + U1I*XI + U2*YR
               BI(I,L1) = U1*XI - U1I*XR + U2*YI
               BR(I,L) = U1*YR - U1I*YI - U2*XR
               BI(I,L) = U1*YI + U1I*YR - U2*XI
  400       CONTINUE
C
            DO 420 I=1,N
               XR = AR(I,L1)
               XI = AI(I,L1)
               YR = AR(I,L)
               YI = AI(I,L)
               AR(I,L1) = U1*XR + U1I*XI + U2*YR
               AI(I,L1) = U1*XI - U1I*XR + U2*YI
               AR(I,L) = U1*YR - U1I*YI - U2*XR
               AI(I,L) = U1*YI + U1I*YR - U2*XI
  420       CONTINUE
C
            IF (.NOT.MATZ) GO TO 460
C
            DO 440 I=1,N
               XR = ZR(I,L1)
               XI = ZI(I,L1)
               YR = ZR(I,L)
               YI = ZI(I,L)
               ZR(I,L1) = U1*XR + U1I*XI + U2*YR
               ZI(I,L1) = U1*XI - U1I*XR + U2*YI
               ZR(I,L) = U1*YR - U1I*YI - U2*XR
               ZI(I,L) = U1*YI + U1I*YR - U2*XI
  440       CONTINUE
C
  460    CONTINUE
C
  480 CONTINUE
C
  500 RETURN
      END
      SUBROUTINE F02GJY(N, AR, IAR, AI, IAI, BR, IBR, BI, IBI,EPS1,
     * ALFR, ALFI, BETA, MATZ, ZR, IZR, ZI, IZI, ITER, IERR)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 9C REVISED. IER-369 (JUN 1982)
C
C     THIS ROUTINE IS A COMPLEX ANALOGUE OF STEPS 2 AND 3 OF THE
C     QZ ALGORITHM FOR SOLVING GENERALIZED MATRIX EIGENVALUE
C     PROBLEMS.
C     SIAM J. NUMER. ANAL. 10, 241-256(1973) BY MOLER AND STEWART,
C     AS MODIFIED IN TECHNICAL NOTE NASA TN D-7305(1973) BY WARD.
C
C     THIS ROUTINE ACCEPTS A PAIR OF COMPLEX MATRICES, ONE OF THEM
C     IN UPPER HESSENBERG FORM AND THE OTHER IN UPPER TRIANGULAR
C     FORM.
C     THE HESSENBERG MATRIX MUST FURTHER HAVE REAL SUBDIAGONAL
C     ELEMENTS.
C     IT REDUCES THE HESSENBERG MATRIX TO TRIANGULAR FORM USING
C     UNITARY TRANSFORMATIONS WHILE MAINTAINING THE TRIANGULAR FORM
C     OF THE OTHER MATRIX AND FURTHER MAKING ITS DIAGONAL ELEMENTS
C     REAL AND NON-NEGATIVE.  IT THEN RETURNS QUANTITIES WHOSE
C     RATIOS GIVE THE GENERALIZED EIGENVALUES. IT IS USUALLY
C     PRECEDED BY F02GJX AND POSSIBLY FOLLOWED BY F02GJZ.
C
C     ON INPUT
C
C     N IS THE ORDER OF THE MATRICES.
C
C     A=(AR,AI) CONTAINS A COMPLEX UPPER HESSENBERG MATRIX
C     WITH REAL SUBDIAGONAL ELEMENTS.
C
C     B=(BR,BI) CONTAINS A COMPLEX UPPER TRIANGULAR MATRIX.
C
C     EPS1 IS A TOLERANCE USED TO DETERMINE NEGLIGIBLE ELEMENTS.
C     EPS1 = 0.0 (OR NEGATIVE) MAY BE INPUT, IN WHICH CASE AN
C     ELEMENT WILL BE NEGLECTED ONLY IF IT IS LESS THAN ROUNDOFF
C     ERROR TIMES THE NORM OF ITS MATRIX.  IF THE INPUT EPS1 IS
C     POSITIVE, THEN AN ELEMENT WILL BE CONSIDERED NEGLIGIBLE
C     IF IT IS LESS THAN EPS1 TIMES THE NORM OF ITS MATRIX.  A
C     POSITIVE VALUE OF EPS1 MAY RESULT IN FASTER EXECUTION,
C     BUT LESS ACCURATE RESULTS.
C
C     MATZ SHOULD BE SET TO .TRUE. IF THE RIGHT HAND TRANSFORMATIONS
C     ARE TO BE ACCUMULATED FOR LATER USE IN COMPUTING
C     EIGENVECTORS, AND TO .FALSE. OTHERWISE.
C
C     Z=(ZR,ZI) CONTAINS, IF MATZ HAS BEEN SET TO .TRUE., THE
C     TRANSFORMATION MATRIX PRODUCED IN THE REDUCTION
C     BY  F02GJX, IF PERFORMED, OR ELSE THE IDENTITY MATRIX.
C     IF MATZ HAS BEEN SET TO .FALSE., Z IS NOT REFERENCED.
C
C     IAR, IAI, IBR, IBI, IZR AND IZI MUST SPECIFY THE FIRST
C     DIMENSIONS OF THE ARRAYS AR, AI, BR, BI, ZR AND ZI AS DECLARED
C     IN THE CALLING (SUB)PROGRAM.
C     IAR,IAI,IBR,IBI,IZR,IZI.GE.N  .
C
C     ON OUTPUT
C
C     A HAS BEEN REDUCED TO UPPER TRIANGULAR FORM.  THE ELEMENTS
C     BELOW THE MAIN DIAGONAL HAVE BEEN SET TO ZERO.
C
C     B IS STILL IN UPPER TRIANGULAR FORM, ALTHOUGH ITS ELEMENTS
C     HAVE BEEN ALTERED.  IN PARTICULAR, ITS DIAGONAL HAS BEEN SET
C     REAL AND NON-NEGATIVE.  THE LOCATION BR(N,1) IS USED TO
C     STORE EPS1 TIMES THE NORM OF B FOR LATER USE BY  F02GJZ.
C
C     ALFR AND ALFI CONTAIN THE REAL AND IMAGINARY PARTS OF THE
C     DIAGONAL ELEMENTS OF THE TRIANGULARIZED A MATRIX.
C
C     BETA CONTAINS THE REAL NON-NEGATIVE DIAGONAL ELEMENTS OF THE
C     CORRESPONDING B.  THE GENERALIZED EIGENVALUES ARE THEN
C     THE RATIOS ((ALFR+I*ALFI)/BETA).
C
C     Z CONTAINS THE PRODUCT OF THE RIGHT HAND TRANSFORMATIONS
C     (FOR BOTH STEPS) IF MATZ HAS BEEN SET TO .TRUE. .
C
C     ITER CONTAINS THE NUMBER OF ITERATIONS REQUIRED TO
C     ISOLATE EACH EIGENVALUE.
C
C     IERR IS SET TO
C     ZERO       FOR NORMAL RETURN,
C     J          MORE THAN 30*N ITERATIONS HAVE
C     BEEN PERFORMED ALTOGETHER
C
C     IMPLEMENTED FROM EISPACK BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION EPS1
      INTEGER IAI, IAR, IBI, IBR, IERR, IZI, IZR, N
      LOGICAL MATZ
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION AI(IAI,N), ALFI(N), ALFR(N), AR(IAR,N), BETA(N),
     *BI(IBI,N), BR(IBR,N), ZI(IZI,N), ZR(IZR,N)
      INTEGER ITER(N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION A1, A1I, A2, A33, A33I, A34, A34I, A43, A43I,
     * A44, A44I,ANI, ANORM, B11, B3344, B3344I, B33, B33I, B44, B44I,
     * BNI,BNORM, EP, EPSA, EPSB, ONE, R, S, SH, SHI, TWO, U1, U1I, U2,
     *XI, XR, YI, YR, ZERO
      INTEGER EN, ENM2, ENORN, I, ITSTOT, J, K1, K2, K, KM1, L1, L,LL,
     * LM1, LOR1, NA
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION A02ABF, DSQRT, X02AAF
C     .. SUBROUTINE REFERENCES ..
C     A02AAF, A02ACF
C     ..
      DATA ZERO /0.0D0/, ONE /1.0D0/, TWO /2.0D0/
      IERR = 0
C     ---------- COMPUTE EPSA,EPSB ----------
      ANORM = ZERO
      BNORM = ZERO
      ITSTOT = 0
C
      DO 40 I=1,N
         ITER(I) = 0
         ANI = ZERO
         IF (I.NE.1) ANI = DABS(AR(I,I-1))
         BNI = ZERO
C
         DO 20 J=I,N
            ANI = ANI + DABS(AR(I,J)) + DABS(AI(I,J))
            BNI = BNI + DABS(BR(I,J)) + DABS(BI(I,J))
   20    CONTINUE
C
         IF (ANI.GT.ANORM) ANORM = ANI
         IF (BNI.GT.BNORM) BNORM = BNI
   40 CONTINUE
C
      IF (ANORM.EQ.ZERO) ANORM = ONE
      IF (BNORM.EQ.ZERO) BNORM = ONE
      EP = EPS1
      IF (EP.LE.ZERO) EP = X02AAF(0.0D0)
      EPSA = EP*ANORM
      EPSB = EP*BNORM
C     REDUCE A TO TRIANGULAR FORM, WHILE KEEPING B TRIANGULAR
      LOR1 = 1
      ENORN = N
      EN = N
C     ---------- BEGIN QZ STEP ----------
   60 IF (EN.EQ.0) GO TO 540
      IF (.NOT.MATZ) ENORN = EN
      NA = EN - 1
      ENM2 = NA - 1
C     CHECK FOR CONVERGENCE OR REDUCIBILITY.
C     FOR L=EN STEP -1 UNTIL 1 DO
   80 DO 100 LL=1,EN
         LM1 = EN - LL
         L = LM1 + 1
         IF (L.EQ.1) GO TO 140
         IF (DABS(AR(L,LM1)).LE.EPSA) GO TO 120
  100 CONTINUE
C
  120 AR(L,LM1) = ZERO
C     ---------- SET DIAGONAL ELEMENT AT TOP OF B REAL ----------
  140 B11 = A02ABF(BR(L,L),BI(L,L))
      IF (B11.EQ.ZERO) GO TO 180
      U1 = BR(L,L)/B11
      U1I = BI(L,L)/B11
C
      DO 160 J=L,ENORN
         XI = U1*AI(L,J) - U1I*AR(L,J)
         AR(L,J) = U1*AR(L,J) + U1I*AI(L,J)
         AI(L,J) = XI
         XI = U1*BI(L,J) - U1I*BR(L,J)
         BR(L,J) = U1*BR(L,J) + U1I*BI(L,J)
         BI(L,J) = XI
  160 CONTINUE
C
      BI(L,L) = ZERO
  180 IF (L.NE.EN) GO TO 200
C     ---------- 1-BY-1 BLOCK ISOLATED ----------
      ALFR(EN) = AR(EN,EN)
      ALFI(EN) = AI(EN,EN)
      BETA(EN) = B11
      EN = NA
      GO TO 60
C     ---------- CHECK FOR SMALL TOP OF B ----------
  200 L1 = L + 1
      IF (B11.GT.EPSB) GO TO 240
      BR(L,L) = ZERO
      S = DABS(AR(L,L)) + DABS(AI(L,L)) + DABS(AR(L1,L))
      U1 = AR(L,L)/S
      U1I = AI(L,L)/S
      U2 = AR(L1,L)/S
      R = DSQRT(U1*U1+U1I*U1I+U2*U2)
      U1 = U1/R
      U1I = U1I/R
      U2 = U2/R
      AR(L,L) = R*S
      AI(L,L) = ZERO
C
      DO 220 J=L1,ENORN
         XR = AR(L,J)
         XI = AI(L,J)
         YR = AR(L1,J)
         YI = AI(L1,J)
         AR(L,J) = U1*XR + U1I*XI + U2*YR
         AI(L,J) = U1*XI - U1I*XR + U2*YI
         AR(L1,J) = U1*YR - U1I*YI - U2*XR
         AI(L1,J) = U1*YI + U1I*YR - U2*XI
         XR = BR(L,J)
         XI = BI(L,J)
         YR = BR(L1,J)
         YI = BI(L1,J)
         BR(L,J) = U1*XR + U1I*XI + U2*YR
         BI(L,J) = U1*XI - U1I*XR + U2*YI
         BR(L1,J) = U1*YR - U1I*YI - U2*XR
         BI(L1,J) = U1*YI + U1I*YR - U2*XI
  220 CONTINUE
C
      LM1 = L
      L = L1
      GO TO 120
C     ---------- ITERATION STRATEGY ----------
  240 IF (ITSTOT.GE.30*N) GO TO 520
      IF (ITER(EN).EQ.10) GO TO 320
C     ---------- DETERMINE SHIFT ----------
      B33 = BR(NA,NA)
      B33I = BI(NA,NA)
      IF (A02ABF(B33,B33I).GE.EPSB) GO TO 260
      B33 = EPSB
      B33I = ZERO
  260 B44 = BR(EN,EN)
      B44I = BI(EN,EN)
      IF (A02ABF(B44,B44I).GE.EPSB) GO TO 280
      B44 = EPSB
      B44I = ZERO
  280 B3344 = B33*B44 - B33I*B44I
      B3344I = B33*B44I + B33I*B44
      A33 = AR(NA,NA)*B44 - AI(NA,NA)*B44I
      A33I = AR(NA,NA)*B44I + AI(NA,NA)*B44
      A34 = AR(NA,EN)*B33 - AI(NA,EN)*B33I - AR(NA,NA)*BR(NA,EN) +AI(NA,
     *NA)*BI(NA,EN)
      A34I = AR(NA,EN)*B33I + AI(NA,EN)*B33 - AR(NA,NA)*BI(NA,EN) -
     *AI(NA,NA)*BR(NA,EN)
      A43 = AR(EN,NA)*B44
      A43I = AR(EN,NA)*B44I
      A44 = AR(EN,EN)*B33 - AI(EN,EN)*B33I - AR(EN,NA)*BR(NA,EN)
      A44I = AR(EN,EN)*B33I + AI(EN,EN)*B33 - AR(EN,NA)*BI(NA,EN)
      SH = A44
      SHI = A44I
      XR = A34*A43 - A34I*A43I
      XI = A34*A43I + A34I*A43
      IF (XR.EQ.ZERO .AND. XI.EQ.ZERO) GO TO 340
      YR = (A33-SH)/TWO
      YI = (A33I-SHI)/TWO
      CALL A02AAF(YR**2-YI**2+XR, TWO*YR*YI+XI, U1, U1I)
      IF (YR*U1+YI*U1I.GE.ZERO) GO TO 300
      U1 = -U1
      U1I = -U1I
  300 CALL A02ACF(XR, XI, YR+U1, YI+U1I, YR, YI)
      CALL A02ACF(SH-YR, SHI-YI, B3344, B3344I, SH, SHI)
      GO TO 340
C     ---------- AD HOC SHIFT ----------
  320 SH = AR(EN,NA) + AR(NA,ENM2)
      SHI = ZERO
C     ---------- DETERMINE ZEROTH COLUMN OF A ----------
  340 A1 = AR(L,L)/B11 - SH
      A1I = AI(L,L)/B11 - SHI
      A2 = AR(L1,L)/B11
      ITER(EN) = ITER(EN) + 1
      ITSTOT = ITSTOT + 1
      IF (.NOT.MATZ) LOR1 = L
C     ---------- MAIN LOOP ----------
      DO 480 K=L,NA
         K1 = K + 1
         K2 = K + 2
         KM1 = MAX0(K-1,L)
C     ---------- ZERO A(K+1,K-1) ----------
         IF (K.EQ.L) GO TO 360
         A1 = AR(K,KM1)
         A1I = AI(K,KM1)
         A2 = AR(K1,KM1)
  360    S = DABS(A1) + DABS(A1I) + DABS(A2)
         U1 = A1/S
         U1I = A1I/S
         U2 = A2/S
         R = DSQRT(U1*U1+U1I*U1I+U2*U2)
         U1 = U1/R
         U1I = U1I/R
         U2 = U2/R
C
         DO 380 J=KM1,ENORN
            XR = AR(K,J)
            XI = AI(K,J)
            YR = AR(K1,J)
            YI = AI(K1,J)
            AR(K,J) = U1*XR + U1I*XI + U2*YR
            AI(K,J) = U1*XI - U1I*XR + U2*YI
            AR(K1,J) = U1*YR - U1I*YI - U2*XR
            AI(K1,J) = U1*YI + U1I*YR - U2*XI
            XR = BR(K,J)
            XI = BI(K,J)
            YR = BR(K1,J)
            YI = BI(K1,J)
            BR(K,J) = U1*XR + U1I*XI + U2*YR
            BI(K,J) = U1*XI - U1I*XR + U2*YI
            BR(K1,J) = U1*YR - U1I*YI - U2*XR
            BI(K1,J) = U1*YI + U1I*YR - U2*XI
  380    CONTINUE
C
         IF (K.EQ.L) GO TO 400
         AI(K,KM1) = ZERO
         AR(K1,KM1) = ZERO
         AI(K1,KM1) = ZERO
C     ---------- ZERO B(K+1,K) ----------
  400    S = DABS(BR(K1,K1)) + DABS(BI(K1,K1)) + DABS(BR(K1,K))
         U1 = BR(K1,K1)/S
         U1I = BI(K1,K1)/S
         U2 = BR(K1,K)/S
         R = DSQRT(U1*U1+U1I*U1I+U2*U2)
         U1 = U1/R
         U1I = U1I/R
         U2 = U2/R
         IF (K.EQ.NA) GO TO 420
         XR = AR(K2,K1)
         AR(K2,K1) = U1*XR
         AI(K2,K1) = -U1I*XR
         AR(K2,K) = -U2*XR
C
  420    DO 440 I=LOR1,K1
            XR = AR(I,K1)
            XI = AI(I,K1)
            YR = AR(I,K)
            YI = AI(I,K)
            AR(I,K1) = U1*XR + U1I*XI + U2*YR
            AI(I,K1) = U1*XI - U1I*XR + U2*YI
            AR(I,K) = U1*YR - U1I*YI - U2*XR
            AI(I,K) = U1*YI + U1I*YR - U2*XI
            XR = BR(I,K1)
            XI = BI(I,K1)
            YR = BR(I,K)
            YI = BI(I,K)
            BR(I,K1) = U1*XR + U1I*XI + U2*YR
            BI(I,K1) = U1*XI - U1I*XR + U2*YI
            BR(I,K) = U1*YR - U1I*YI - U2*XR
            BI(I,K) = U1*YI + U1I*YR - U2*XI
  440    CONTINUE
C
         BI(K1,K1) = ZERO
         BR(K1,K) = ZERO
         BI(K1,K) = ZERO
         IF (.NOT.MATZ) GO TO 480
C
         DO 460 I=1,N
            XR = ZR(I,K1)
            XI = ZI(I,K1)
            YR = ZR(I,K)
            YI = ZI(I,K)
            ZR(I,K1) = U1*XR + U1I*XI + U2*YR
            ZI(I,K1) = U1*XI - U1I*XR + U2*YI
            ZR(I,K) = U1*YR - U1I*YI - U2*XR
            ZI(I,K) = U1*YI + U1I*YR - U2*XI
  460    CONTINUE
C
  480 CONTINUE
C     SET LAST A SUBDIAGONAL REAL AND END QZ STEP
      IF (AI(EN,NA).EQ.ZERO) GO TO 80
      R = A02ABF(AR(EN,NA),AI(EN,NA))
      U1 = AR(EN,NA)/R
      U1I = AI(EN,NA)/R
      AR(EN,NA) = R
      AI(EN,NA) = ZERO
C
      DO 500 J=EN,ENORN
         XI = U1*AI(EN,J) - U1I*AR(EN,J)
         AR(EN,J) = U1*AR(EN,J) + U1I*AI(EN,J)
         AI(EN,J) = XI
         XI = U1*BI(EN,J) - U1I*BR(EN,J)
         BR(EN,J) = U1*BR(EN,J) + U1I*BI(EN,J)
         BI(EN,J) = XI
  500 CONTINUE
C
      GO TO 80
C     ---------- SET ERROR -- BOTTOM SUBDIAGONAL ELEMENT HAS NOT
C     BECOME NEGLIGIBLE AFTER 50 ITERATIONS ----------
  520 IERR = EN
C     ---------- SAVE EPSB FOR USE BY F02GJZ ----------
  540 IF (N.GT.1) BR(N,1) = EPSB
      RETURN
      END
      SUBROUTINE F02GJZ(N, AR, IAR, AI, IAI, BR, IBR, BI, IBI,ALFR,
     * ALFI, BETA, ZR, IZR, ZI, IZI)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C
C     THIS ROUTINE IS A COMPLEX ANALOGUE OF THE FOURTH STEP OF THE
C     QZ ALGORITHM FOR SOLVING GENERALIZED MATRIX EIGENVALUE
C     PROBLEMS
C     SIAM J. NUMER. ANAL. 10, 241-256(1973) BY MOLER AND STEWART.
C
C     THIS ROUTINE ACCEPTS A PAIR OF COMPLEX MATRICES IN UPPER
C     TRIANGULAR FORM, WHERE ONE OF THEM FURTHER MUST HAVE REAL
C     DIAGONAL ELEMENTS. IT COMPUTES THE EIGENVECTORS OF THE
C     TRIANGULAR PROBLEM AND TRANSFORMS THE RESULTS BACK TO THE
C     ORIGINAL COORDINATE SYSTEM. IT IS USUALLY PRECEDED BY
C     F02GJX AND F02GJY.
C
C     ON INPUT
C
C     N IS THE ORDER OF THE MATRICES.
C
C     A=(AR,AI) CONTAINS A COMPLEX UPPER TRIANGULAR MATRIX.
C
C     B=(BR,BI) CONTAINS A COMPLEX UPPER TRIANGULAR MATRIX WITH REAL
C     DIAGONAL ELEMENTS.  IN ADDITION, LOCATION BR(N,1) CONTAINS
C     THE TOLERANCE QUANTITY (EPSB) COMPUTED AND SAVED IN  F02GJY.
C
C     ALFR, ALFI, AND BETA ARE VECTORS WITH COMPONENTS WHOSE
C     RATIOS ((ALFR+I*ALFI)/BETA) ARE THE GENERALIZED
C     EIGENVALUES.  THEY ARE USUALLY OBTAINED FROM F02GJY.
C
C     Z=(ZR,ZI) CONTAINS THE TRANSFORMATION MATRIX PRODUCED IN THE
C     REDUCTIONS BY  F02GJX  AND  F02GJY, IF PERFORMED.
C     IF THE EIGENVECTORS OF THE TRIANGULAR PROBLEM ARE
C     DESIRED, Z MUST CONTAIN THE IDENTITY MATRIX.
C
C     IAR, IAI, IBR, IBI, IZR AND IZI MUST SPECIFY THE FIRST
C     DIMENSIONS OF THE ARRAYS AR, AI, BR, BI, ZR AND ZI AS DECLARED
C     IN THE CALLING (SUB)PROGRAM.
C     IAR,IAI,IBR,IBI,IZR,IZI.GE.N  .
C
C     ON OUTPUT
C
C     A IS UNALTERED.
C
C     B HAS BEEN DESTROYED.
C
C     ALFR, ALFI, AND BETA ARE UNALTERED.
C
C     Z CONTAINS THE EIGENVECTORS.  EACH EIGENVECTOR IS NORMALIZED
C     SO THAT THE SUM OF SQUARES OF THE MODULI OF THE COMPONENTS IS
C     EQUAL TO 1.0 AND THE COMPONENT OF LARGEST MODULUS IS REAL.
C
C     IMPLEMENTED FROM EISPACK BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C
C     .. SCALAR ARGUMENTS ..
      INTEGER IAI, IAR, IBI, IBR, IZI, IZR, N
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION AI(IAI,N), ALFI(N), ALFR(N), AR(IAR,N), BETA(N),
     *BI(IBI,N), BR(IBR,N), ZI(IZI,N), ZR(IZR,N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION ALMI, ALMR, BETM, C, D, EPSB, MAX, R, RI, SUM, T,
     * TERM,TI, XI, ZERO
      INTEGER EN, I, II, J, JJ, K, M, NA, NN
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION DSQRT
C     .. SUBROUTINE REFERENCES ..
C     A02ACF
C     ..
      DATA ZERO /0.0D0/
      IF (N.LE.1) GO TO 300
      EPSB = BR(N,1)
C     ---------- FOR EN=N STEP -1 UNTIL 2 DO -- ----------
      DO 80 NN=2,N
         EN = N + 2 - NN
         NA = EN - 1
         ALMR = ALFR(EN)
         ALMI = ALFI(EN)
         BETM = BETA(EN)
C     ---------- FOR I=EN-1 STEP -1 UNTIL 1 DO -- ----------
         DO 60 II=1,NA
            I = EN - II
            R = ZERO
            RI = ZERO
            M = I + 1
C
            DO 40 J=M,EN
               T = BETM*AR(I,J) - ALMR*BR(I,J) + ALMI*BI(I,J)
               TI = BETM*AI(I,J) - ALMR*BI(I,J) - ALMI*BR(I,J)
               IF (J.EQ.EN) GO TO 20
               XI = T*BI(J,EN) + TI*BR(J,EN)
               T = T*BR(J,EN) - TI*BI(J,EN)
               TI = XI
   20          R = R + T
               RI = RI + TI
   40       CONTINUE
C
            T = ALMR*BETA(I) - BETM*ALFR(I)
            TI = ALMI*BETA(I) - BETM*ALFI(I)
            IF (T.EQ.ZERO .AND. TI.EQ.ZERO) T = EPSB
            CALL A02ACF(R, RI, T, TI, BR(I,EN), BI(I,EN))
   60    CONTINUE
C
   80 CONTINUE
C     END BACK SUBSTITUTION.
C     TRANSFORM THE ORIGINAL COORDINATE SYSTEM.
C     FOR J=N STEP -1 UNTIL 2 DO
      DO 140 JJ=2,N
         J = N + 2 - JJ
         M = J - 1
C
         DO 120 I=1,N
C
            DO 100 K=1,M
               ZR(I,J) = ZR(I,J) + ZR(I,K)*BR(K,J) - ZI(I,K)*BI(K,J)
               ZI(I,J) = ZI(I,J) + ZR(I,K)*BI(K,J) + ZI(I,K)*BR(K,J)
  100       CONTINUE
C
  120    CONTINUE
  140 CONTINUE
C     NORMALIZE SO THAT THE SUM OF SQUARES OF THE MODULI OF THE
C     COMPONENTS IS EQUAL TO 1.0 AND THE COMPONENT OF LARGEST
C     MODULUS IS REAL.
      DO 280 I=1,N
         SUM = ZERO
         MAX = ZERO
         DO 180 J=1,N
            IF (DABS(ZR(J,I)).LE.MAX) GO TO 160
            MAX = DABS(ZR(J,I))
  160       IF (DABS(ZI(J,I)).LE.MAX) GO TO 180
            MAX = DABS(ZI(J,I))
  180    CONTINUE
         DO 200 J=1,N
            ZR(J,I) = ZR(J,I)/MAX
            ZI(J,I) = ZI(J,I)/MAX
  200    CONTINUE
         MAX = ZERO
         DO 240 J=1,N
            TERM = ZR(J,I)**2 + ZI(J,I)**2
            SUM = SUM + TERM
            IF (TERM.LE.MAX) GO TO 220
            MAX = TERM
            C = ZR(J,I)
            D = -ZI(J,I)
  220       CONTINUE
  240    CONTINUE
         SUM = SUM*(C**2+D**2)
         SUM = DSQRT(SUM)
         DO 260 J=1,N
            TERM = ZR(J,I)
            ZR(J,I) = (ZR(J,I)*C-ZI(J,I)*D)/SUM
            ZI(J,I) = (D*TERM+C*ZI(J,I))/SUM
  260    CONTINUE
  280 CONTINUE
C
  300 RETURN
      END
      SUBROUTINE F04JGT(N, X, SCALE, SUMSQ, TINY, UNDFLW)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (SCLSQS)
C
C     F04JGT RETURNS THE VALUES SCL AND SUM SUCH THAT
C
C     (SCL**2)*SUM = X(1)**2+X(2)**2+...+X(N)**2+(SCALE**2)*SUMSQ .
C
C     SCL IS OVERWRITTEN ON SCALE AND SUM IS OVERWRITTEN ON SUMSQ.
C
C     THE SUPPLIED VALUE OF SUMSQ IS ASSUMED TO BE AT LEAST
C     UNITY IN WHICH CASE SUM WILL SATISFY THE BOUNDS
C
C     1.0 .LE. SUM .LE. SUMSQ+N .
C
C     ONLY ONE PASS THROUGH THE VECTOR X IS MADE.
C
C     TINY MUST BE SUCH THAT
C
C     TINY = SQRT(X02AGF) ,
C
C     WHERE X02AGF IS THE SMALL VALUE RETURNED FROM ROUTINE X02AGF.
C
C     UNDFLW MUST BE THE VALUE RETURNED BY X02DAF
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION SCALE, SUMSQ, TINY
      INTEGER N
      LOGICAL UNDFLW
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION X(N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION ABSXI, Q
      INTEGER I
C     ..
      IF (UNDFLW) GO TO 60
C
      DO 40 I=1,N
         IF (X(I).EQ.0.0D0) GO TO 40
C
         ABSXI = DABS(X(I))
         IF (SCALE.GE.ABSXI) GO TO 20
C
         SUMSQ = 1.0D0 + SUMSQ*(SCALE/ABSXI)**2
         SCALE = ABSXI
         GO TO 40
C
   20    SUMSQ = SUMSQ + (ABSXI/SCALE)**2
C
   40 CONTINUE
C
      RETURN
C
   60 DO 100 I=1,N
         IF (X(I).EQ.0.0D0) GO TO 100
C
         ABSXI = DABS(X(I))
         Q = 0.0D0
         IF (SCALE.LT.ABSXI) GO TO 80
C
         IF (SCALE.GT.TINY) Q = SCALE*TINY
         IF (ABSXI.GE.Q) SUMSQ = SUMSQ + (ABSXI/SCALE)**2
         GO TO 100
C
   80    IF (ABSXI.GT.TINY) Q = ABSXI*TINY
         IF (SCALE.GE.Q) SUMSQ = 1.0D0 + SUMSQ*(SCALE/ABSXI)**2
         SCALE = ABSXI
C
  100 CONTINUE
C
      RETURN
      END
      DOUBLE PRECISION FUNCTION F04JGU(SCALE, SUMSQ, BIG)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (TWONRM)
C
C     F04JGU RETURNS THE VALUE
C
C     F04JGU = SCALE*SQRT(SUMSQ) .
C
C     SCALE IS ASSUMED TO BE NON-NEGATIVE AND SUMSQ IS ASSUMED
C     TO BE AT LEAST UNITY.
C
C     BIG MUST BE GIVEN BY
C
C     BIG = 1.0/X02AGF ,
C
C     WHERE X02AGF IS THE SMALL REAL VALUE RETURNED FROM
C     ROUTINE X02AGF.
C
C     F04JGU IS USED IN CONJUNCTION WITH F04JGT BY VARIOUS
C     EUCLIDEAN NORM ROUTINES.
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION BIG, SCALE, SUMSQ
C     ..
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION DSQRT
C     ..
      IF (SCALE.GE.BIG/SUMSQ) GO TO 20
      F04JGU = SCALE*DSQRT(SUMSQ)
      RETURN
C
   20 F04JGU = BIG
      RETURN
      END
      DOUBLE PRECISION FUNCTION F04JGV(N, X, TINY, BIG)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (VENORM)
C
C     REAL FUNCTION F04JGV RETURNS THE VALUE OF THE EUCLIDEAN
C     LENGTH OF THE N ELEMENT VECTOR X. F04JGV IS DEFINED AS
C
C     F04JGV = SQRT(X(1)**2+X(2)**2+...+X(N)**2).
C
C     TINY AND BIG MUST BE GIVEN BY
C
C     TINY = SQRT(X02AGF)   AND   BIG = 1.0/X02AGF
C
C     WHERE X02AGF IS THE SMALL REAL VALUE RETURNED FROM
C     ROUTINE X02AGF.
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION BIG, TINY
      INTEGER N
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION X(N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION SCALE, SUMSQ
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION F04JGU
      LOGICAL X02DAF
C     .. SUBROUTINE REFERENCES ..
C     F04JGT
C     ..
      SCALE = 0.0D0
      SUMSQ = 1.0D0
C
      CALL F04JGT(N, X, SCALE, SUMSQ, TINY, X02DAF(0.0D0))
C
      F04JGV = F04JGU(SCALE,SUMSQ,BIG)
C
      RETURN
      END
      DOUBLE PRECISION FUNCTION F04JGW(N, X)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (V2NORM)
C
C     REAL FUNCTION F04JGW RETURNS THE VALUE OF THE EUCLIDEAN
C     LENGTH OF THE N ELEMENT VECTOR X. F04JGW IS DEFINED AS
C
C     F04JGW = SQRT(X(1)**2+X(2)**2+...+X(N)**2).
C
C     .. SCALAR ARGUMENTS ..
      INTEGER N
C     .. ARRAY ARGUMENTS ..
      DOUBLE PRECISION X(N)
C     ..
C     .. LOCAL SCALARS ..
      DOUBLE PRECISION BIG, SMALL, TINY
C     .. FUNCTION REFERENCES ..
      DOUBLE PRECISION F04JGV, DSQRT, X02AGF
C     ..
      SMALL = X02AGF(SMALL)
      BIG = 1.0D0/SMALL
      TINY = DSQRT(SMALL)
C
      F04JGW = F04JGV(N,X,TINY,BIG)
C
      RETURN
      END
      INTEGER FUNCTION P01AAF(IFAIL, ERROR, SRNAME)
C     MARK 1 RELEASE.  NAG COPYRIGHT 1971
C     MARK 3 REVISED
C     MARK 4A REVISED, IER-45
C     MARK 4.5 REVISED
C     MARK 7 REVISED (DEC 1978)
C     MARK 11 REVISED (FEB 1984)
C     RETURNS THE VALUE OF ERROR OR TERMINATES THE PROGRAM.
      INTEGER ERROR, IFAIL, NOUT
C$P 1
      DOUBLE PRECISION SRNAME
C     TEST IF NO ERROR DETECTED
      IF (ERROR.EQ.0) GO TO 20
C     DETERMINE OUTPUT UNIT FOR MESSAGE
      CALL X04AAF (0,NOUT)
C     TEST FOR SOFT FAILURE
      IF (MOD(IFAIL,10).EQ.1) GO TO 10
C     HARD FAILURE
      WRITE (NOUT,99999) SRNAME, ERROR
C     ******************** IMPLEMENTATION NOTE ********************
C     THE FOLLOWING STOP STATEMENT MAY BE REPLACED BY A CALL TO AN
C     IMPLEMENTATION-DEPENDENT ROUTINE TO DISPLAY A MESSAGE AND/OR
C     ABORT THE PROGRAM.
C     *************************************************************
      STOP
C     SOFT FAIL
C     TEST IF ERROR MESSAGES SUPPRESSED
   10 IF (MOD(IFAIL/10,10).EQ.0) GO TO 20
      WRITE (NOUT,99999) SRNAME, ERROR
   20 P01AAF = ERROR
      RETURN
99999 FORMAT (1H0, 38HERROR DETECTED BY NAG LIBRARY ROUTINE , A8,
     * 11H - IFAIL = , I5//)
      END
      DOUBLE PRECISION FUNCTION X02AAF(X)
C     NAG COPYRIGHT 1975
C     MARK 4.5 RELEASE
C
C     THIS VERSION IS FROM EISPACK III, COURTESY OF NETLIB.
C     OBTAINED BY OLE H. NIELSEN
C
C     ESTIMATE UNIT ROUNDOFF IN QUANTITIES OF SIZE X.
C
      DOUBLE PRECISION A,B,C,EPS,X
C
C     THIS PROGRAM SHOULD FUNCTION PROPERLY ON ALL SYSTEMS
C     SATISFYING THE FOLLOWING TWO ASSUMPTIONS,
C        1.  THE BASE USED IN REPRESENTING FLOATING POINT
C            NUMBERS IS NOT A POWER OF THREE.
C        2.  THE QUANTITY  A  IN STATEMENT 10 IS REPRESENTED TO
C            THE ACCURACY USED IN FLOATING POINT VARIABLES
C            THAT ARE STORED IN MEMORY.
C     THE STATEMENT NUMBER 10 AND THE GO TO 10 ARE INTENDED TO
C     FORCE OPTIMIZING COMPILERS TO GENERATE CODE SATISFYING
C     ASSUMPTION 2.
C     UNDER THESE ASSUMPTIONS, IT SHOULD BE TRUE THAT,
C            A  IS NOT EXACTLY EQUAL TO FOUR-THIRDS,
C            B  HAS A ZERO FOR ITS LAST BIT OR DIGIT,
C            C  IS NOT EXACTLY EQUAL TO ONE,
C            EPS  MEASURES THE SEPARATION OF 1.0 FROM
C                 THE NEXT LARGER FLOATING POINT NUMBER.
C     THE DEVELOPERS OF EISPACK WOULD APPRECIATE BEING INFORMED
C     ABOUT ANY SYSTEMS WHERE THESE ASSUMPTIONS DO NOT HOLD.
C
C     THIS VERSION DATED 4/6/83.
C
      A = 4.0D0 / 3.0D0
   10 B = A - 1.0D0
      C = B + B + B
      EPS = DABS(C-1.0D0)
      IF (EPS .EQ. 0.0D0) GO TO 10
      X02AAF = EPS
C
      RETURN
      END
      DOUBLE PRECISION FUNCTION X02AGF(X)
C     MARK 8 RELEASE. NAG COPYRIGHT 1980.
C     ALTERED BY RICHARD NEEDS FOR USE WITH SEVERAL COMPUTERS
C
C     RETURNS THE SMALLEST POSITIVE FLOATING-POINT NUMBER  R
C     EXACTLY REPRESENTABLE ON THE COMPUTER SUCH THAT  -R, 1.0/R,
C     AND -1.0/R CAN ALL BE COMPUTED WITHOUT OVERFLOW OR UNDERFLOW.
C     ON MANY MACHINES THE CORRECT VALUE CAN BE DERIVED FROM THOSE
C     OF X02AAF, X02ABF AND X02ACF AS FOLLOWS
C
C     IF (X02ABF(X)*X02ACF(X).GE.1.0) X02AGF = X02ABF(X)
C     IF (X02ABF(X)*X02ACF(X).LT.1.0)
C    *                            X02AGF = (1.0+X02AAF(X))/X02ACF(X)
C
C     THE CORRECT VALUE SHOULD BE DEFINED AS A CONSTANT,
C     POSSIBLY IN SOME BINARY, OCTAL OR HEXADECIMAL REPRESENTATION,
C     AND INSERTED INTO THE ASSIGNMENT STATEMENT BELOW.
C
C     X IS A DUMMY ARGUMENT
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION X
C     ..
      COMMON /MACH1/ MACTYP
      COMMON /MACH2/ MACHIN(0:20)
      CHARACTER*7 MACHIN
      DOUBLE PRECISION Z(0:12)
      DOUBLE PRECISION X02AAF
C

#ifdef x86_64
      DATA Z(12) /0.1382D-75/
#else
C Unknown
      DATA Z(0) /0.1382D-75/
C IBM
      DATA Z(1) /0.1382D-75/
C CRAY-1 or X-MP
      DATA Z(2) /0.7335D-2465/
C VAX
      DATA Z(3) /5.9D-39/
C CDC
      DATA Z(4) /0.7335D-2465/
C UNIVAC = Sperry = Unisys
      DATA Z(5) /2.225074D-308/
C FPS
      DATA Z(6) /2.225074D-308/
C CRAY-2
      DATA Z(7) /0.7335D-2465/
C Fujitsu VP-100/200/400 (= Amdahl 1XXX = Siemens)
      DATA Z(8) /0.1382D-75/
C VAX + MAP attached processor
      DATA Z(9) /0.1382D-75/
C Generic UNIX (tested on SunOS3.4)
      DATA Z(10) /5.9D-39/
C Apollo
      DATA Z(11) /5.9D-39/
#endif
C
      X02AGF = Z(MACTYP)
C
      IF (MACTYP .LE. 0 .OR. MACTYP .GT. 12) THEN
        WRITE(6,*) '***WARNING*** X02AGF illegal MACTYP=',MACTYP
C       A FUDGE:
        X02AGF = X02AAF(X)
        ENDIF
      RETURN
      END
      LOGICAL FUNCTION X02DAF(X)
C     MARK 8 RELEASE. NAG COPYRIGHT 1980.
C
C     RETURNS .FALSE. IF THE SYSTEM SETS UNDERFLOWING QUANTITIES
C     TO ZERO, WITHOUT ANY ERROR INDICATION OR UNDESIRABLE WARNING
C     OR SYSTEM OVERHEAD.
C     RETURNS .TRUE. OTHERWISE, IN WHICH CASE CERTAIN LIBRARY
C     ROUTINES WILL TAKE SPECIAL PRECAUTIONS TO AVOID UNDERFLOW
C     (USUALLY AT SOME COST IN EFFICIENCY).
C
C     X IS A DUMMY ARGUMENT
C
C     .. SCALAR ARGUMENTS ..
      DOUBLE PRECISION X
C     ..
      X02DAF = .FALSE.
      RETURN
      END
      SUBROUTINE X04AAF(I,NERR)
C     MARK 7 RELEASE. NAG COPYRIGHT 1978
C     MARK 7C REVISED IER-190 (MAY 1979)
C     IF I = 0, SETS NERR TO CURRENT ERROR MESSAGE UNIT NUMBER
C     (STORED IN NERR1).
C     IF I = 1, CHANGES CURRENT ERROR MESSAGE UNIT NUMBER TO
C     VALUE SPECIFIED BY NERR.
C
C     *** NOTE ***
C     THIS ROUTINE ASSUMES THAT THE VALUE OF NERR1 IS SAVED
C     BETWEEN CALLS.  IN SOME IMPLEMENTATIONS IT MAY BE
C     NECESSARY TO STORE NERR1 IN A LABELLED COMMON
C     BLOCK /AX04AA/ TO ACHIEVE THIS.
C
C     .. SCALAR ARGUMENTS ..
      INTEGER I, NERR
C     ..
C     .. LOCAL SCALARS ..
      INTEGER NERR1
C     ..
      DATA NERR1 /6/
      IF (I.EQ.0) NERR = NERR1
      IF (I.EQ.1) NERR1 = NERR
      RETURN
      END
