      SUBROUTINE VNLKKA (LSTRES,GK,I1,I2,IROW,
     +  POTPAR,POTTYP,NPARAM,
     +  STRFAC,IPLACE,NTYPMX,NDIM1,VOLUM,ULA,LREAL,
     +  UPRIM,STRESS,VK1K2)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     CALCULATE THE  N O N - L O C A L  CONTRIBUTION TO THE
C     MATRIX ELEMENT V(K,K') .
C     HAMANN-SCHLUTER-CHIANG NON-LOCAL POTENTIAL
C
C     Version using analytical evaluation of matrix elements.
C     Not well-vectorized.
C
C     WRITTEN  16-APR-1982 BY OHN.
C     MODIFIED 01-SEP-1982 TO INCLUDE STRESSES
C     MODIFIED 13-AUG-1985 FOR VECTORIZATION
C
C     INPUT:
C     LSTRES ........ LOGICAL SWITCH FOR CALCULATING STRESS TENSOR
C     GK ............ ARRAY CONTAINING THE LENGTHS AND VECTORS FOR (K+G)
C     I1,I2 ......... ELEMENTS OF THIS LIST TO BE CONSIDERED IN
C                     THE PRESENT CALL TO THE ROUTINE
C     POTPAR ........ POTENTIAL PARAMETERS - FOR DEFINITIONS
C                     SEE THE WAY POTPAR IS CONSTRUCTED IN THE
C                     SETTING-UP ROUTINE K213 (OR A SIMILAR ONE)
C     POTTYP ........ POTENTIAL TYPES (16,17,...)
C     NPARAM ........ NUMBER OF PARAMETERS
C     STRFAC ........ ATOMIC STRUCTURE FACTORS
C     IPLACE ........ LOCATION OF (G-G') IN LIST OF STRFAC,
C                     AS DETERMINED BY A PREVIOUS LOOKUP IN PSPT6
C     CUT-OFF:        IN THIS WAY THE CUT-OFF OF G**2, WHICH WAS
C                     FULFILLED IN "LOOKUP" IS ALSO APPLIED TO THE
C                     NON-LOCAL POTENTIAL.
C     NTYPMX,NDIM1 .. DIMENSIONS OF STRFAC
C     TY ............ INTEGERS DETERMINING THE TYPES OF ATOMS
C     NAT ........... NUMBER OF ATOMS IN TE UNIT CELL
C     ULA ........... LATTICE CONSTANT
C     OUTPUT:
C     UPRIM ......... MATRIX ELEMENTS FOR TYPES OF ATOMS (FOR FORCES)
C     STRESS ........ STRESS TENSOR MATRIX ELEMENT (UPPER TRIANGLE)
C     VK1K2 ......... V(K+G,K+G') MATRIX ELEMENT
C
C     METHOD:
C     THE GAUSSIANS TO BE SUMMED OVER ARE ARRANGED IN ARRAYS
C     CONTAINING THE RELEVANT INFORMATION:
C     RLA2,RLA3,ALAR3,IATTYP,LPLUS1,NEWSUM.
C     THEN A SIMPLE DO-LOOP CAN BE PERFORMED.
C     CALCULATION OF BESSEL FUNCTIONS IS CAREFULLY OPTIMIZED FOR SPEED.
C     IT WAS FOUND THAT THEY ARE VERY HARD TO CALCULATE NUMERICALLY,
C     SO WE HAD TO DIVIDE THE X-VALUES INTO 3 DIFFERENT RANGES (3-MAY-82
C
      PARAMETER ( NLMAX = 3, MAXCNT=100 )
C     NLMAX MUST NOT BE INCREASED OVER 3 WITHOUT REPROGRAMMING THE
C     BESSEL AND LEGENDRE FUNCTIONS BELOW
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI
C
      LOGICAL LSTRES, LREAL
      DOUBLE PRECISION POTPAR(NTYPMX,NPARAM)
      REAL GK(4,*), UPRIM(NTYPMX,*)
      REAL ULA, VOLUM
      INTEGER POTTYP(NTYPMX), IPLACE(*)
      COMPLEX STRFAC(NTYPMX,NDIM1)
      LOGICAL INIT,GKGT0,LPOT16,LPOT17,LREALI
C
C-----------------------------------------------------------------------
C     For real Hamiltonians
      REAL VK1K2(*), STRESS(6,*)
      PARAMETER (LREALI = .TRUE.)
C-----------------------------------------------------------------------
C     For complex Hamiltonians
C     COMPLEX VK1K2(*), STRESS(6,*)
C     PARAMETER (LREALI = .FALSE.)
C-----------------------------------------------------------------------
      COMPLEX    SGG,V12,SS(6)
C
C     GAUSSIAN PARAMETERS
      DIMENSION RLA2(MAXCNT),RLA3(MAXCNT),ALAR3(MAXCNT),A3LAR3(MAXCNT),
     +          PL(NLMAX),PLP(NLMAX),BESSEL(3)
      INTEGER   IATTYP(MAXCNT),LPLUS1(MAXCNT),NEWSUM(MAXCNT)
C
      SAVE RLA2,RLA3,ALAR3,A3LAR3,PL,PLP,IATTYP,LPLUS1,NEWSUM,ICOUNT,
     +     IBESSL,INIT,VOL,LPOT16,LPOT17,III,JJJ,DIJ
C
C     SYMMETRIC PART OF TENSORS: INDEX FUNCTIONS
      DIMENSION COSEIJ(6),F1(6),F2(6),DIJ(6)
C     INDEXING UPPER TRIANGLE OF STRESS TENSOR:
      INTEGER III(6),JJJ(6)
      DATA III /1,1,1, 2,2, 3/, JJJ /1,2,3, 2,3, 3/
C     KRONECKER DELTA:
      DATA DIJ /1.0,0.0,0.0, 1.0,0.0, 1.0/
C     LEGENDRE POLYNOMIALS:
      DATA PL(1) /1.0/, PLP(1),PLP(2) /0.0,3.0/
      DATA INIT,LPOT16,LPOT17 /3* .FALSE./
C-----------------------------------------------------------------------
C
      IF (INIT) GOTO 290
C
C     FIRST TIME CALLING VNLKK
C
      IF (LREAL .NEQV. LREALI) THEN
        WRITE (IOUT,*) 'VNLKK *** ERROR *** LREAL, LREALI=',
     +    LREAL, LREALI
        CALL EXIT
        ENDIF
      INIT = .TRUE.
C     CONVERSION FACTOR FROM UNITS A.U. TO RYDBERGS:
C     4*PI FROM THE MATRIX ELEMENT FORMULA
C     2 TO CONVERT HARTREES INTO RYDBERGS
C     VOLUME IN ATOMIC UNITS
C     SQRT(PI)/4 FROM THE REWRITTEN F-FUNCTION
      VOL = VOLUM*(ULA/ABOHR)**3
      CONV = 4.0D0*PI*2.0D0/VOL*SPI/4.0D0
C     CONVERSION OF G**2 INTO A.U. (RYDBERGS)
      CONV1 = (2.0D0*PI*ABOHR/ULA)**2
C     POT16 OR POT17 ?
      LPOT16 = .FALSE.
      LPOT17 = .FALSE.
C     INITIALIZE BESSL:
      CALL BESSL0
C
      DO 150 ICOUNT  = 1,MAXCNT
        IATTYP(ICOUNT) = 0
        LPLUS1(ICOUNT) = 0
        NEWSUM(ICOUNT) = 0
        RLA2(ICOUNT)   = 0.0D0
        RLA3(ICOUNT)   = 0.0D0
        ALAR3(ICOUNT)  = 0.0D0
        A3LAR3(ICOUNT) = 0.0D0
150     CONTINUE
C     DECODE POTENTIAL PARAMETERS
C     ICOUNT IS THE INDEX COUNTING THE GAUSSIANS
      ICOUNT = 0
C
      DO 240 ITYPE = 1,NTYPMX
C
      IF (POTTYP(ITYPE) .EQ. 16) THEN
C
C     POTENTIAL FROM BACHELET ET AL., PHYS. REV. B 24, 4745 (1981)
C
      IF (LPOT17) GOTO 440
      LPOT16 = .TRUE.
      IBESSL = 1
C     MAXIMUM L-VALUE PLUS 1
      LM1 = NINT(POTPAR(ITYPE,3)) + 1
      IF (LM1 .GT. NLMAX) GOTO 380
C     SKIP THE LOCAL-POTENTIAL PARAMETERS
      IGAUS = NINT(POTPAR(ITYPE,4))
      IPARAM = 4 + IGAUS*2
C
      DO 230 IL = 1,LM1
C
      IPARAM = IPARAM + 1
      IGAUS  = NINT(POTPAR(ITYPE,IPARAM))
      IF (IGAUS .EQ. 0) GOTO 230
C
      DO 220 NG = 1,IGAUS
        ICOUNT = ICOUNT + 1
        IF (ICOUNT .GT. MAXCNT) GOTO 350
        IATTYP(ICOUNT) = ITYPE
        LPLUS1(ICOUNT) = IL
        ALAR3(ICOUNT)  = POTPAR(ITYPE,IPARAM + 1)
C       R**2
        RLA2(ICOUNT)   = 1.0D0/POTPAR(ITYPE,IPARAM + 2)
C       R**3
        RLA3(ICOUNT)   = POTPAR(ITYPE,IPARAM + 2)**(- 1.5 D0)
        IPARAM = IPARAM + 2
220     CONTINUE
      NEWSUM(ICOUNT) = 1
230   CONTINUE
      NEWSUM(ICOUNT) = 2
C
      ELSE IF (POTTYP(ITYPE) .EQ. 17) THEN
C
C     POTENTIAL FROM BACHELET ET AL., PHYS. REV. B 26, 4199 (1982).
C
      IF (LPOT16) GOTO 440
      LPOT17 = .TRUE.
      IBESSL = 2
      IPARAM = 6
C     MAXIMUM L-VALUE PLUS 1
      LMAX = NINT(POTPAR(ITYPE,IPARAM))
C     THE ANGULAR MOMENTUM CHOSEN AS THE LOCAL POTENTIAL
      LOCAL = NINT(POTPAR(ITYPE,16 + 9*LMAX))
      WRITE (IOUT,171) ITYPE,LOCAL
171   FORMAT(' VNLKK - LOCAL POTENTIAL FOR ATOMIC TYPE',I3,
     +' IS DETERMINED BY L =',I3)
      LM1  = LMAX + 1
      IF (LM1 .GT. NLMAX) GOTO 380
      NGAUS = 3
      IF (LOCAL .GE. 0) NGAUS = 6
C
      DO 179 IL = 1,LM1
      IF (IL - 1 .EQ. LOCAL) GOTO 179
      IPARAM = 6 + (IL - 1)*9
      FAC = 1.0D0
      DO 177 IG = 1,NGAUS
        IF (IG .EQ. 4) THEN
          FAC = - 1.0D0
          IPARAM = 6 + LOCAL*9 - 3
          ENDIF
        ICOUNT = ICOUNT + 1
        IF (ICOUNT .GT. MAXCNT) GOTO 350
        IATTYP(ICOUNT) = ITYPE
        LPLUS1(ICOUNT) = IL
C       R**2
        RLA2(ICOUNT)   = 1.0D0/POTPAR(ITYPE,IPARAM + IG)
C       R**3
        RLA3(ICOUNT)   = POTPAR(ITYPE,IPARAM + IG)**(- 1.5 D0)
C       A(I) AND A(I+3)
        ALAR3(ICOUNT)  = POTPAR(ITYPE,IPARAM + 3 + IG) * FAC
        A3LAR3(ICOUNT) = POTPAR(ITYPE,IPARAM + 6 + IG) * FAC
177     CONTINUE
      NEWSUM(ICOUNT) = 1
179   CONTINUE
      NEWSUM(ICOUNT) = 2
C
      ELSE IF (POTTYP(ITYPE) .EQ. 10) THEN
C       JELLIUM: DO NOTHING
C
      ELSE IF (POTTYP(ITYPE) .EQ. 11) THEN
C       COULOMB POTENTIAL: DO NOTHING
C
      ELSE IF (POTTYP(ITYPE) .EQ.  0) THEN
C       DO NOTHING
C
      ELSE
C       ILLEGAL POTENTIAL TYPE
        WRITE (IOUT,*) 'VNLKK (ANALYTIC): ILLEGAL POTENTIAL TYPE=',
     +    POTTYP(ITYPE)
        CALL EXIT
        ENDIF
C
240   CONTINUE
C
C     PRINT OUT PARAMETERS
C
      WRITE(IUNIT8,250)
250   FORMAT(' SUBROUTINE VNLKK --- PARAMETERS ---'/
     +' TYPE L ALPHAI      C(I) OR A(I)       A(I+3)',T53,'NEWSUM')
      DO 270 IC=1,ICOUNT
      WRITE(IUNIT8,260) IATTYP(IC), LPLUS1(IC)-1,
     +          1.0D0/RLA2(IC),ALAR3(IC),A3LAR3(IC),NEWSUM(IC)
260   FORMAT(1X,I2,3X,I1,F7.3,3X,2F16.5,I6)
C
C     AT THIS PLACE WE SCALE THE PARAMETER A(L,ALPHA) BY THE
C     ENERGY-CONVERSION FACTOR AND R**3
      ALAR3(IC)  = ALAR3(IC)  * CONV * RLA3(IC)
C     A(I+3) CONTAINS ALSO THE 1/ALPHA FACTOR
      A3LAR3(IC) = A3LAR3(IC) * RLA2(IC) * CONV * RLA3(IC)
C     RLA2 IS SCALED SO THAT GK1GK2*R2 IS DIMENSIONLESS
      RLA2(IC)   = RLA2(IC) * CONV1
      IF (RLA2(IC) .LT. 1.0E-6) THEN
C       ERROR: CANNOT HAVE A NEGATIVE (OR ZERO) RADIUS.
        WRITE (IOUT,265) IC,RLA2(IC)
265     FORMAT('0SUBROUTINE VNLKK - GAUSSIAN NO.',I5,
     +  ' RADIUS**2=',E15.6,' UNREALISTIC')
        CALL EXIT
        ENDIF
C
270   CONTINUE
C
C-----------------------------------------------------------------------
C
290   DO 500 IG1 = I1, I2
C
      IPL    = IPLACE(IG1)
      V12    = 0.0
      GK1LEN = GK(4,IG1)
      GK2LEN = GK(4,IROW)
      GKDIFF = - 0.25D0*(GK1LEN - GK2LEN)**2
      GKSUM  = - 0.25D0*(GK1LEN**2 + GK2LEN**2)
      GK1GK2 = GK1LEN*GK2LEN
      GKGT0  = GK1GK2 .GT. 1.0E-6
C
      IF (GKGT0) THEN
C       THE ANGLE BETWEEN K AND K'
C       (DPROD IS THE DOUBLE PRECISION PRODUCT OF TWO NUMBERS)
        COSINE = ( DPROD(GK(1,IG1),GK(1,IROW)) +
     +             DPROD(GK(2,IG1),GK(2,IROW)) +
     +             DPROD(GK(3,IG1),GK(3,IROW))  ) /GK1GK2
      ELSE
C       GK1 AND/OR GK2 = 0, COSINE IS ARBITRARY
        COSINE = 0.0D0
        ENDIF
C     (2*L+1) * PL(COSINE)
C     PL(1) = 1.0 (IS DEFINED IN A DATA STATEMENT)
      PL(2) = 3.0D0*COSINE
      PL(3) = 7.5D0*COSINE*COSINE - 2.5D0
C
      IF (LSTRES) GOTO 301
C
C     MATRIX ELEMENT CALCULATION (NO STRESS)
C
C     LOOP OVER GAUSSIANS
C
      AF  = 0.0D0
      AFP = 0.0D0
C
      DO 320 IC = 1,ICOUNT
C
      IL   = LPLUS1(IC)
C     CALCULATE EXP*BESSEL FUNCTION (ARG = 2X = K*K'*R**2)
      RR2  = RLA2(IC)
      ARG  = GK1GK2*RR2
      CALL BESSL(ARG,IL,IBESSL,BESSEL)
C.....THE FUNCTION F, EXCEPT FOR R**3*SQRT(PI)/4 (SEE ABOVE).
      FEXP = EXP( RR2*GKDIFF )
      AF   = AF + ALAR3(IC) * FEXP *BESSEL(1)
      IF (LPOT17) THEN
C       POT17: ADD TERM FROM R**2 * GAUSSIAN
        R2G  = (1.5D0 + RR2*GKSUM)*BESSEL(1) + 0.5D0*ARG*BESSEL(2)
        AF   = AF + A3LAR3(IC) * FEXP * R2G
        ENDIF
      IF (NEWSUM(IC) .GT. 0) THEN
C       NEXT VALUE OF L IS DIFFERENT - SUM UP CONTRIBUTION
        AFP  = AFP + AF*PL(IL)
        AF   = 0.0D0
        IF (NEWSUM(IC) .GT. 1) THEN
C         NEXT ATOMIC TYPE IS DIFFERENT - SUM UP CONTRIBUTION
          ITYPE = IATTYP(IC)
          UPRIM(ITYPE,IG1) = AFP
          SGG   = STRFAC(ITYPE,IPL)
          V12   = V12 + SNGL(AFP)*SGG
          AFP   = 0.0D0
          ENDIF
        ENDIF
320   CONTINUE
      VK1K2(IG1) = V12
C
      GOTO 500
C
C.......................................................................
C
C     CALCULATION INCLUDING STRESS
C
C     SETTING UP (K+G)-TENSORS FOR THE STRESS
C     (2*L+1) * PL'(COSINE)
C     PLP(1) = 0.0 (IS DEFINED IN A DATA STATEMENT)
C     PLP(2) = 3.0 (IS DEFINED IN A DATA STATEMENT)
301   PLP(3) = 15.0D0*COSINE
C     AT PRESENT, L=2 IS MAXIMUM
      G1122  = 0.0D0
      DO 305 K = 1,6
C       INITIALIZE STRESS ARRAY
        SS(K) = (0.0D0,0.0D0)
C       FOR SPEED, WE USE A SINGLE INDEX OVER THE UPPER TRIANGLE, ONLY.
        I      = III(K)
        G1I    = GK(I,IG1)
        G2I    = GK(I,IROW)
        J      = JJJ(K)
        G1J    = GK(J,IG1)
        G2J    = GK(J,IROW)
        IF (GKGT0) THEN
C         DERIVATIVE OF COSINE W.R.T. EPS(I,J)
          G1122  = G1I*G1J/GK1LEN**2 + G2I*G2J/GK2LEN**2
          COSEIJ(K) = G1122*COSINE - (G1I*G2J + G1J*G2I)/GK1GK2
          F2(K)  = - 0.5D0*G1122
        ELSE
C         GK1 AND/OR GK2 ARE ZERO:
          COSEIJ(K) = 0.0D0
          F2(K)     = 0.0D0
          ENDIF
        F1(K)  = 0.5D0*(G1I*G1J + G2I*G2J)
305     CONTINUE
      AF    = 0.0D0
      AFP   = 0.0D0
      AFPP  = 0.0D0
      SUM1  = 0.0D0
      SUM2  = 0.0D0
      SUM1P = 0.0D0
      SUM2P = 0.0D0
C
C     LOOP OVER GAUSSIANS
C
      DO 340 IC = 1,ICOUNT
C
      IL    = LPLUS1(IC)
      RR2   = RLA2(IC)
C     CALCULATE EXP*BESSEL FUNCTION (ARG = 2X = K*K'*R**2)
      ARG   = GK1GK2*RR2
      CALL BESSL(ARG,IL,IBESSL + 1,BESSEL)
C.....THE FUNCTION F, AND D(F)/D(EIJ)
      FEXP  = EXP( RR2 * GKDIFF )
      TEMP  = ALAR3(IC) * FEXP
      SUM2  = SUM2 + TEMP * ARG * BESSEL(2)
      TEMP  = TEMP * BESSEL(1)
      AF    = AF   + TEMP
      SUM1  = SUM1 + TEMP * RR2
      IF (LPOT17) THEN
C       POT17: ADD TERM FROM R**2 * GAUSSIAN
        TEMP  = A3LAR3(IC) * FEXP
        P1    = 1.5D0 + RR2*GKSUM
        ARG2  = 0.5D0 * ARG
        R2G   = P1*BESSEL(1) + ARG2*BESSEL(2)
        AF    = AF   + TEMP * R2G
        SUM1  = SUM1 + TEMP*RR2*(BESSEL(1) + R2G)
        SUM2 = SUM2 + TEMP*ARG*((P1 + 1.0D0)*BESSEL(2) + ARG2*BESSEL(3))
        ENDIF
      IF (NEWSUM(IC) .GT. 0) THEN
C       NEXT VALUE OF L IS DIFFERENT - SUM UP CONTRIBUTION
        AFP   = AFP  + AF*PL(IL)
        AFPP  = AFPP + AF*PLP(IL)
        AF    = 0.0D0
        SUM1P = SUM1P + SUM1*PL(IL)
        SUM2P = SUM2P + SUM2*PL(IL)
        SUM1  = 0.0D0
        SUM2  = 0.0D0
        IF (NEWSUM(IC) .GT. 1) THEN
C         NEXT ATOMIC TYPE IS DIFFERENT - SUM UP CONTRIBUTION
          ITYPE = IATTYP(IC)
          UPRIM(ITYPE,IG1) = AFP
          SGG   = STRFAC(ITYPE,IPL)
          V12   = V12 + SNGL(AFP)*SGG
          DO 335 K = 1,6
            SS(K) = SS(K) + SGG * SNGL(
     +      (AFPP*COSEIJ(K) + SUM1P*F1(K) + SUM2P*F2(K) - AFP*DIJ(K)))
335         CONTINUE
          AFP   = 0.0D0
          AFPP  = 0.0D0
          SUM1P = 0.0D0
          SUM2P = 0.0D0
          ENDIF
        ENDIF
340   CONTINUE
C
      VK1K2(IG1) = V12
      DO 345 K = 1,6
        STRESS(K,IG1) = SS(K)
345     CONTINUE
C
500   CONTINUE
C
      RETURN
C-----------------------------------------------------------------------
C
C     ERROR MESSAGES
C
350   WRITE(IOUT,360)
360   FORMAT(' SUBROUTINE VNLKK *** FATAL ERROR ***')
      WRITE(IOUT,370) MAXCNT
370   FORMAT(' NUMBER OF GAUSSIANS EXCEEDS MAXCNT = ',I6)
      CALL EXIT
C
380   WRITE(IOUT,360)
      WRITE(IOUT,390) LMAX
390   FORMAT(' LMAX = ',I5,' DOES NOT FIT INTO ARRAYS')
      CALL EXIT
C
440   WRITE (IOUT,360)
C     MIXING POT16 AND POT17 POTENTIALS
      WRITE (IOUT,*) 'MIXING POT16 AND POT17 POTENTIALS IS NOT FORESEEN'
      CALL EXIT
C
      RETURN
      END
      SUBROUTINE BESSL (ARG,IL,ISWITC,BESSEL)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     MODIFIED SPHERICAL BESSEL FUNCTION, IN O.H.N.'S NOTATION
C
C     ARG ........ IS THE 2*ARGUMENT OF BESSEL FUNCTION (ARG = 2*X)
C     IL ......... (L+1), WHERE L IS ANGULAR MOMENTUM
C                  (AT PRESENT, L=2 IS MAXIMUM)
C     ISWITC ..... BESSEL(1..ISWITCH) IS CALCULATED
C     BESSEL ..... BESSEL FUNCTION ARRAY(1..3)
C                  1 = I(X); 2 = (I + I'); 3 = ((I + I') + (I + I')')
C
C.....FILES
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C
      DIMENSION BESSEL(3)
      DOUBLE PRECISION DBES12,DBES32,DBES52,DARG1
      DIMENSION TAYLOR(10,3,3)
      SAVE TAYLOR
C-----------------------------------------------------------------------
C     IF (IL .LT. 1 .OR. IL .GT. 3) GOTO 300
C     IF (ISWITC .LT. 1 .OR. ISWITC .GT. 3) GOTO 300
      DO 100 I = 1, ISWITC
        BESSEL(I) = 0.0D0
100     CONTINUE
C
      IF (ARG .GT. 0.1) GOTO 180
C
C     TAYLOR SERIES EXPANSION (REMEMBER ARG = 2*X)
C
      ARGN   = 1.0D0
      DO 130 N = 1,6
        DO 120 I = 1, ISWITC
          BESSEL(I) = BESSEL(I) + ARGN*TAYLOR(N,I,IL)
120       CONTINUE
        ARGN   = ARGN*ARG
130     CONTINUE
      RETURN
C
C     DOUBLE PRECISION EVALUATION
C
C     1/ARG (FOR FASTER EXECUTION)
180   DARG1  = 1.0D0/DBLE(ARG)
      IF (IL - 2) 190,200,210
C.....L = 0
190   DBES12    = DARG1 - DARG1*DEXP( DBLE(-ARG))
      BESSEL(1) = DBES12
      IF (ISWITC .LE. 1) RETURN
      DBES32    = DARG1 - DARG1*DBES12
      DBES32    = DBES32 + DBES32 - DBES12
      BESSEL(2) = DBES32
      IF (ISWITC .LE. 2) RETURN
      BESSEL(3) = DBES12 - 4.0D0*DARG1*DBES32
      RETURN
C.....L = 1
200   DBES12    = DARG1 - DARG1*DEXP( DBLE(-ARG))
      DBES32    = DARG1 - DARG1*DBES12
      DBES32    = DBES32 + DBES32 - DBES12
      BESSEL(1) = DBES32
      IF (ISWITC .LE. 1) RETURN
      BESSEL(2) = DBES12 - 4.0D0*DARG1*DBES32
      IF (ISWITC .LE. 2) RETURN
      DBES52    = DBES12 - 6.0D0*DARG1*DBES32
      BESSEL(3) = DBES32 - 4.0D0*DARG1*DBES52
      RETURN
C.....L = 2
210   DBES12    = DARG1 - DARG1*DEXP( DBLE(-ARG))
      DBES32    = DARG1 - DARG1*DBES12
      DBES32    = DBES32 + DBES32 - DBES12
      DBES52    = DBES12 - 6.0D0*DARG1*DBES32
      BESSEL(1) = DBES52
      IF (ISWITC .LE. 1) RETURN
      BESSEL(2) = DBES32 - 6.0D0*DARG1*DBES52
      IF (ISWITC .LE. 1) RETURN
      BESSEL(3) = (1.D0 + 48.D0*DARG1*DARG1)*DBES52 - 4.D0*DARG1*DBES32
      RETURN
C-----------------------------------------------------------------------
C
      ENTRY BESSL0
C
C     SET UP TAYLOR EXPANSION COEFFICIENTS
C
C     I(N+1/2):
C
      IFAC = 1
      ISIGN = -1
      DO 270 IN = 1,10
        IFAC = IFAC * IN
        ISIGN = - ISIGN
        TAYLOR(IN,1,1) = DBLE(ISIGN)/DBLE(IFAC)
        TAYLOR(IN,1,2) = 0.0D0
        TAYLOR(IN,1,3) = 0.0D0
          IF (IN .LT. 3) GOTO 270
        TAYLOR(IN-1,1,2) = DBLE(ISIGN*(IN-2))/DBLE(IFAC)
          IF (IN .LT. 5) GOTO 270
        TAYLOR(IN-2,1,3) = DBLE(ISIGN*(IN-3)*(IN-4))/DBLE(IFAC)
270     CONTINUE
C     WRITE (IOUT,271) ((1.0D0/(TAYLOR(IN,1,I)+1E-30),I=1,3),IN=1,10)
C271  FORMAT(' 1/TAYLOR SERIES COEFFICIENTS:'/10(1X,3G20.10/))
C
C     I(N+1/2)' AND I(N+1/2)'': ANALYTIC DIFFERENTIATION
      DO 280 ID = 2,3
      DO 280 LL = 1,3
      DO 280 IN = 1,(11-ID)
        TAYLOR(IN,ID,LL) = 2.0D0 * TAYLOR(IN+1,ID-1,LL)*DBLE(IN)
280     CONTINUE
C     WRITE (IOUT,*) 'DERIVATIVE:'
C     WRITE (IOUT,271) ((1.0D0/(TAYLOR(IN,2,I)+1E-30),I=1,3),IN=1,10)
C     WRITE (IOUT,*) 'SECOND DERIVATIVE:'
C     WRITE (IOUT,271) ((1.0D0/(TAYLOR(IN,3,I)+1E-30),I=1,3),IN=1,10)
C
C     COMBINE COEFFICIENTS FOR (I+I') AND ((I+I')+(I+I')'):
      DO 290 J = 1,3
      DO 290 I = 1,6
      TAYLOR(I,3,J) = TAYLOR(I,1,J) + 2.D0*TAYLOR(I,2,J) + TAYLOR(I,3,J)
      TAYLOR(I,2,J) = TAYLOR(I,1,J) + TAYLOR(I,2,J)
290   CONTINUE
      RETURN
      END
