      SUBROUTINE VNLRED (ITYPE,POTFIL,POTPAR,VNLIJ,VOLUM,ULA,   
     +                   NTYPMX,NPARAM,NDIM20,NLMAX,NSPIN)  
C   
C     READ IN THE NONLOCAL MATRIX ELEMENTS FROM FILES   
C     OF FOURIER-TRANSFORMED POTENTIALS.
C   
C     ITYPE ....... ATOMIC TYPE 
C     POTFIL ...... NAME OF ATOMIC FILE 
C     POTPAR ...... POTENTIAL PARAMETERS
C     VNLIJ ....... NON-LOCAL MATRIX ELEMENTS   
C     VOLUM ....... UNIT CELL VOLUME
C     ULA ......... UNIT OF LENGTH  
C   
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)   
C   
      DOUBLE PRECISION POTPAR (NTYPMX,NPARAM)   
      REAL VOLUM,ULA
      REAL VNLIJ(0:NDIM20,0:NDIM20,NLMAX,NTYPMX,NSPIN)  
      CHARACTER*(*) POTFIL(NTYPMX)  
C   
      PARAMETER (MAXTIT=20) 
      CHARACTER*40 TITLE(MAXTIT)
      CHARACTER NAME*2, ICORR*2, IREL*3, IFCORE*4,  
     +  ICALC*2, CDTYPE*2, FILNAM*70
      DOUBLE PRECISION DUMMY(5) 
      LOGICAL LOPEN 
C.....FILES 
      COMMON /FILES/INPUT,IOUT,IN290,IN213,ISTORE,IUNIT7,IUNIT8,ISTRUC,
     +               IVNLKK,ISUMRY,IKPTS
C.....PHYSICAL AND MATHEMATICAL CONSTANTS   
      DOUBLE PRECISION ABOHR,RYEV,RYDERG,PI,SPI 
      COMMON /CONST/   ABOHR,RYEV,RYDERG,PI,SPI 
C.....WARNINGS: 
      COMMON /WARN/ IWARN   
C.....Machine types
      COMMON /MACH1/ MACTYP
      DATA NO,LO /2 * -1/   
C-----------------------------------------------------------------------
C   
      WRITE (IUNIT7,1030) ITYPE 
1030  FORMAT (/' VNLRED: NONLOCAL POTENTIALS FOR ITYPE=',I4)
      FILNAM = POTFIL(ITYPE)
      WRITE (IOUT,*) 'FILE:',FILNAM 
      IUNIT  = 20 + ITYPE   
      IF (LENSTR(FILNAM) .LE. 0) THEN   
        WRITE (IOUT,1000) FILNAM
1000    FORMAT('0SUBROUTINE VNLRED *** ERROR ***'/  
     +    ' NO FILENAME WAS GIVEN, FILNAM=',A)  
        CALL EXIT   
        ENDIF   
C   
      IRECTP = 0
      NTITLE = MAXTIT   
      INDEX  = 0
C     LIST OF ANGULAR MOMENTA:  
      DO 110 L = 0, NLMAX   
        POTPAR (ITYPE, 20 + L) = - 1.0  
110     CONTINUE
C   
C     OPEN THE FILE 
C   
      IFIL = LENSTR(FILNAM) 
      INQUIRE (FILE = FILNAM(1:IFIL), OPENED = LOPEN)   
      IF (LOPEN) THEN   
        REWIND IUNIT
      ELSE  
C	Other machines don't like Apollo specials
C       IF (MACTYP .EQ. 11) THEN
C         Apollo: non-ANSI RECL:
C         OPEN (UNIT = IUNIT, FILE = FILNAM(1:IFIL), STATUS = 'OLD',  
C    +        FORM = 'UNFORMATTED', RECL=4*NDIM20**2)
C       ELSE
          OPEN (UNIT = IUNIT, FILE = FILNAM(1:IFIL), STATUS = 'OLD',  
     +        FORM = 'UNFORMATTED') 
C         ENDIF
        ENDIF   
C   
100   CALL ATOMRD   
     +  (IUNIT,IRECTP,NAME,ICORR,IREL,IFCORE,ZION,NTITLE,TITLE, 
     +   NR,A,B,DUMMY,NQL,DELQL,NQNL,DELQNL,NUMNL,  
     +   ICALC,CDTYPE,NO,LO,MODE,DUMMY) 
C   
C     WE WANT TO SKIP LOCAL POTENTIAL:  
      NQL = 1   
      NR  = 1   
      IF (IRECTP .EQ. 0) THEN   
        WRITE (IUNIT7,*) 'NONLOCAL MATRIX ELEMENTS READ IN' 
        WRITE (IUNIT7,*) ' '
        CLOSE (UNIT = IUNIT)
        RETURN  
        ENDIF   
      IF (IRECTP .NE. 36) GOTO 100  
C   
C     READ RECORD TYPE 36 (N0N-LOCAL POTENTIAL) 
C   
C     IS THE POTENTIAL SPIN-POLARIZED ? 
      NSPEN = 1 
      IF (IREL .EQ. 'SPP' .OR. IREL .EQ. 'spp') NSPEN = 2   
C   
      IF (NQNL .GT. NDIM20 .OR. NQNL .LE. 0) THEN   
        WRITE (IOUT,1020) NQNL,NDIM20   
1020    FORMAT('0SUBROUTINE VNLRED *** ERROR ***'/  
     +    ' NONLOCAL MATRIX HAS DIMENSION=',I6,' BUT NDIM20=',I6)   
        IWARN = 2   
        CALL EXIT   
        ENDIF   
C   
C     READ NONLOCAL MATRIX ELEMENTS 
C   
C      WRITE (IUNIT7,1040) LO
C1040  FORMAT (/' VNLRED: READING NONLOCAL POTENTIAL, L=',I3)
      INDEX = INDEX + 1 
C   
      IF (INDEX .GT. NLMAX) THEN
        WRITE (IOUT,1010) LO
1010    FORMAT('0SUBROUTINE VNLRED *** ERROR ***'/  
     +    ' EXCEEDED ARRAY VNLIJ FOR L =',I10)  
        IWARN = 2   
        CALL EXIT   
        ENDIF   
C     STORE THE ANGULAR MOMENTUM IN POTPAR: 
      POTPAR(ITYPE, 20 + INDEX ) = LO   
C   
      DO 200 ISPIN = 1, NSPIN   
C   
      IF (NSPEN .EQ. NSPIN) THEN
        READ (IUNIT)
     +    ((VNLIJ(I,J,INDEX,ITYPE,ISPIN), I=1,NQNL), J=1,NQNL)  
C   
      ELSE IF (NSPEN .EQ. 1 .AND. NSPIN .EQ. 2) THEN
C       NON-SPINPOLARIZED INPUT 
        IF (ISPIN .EQ. 1) THEN  
          READ (IUNIT)  
     +      ((VNLIJ(I,J,INDEX,ITYPE,1), I=1,NQNL), J=1,NQNL)
        ELSE
C         COPY INTO SPIN-UP POTENTIAL   
          DO 105 I = 1, NQNL
          DO 105 J = 1, NQNL
            VNLIJ(I,J,INDEX,ITYPE,2) = VNLIJ(I,J,INDEX,ITYPE,1) 
105         CONTINUE
        ENDIF   
      ELSE  
        WRITE (IOUT,115) NSPEN,NSPIN
115     FORMAT('0VNLRED *** NO PROVISION WAS MADE FOR NSPEN,NSPIN =',   
     +    2I5)  
        IWARN = 2   
        CALL EXIT   
        ENDIF   
C   
C     ASSIGN VALUE TO ARRAY-INDEX =0, FOR INTERPOLATION IN VNLKK.   
C     VNLIJ(1,1,*,*) CORRESPONDS TO (K1,K2) = (0,0).
C     INTERPOLATION NEAR K1=0 AND/OR K2=0:  
                        FACTOR = + 1.0  
      IF (LO .GT. 0)    FACTOR = - 1.0  
      VNLIJ(0,0,INDEX,ITYPE,ISPIN) =
     +  VNLIJ(2,2,INDEX,ITYPE,ISPIN) * FACTOR   
CDIR$ IVDEP 
      DO 120 J = 1, NQNL
        VNLIJ(0,J,INDEX,ITYPE,ISPIN) =  
     +    VNLIJ(2,J,INDEX,ITYPE,ISPIN) * FACTOR 
        VNLIJ(J,0,INDEX,ITYPE,ISPIN) =  
     +    VNLIJ(J,2,INDEX,ITYPE,ISPIN) * FACTOR 
120     CONTINUE
C   
C     N O T E : 
C     4*PI*(2*L+1) IS INCLUDED IN ARRAY VNLIJ (SEE 'PSTRAN').   
C     (IN THE 'ANALYTICAL' VNLKK, (2*L+1) IS CONTAINED IN PL(X).)   
C   
C     PRINT OUT FOR CHECKING
C   
      IPRINT = 0
      IF (IPRINT .NE. 1) GOTO 200
C
      IF (NSPIN .EQ. 1) THEN
        WRITE (IUNIT8,135) ' '  
      ELSE IF (ISPIN .EQ. 1) THEN   
        WRITE (IUNIT8,135) 'SPIN UP'
      ELSE IF (ISPIN .EQ. 2) THEN   
        WRITE (IUNIT8,135) 'SPIN DOWN'  
        ENDIF   
135   FORMAT (' THE ',A,' CORNER (1-6,1-6) IS:')
      DO 140 I = 1, 6   
        WRITE (IUNIT8,130) (VNLIJ(I,J,INDEX,ITYPE,ISPIN), J = 1, 6) 
130     FORMAT(1X,6F12.5)   
140     CONTINUE
C   
200   CONTINUE  
C   
      GOTO 100  
C   
      END   
